### ISSUE TITLE
Redis binding spec

### ISSUE THREAD

**Issue by roberto-mardeni** [dapr/docs#1001]
https://docs.dapr.io/operations/components/setup-bindings/supported-bindings/redis/

Page is missing a sample and it took me a little of troubleshooting to figure out what was needed, but it should be something like:

```
curl -X POST http://localhost:3500/v1.0/bindings/<binding name> \
  -H "Content-Type: application/json" \
  -d '{
        "data": {
          "message": "Hi"
        },
        "metadata": {
          "key": "<redis key>"
        },
        "operation": "create"
      }'
```

**Comment by mchmarny** [comment]
We've been adding reference links at the bottom of the page. On this page, there is now Binding API reference link which points to page with the right example.
