### ISSUE TITLE
Supported stores

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/docs#1006]
It could be helpful to add a column on the Supported stores page table for Actor support.
For example, the Azure SQL Server does not support Actors but the table makes no indication of that. 
Columns could be Name, CRUD, Transactional, Actor.

**Comment by DarqueWarrior** [comment]
Actually, I am confused now.  The error I got was this. 

failed to init actors: state store does not support transactions which actors require to save state 

But the table shows that SQL Server does support Transactions but failed to support Actors.  

I am using SQL 2019 running in docker.

**Comment by yaron2** [comment]
Do you have the `actorStateStore` field set to `true` on the Component metadata?

**Comment by orizohar** [comment]
We need to add clarity on supported SQL versions (Azure SQL vs. SQL 2019 etc.)

**Comment by DarqueWarrior** [comment]
> Do you have the `actorStateStore` field set to `true` on the Component metadata?

I did not.  I missed that when I was switching from redis to SQL. 

Thanks. No more error.

**Comment by msfussell** [comment]
@orizohar  - can you take a look at this, since apart from you comment, this can be closed
