### ISSUE TITLE
Missing queue name required property on Azure Service Bus Queue example yaml

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#1015]
## Expected Behavior
This is for RC1 documentation.
All examples of yaml should include the required properties.
## Actual Behavior

One example includes the queue name in the yaml -- Has -name: queueName
https://v1-rc1.docs.dapr.io/operations/components/setup-bindings/supported-bindings/servicebusqueues/

Another example does NOT include the queue name in the yaml -- Does not have -name: queueName
https://v1-rc1.docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-azure-servicebus/

This mismatch leads me to wonder if queueName is a required property for yaml, or can it be supplied programmatically somehow?

## Steps to Reproduce the Problem
Read the documents at the above links.

## Release Note

RELEASE NOTE:  Fixed Azure Pub Sub binding  yaml content mismatch across 2 documents.

**Comment by georgestevens99** [comment]
This issue may be irrelevant since one of the documents is about Service Bus binding components (for queues) and the other is about Service Bus pubsub components (for topics).  It has not been clear to me until now that there were 2 different ways to interact with the Service Bus via Dapr.

**Comment by msfussell** [comment]
Closing this issue. Yes, there are two components that are very different. The metadata for each component has been updated to include whether the fields are required and also made a comprehensive list of the fields. Thanks
