### ISSUE TITLE
Ensure strong clear guidance on how to version your app when using Dapr

### ISSUE THREAD

**Issue by lukekim** [dapr/docs#102]
- [ ] Create How-To on how to both version your app (multiple versions of the new order method)
- [ ] At least one sample showing versioning
- [ ] Guidance on how the developer knows what version of Dapr runtime is running at any one time so the App can be Dapr API/functionality aware.

**Comment by orizohar** [comment]
@msfussell @yaron2 - we covered Dapr versioning in the versioning docs. Do we want to extend this section to cover user apps? 
If this also requires a new API for the sidecar to determine version, we need another issue at dapr/dapr

**Comment by hhunter-ms** [comment]
Closing, as this looks to have been resolved. Feel free to open a new issue if necessary.
