### ISSUE TITLE
Comments on the Dapr overview

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#1048]
**Describe the issue**
You need to change https://v1-rc2.docs.dapr.io/concepts/overview/ in 2 ways, shown below.

One -- In the “Developer languages SDKs and frameworks.Web” section at https://v1-rc2.docs.dapr.io/concepts/overview/#web
It now says “In the Dapr .NET SDK you can find ASP.NET Core integration, which brings stateful routing controllers that respond to pub/sub events from other services.”

This **also needs to mention ASP.NET Core gRPC Services** that can use all Dapr features as well.

Two -- In the “Run Anywhere.Running Dapr on a local developer machine in self hosted  mode” diagram at https://v1-rc2.docs.dapr.io/concepts/overview/#running-dapr-on-a-local-developer-machine-in-self-hosted-mode.

In this diagram the double-ended arrow between the service code of the app and the Dapr Sidecar is labeled as follows:
**Dapr Api
Tracking, logs and metrics**

This would be clearer that there are 2 kinds of traffic over the double-ended arrow if labled as follows since there is plenty of space
**Dapr Api requests/responses
Tracking, logs and metrics**

**URL of the docs**
https://v1-rc2.docs.dapr.io/concepts/overview/
https://v1-rc2.docs.dapr.io/concepts/overview/#web
https://v1-rc2.docs.dapr.io/concepts/overview/#running-dapr-on-a-local-developer-machine-in-self-hosted-mode

**Expected content**
Please see the "Describe the issue" above.
**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
@georgestevens99 - Point 1 is fair enough to add. However I think for point 2, adding two arrows into the diagrams doesn't add any real additional clarity and makes for a busier diagram.

**Comment by georgestevens99** [comment]
Thanks.  On point 2.  I did not mean add another double ended error, rather I meant add another label or extend the existing label to include requests and responses.  The current diagram shows no requests and responses and leaves the reader (many viewing it with "beginners eyes") wondering where they are.  Try a label like "Requests, responses, tracking, logs, metrics" -- This can be easily split to fit on 3 lines under the arrow which is not too busy, given the key request/response info it provides.
