### ISSUE TITLE
Add additional information to the Concepts overview

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#1049]
**What content needs to be created or modified?**
Your documents need to change so as to clarify and enhance the definitions, and relationships, between the concepts of Building Blocks, Components, Resource Bindings, and Extensibility.

**Describe the solution you'd like**
A clear conceptual model of a system is worth its weight in gold when it comes to quickly learning the system and clearly communicating with others. Here are specific changes that will accomplish this goal regarding the concepts of Building Blocks, Components, Resource Bindings, and the feature (?) called Extensibe shown below from https://v1-rc2.docs.dapr.io/concepts/overview/

![image](https://user-images.githubusercontent.com/6517661/102697514-416e9280-4204-11eb-855a-1dd7ba0f4854.png)

**One** -- On the “Dapr Concepts” high level page at https://v1-rc2.docs.dapr.io/concepts/

Change this sentence:  “Building Blocks:   Modular best practices accessible over standard HTTP or gRPC APIs” 

To this: “Building Blocks:   Modular best practices accessible over standard HTTP or gRPC APIs and using Components”

Doing this will make the relationship between Building Blocks and Components clear from the start, and reinforce this difference in the definition of Components that follows.  Note that in the “Learning Dapr” book, Building Blocks and Components were equivalent, stated on p 17.

**Two** -- To the list of “Dapr Concepts” high level page at https://v1-rc2.docs.dapr.io/concepts/

**Add the concept of Extensibility to the list** of Dapr Concepts. The overall goal here is that of integration in the reader’s mind of some of the key concepts in the list of Dapr Concepts.  And, to highlight one of the key things that sets Dapr apart from the "rest of the pack" --  easy extensibility of service oriented systems.

Then create a separate high level Extensibility page, similar in function to the other high level concept pages.  In the Extensibility page specifically explain how extensibility is enabled by Building Blocks, their use of Components, and how Resource Bindings fit in to support both Building Blocks and Components, plus other ways that extensibility is supported as well.

To visually tie it all together:
1. Show a conceptual diagram or two, like the diagram here: https://v1-rc2.docs.dapr.io/concepts/building-blocks-concept/

2. And (this is really important) show a diagram of how the highly used building blocks of State Storage and Pub Sub actually utilize the specific Components they use and how Resource Bindings fit it.  Then, finally, show a diagram of a Building Block that does not use Resource Bindings (is that state?).

Again, the goal here is to tie together key Dapr concepts in the mind of the reader. Any small duplication of content is beside the point.

**Where should the new material be placed?**
Placement is stated above.
**Additional context**

**Comment by hhunter-ms** [comment]
It looks like these items are either obsolete or have been resolved since v1. Closing.
