### ISSUE TITLE
[CONTENT] How to get state uses deprecated CLI flag --port (v1.0-rc2)

### ISSUE THREAD

**Issue by orizohar** [dapr/docs#1052]
**Describe the issue**

Need to update --port CLI flag in dapr run command:

```
dapr --app-id myapp --port 3500 run
```

**URL of the docs**

https://v1-rc2.docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/#step-2-save-state

**Expected content**

```
dapr run --app-id myapp --dapr-http-port 3500 run
```

**Comment by msfussell** [comment]
Resolved
