### ISSUE TITLE
We want to translate content into Chinese

### ISSUE THREAD

**Issue by newbe36524** [dapr/docs#1057]
Hi, I am a member of Chinese Dapr SIG. 
We want to translate content into Chinese and host it.
We need some support from dapr official team.

## What we have done

We have already setup an open source project to translate content on github at in https://github.com/dapr-cn/docs .
We have integrate it with crowdin.com as a translation manager for us to translate content more effceintly
It is publish on github pages in https://dapr-cn.github.io/.

We have created a git repository in gitee.com which is 'github' in China and mirror everything translated in github`s repository.
It is because that it is a little difficult to visit github pages for some developer in China.
Repo: https://gitee.com/dapr-cn/docs
Gitee pages: http://dapr-cn.gitee.io/

### CNAME 'cn.docs.dapr.io' to github pages.

So if there is a CNAME record like, it will be great for developer to find out the docs site.

```
CNAME cn.docs.dapr.io dapr-cn.github.io
```

### It will be nice , If there is another Azure static web site for us to publish pages

We have setup Gitee pages for developer in China to touch documents faster than github.
However, there is a problem that gitee pages is not supported to add custom doamin.

So if there is a Azure static web site like docs.dapr.io for up to publish translated content, it will be great helpful.
And in that case, we can add CNAME  or A record to point 'cn.docs.dapr.io' to that site directly

**Comment by newbe36524** [comment]
I have update this issue since we have already fix issue that  we can`t publish to root path in github and gitee pages.

There is still issue about domain.

**Comment by yaron2** [comment]
@newbe36524 most maintainers are currently on holiday vacation, we'll reach out mid-next week.

**Comment by AaronCrawfis** [comment]
Hi @newbe36524, thank you for kicking off the work to translate Dapr into Chinese! This is very exciting and we're happy to work with you on this.

I'll take a look at your sites and discuss with the docs maintainers this week. We were originally wanting to use the built-in multi-language support that hugo provides: https://regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/

Are there any reasons why this would not work?

**Comment by newbe36524** [comment]
Thanks, @AaronCrawfis  , There are some reasons for this:

1. For better performance. Most of developers in Chinese are in China, It will be more faster to access documents if there is a standlone site hosted in or nearby China mainland.
In this way, there are a few solution: 1) To setup a static web site in Azure East Asia zone 2) To setup a static web site in gitee.com pages which is a site like github.com in China.

2. For integration better to crowdin.com. Translating documents is a hard job, so we want to introduce a translation manager system for us to help us translate docs. We have already set up the translation project in corwdin.com: https://crowdin.com/project/daprcndocs . It workd well. If we need integrate crowdin.com into docs.dapr.io. I need to be have owner access to the repository. I think it will be more difficult to be done.

3. It will be ok if you think it is better to commit translated docs back to docs.dapr.io. I can add a github action to commit latest changes back to docs.dapr.io.


Here is the full solution in my mind for this project:

1. We can transfer the repository https://github.com/dapr-cn/docs to dapr group, but I need a owner access to the repo
2. It should be a static web site hosted in Azure East Asia zone
3. Add a domain cn.docs.dapr.io to the static site
4. Submit translated docs in docs.dapr.io if needed.

**Comment by skyao** [comment]
@AaronCrawfis  @yaron2 

I have discussed with @newbe36524 (we are both in the dapr Chinese community), we have some suggestion:

1. we agree with @AaronCrawfis that the translated Chinese content should save in `dapr/docs` repo: in `daprdocs/content` folder we will setup an `zh ` folder (and also update hugo config.toml) and later all the Chinese content will put here

2. We will PR to submit the translated Chinese content to `dapr/docs` repo

3. We apply to at least one account from Chinese community to have the premission to merge the Chinese translate PRs so that we can speed up the process ( and I think it's not a good idea for you to review Chinese content). 

4.Speed up the dapr website: deploying dapr website in the Asia Pacific region (Hong Kong/Japan is recommended), allowing the users from China to access this website server through DNS

**Comment by yaron2** [comment]
> @AaronCrawfis @yaron2
> 
> I have discussed with @newbe36524 (we are both in the dapr Chinese community), we have some suggestion:
> 
> 1. we agree with @AaronCrawfis that the translated Chinese content should save in `dapr/docs` repo: in `daprdocs/content` folder we will setup an `zh ` folder (and also update hugo config.toml) and later all the Chinese content will put here
> 2. We will PR to submit the translated Chinese content to `dapr/docs` repo
> 3. We apply to at least one account from Chinese community to have the premission to merge the Chinese translate PRs so that we can speed up the process ( and I think it's not a good idea for you to review Chinese content).
> 
> 4.Speed up the dapr website: deploying dapr website in the Asia Pacific region (Hong Kong/Japan is recommended), allowing the users from China to access this website server through DNS

/cc @msfussell @orizohar

**Comment by orizohar** [comment]
@AaronCrawfis - My one concern about having this content in the dapr/docs repo is our ability to do the recurring merges across branches that we do every week. We keep a close eye to make sure only the right stuff is carried over from past branches. I believe it will be hard for us to continue doing so with content in Chinese.

**Comment by skyao** [comment]
> @AaronCrawfis - My one concern about having this content in the dapr/docs repo is our ability to do the recurring merges across branches that we do every week. 

Can we use git submodule for this? 

1. Put all the Chinese content to a new repo like `dapr/docs-zh` and only contains the `zh` folder ( like move the `zh` folder to a new repo). There are some branches in this repo like v1.0, v1.1 ... We (Dapr Chinese community)  will manage the content of this repo and now we only need the permission of this repo, not  `dapr/docs`.

2. In `dapr/docs`, add submudule to link above `dapr/docs-zh`  repo with correct branch using `git submodule add -b` command.

Then for `dapr/docs`, it is very easy to manage the content of Chinese: just add submudule to the correct branch of `dapr/docs-zh` repo. 

In .gitmodules file it looks like this: 

```
[submodule "zh"]
    path = zh
    url = https://github.com/dapr/docs-zh.git
    branch = v1.0
```

**Comment by skyao** [comment]
@orizohar @yaron2 @AaronCrawfis 

I think submodule can help us to easy manage the Chinese translation docs, we can have a try.

- Please help to create a new repo `dapr/docs-zh`
- Please let me have the  permission of this  `dapr/docs-zh` repo: let me be the owner
- I will submit the PR in `dapr/docs` to init Chinese support:  update config.toml to add zh and add submodule for `dapr/docs-zh`
- We (Chinese Dapr Community) have completed (translation and review) the two part of dapr docs ( concept and contributing ), we will contribute these docs and push to `dapr/docs-zh`.
- Then when you publish the docs, it will include the Chinese part.

Let's go!

**Comment by skyao** [comment]
@orizohar @yaron2 @AaronCrawfis

How about above proposal of using git submodule?  We are waiting for the answer.

**Comment by orizohar** [comment]
> @orizohar @yaron2 @AaronCrawfis
> 
> How about above proposal of using git submodule? We are waiting for the answer.

I think that is a good solution. @AaronCrawfis, we are already using submodules for SDKs right? Do you see this as a good way to avoid the complexity of upmerging?

**Comment by AaronCrawfis** [comment]
@skyao Your proposal sounds like a perfect solution. I will get everything created and add you to the new repo.

**Comment by AaronCrawfis** [comment]
@skyao I've created a private repo here: https://github.com/dapr/docs-zh

We can make it public as soon as we complete the integration with the main site

**Comment by newbe36524** [comment]
> @skyao I've created a private repo here: https://github.com/dapr/docs-zh
> 
> We can make it public as soon as we complete the integration with the main site

@AaronCrawfis I think I can make it ok at the end of this week.

**Comment by newbe36524** [comment]
@AaronCrawfis I think it is ready to make it public.

**Comment by newbe36524** [comment]
Hi, I close this issue since everything works well for now.
We change can update simplified Chinese content to docs.
I will create another issue about domain if needed in the future.
