### ISSUE TITLE
"How To: Use secret scoping" article only mentions K8s and k8s secret store.  Needs to explicitly include other secret stores.

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#1063]
**Describe the issue**
The "How to: Use secret scoping" article covers the k8s secret store.  This makes me wonder whether it applies to others as well.  I asked on Dapr Discord on 12/30/20 in Documents since I was unsure and did not want to waste time chasing something that is not implemented.

**URL of the docs**
https://v1-rc2.docs.dapr.io/developing-applications/building-blocks/secrets/secrets-scopes/

**Expected content**
This needs to 1) include words about secret stores other than K8s, plus 2) show an example of how to setup a secret store config for a standalone situation using a popular secret store like the Azure Key Vault.

**Screenshots**
NA

**Additional context**
NA

**Comment by AaronCrawfis** [comment]
There are now multiple examples with different secret store types and links to setup other secret stores. https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-scopes/
