### ISSUE TITLE
Incorrect instructions for sending ETag

### ISSUE THREAD

**Issue by amolenk** [dapr/docs#1071]
The state management overview page has some details on concurrency (https://v1-rc2.docs.dapr.io/developing-applications/building-blocks/state-management/state-management-overview/#concurrency). It explains how to send an ETag with a request:

> And when the user code tries to update or delete a state, it’s expected to attach the ETag through the If-Match header.

I believe this to be incorrect. According to the API spec, the ETag is part of the request body: https://v1-rc2.docs.dapr.io/reference/api/state_api/#http-request

**Comment by mukundansundar** [comment]
@msfussell Seems that this is fixed ...

**Comment by amolenk** [comment]
The latest version (https://v1-rc3.docs.dapr.io/developing-applications/building-blocks/state-management/state-management-overview/#concurrency) still mentions `it’s expected to attach the ETag through the If-Match header`. That's incorrect, ETag are passed in the request body.

**Comment by halspang** [comment]
It actually looks like both things are correct. Save state has it in the request body, delete has it as the If-Match header. 

https://v1-rc2.docs.dapr.io/reference/api/state_api/#save-state
https://v1-rc2.docs.dapr.io/reference/api/state_api/#delete-state

**Comment by yaron2** [comment]
Closed with https://github.com/dapr/docs/pull/1213
