### ISSUE TITLE
Updating K8s guidance to include app rollout step for when a cluster is completely restarted

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1072]
In some k8 clustering environments, the cluster can be stopped (all node shut down) and then restarted. This is to save money and not typically done in production. In this scenario the app pods can start before the Dapr sidecar injector pod is running, hence no sidecars are injected to the apps. There's nothing Dapr can do here, as k8s doesn't let you define dependencies, hence an operator will have to do an K8s app rollout command on the apps to restart the pods after the sidecar injector pod is running. 

Worth having a note about this in the docs, to clarify this. Note: This does not happen in prod scenarios, since the cluster is always running.

**Comment by hhunter-ms** [comment]
closing as this would now be redundant
