### ISSUE TITLE
Useless topic parameter in GCP Pub/Sub metadata description

### ISSUE THREAD

**Issue by sergey-komarov** [dapr/docs#1082]
The description of yaml file for GCP Pub/Sub component creation contains useless parameter topic. The metadata of component does not contains such parameter (see https://github.com/dapr/components-contrib/blob/4d3e1be105ef2c10f64d6b80f87341244a6751e0/pubsub/gcp/pubsub/metadata.go#L4) so this parameter can be removed.

https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-gcp/

Expected content: without topic parameter

**Comment by yaron2** [comment]
This was resolved
