### ISSUE TITLE
Update Secrets API reference with the new Get Bulk Secret HTTP Response type

### ISSUE THREAD

**Issue by cmendible** [dapr/docs#1089]
**What content needs to be created or modified?**

Update Secrets API reference with the new Get Bulk Secret HTTP Response since it will now return `map[string]map[string]string` insted of  `map[string]string`

**Where should the new material be placed?**
daprdocs/content/en/reference/api/secrets_api.md

**Additional context**

https://github.com/dapr/components-contrib/issues/590
https://github.com/dapr/dapr/issues/2652

**Comment by msfussell** [comment]
@cmendible @orizohar  - can this issue now be closed?

**Comment by cmendible** [comment]
@msfussell Yes the docs were updated.
