### ISSUE TITLE
Add competing consumer concept to pub/sub overview docs

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#1093]
**What content needs to be created or modified?**
In this section of the Pub Sub Overview -- https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#consumer-groups-and-multiple-instances -- please include the fact that "multiple instances" of a daperized service implements the "competing consumers" pattern.

**Describe the solution you'd like**
See above. Also make sure the term "competing consumers" shows up on searches of Dapr Docs since this term is the way most developers and architects use rather than "multiple instances".

**Where should the new material be placed?**
See above

**Additional context**
None.

**Comment by msfussell** [comment]
PR https://github.com/dapr/docs/pull/1140/files now includes this
