### ISSUE TITLE
[CONTENT] Add documentation for the "--dapr-http-max-request-size" argument for the CLI and "dapr.io/http-max-request-size"  annotation

### ISSUE THREAD

**Issue by apuzyrevsky** [dapr/docs#1099]
**What content needs to be created or modified?**
Within this issue https://github.com/dapr/dapr/issues/2659 and this https://github.com/dapr/dapr/pull/2679 I am adding the possibility to define custom fasthttp server MaxRequestBodySize parameter to handle uploading of big files.

**Describe the solution you'd like**
Add documentation for the `--dapr-http-max-request-size` argument for the CLI and `"dapr.io/http-max-request-size"` annotation for the Kubernetes pods

**Where should the new material be placed?**
https://docs.dapr.io/operations/configuration/

**Comment by msfussell** [comment]
@apuzyrevsky  - Can you create the docs for this update?

Need to update the following topics
1) https://v1-rc3.docs.dapr.io/operations/hosting/kubernetes/kubernetes-annotations/
2) Document the CLI command this is used with in the CLI reference docs.
3) Document in the https://docs.dapr.io/operations/configuration/ topic

**Comment by apuzyrevsky** [comment]
Hi, @msfussell 
1. It's already in the link that you specified. Here is the closed PR: https://github.com/dapr/docs/pull/1104
2. I did not add a CLI command, only a flag.
3.  Here is one more PR: https://github.com/dapr/docs/pull/1183

**Comment by msfussell** [comment]
Resolved. Closed
