### ISSUE TITLE
[CONTENT] Priority param for RabbitMQ pubsub/binding

### ISSUE THREAD

**Issue by kzmake** [dapr/docs#1101]
**What content needs to be created or modified?**

If the maintainers approve it there will need to be new documentation.  ref: https://github.com/dapr/components-contrib/pull/606

- [supported-bindings/rabbitmq](https://github.com/dapr/docs/blob/v0.11/daprdocs/content/en/operations/components/setup-bindings/supported-bindings/rabbitmq.md)

**Describe the solution you'd like**

- Document how Dapr handles max-priority/priority metadata for Binding.

**Where should the new material be placed?**

- [supported-bindings/rabbitmq](https://github.com/dapr/docs/blob/v0.11/daprdocs/content/en/operations/components/setup-bindings/supported-bindings/rabbitmq.md)

**Additional context**

**Comment by msfussell** [comment]
@kzmake  - Please push a PR for this soon. We really like to keep the docs and code in sync. Thanks

**Comment by msfussell** [comment]
Closing as complete
