### ISSUE TITLE
https://docs.dapr.io/contributing/contributing-docs/#branch-guidance

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/docs#1103]
**Describe the bug**
The Hugo front-matter link under the Contributing a new docs page is a 404. It is currently pointing to 
[https://docs.dapr.io/contributing/contributing-docs/front-matter](https://docs.dapr.io/contributing/contributing-docs/front-matter)
Not sure where it is supposed to point.

**Steps to reproduce**
1. Go to 'https://docs.dapr.io/contributing/contributing-docs/#branch-guidance'
2. Scroll down to 'Contributing a new docs page'
3. Click on 'Hugo front-matter'

**Expected behavior**
Link is not 404

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 87.0.664.75

**Additional context**

**Comment by AaronCrawfis** [comment]
@DarqueWarrior good find! Should reference the section below
