### ISSUE TITLE
Wrong separator char in Actor state keys

### ISSUE THREAD

**Issue by amolenk** [dapr/docs#1112]
According to the docs, actor state keys have the following format: `myapp-cat-hobbit-food`

The actual format is `myapp||cat||hobbit||food`.

Tested with Redis and Azure Cosmos DB

**Comment by msfussell** [comment]
Looks like there is one wrong entry. This link
https://docs.dapr.io/developing-applications/building-blocks/state-management/query-state-store/query-sqlserver-store/

Can you clarify?

**Comment by amolenk** [comment]
The other entry is on the Actor API reference page. I've created a PR to fix both pages.
