### ISSUE TITLE
wrong port parameter in sample.

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#1113]
**Describe the issue**
In an example dapr run command in the doc, one of the arguments is out of date.  The --port argument used in the example below  is no longer supported:

dapr run --app-id my-app **--port 3500** --components-path ./components

The above command results in the following error:  Error: unknown flag: --port

**URL of the docs**
https://v1-rc2.docs.dapr.io/developing-applications/building-blocks/secrets/howto-secrets/

**Expected content**
According to the output of   dapr run --help   the up-tp-date argument should be as follows :
-H, --dapr-http-port int              The HTTP port for Dapr to listen on (default -1)

Therefore the command in the docs should be as follows:
dapr run --app-id my-app **--dapr-http-port 3500** --components-path ./components

NA
**Screenshots**

NA
**Additional context**

NA

**Comment by msfussell** [comment]
fixed
