### ISSUE TITLE
[CONTENT] Incomplete info in "How to reference secrets in components" leads to dapr run errors

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#1116]
**Describe the issue**
The current version of "How to reference secrets in components" provides inaccurate examples and no explanation for self hosted situations referencing secrets that are stored in local files secret stores, environment variable secret stores, and perhaps the Azure Key value.   For these stores, setting the secretRef name and key to **DIFFERENT** string values results in dapr run error messages like:

time="2021-01-22T14:48:29.5541945-05:00" level=error msg="failed to init output binding svs-servicec-inputq-localsecret-asbqueue (bindings.azure.servicebusqueues): failed parsing connection string due to unmatched key value separated by '='" app_id=serviceA instance=A-GeorgeXPS1 scope=dapr.runtime type=log ver=1.0.0-rc.2

time="2021-01-22T14:48:29.5562059-05:00" level=error msg="failed to init output bindings: failed parsing connection string due to unmatched key value separated by '='" app_id=serviceA instance=A-GeorgeXPS1 scope=dapr.runtime type=log ver=1.0.0-rc.2

time="2021-01-22T14:48:29.5562059-05:00" level=fatal msg="process component svs-servicec-inputq-localsecret-asbqueue error: failed parsing connection string due to unmatched key value separated by '='" app_id=serviceA instance=A-GeorgeXPS1 scope=dapr.runtime type=log ver=1.0.0-rc.2

 
**URL of the docs**
https://v1-rc2.docs.dapr.io/operations/components/component-secrets/
**Expected content**
In addition to the existing content, yaml needs to be shown for local file and environment variable secret stores in self hosted scenarios.  In these stores the secretRef name and key must be set to the **SAME** string value.  The Azure Key Vault may be the same.  Plus there needs to be text that warns the user of what causes the above errors.  
**Screenshots**

**Additional context**
Here is the conversation on Dapr Discord that revealed this fact -- See CMendible3's comment near the end of the thread for a terse summary of the actual behavior (https://discord.com/channels/778680217417809931/781589820128493598/802585525655568414)

**Comment by msfussell** [comment]
This issue is resolved with the PR. Closing unless @georgestevens99 you say otherwise
