### ISSUE TITLE
Need examples of acceptable syntax and formats for .PFX file path name in Az KeyVault Secret Store component

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#1128]
**What content needs to be created or modified?**
The Azure Key Vault Secret Store component definition requires a name value pair for the certificate .pfx file: 
- name: spnCertificateFile
    value : "[pfx_certificate_file_local_path]"

Please provide examples of acceptable paths.  Like fully qualified path, or just the .pfx file name in the .components directory (which does not seem to work -- does it always have to be a fully qualified path?). 

Please provide examples of acceptable path syntax.  For Linix based systems I assume C:/something/somethingelse/ttt.pfx works, but this will not work on Windows systems which needs C:\\something\\somethingelse\\ttt.pfx.

Make the examples you furnish so complete that it is so easy write a key vault component definition that one can't possibly make a mistake, even a stupid one!

**Describe the solution you'd like**
See above.

**Where should the new material be placed?**
Place this just under the text of the component definition.

**Additional context**

**Comment by msfussell** [comment]
Fixed
