### ISSUE TITLE
Add documentation for the SMTP output binding

### ISSUE THREAD

**Issue by EdwinVW** [dapr/docs#1145]
**What content needs to be created or modified?**
Documentation on how to use the new SMTP output binding (see https://github.com/dapr/components-contrib/pull/646).

**Where should the new material be placed?**
Operations/Components/Bindings/Supported bindings/SMTP

**Additional context**
I created a proposal for this binding in the components-contrib repo (still to be approved).

**Comment by msfussell** [comment]
Closed, fixed
