### ISSUE TITLE
Observability link points to page you are on

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/docs#1147]
I am using version v1.0-rc.2 (preview) of docs.

**URL of the docs page**
https://v1-rc2.docs.dapr.io/developing-applications/building-blocks/observability/

**How is it currently worded?**
The `general overview of the observability concept` link points to the page you are on instead of observability section under concepts that is here https://v1-rc2.docs.dapr.io/concepts/observability-concept/

**How should it be worded?**
The link should point to https://v1-rc2.docs.dapr.io/concepts/observability-concept/

**Screenshots**

**Additional context**

**Comment by orizohar** [comment]
Fixed via https://github.com/dapr/docs/pull/1175 
Note the issue was merged to v0.11 rc.3 and v1.0 branches. rc.2 is no longer maintained
