### ISSUE TITLE
HTTP Binding missing information/outdated

### ISSUE THREAD

**Issue by halspang** [dapr/docs#1153]
**Describe the issue**
HTTP Binding is listed as an output binding only when it also has input bindings.

Method field is no longer used as input/output bindings have replaced that.

**URL of the docs**
https://docs.dapr.io/operations/components/setup-bindings/supported-bindings/
https://docs.dapr.io/operations/components/setup-bindings/supported-bindings/http/

**Expected content**
HTTP Binding should be listed as an input and output binding.

Callout that method does not do anything or remove the field from the docs.

Alternate: update the HTTP binding to actually use the field and then the docs are accurate.

**Additional context**
It may have always been an input/output binding and method may have never been used going back to the initial commit:
https://github.com/dapr/components-contrib/commit/22fea6f43d53a6dc4780132c8849577928e6ebcf#diff-50e6b52eb3eded23c24e7ac1117cb029862ee7ead109191d65cc1b13d54ed8da

**Comment by msfussell** [comment]
Closed, fixed
