### ISSUE TITLE
Update the Service Invocation Perf numbers for v1.0

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1169]
Update this topic based and remove the reference to v0.11 runtime version
https://v1-rc3.docs.dapr.io/operations/performance-and-scalability/perf-service-invocation/

This article is going to be reference from the blog and hence needs to be updated.

**Comment by yaron2** [comment]
Note: add baseline reference text: "This performance is on par or better than commonly used service meshes"

**Comment by yaron2** [comment]
Done
