### ISSUE TITLE
Create FAQ/Troubleshooting on local mDNS

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#1173]
We should have:

- Troubleshooting tip on how to check in mDNS is enabled and running on your local machine
- Alert in the service invocation section saying it depends on mDNS, and how to check if it's enabled

**Comment by AaronCrawfis** [comment]
Microsoft ATP on Mac:

Open Network Settings, on the left you’ll see a network profile called “Microsoft Content Filter” or something similar.

Click it and then the little cogs dropdown below and click “Make Service Inactive”.

**Comment by philliphoff** [comment]
And note that certain IT organizations will attempt to re-enable the filter from time to time, so one has to repeatedly check and disable it again.  As in, if it *was* working yesterday and *not* working today, first check to see if the filter has been re-enabled before doing more extensive troubleshooting.

**Comment by greenie-msft** [comment]
@AaronCrawfis Can we close this issue?

**Comment by DanielHazlewood** [comment]
This was closed, but the documentation was only added for MacOS. What about Windows?
