### ISSUE TITLE
[CONTENT] - v1.0 - Update RC related commands in "getting-started"

### ISSUE THREAD

**Issue by orizohar** [dapr/docs#1188]
**Describe the issue**

Need to make the following changes in v1.0 branch:
- [ ] Remove all "Notes" about RC vs. latest release
- [ ] Update CLI installation commands
- [ ] Update Dapr init for self host
- [ ] Update Dapr init for k8s

**URL of the docs**

https://v1-0.docs.dapr.io/getting-started/install-dapr-cli/
https://v1-0.docs.dapr.io/getting-started/install-dapr-selfhost/
https://v1-0.docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/

**Expected content**

**Screenshots**

**Additional context**

Part of v1.0 endgame

**Comment by yaron2** [comment]
Done
