### ISSUE TITLE
Provide guidance on required ports for control-plane

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/docs#1195]
**What content needs to be created or modified?**
Provide guidance on required ports for control-plane so that this can be opened up when defining network restrictions and security rules.

**Describe the solution you'd like**
A nice overview of the production guidance elaborating on the ports per component and if they are required or not would be great.

**Where should the new material be placed?**
Would be great to add this to https://v1-rc3.docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/.

**Comment by tomkerkhove** [comment]
Any thoughts on this @yaron2 ?

**Comment by orizohar** [comment]
@wcs1only - can you take a look at this?

**Comment by hhunter-ms** [comment]
Related to #1168

**Comment by msfussell** [comment]
@yaron2 - can you assign yourself this issue?

**Comment by hhunter-ms** [comment]
@yaron2 friendly bump

**Comment by tomkerkhove** [comment]
@hhunter-ms Thanks for closing! Where can we find these docs?

**Comment by hhunter-ms** [comment]
@tomkerkhove I believe this may have been addressed in the [Kubernetes hosting docs](https://docs.dapr.io/operations/hosting/kubernetes/)!

**Comment by tomkerkhove** [comment]
Unfortunately I do not see it there, do you know who contributed this or through what PR?
