### ISSUE TITLE
Create a "invoke service" article that shows how to use gRPC from your application to call Dapr

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1215]
We have this article on using HTTP to call to Dapr https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/ 
We also have this article to configure Dapr to *receive* gRPC calls
We do not have an article that shows how to call from your application *using gRPC* to invoke another service (or any of the Daprs APIs for that matter using gRPC)

**Comment by willtsai** [comment]
I believe this can now be resolved since it seems that this documentation now exists? https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/

**Comment by hhunter-ms** [comment]
Resolved - closing
