### ISSUE TITLE
Documentation for DynamoDB State store is missing

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#1216]
**What content needs to be created or modified?**
A page for dynamodb state store

**Describe the solution you'd like**
N/A

**Where should the new material be placed?**
https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/

**Additional context**
Ref https://github.com/dapr/components-contrib/issues/647#event-4329166798

**Comment by trondhindenes** [comment]
I'd be happy to take a stab at this.

**Comment by yaron2** [comment]
> I'd be happy to take a stab at this.

Please :)

**Comment by trondhindenes** [comment]
closing this, since the doc PR is merged.
