### ISSUE TITLE
Chinese VPNs block Dapr docs site scripts

### ISSUE THREAD

**Issue by DuanShaolong** [dapr/docs#1245]
When I click the "Windows" tab, It can't jump to Windows version download tab.
![image](https://user-images.githubusercontent.com/19683994/108591393-84cfb380-73a3-11eb-9b29-37e4be319eb7.png)

**Comment by orizohar** [comment]
@DuanShaolong - can you provide more details such as OS and browser you are using? For me on Windows and Chrome this does not reproduce

@AaronCrawfis - can you take a look at this as well?

**Comment by AaronCrawfis** [comment]
This is most likely an issue with the script source not loading. @DuanShaolong when you go into the developer portal (F12 or right click + ctrl) and refresh the page, do you get any errors?

Also are you using a VPN?

**Comment by AaronCrawfis** [comment]
Duplicate of #900
