### ISSUE TITLE
Need documentation regarding trace annotations

### ISSUE THREAD

**Issue by tcnghia** [dapr/docs#1248]
**What content needs to be created or modified?**
We need to document the usage of `dapr`-prefixed headers as trace annotations.

**Describe the solution you'd like**
Observability doc adds instruction how to use `dapr`-prefix headers and examples of how those can be used to troubleshoot an application.

**Where should the new material be placed?**
https://docs.dapr.io/developing-applications/building-blocks/observability/tracing-overview/

**Additional context**

**Comment by tcnghia** [comment]
See code [here](https://github.com/dapr/dapr/blob/9341e3faa67ede470febe987b3398775759cf38f/pkg/diagnostics/grpc_tracing.go#L85) and [here](https://github.com/dapr/dapr/blob/9341e3faa67ede470febe987b3398775759cf38f/pkg/diagnostics/grpc_tracing.go#L94).

**Comment by msfussell** [comment]
Closing. No longer relevant
