### ISSUE TITLE
Production guidelines on Kubernetes broken link to chart readme

### ISSUE THREAD

**Issue by MauRiEEZZZ** [dapr/docs#1263]
https://github.com/dapr/docs/blame/v1.0/daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md#L24

the link to the readme.md leads to 404 error

**Comment by orizohar** [comment]
Thanks for catching this! Seems like `.md` was missing. Addressed in https://github.com/dapr/docs/pull/1282
