### ISSUE TITLE
SQL Server doc says it does not support actors

### ISSUE THREAD

**Issue by artursouza** [dapr/docs#1274]
**Describe the issue**
Doc says that SQL server does not support actors, but table shows that it does: https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/

**URL of the docs**
https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/setup-sqlserver/

**Expected content**
Updated documentation to mention how to configure it as an actor state store.

**Screenshots**

**Additional context**

**Comment by AaronCrawfis** [comment]
@artursouza @yaron2 does SQL support actors? Easy fix to remove the incorrect message if it does

**Comment by artursouza** [comment]
@AaronCrawfis Yes, actors can be used with SQL State Store.
