### ISSUE TITLE
[CONTENT] Update ASB metadata

### ISSUE THREAD

**Issue by jjcollinge** [dapr/docs#1275]
**Describe the issue**
Updating the ASB metadata to display updated config from https://github.com/dapr/components-contrib/issues/692

**URL of the docs**
https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-azure-servicebus/

Do not merge unless PR (https://github.com/dapr/components-contrib/pull/713) is merged.

**Comment by AaronCrawfis** [comment]
Seems to have been updated at https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/
