### ISSUE TITLE
Actor concepts missing types and ids

### ISSUE THREAD

**Issue by rynowak** [dapr/docs#1298]
**What content needs to be created or modified?**

The actors documentation doesn't describe actor types or actor ids. Basically we're missing the documentation about how these concepts function, and how they integrate with the hosting model, routing, and placement.

**Describe the solution you'd like**

We should document these concepts broadly in one place and lets SDKs point to it. 

I came across this while improving docs for the .NET SDK actor framework, and it doesn't seem right to include in .NET as a one-off, it is more general.

**Where should the new material be placed?**

https://docs.dapr.io/developing-applications/building-blocks/actors/actors-overview/

**Comment by orizohar** [comment]
related to #804

**Comment by olitomlinson** [comment]
From a user on Discord :

The docs are missing any definition of the Actor Id and what are the allowed and restricted characters, plus the overall length of the actor id.
