### ISSUE TITLE
[CONTENT] Document GCP Pubsub refactoring

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#1308]
**What content needs to be created or modified?**
With https://github.com/dapr/components-contrib/pull/760 there are some changes to metadata field names, and most fields are now optional (if using implicit auth). 

**Describe the solution you'd like**
Updated "Spec metadata fields" table

**Where should the new material be placed?**
operations/components/setup-pubsub/supported-pubsub/setup-gcp-pubsub/

**Additional context**

**Comment by msfussell** [comment]
@trondhindenes - Are you going to issue a PR to the docs for this code re-organization change?

**Comment by trondhindenes** [comment]
I am, and I'm sorry I haven't been able to do it yet. I'll set aside some time tonight and get it done.
