### ISSUE TITLE
Outdated instructions for running Kafka on Kubernetes

### ISSUE THREAD

**Issue by mausch** [dapr/docs#1327]
In https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-apache-kafka/ , the helm chart link points to https://github.com/helm/charts/tree/master/incubator/kafka#installing-the-chart .

[That repo has been obsolete for several months now](https://www.cncf.io/blog/2020/10/07/important-reminder-for-all-helm-users-stable-incubator-repos-are-deprecated-and-all-images-are-changing-location/).

There's a link in that deprecated repo pointing to this other helm chart for Kafka: https://github.com/Yolean/kubernetes-kafka
Though the Strimzi operators are quickly becoming the new de-facto standard for this I think: https://strimzi.io/

**Comment by yaron2** [comment]
Thanks for opening this. Would you like to submit a PR to fix this?

**Comment by msfussell** [comment]
@mausch  - It would be useful if you could submit a PR, so that the we get this correct.
