### ISSUE TITLE
https://docs.dapr.io/getting-started/configure-redis/#create-a-redis-store points to docs in Chinese

### ISSUE THREAD

**Issue by vinayada1** [dapr/docs#1336]
**Describe the bug**
https://docs.dapr.io/getting-started/configure-redis/#create-a-redis-store points to Chinese docs.

**Steps to reproduce**
1. Go to https://github.com/dapr/quickstarts/tree/master/pub-sub
2. Go to the paragraph below and click the "these steps" link
```
Follow these steps to create a Redis store using Helm.

Note: Currently the version of Redis supported by Azure Redis Cache is less than 5, so using Azure Redis Cache will not work.
```
3. It points to docs in Chinese

**Expected behavior**
The default language should be English

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by orizohar** [comment]
@AaronCrawfis - My suspicion is that this has to do with Hugo aliases. The above link is an old link, if the Chinese page defines it as an alias without the /zh-hans/ path it will "hijack" the English page

**Comment by orizohar** [comment]
Also happens with [https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster](https://docs.dapr.io/getting-started/install-dapr/#install-dapr-on-a-kubernetes-cluster)
