### ISSUE TITLE
How does service invocation work when there are multiple instances of the target?

### ISSUE THREAD

**Issue by mii9000** [dapr/docs#1345]
**What content needs to be created or modified?**
There should be docs on how service invocation would work when there are multiple instances of services.

**Describe the solution you'd like**
Docs on how service invocation would work when there are multiple instances of services

**Where should the new material be placed?**
docs.dapr.io

**Additional context**
Could be compared to service discovery solutions like Consul

**Comment by hhunter-ms** [comment]
This looks like it may have been resolved in [How to: Service invocation across namespaces](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-namespaces/)
