### ISSUE TITLE
AWS ECS/Fargate Documentation

### ISSUE THREAD

**Issue by NapalmCodes** [dapr/docs#1346]
**What content needs to be created or modified?**
AWS ECS Support/Fargate instructions

**Describe the solution you'd like**
Documentation describing utilization of Dapr on the aforementioned platform.

**Where should the new material be placed?**
https://docs.dapr.io/operations/hosting/

**Additional context**
None

**Comment by AaronCrawfis** [comment]
@napalm684 if you're interested in helping out feel free to write up a PR. For now marking this as a P3 and new feature request.
