### ISSUE TITLE
Explain why we need to do `dapr uninstall --all` with regard to exporters component

### ISSUE THREAD

**Issue by tcnghia** [dapr/docs#1348]
**What content needs to be created or modified?**
Currently upgrade instruction from 0.11 asks users to do `dapr uninstall --all` without explaining that we needs such instruction because of https://github.com/dapr/dapr/issues/2522 .

**Describe the solution you'd like**
Clarify the instruction, so that users seeing the issues can be pointed to.

**Where should the new material be placed?**
- Observability docs
- Upgrade instructions from 0.11
- 
**Additional context**
cc @wcs1only

**Comment by orizohar** [comment]
@tcnghia is this still relevant post v1.0?
