### ISSUE TITLE
Wrong info on default port number

### ISSUE THREAD

**Issue by kamialie** [dapr/docs#1352]
**Describe the issue**
99% confident that information for default ports of http and grpc are mixed up, please correct me if I'm wrong. Documentation says default http port is 50001. Tried with `daprio/daprd:1.0.0` image and getting http response from 3500 port.

**URL of the docs**
https://docs.dapr.io/reference/cli/dapr-run/

**Expected content**
| Name | Default |
|-------|--------|
| --dapr-grpc-port | 50001 |
| --dapr-http-port | 3500 |

**Screenshots**
<img width="923" alt="Screenshot 2021-04-01 at 12 43 03" src="https://user-images.githubusercontent.com/43202110/113275851-e6126d00-92e7-11eb-8f38-0800f1150ea1.png">

**Comment by msfussell** [comment]
Fixed. Closed
