### ISSUE TITLE
Add documentation for PowerShell and Command Prompt

### ISSUE THREAD

**Issue by poroburu** [dapr/docs#1373]
**Describe the issue**

On step 5 using windows, ``explorer "%USERPROFILE%\.dapr\"``
takes me to the ``~\Documents`` directory

**URL of the docs**

https://docs.dapr.io/getting-started/install-dapr-selfhost/

**Expected content**

Explorer to open ``~\.dapr\`` 

**Screenshots**

**Additional context**

Windows 10
CLI version: 1.1.0
Runtime version: 1.1.0

**Comment by AaronCrawfis** [comment]
Running this command in PowerShell results in documents, whereas running in COmmand Prompt opens .dapr. I'll update this issue and assign to myself to add wording into the docs for both scenarios.
