### ISSUE TITLE
Broken link in New Relic page

### ISSUE THREAD

**Issue by orizohar** [dapr/docs#1382]
**Describe the issue**

One of the related links in the New Relic tracing page is broken (most likely due to a move of the doc in the New Relic website):
https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api

**URL of the docs**

https://docs.dapr.io/operations/monitoring/tracing/supported-tracing-backends/newrelic/

**Expected content**

Need to replace the link for "New Relic Trace API" in the related links section. Currently the following link is broken
https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api

**Screenshots**

N/A

**Additional context**

N/A

**Comment by orizohar** [comment]
@harrykimpel - can you look at this and suggest a fix?

**Comment by harrykimpel** [comment]
> @harrykimpel - can you look at this and suggest a fix?

will do so asap
