### ISSUE TITLE
Add a workaround for MTLS disabled bug

### ISSUE THREAD

**Issue by mukundansundar** [dapr/docs#1385]
**Describe the issue**

See https://github.com/dapr/cli/issues/664

Add a workaround in the upgrade section.
**URL of the docs**

**Expected content**

**Screenshots**

**Additional context**

**Comment by AaronCrawfis** [comment]
@mukundansundar please submit a PR for this and we will review

**Comment by AaronCrawfis** [comment]
@mukundansundar  could you take a look at this please?
