### ISSUE TITLE
Remove workaround for mTLS bug

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#1387]
Make sure mTLS workaround at https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-upgrade/#dapr-cli is removed in v1.2.

**Comment by AaronCrawfis** [comment]
Code issue: https://github.com/dapr/cli/issues/664

**Comment by mukundansundar** [comment]
Active PR .. https://github.com/dapr/cli/pull/706
