### ISSUE TITLE
[CONTENT] Add CLI reference docs for `--data-file` flags for invoke and publish

### ISSUE THREAD

**Issue by mukundansundar** [dapr/docs#1391]
**What content needs to be created or modified?**

[CONTENT] Add CLI reference docs for `--data-file` flags for invoke and publish
**Describe the solution you'd like**

Add in the flags in the reference for CLI docs.
**Where should the new material be placed?**

v1.2
**Additional context**

**Comment by wcs1only** [comment]
Just need to update these two tables:
https://docs.dapr.io/reference/cli/dapr-invoke/
https://docs.dapr.io/reference/cli/dapr-publish/
