### ISSUE TITLE
Update MySQL State store

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/docs#1399]
**What content needs to be created or modified?**
The MySQL State store has been updated to allow a 64bit encoded PEM to be used instead of reading from disk. This will allow the component to be used in K8s where you can't read a file from the sidecar. You can now store the PEM in a secret. I tested with Azure Keyvault. 

The string must be 64bit encoded so the new lines are retained.

**Describe the solution you'd like**
Add a section for local vs k8s configuration. There was a new metadata field added to how the Pem Contents for k8s whereas for local it can be a Pem Path.

**Where should the new material be placed?**
On the existing MySQL State store docs page.

**Additional context**

**Comment by orizohar** [comment]
@DarqueWarrior is this still missing here? https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-mysql/

**Comment by DarqueWarrior** [comment]
I will complete next week. Sorry for delay. Docs have been getting pushed. I will make a priority.

**Comment by DarqueWarrior** [comment]
This can be closed. The changes are in docs now.
