### ISSUE TITLE
[CONTENT] Consul nameresolution component

### ISSUE THREAD

**Issue by a-elsheikh** [dapr/docs#1408]
**What content needs to be created or modified?**
We need a new section covering the consul name resolution component

**Where should the new material be placed?**
I imagine there'll need to be a new area for nameresolution components under: https://docs.dapr.io/reference/components-reference/

and then within that a section for the consul spec

**Additional context**
The information should reflect that which is in dapr/components-contrib/nameresolution/consul/Readme.md

**PR** - #1443

**Comment by yaron2** [comment]
@a-elsheikh the main PR in `dapr/dapr` is merged, please continue with the PR for docs. Thanks!

**Comment by CodeMonkeyLeet** [comment]
@AaronCrawfis @msfussell Looks like this can be closed given the merge of #1443.
