### ISSUE TITLE
Update SQL Server state store

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/docs#1410]
**What content needs to be created or modified?**
The SQL server state store will create the database if it is missing and the docs need to be updated to reflect that.

**Describe the solution you'd like**
Update docs to make it clear the database will be created if the user has permissions. 
State the defaults that will be used for table and database names.

**Where should the new material be placed?**
In the original location for SQL State Store

**Additional context**
This goes with issues [798](https://github.com/dapr/components-contrib/issues/798) of the components-contrib repo.

**Comment by orizohar** [comment]
@DarqueWarrior since you are the owner of the PR, can I assign this doc update to you?

**Comment by DarqueWarrior** [comment]
Sure

**Comment by DarqueWarrior** [comment]
Looking into this now.
