### ISSUE TITLE
.NET Actor example includes the code line app.UseHttpsRedirection();

### ISSUE THREAD

**Issue by theperm** [dapr/docs#1426]
**Describe the issue**
The example includes the code line
app.UseHttpsRedirection();

but this contradicts the guidance here
https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-actors/dotnet-actors-usage/#problematic-middleware

**URL of the docs**
https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-actors/dotnet-actors-howto/#register-actor-runtime-with-aspnet-core-startup

**Expected content**
Remove 
app.UseHttpsRedirection();
from the example

**Screenshots**

**Additional context**

**Comment by AaronCrawfis** [comment]
@dapr/maintainers-dotnet-sdk please advise

**Comment by hhunter-ms** [comment]
@halspang can you take a look at this?
