### ISSUE TITLE
[CONTENT] how to integrate Dapr into the existing microservices

### ISSUE THREAD

**Issue by CJ99** [dapr/docs#1434]
**What content needs to be created or modified?**
There should be docs on integrating Dapr into the existing microservices, especially add Dapr to the services in Kubernetes. 

**Describe the solution you'd like**
I believe the best practice and guidelines on applying Dapr for the existing services will be helpful for developers and architects to promote Dapr in the solutions.  For example, 
- How to adapt Dapr into a large project which includes over 200 microservices
- How to integrate the external identity provider (OAuth2) (if necessary)

**Comment by orizohar** [comment]
@CJ99 - Do these docs help with your needs:

- https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/
- https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-oauth2clientcredentials/

**Comment by hhunter-ms** [comment]
This looks like it has been resolved - closing.
