### ISSUE TITLE
Don't use 'X-' in HTTP headers

### ISSUE THREAD

**Issue by jchesterpivotal** [dapr/docs#147]
The IETF guidance to prefix `X-` to experimental headers or to other extension field types has been deprecated since June 2012, per [RFC 6648](https://tools.ietf.org/html/rfc6648).

I'd suggest prefixing with `Dapr-` where you feel namespacing is necessary.

**Comment by jchesterpivotal** [comment]
Meta question: is this the right place to raise the issue? I wasn't looking at the repository when I opened the issue.

**Comment by ChrisMcKee** [comment]
The RFC does state that and mdn even notes it (before listing off some X headers that stemmed from Mozilla)  but X prefixes are still heavily in use and filtering often allows them to freely pass Vs non standard ones. 
Assuming the usage is always within a private network the risk of either options probably low, but with considering as a risk factor. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

**Comment by jchesterpivotal** [comment]
Fairy nuff. Should I close? Short of a "guidance for Dapr architecture" doc, I think this issue would have no further concrete steps. I've at least got to lob on of my favourite nitpicks over the wall.

**Comment by amanbha** [comment]
@jchesterpivotal no worries. Feel free to raise any issues.
