### ISSUE TITLE
Document how to set the default values for actors

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1470]
Actors have a number of values including, default garbage collection, default timers and reminders etc.
These can be overridded on a per type basis, but the defaults values are not documented.

**Comment by berndverst** [comment]
Garbage collection default is 1 hour of idle time:
https://github.com/dapr/dapr/blob/master/pkg/actors/config.go#L26

We should also document the scan interval which is relevant in connection with the Idle Timeout.

**Comment by berndverst** [comment]
@msfussell can these defaults really be overridden on a per type basis? It is my understanding that these live in the Actor Runtime Config which is global to a given app (e.g. Kubernetes deployment)

The SDKs only support setting the timeout interval and scan interval. Not changing the timer and reminder defaults.

https://github.com/dapr/dapr/blob/master/pkg/config/app_configuration.go

**Comment by berndverst** [comment]
"type" == actor type? or event / trigger type?
