### ISSUE TITLE
Enabling HA for existing Dapr installations on Kubernetes

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/docs#1476]
## In what area(s)?

/area placement
/area docs

## Ask your question here

It would be good to have guidance on how to enabling HA for existing Dapr installations on Kubernetes.

Unfortunately, this is not a walk in the park since Kubernetes does not allow you to update volume claims for existing StatefulSets and thus you will get this error:

> ##[error]Error: UPGRADE FAILED: cannot patch "dapr-placement-server" with kind StatefulSet: StatefulSet.apps "dapr-placement-server" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

_While this error comes from Helm, it is actually due to Kubernetes itself_

I currently see the following options:
1. Manually uninstall and re-install Dapr with HA enabled (which is a no-go since this has production impact)
2. Run Dapr side-by-side, one with HA and one without HA (although I'm not sure if this is supported)

**Comment by tomkerkhove** [comment]
Any update on this @msfussell @yaron2? This is still blocking us.

**Comment by yaron2** [comment]
@artursouza we need to look at this for 1.3.

**Comment by tomkerkhove** [comment]
Any update on this @artursouza? Happy to help where I can.

**Comment by tomkerkhove** [comment]
Based on https://github.com/dapr/dapr/issues/3260 1.3 is freezing soon which will include some nice HA features that need this to be able to use them :/

**Comment by artursouza** [comment]
We will look into docs soon. I cannot guarantee if this one will make it.

**Comment by tomkerkhove** [comment]
Thanks for the update! It would be nice though since it's been open since before 1.2 I think but happy to help where I can.

**Comment by dmitsh** [comment]
@tomkerkhove , is running `helm upgrade dapr --set global.ha.enabled=true ...` an option?

Could you provide steps to reproduce the issue?

**Comment by tomkerkhove** [comment]
Sure thing, it's actually fairly simple to do:
1. Install Dapr without HA enabled (`helm install dapr dapr/dapr`)
2. Change Dapr to enable HA (`helm upgrade dapr dapr/dapr --set global.ha.enabled=true`)

It will then fail with following error:
> Error: UPGRADE FAILED: cannot patch "dapr-placement-server" with kind StatefulSet: StatefulSet.apps "dapr-placement-server" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

So probably an uninstall would work, but that's not really a solution in my opinion as it impacts a lot of apps.

**Comment by dmitsh** [comment]
> Sure thing, it's actually fairly simple to do:
> 
> 1. Install Dapr without HA enabled (`helm install dapr dapr/dapr`)
> 2. Change Dapr to enable HA (`helm upgrade dapr dapr/dapr --set global.ha.enabled=true`)

I did exactly that in minikube, and I didn't get any error.
I haven't tried `helm upgrade` on a "real" cluster yet, but I will.
Could you meanwhile check your scenario with minikube?

**Comment by tomkerkhove** [comment]
I'm using Kubernetes v1.20.5 on AKS and I do not have minikube but reproducing with Kubernetes cluster through Docker Desktop results in the same outcome.

Do note that you have to wait for everything to be up and running before running upgrade or you will not have the same error.

**Comment by dmitsh** [comment]
I still cannot reproduce this issue.
I'm running 2-nodes cluster in AKS. Same k8s version as yours:

```sh
% k get no
NAME                                STATUS   ROLES   AGE   VERSION
aks-nodepool1-32736308-vmss000000   Ready    agent   15m   v1.20.5
aks-nodepool1-32736308-vmss000001   Ready    agent   15m   v1.20.5

% h install \
                dapr --namespace=${DAPR_NAMESPACE} --wait --timeout 5m0s \
                --set global.ha.enabled=false --set global.logAsJson=true \
                --set dapr_placement.logLevel=debug --set dapr_sidecar_injector.sidecarImagePullPolicy=Always \
                --set global.imagePullPolicy=Always --set dapr_placement.cluster.forceInMemoryLog=true ./charts/dapr
NAME: dapr
LAST DEPLOYED: Mon Jul 12 09:29:22 2021
NAMESPACE: dapr-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing Dapr: High-performance, lightweight serverless runtime for cloud and edge

Your release is named dapr.

To get started with Dapr, we recommend using our quickstarts:
https://github.com/dapr/quickstarts

For more information on running Dapr, visit:
https://dapr.io

% kd get po
NAME                                     READY   STATUS    RESTARTS   AGE
dapr-dashboard-65cf98949c-l7njn          1/1     Running   0          3m18s
dapr-operator-7dd7864d74-n4b85           1/1     Running   0          3m18s
dapr-placement-server-0                  1/1     Running   0          3m18s
dapr-sentry-5b5cf69f89-jh9jw             1/1     Running   0          3m18s
dapr-sidecar-injector-658b47dcb4-bjmk5   1/1     Running   0          3m18s

% h upgrade \
                dapr --namespace=${DAPR_NAMESPACE} --wait --timeout 5m0s \
                --set global.ha.enabled=true --set global.logAsJson=true \
                --set dapr_placement.logLevel=debug --set dapr_sidecar_injector.sidecarImagePullPolicy=Always \
                --set global.imagePullPolicy=Always --set dapr_placement.cluster.forceInMemoryLog=true ./charts/dapr
Release "dapr" has been upgraded. Happy Helming!
NAME: dapr
LAST DEPLOYED: Mon Jul 12 09:33:16 2021
NAMESPACE: dapr-system
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
Thank you for installing Dapr: High-performance, lightweight serverless runtime for cloud and edge

Your release is named dapr.

To get started with Dapr, we recommend using our quickstarts:
https://github.com/dapr/quickstarts

For more information on running Dapr, visit:
https://dapr.io

% kd get po
NAME                                     READY   STATUS    RESTARTS   AGE
dapr-dashboard-957cd5777-c5smz           1/1     Running   0          60s
dapr-operator-6fd97c968-5vzv6            1/1     Running   0          60s
dapr-operator-6fd97c968-dcmqv            1/1     Running   0          45s
dapr-operator-6fd97c968-jdrvl            1/1     Running   0          55s
dapr-placement-server-0                  1/1     Running   0          42s
dapr-placement-server-1                  1/1     Running   0          60s
dapr-placement-server-2                  1/1     Running   0          60s
dapr-sentry-86d9b68466-k2vvc             1/1     Running   0          40s
dapr-sentry-86d9b68466-lfcvj             1/1     Running   0          46s
dapr-sentry-86d9b68466-r9sh2             1/1     Running   0          60s
dapr-sidecar-injector-648b979c5b-6dxgr   1/1     Running   0          42s
dapr-sidecar-injector-648b979c5b-hlqjg   1/1     Running   0          60s
dapr-sidecar-injector-648b979c5b-lrr58   1/1     Running   0          47s
```

**Comment by tomkerkhove** [comment]
Not sure what's up though - I tried it on 2 different AKS clusters and a local Docker Desktop cluster.
Can anyone else reproduce this?

For what it's worth, but I don't think it makes a difference, I did not specify any configuration.

**Comment by dmitsh** [comment]
@tomkerkhove , could you list your steps verbatim? I will try to reproduce.
Also, I'm using dapr's master/HEAD. Which tag/commit are you on?
If you are not on the latest master, could you give it a try?

**Comment by tomkerkhove** [comment]
We are using the latest Helm chart with the steps described above.

I will give master a try tomorrow.

**Comment by tomkerkhove** [comment]
> Sure thing, it's actually fairly simple to do:
> 
> 1. Install Dapr without HA enabled (`helm install dapr dapr/dapr`)
> 2. Change Dapr to enable HA (`helm upgrade dapr dapr/dapr --set global.ha.enabled=true`)
> 
> It will then fail with following error:
> 
> > Error: UPGRADE FAILED: cannot patch "dapr-placement-server" with kind StatefulSet: StatefulSet.apps "dapr-placement-server" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
> 
> So probably an uninstall would work, but that's not really a solution in my opinion as it impacts a lot of apps.

I applied the same steps using master branch and it gives the same outcome

![image](https://user-images.githubusercontent.com/4345663/125616484-1ba8d301-2b15-48f7-827b-dd8fb97ebd51.png)
![image](https://user-images.githubusercontent.com/4345663/125616496-976bfcc7-8e55-4113-8840-003adbcadca6.png)
![image](https://user-images.githubusercontent.com/4345663/125616508-503f5699-6dd9-4e10-a7d0-0b224008bb80.png)

**Comment by dmitsh** [comment]
@tomkerkhove , did you deploy any application after installing dapr?

**Comment by tomkerkhove** [comment]
Nope

**Comment by dmitsh** [comment]
Could you provide the following details about your AKS cluster:
 - VM size
 - VM set type (scale set or availability set)
 - Number of worker nodes

**Comment by tomkerkhove** [comment]
The scenarios I've tried are:
- Docker Desktop with Kubernetes (6 cores, 32 GB memory machine)
- AKS cluster with 5x DS2v2 nodes running Kubernetes 1.20.5 ([AKS-ARM.zip](https://github.com/dapr/docs/files/6820679/AKS-ARM.zip))
- AKS cluster with 1x D4asv4 nodes running Kubernetes 1.20.5

**Comment by dmitsh** [comment]
@tomkerkhove , I reproduced the error and I think I have a workaround.
Add `--set dapr_placement.cluster.forceInMemoryLog=true` to your upgrade command:
`helm upgrade dapr ./charts/dapr -n dapr-system --set global.ha.enabled=true --set dapr_placement.cluster.forceInMemoryLog=true`
LMK

**Comment by tomkerkhove** [comment]
I will give it a try, but can I revert it afterwards by setting it to false? (just confirming)

**Comment by dmitsh** [comment]
No, it has to remain `true`.
If you set it to `false`, you will get the error.
See this thread: https://github.com/helm/helm/issues/7998

**Comment by dmitsh** [comment]
@tomkerkhove, I did more digging, and now I have additional info.

The upgrade failure was expected, because placement service does not support transition from non-HA to HA mode, due to differences in data placement. In non-HA mode the data is stored in memory, while in HA mode the data is stored in Raft. During the upgrade, the current container is terminated, and the new container is started. There is no way to transfer data from memory between these containers.

The good news is that placement service is only used in actors runtime. In addition, Dapr actors don't require the placement service in order to work. 

To upgrade existing Dapr to HA, delete current placement stateful set, then issue `helm upgrade` command:
`kubectl delete statefulset.apps/dapr-placement-server -n dapr-system`
`helm upgrade dapr ./charts/dapr -n dapr-system --set global.ha.enabled=true`

**Comment by tomkerkhove** [comment]
Thanks for digging into this - But unfortunately we rely on Actors and cannot lose state.

> To upgrade existing Dapr to HA, delete current placement stateful set, then issue `helm upgrade` command:
> `kubectl delete statefulset.apps/dapr-placement-server -n dapr-system`
> `helm upgrade dapr ./charts/dapr -n dapr-system --set global.ha.enabled=true`

If we were to do the steps, what is impact our platform? What data loss can we expect?

Once this is cleared out, I'm happy to send a PR on this for the docs.

**Comment by orizohar** [comment]
Addressed in #1661

**Comment by dmitsh** [comment]
@tomkerkhove , we have updated documentation for v1.3.
Let us know if there is any unclarity left.

**Comment by tomkerkhove** [comment]
What's not clear to me yet is, if I use this approach - Do we lose any info with regards to actors? If so, what do we lose?

**Comment by artursouza** [comment]
@tomkerkhove You can have an outage for Actors during the change. Placement service does not hold data beyond which sidecar instances are up/down.

**Comment by tomkerkhove** [comment]
> To upgrade existing Dapr to HA, delete current placement stateful set, then issue `helm upgrade` command:
> `kubectl delete statefulset.apps/dapr-placement-server -n dapr-system`
> `helm upgrade dapr ./charts/dapr -n dapr-system --set global.ha.enabled=true`

This approach worked fine, thank you for your help and nice docs on it!

**Comment by dmitsh** [comment]
@tomkerkhove , thank you for confirming!
