### ISSUE TITLE
Move install CLI script behind a CDN with custom domain name

### ISSUE THREAD

**Issue by mukundansundar** [dapr/docs#1513]
**Describe the issue**
In getting started CLI, instead of the install script being got from master, it should be got from a CDN with dapr domain name. 

**URL of the docs**
https://docs.dapr.io/getting-started/install-dapr-cli/

And other occurrences of the same

**Expected content**
Change to
```
wget -q https://get.dapr.io/linux -O - | /bin/bash
```

```
wget -q https://get.dapr.io/macos -O - | /bin/bash
```

```
powershell -Command "iwr -useb https://get.dapr.io/windows | iex"
```

**Screenshots**

**Additional context**

**Comment by hhunter-ms** [comment]
@mukundansundar following up on this - is there a code issue/PR related to this?

**Comment by mukundansundar** [comment]
Not as of now ... This needs some discussion and then a change in website/docs to point to the right version of install script ...

**Comment by hhunter-ms** [comment]
closing for now until this is ready
