### ISSUE TITLE
VS Code Dapr Extension Documentation Update

### ISSUE THREAD

**Issue by jasonviviano** [dapr/docs#1533]
**Describe the issue**
Dapr Visual Studio Code webpage will need to be updated as extension starts adding new features and will need clearer examples as to not rely on the video to convey information to users.

**URL of the docs**
https://docs.dapr.io/developing-applications/ides/vscode/

**Expected content**
Will depend on features rolling out

**Comment by AaronCrawfis** [comment]
We should also split https://docs.dapr.io/developing-applications/ides/vscode/#remote-dev-containers into 3 sections:

- Extension
- Remote Dev Containers
- Troubleshooting/Debugging

**Comment by orizohar** [comment]
Addressed via #1687
