### ISSUE TITLE
GCP Pub/Sub Binding required fields

### ISSUE THREAD

**Issue by kb2ma** [dapr/docs#1534]
**Describe the issue**
Presently the GCP Pub/Sub Binding page shows that all metadata fields are required. However, I am able to successfully use this binding when providing only the fields below:
1. topic
2. type
3. project_id
4. private_key
5. client_email

Note that items 2-5 also are the only fields required for [GCP Secret Manager](https://docs.dapr.io/reference/components-reference/supported-secret-stores/gcp-secret-manager/). That's why I tried this experiment. The _topic_ field of course is specific to Pub/Sub.

Are these five fields in fact the only required ones for this binding?

**URL of the docs**
https://docs.dapr.io/reference/components-reference/supported-bindings/gcppubsub/

**Expected content**
Update the _Required_ column to "N" for non-required fields.

**Comment by AaronCrawfis** [comment]
![image](https://user-images.githubusercontent.com/54363786/121961157-e5e91180-cd1b-11eb-8ce7-a0902910b772.png)
Yep, looks like it's marking everything as required.

**Comment by kb2ma** [comment]
Thanks for the fix!
