### ISSUE TITLE
Alibaba Cloud TableStore state Component

### ISSUE THREAD

**Issue by theonefx** [dapr/docs#1535]
**What content needs to be created or modified?**
Alibaba Cloud TableStore state Component

**Additional context**
https://github.com/dapr/components-contrib/issues/1116

**Comment by CodeMonkeyLeet** [comment]
@AaronCrawfis Note that the corresponding components-contrib https://github.com/dapr/components-contrib/issues/914 and https://github.com/dapr/components-contrib/pull/915 are not currently being tracked for v1.3

**Comment by willtsai** [comment]
Looks like this was done as a part of https://github.com/dapr/docs/pull/1778 - think we can close this one.

**Comment by shubham1172** [comment]
@greenie-msft we should re-open this issue, #1778 closed the docs issue for adding a alicloud.tablestore **bindings**, this issue is for the **state** component that was added.
