### ISSUE TITLE
gRPC service extension examples won't run

### ISSUE THREAD

**Issue by jonashelgemo** [dapr/docs#1542]
**Describe the issue**
Dapr API in the Python SDK has changed, documentation examples do not run and gives errors

**URL of the docs**
This example fails: [https://docs.dapr.io/developing-applications/sdks/python/python-sdk-extensions/python-grpc/#listen-for-service-invocation-requests](https://docs.dapr.io/developing-applications/sdks/python/python-sdk-extensions/python-grpc/#listen-for-service-invocation-requests) 

**Expected content**
```
from dapr.ext.grpc import App, InvokeMethodRequest, InvokeMethodResponse

app = App()

@app.method(name='my-method')
def mymethod(request: InvokeServiceRequest) -> InvokeServiceResponse:
    print(request.metadata, flush=True)
    print(request.text(), flush=True)

    return InvokeServiceResponse(b'INVOKE_RECEIVED', "text/plain; charset=UTF-8")

app.run(50051)
```

**Screenshots**

**Additional context**
Seems to be correct in `master`: https://github.com/dapr/python-sdk/blob/master/examples/invoke-simple/invoke-receiver.py, so might be resolved when version is bumped

**Comment by AaronCrawfis** [comment]
Fixed by #1553
