### ISSUE TITLE
Azure Key Vault and Azure Key Vault w/ Managed Identity should be merged

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#1547]
**What content needs to be created or modified?**
https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault/
https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault-managed-identity/

**Describe the solution you'd like**
Merge these into one file named "Azure Key Vault"

**Additional context**
It's the same component, just different configuration

**Comment by AaronCrawfis** [comment]
Also need to callout that managed identity and standard are in different lifecycle status

**Comment by hhunter-ms** [comment]
Resolved - closing
