### ISSUE TITLE
Update component references and examples to always use secretKeyRef instead of clear text credentials

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#1566]
Update all yaml reference components to use secretRef instead of clear text credentials.

Will require:

- https://github.com/dapr/cli/issues/742
- https://github.com/dapr/cli/issues/741

**Comment by AaronCrawfis** [comment]
Mockup
![image](https://user-images.githubusercontent.com/54363786/123138081-8240a180-d409-11eb-8da8-e48ba18836f1.png)

**Comment by hhunter-ms** [comment]
Closing for now - will reopen or open a new issue when a local secret store at dapr init is actually in the works.
