### ISSUE TITLE
No Actors in Kubernetes Documentation

### ISSUE THREAD

**Issue by idjohnson** [dapr/docs#1572]
**What content needs to be created or modified?**
I cannot find anywhere information on deploying an actor into Dapr running on kubernetes.
I see a feature enablement listed (https://github.com/dapr/dapr/blob/db799ba12f35d811b2f30b587009702a4b085971/pkg/config/testdata/feature_config.yaml) but no information on deploying an actor into kubernetes.

**Describe the solution you'd like**
Extend the working example with .NET to include how to package and deploy (https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-actors/dotnet-actors-howto/) .  or just somewhere say how to launch an actor (needs a YAML like this and listen on these ports, etc)

**Where should the new material be placed?**
dapr/docs

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
N/A

**Additional context**
Happy to write the docs for you if you can point me at any info on getting an actor into Dapr in Kubernetes (not locally)

**Comment by halspang** [comment]
The feature that you referenced is a preview features ability and is actually part of Dapr core. In v1.2 it just happens to be the only preview feature. That being said, we could still use more documentation around launching actors and I could add some configuration to the example to make it compatible with local or k8s. To keep it relevant to docs, I'll also look and see if there's a good place to add documentation in the main pages.

**Comment by orizohar** [comment]
> The feature that you referenced is a preview features ability and is actually part of Dapr core. In v1.2 it just happens to be the only preview feature. That being said, we could still use more documentation around launching actors and I could add some configuration to the example to make it compatible with local or k8s. To keep it relevant to docs, I'll also look and see if there's a good place to add documentation in the main pages.

Based on this seems like this is related: https://github.com/dapr/docs/issues/1592

**Comment by hhunter-ms** [comment]
@halspang following up - is there an existing example for actors in k8s? I can definitely help add to docs if I have something to test/work from.

**Comment by hhunter-ms** [comment]
closing until someone creates an example for this that we can add to docs
