### ISSUE TITLE
metadata missing consumerGroup

### ISSUE THREAD

**Issue by iamazy** [dapr/docs#1575]
**What content needs to be created or modified?**

[metadata fields](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/) missing consumerGroup

**Describe the solution you'd like**

Add a consumerGroup field description in `Spec metadata fields` table

**Where should the new material be placed?**

## Spec metadata fields

| Field              | Required | Details | Example |
|--------------------|:--------:|---------|---------|
| brokers             | Y  | Comma separated list of kafka brokers  | `localhost:9092`, `dapr-kafka.myapp.svc.cluster.local:9092`
| consumerGroup  | N | Consumers label themselves with a consumer group name, and each record published to a topic is delivered to one consumer instance within each subscribing consumer group. | ""
| authRequired        | N  | Enable authentication on the Kafka broker. Defaults to `"false"`.   |`"true"`, `"false"`
| saslUsername        | N  | Username used for authentication. Only required if authRequired is set to true.   | `"adminuser"`
| saslPassword        | N  | Password used for authentication. Can be `secretKeyRef` to use a secret reference. Only required if authRequired is set to true. Can be `secretKeyRef` to use a [secret reference]({{< ref component-secrets.md >}})  |  `""`, `"KeFg23!"`
| maxMessageBytes | N  | The maximum message size allowed for a single Kafka message. Default is 1024. | `2048`

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/issues/928 
https://github.com/dapr/components-contrib/pull/965

**Additional context**

**Comment by CodeMonkeyLeet** [comment]
@AaronCrawfis We might want to pull this into tracking for v1.3 since the related code change and issue is in v1.3 tracking for components-contrib.

**Comment by CodeMonkeyLeet** [comment]
Closed by #1656
