### ISSUE TITLE
Last modified date shows `January 1, 0001` within SDK docs

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#1583]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/54363786/122792457-0d396480-d26f-11eb-812b-6f1361b306b0.png)

**Comment by AaronCrawfis** [comment]
Most likely due to the use of submodules within the SDK repos and docs.

Fix will require upstream docsy update to look at the child git information instead of the parent. Alternately we can just disable this feature, potentially just at the SDK docs level.

Related to the issue that the "Edit this page" button or "Create an issue" button doesn't work for submodule pages

**Comment by hhunter-ms** [comment]
Looks like this has been handled.
