### ISSUE TITLE
Need topic that list all the **preview features** and when they were introduced

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1592]
Each release can now have a list of preview features. Under Support there needs to be a table that list the preview features, which build they were introduced in, a link to the topic and which build they became GA in. This way there is a single table in the docs updated after each release, that clearly provides the latest information, rather than searching through multiple docs and having to update them.

**Comment by orizohar** [comment]
Looks like we are already listing the current preview features in https://docs.dapr.io/operations/configuration/preview-features/ I think support is the right place for this. It would be better if we have "one source of truth" under support and the list in the page link above just sends the reader there.
@halspang please include this in your work on the issue

**Comment by msfussell** [comment]
This is different. This is a how to. We need the actual list of features.

**Comment by msfussell** [comment]
Content created and merged
