### ISSUE TITLE
Actors reminder and triggers support ISO 8601 intervals standard format

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1600]
This is to document https://github.com/dapr/dapr/pull/3095 (and dup https://github.com/dapr/dapr/issues/2513)
Update the Reference Documentation here https://docs.dapr.io/reference/api/actors_api/#create-actor-reminder and https://docs.dapr.io/reference/api/actors_api/#create-actor-timer

This also can be documented in the SDKs.

**Comment by berndverst** [comment]
A few things to add here:

Only a single one of the possible ISO 8601 recurrence formats is supported. The standard technically also allows to optionally specify a start date, end date, or both. That's how one could say repeat weekly on Mondays at 2 pm. However we do not support this.

Additionally, it does not appear we support the case where the recurrence number is `-1` which would be an indefinite repeat.

We need to be clear that we only support repeating intervals from the current time (implicit) and that the recurrence number if provided must be positive.

**Comment by orizohar** [comment]
@jigargandhi - we really need to get this merged in. We are at the endgame of v1.3 that is targeted to be released next week. Can you submit a PR asap?

**Comment by msfussell** [comment]
Content created and merged
