### ISSUE TITLE
Add the use of OpenTelemetry SDKs for observability when creating scopes/spans

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1606]
The current docs describing trace headers and how to create spans refer to using the OpenCensus SDK here https://docs.dapr.io/developing-applications/building-blocks/observability/w3c-tracing/w3c-tracing-howto/

These docs need to be updated to describe how to use the OpenTelemetry SDK with Dapr for creating new scopes and spans and coping the W3C traceheader as the prefer method going forward to answers questions like this https://discordapp.com/channels/778680217417809931/780574672495312936/859637474363572224 and with suggestions like this https://discordapp.com/channels/778680217417809931/780574672495312936/859957286192545822

**Comment by andreatosato** [comment]
I can help

**Comment by andreatosato** [comment]
@msfussell
I create sample with angular frontend and this npm package: [opentelemetry-angular-interceptor](https://jufab.github.io/opentelemetry-angular-interceptor/)
I see all trace correctly without change any DAPR code.

I need to try a microservices with Open Telemetry, so I can describe all steps in docs.
I think that _W3C traceheader_ is no longer necessary, but I need to test it.

**Comment by msfussell** [comment]
@andreatosato - Following up here. Realize this has been a while. Would appreciate help with your investigation here and on how to structure the docs.

**Comment by hhunter-ms** [comment]
@andreatosato friendly bump. I can help with docs if necessary.
