### ISSUE TITLE
Adding documentation for the new GraphQL binding

### ISSUE THREAD

**Issue by amirmm11** [dapr/docs#1612]
**What content needs to be created or modified?**
Adding documentation for the new GraphQL binding

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/docs/pull/1613

**Additional context**

**Comment by msfussell** [comment]
Content created merged in v1.3
