### ISSUE TITLE
component pubsub can not use redis  cluster

### ISSUE THREAD

**Issue by Huawu777** [dapr/docs#1615]
![image](https://user-images.githubusercontent.com/14233576/124577865-40d7d980-de80-11eb-8894-671fb8292623.png)

Result:

![image](https://user-images.githubusercontent.com/14233576/124578107-7e3c6700-de80-11eb-9aeb-2475f8f0ec56.png)

but when i set 
'redis-cluster-0.redis.svc.cluster.local:6379`,it works

**Comment by AaronCrawfis** [comment]
Hi @Sunny5151 in your screenshot your component is of type `state.redis`. For cluster behavior in pubsub please use component type `pubsub.redis`. https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/

**Comment by Huawu777** [comment]
oh,my bad。

**so the component of  type state.redis can not use cluster?**

![image](https://user-images.githubusercontent.com/14233576/124689873-e2f0d380-df0b-11eb-820d-71b9b9a0c2f3.png)
