### ISSUE TITLE
Clarify Step 9 Configure the Azure Identity and AzureIdentityBinding yaml

### ISSUE THREAD

**Issue by HectorMeneses333** [dapr/docs#1619]
**What content needs to be created or modified?**
in step 9 Configure the Azure Identity and AzureIdentityBinding yaml

Provide more info on how to get the following:
    name: [your managed identity name]
    resourceID: [your managed identity id]
    clientID: [your managed identity Client ID]
    selector: [your managed identity selector]

Specially "selector"... what is that?

Thanks!

**Comment by berndverst** [comment]
@HectorMeneses333 authenticating to Azure via managed system identity is done via an additional tool not provided by Dapr called AAD pod identity. For convenience AKS makes it easy to deploy AAD pod identity. For all the info you could want see: https://azure.github.io/aad-pod-identity/docs/

In the `AzureIdentityBinding` spec you specify a selector name you want to use to inject this identity into pods. This can be any name you want. Let's say `myaadidentity`

Then in the pods that should receive that very identity you created you add labels of the form `aadpodidbinding: "myaadidentity"`

**Comment by hhunter-ms** [comment]
closing as it seems to have been resolved - feel free to reopen as new issue
