### ISSUE TITLE
State Management - Inconsistency in value vs data

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/docs#1638]
**URL of the docs page**

https://docs.dapr.io/reference/api/state_api/#example-2
and
https://docs.dapr.io/reference/api/state_api/#request-body

**How is it currently worded?**

State Save - Request: utilizes properties `key` and `value`
State Get - Response: utilizes properties `key` and `data` 🤔

**How should it be worded?**

`key` and `value`

**Screenshots**

**Additional context**

Might make sense to also make the response return `key` and `value` instead of `data` seeing that the request for saving the state requires `value`. In the end, value can contain a JSON object or a String object, so either `data` or `value` would make sense, but I would like to see consistency in the request and response

**Comment by hhunter-ms** [comment]
@XavierGeerinck I opened a PR, but this was tested and 'data' is seen in the bulk get... could you clarify what exactly is incorrect or needs to be fixed?

**Comment by XavierGeerinck** [comment]
Thanks! That was it :)
