### ISSUE TITLE
Documentation dapr-operator Readme link does not available in installing-dapr-on-a-kubernetes-cluster

### ISSUE THREAD

**Issue by younss** [dapr/docs#164]
this link does not exist http://github.com/dapr/dapr/blob/master/charts/dapr-operator/README.md
on https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#installing-dapr-on-a-kubernetes-cluster

**Comment by yaron2** [comment]
Thanks, fixing PR submitted.

**Comment by yaron2** [comment]
Merged. Recheck the link.
