### ISSUE TITLE
Update docs for sidecar listen behavior on Kubernetes

### ISSUE THREAD

**Issue by wcs1only** [dapr/docs#1654]
**What content needs to be created or modified?**

Change is here: https://github.com/dapr/dapr/pull/3429

This table needs to be updated for sure: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-annotations/

Maybe a note here? I have to think about it, I don't think any of these docs create an expectation that dapr would be available on anything other than localhost: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/

**Comment by hhunter-ms** [comment]
looks like this was resolved - closing
