### ISSUE TITLE
Update docs add new binding AWS SES

### ISSUE THREAD

**Issue by fjvela** [dapr/docs#1667]
**What content needs to be created or modified?**
Add docs for new binding AWS SES 

**Describe the solution you'd like**

**Where should the new material be placed?**
https://docs.dapr.io/reference/components-reference/supported-bindings/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
- dapr: https://github.com/dapr/dapr/pull/3550
- componentes: https://github.com/dapr/components-contrib/issues/1019

**Additional context**

**Comment by msfussell** [comment]
Resolved
