### ISSUE TITLE
Update the list of supported Dapr versions for v1.3 

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1684]
Need to update the list of Dapr supported versions. This table https://v1-1.docs.dapr.io/operations/support/support-release-policy/#supported-versions

This is also missing the hotfix release from the v1.2 release. v1.2.1. and v1.2.2 should be included with the dates of the releases.

Also add 1.3.0 release.

**Comment by greenie-msft** [comment]
Content updated and merged
