### ISSUE TITLE
Missing TTL for actors timers and reminders

### ISSUE THREAD

**Issue by dmitsh** [dapr/docs#1700]
**What content needs to be created or modified?**
Although there is information on timers and reminders the added TTL feature has not be included. This needs adding

The actors overview page mentions timers and reminders without introducing these terms and explaining their purpose and differences.

**Describe the solution you'd like**

Adding an overview for timers and reminders
**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by AaronCrawfis** [comment]
@dmitsh  Does https://docs.dapr.io/developing-applications/building-blocks/actors/howto-actors/#actor-timers and https://docs.dapr.io/developing-applications/building-blocks/actors/howto-actors/#actor-reminders match what you're wanting?

**Comment by msfussell** [comment]
Reopening this issue to account for the added TTL functionality on Timers and Reminders as added here https://github.com/dapr/dapr/issues/2906

**Comment by msfussell** [comment]
This has been added
