### ISSUE TITLE
Add documentation for extending of configuring HTTP and gRPC servers

### ISSUE THREAD

**Issue by apuzyrevsky** [dapr/docs#1708]
**What content needs to be created or modified?**
add documentation for adding read buffer size argument to fasthttp server and grpc server  https://github.com/dapr/dapr/issues/3319

**Describe the solution you'd like**
I will provide a pull request, please assign this task to me
**Where should the new material be placed?**
https://docs.dapr.io/reference/arguments-annotations-overview/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/3346

**Comment by Taction** [comment]
@apuzyrevsky Hi, thanks for your contribution! The pr has been merged, would you mind fixing the doc？
