### ISSUE TITLE
Topic creation is not detailed enough

### ISSUE THREAD

**Issue by FunnyYish** [dapr/docs#1714]
**What content needs to be created or modified?**

page: https://docs.dapr.io/operations/components/setup-pubsub/
Topic creation. This part requires users to create their own topics, but different Messaging brokers have different Messaging models. For example, RabbitMQ has only Exchange and Queue, Binding,Users don't know how to use them to create the topics needed for DAPR

**Describe the solution you'd like**
add link for detail

**Comment by msfussell** [comment]
@FunnyYish - Would like to see the details that you think should be here

**Comment by hhunter-ms** [comment]
Closing for now - feel free to reopen as a new issue if necessary
