### ISSUE TITLE
Redis component needs to include enableTLS:true for Azure Redis Cache

### ISSUE THREAD

**Issue by rishabhsaha** [dapr/docs#1719]
**Describe the issue**
Hi, in the step to use Azure Redis Cache the docs mention to use port 6380 which is over TLS. But the component doesn't mention the enableTLS flag which means the sidecar can't connect with Azure Redis Cache if one follows the component definition in the doc.
**URL of the docs**
https://docs.dapr.io/getting-started/configure-state-pubsub/#create-pubsub-message-broker-component

**Expected content**
enableTLS: true needs to be included in the component definition for Azure Redis Cache over port 6380

**Screenshots**
![image](https://user-images.githubusercontent.com/12716801/129409330-0c79e1a2-38ae-429e-8a93-4d1152081885.png)
![image](https://user-images.githubusercontent.com/12716801/129409377-703a3daf-7d5f-421c-a9c3-ebfbfcf34c9f.png)

**Additional context**

**Comment by yaron2** [comment]
That's a good call out, and true for AWS ElasticCache also.

Would you like to open a PR to make this notable to users?

**Comment by rishabhsaha** [comment]
Will do. Thanks!

**Comment by msfussell** [comment]
FIXED
