### ISSUE TITLE
Two different meanings of the startAtTimeDelta parameter

### ISSUE THREAD

**Issue by tpiperatgod** [dapr/docs#1721]
**Describe the issue**

Hi, I'm learning how to configure nats pubsub and then noticed that it has two startAtTimeDelta parameters, in context I think the last startAtTimeDelta should be startAtTimeFormat?

**URL of the docs**

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-nats-streaming/

**Expected content**

The last startAtTimeDelta should be startAtTimeFormat?

**Screenshots**

![image](https://user-images.githubusercontent.com/2360535/129502157-7b1bcc26-bf97-44c2-941c-a06f5e6eb0e6.png)

**Additional context**

none

**Comment by CodeMonkeyLeet** [comment]
Yes, that's right, thanks for the catch!
