### ISSUE TITLE
Update S3 binding 

### ISSUE THREAD

**Issue by fjvela** [dapr/docs#1722]
**What content needs to be created or modified?**
Update S3 binding, add documentation:

- update create operation: support upload files in base64, return location and version id
- add get operation
- add delete operation
- add list operation

**Describe the solution you'd like**

**Where should the new material be placed?**

https://docs.dapr.io/reference/components-reference/supported-bindings/s3/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1081

**Additional context**

**Comment by CodeMonkeyLeet** [comment]
@orizohar FYI, it looks like the related code tasks for this are going to be for v1.4, so you might want to track this as well.
