### ISSUE TITLE
Typo on dapr.io Homepage

### ISSUE THREAD

**Issue by howlowck** [dapr/docs#1724]
**URL of the docs page**
https://docs.dapr.io/

**How is it currently worded?**
"secretes"

**How should it be worded?**
"secrets"

**Screenshots**
![image](https://user-images.githubusercontent.com/338265/129609294-c4dd1d97-b60e-4634-be29-0244b7c2188a.png)

**Additional context**
NA

**Comment by yaron2** [comment]
Thanks for bringing this up! this is now fixed (website should update within the next hour).
