### ISSUE TITLE
Document more attributes for Azure Service Bus pubsub

### ISSUE THREAD

**Issue by artursouza** [dapr/docs#1727]
**What content needs to be created or modified?**
`ConsumerID` is in the ASB pubsub component code but not documented in docs. There might be others too.

**Describe the solution you'd like**
All metadata attributes for ASB pubsub component are documented.

**Where should the new material be placed?**
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
Code is already live.

**Additional context**
Relates to: https://github.com/dapr/components-contrib/issues/378

**Comment by nyemade-uversky** [comment]
@halspang Wanted to check in on this issue to see if you'd be able to get the metadata attributes documented for the Azure Service Bus (ASB) pubsub component.

I checked the [docs for ASB ](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/), and it looks like we're missing these three metadata attributes in the docs:

- MaxConnectionRecoveryInSec
- MinConnectionRecoveryInSec


Once we get these attributes documented in the _Spec metadata fields_ table this issue should be good to close.

**Comment by berndverst** [comment]
@ItalyPaleAle is this something you can help @halspang with? You both touched these components the most.

**Comment by ItalyPaleAle** [comment]
👋 @nyemade-uversky ! Those metadata options are new for 1.8 and you can find them in the docs here: https://v1-8.docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/

I went thorough the docs when I made the updates for the new service bus components landing in 1.8. However I am not excluding the possibility that I may have missed something!

**Comment by nyemade-uversky** [comment]
@ItalyPaleAle Just checked and both MaxConnectionRecoveryInSec and MinConnectionRecoveryInSec are documented in the link you shared.

@greenie-msft and @msfussell This Issue can be closed, all ASB metadata attributes in the ASB [ metadata.go](https://github.com/dapr/components-contrib/blob/master/pubsub/azure/servicebus/metadata.go) file are reflected in the 1.8 docs.

**Comment by msfussell** [comment]
Resolved
