### ISSUE TITLE
what is the use of dapr placement running in docker while standalone mode?

### ISSUE THREAD

**Issue by gItSpLasHeR** [dapr/docs#174]
hi,
try with standalone sample, and notice there is a dapr_placement running in the docker, i try to find something about it in doc but no luck, would anyone tell me what it is? 
is it the dapr runtime in below overview picture?

<img width="607" alt="overview_standalone" src="https://user-images.githubusercontent.com/8559113/67165731-53179880-f3bb-11e9-844c-faaed2da2682.png">

**Comment by amanbha** [comment]
The placement service provided a distributed hashing, it's used by Dapr runtimes to distribute the actor instances across various pods of the user service.
https://github.com/dapr/docs/blob/master/concepts/actor/actor_overview.md#distribution-and-failover

**Comment by benc-uk** [comment]
I was wondering exactly the same as @gItSpLasHeR, and also found nothing in the docs.

Does this mean if you're not using the actors "feature" of dapr, the placement service plays no role?
Putting actor in the name would make this clearer

**Comment by msfussell** [comment]
Yes, the "placement" service is only used for actor capability, to hash the value of a particular actor type to a given pods in the user service.

**Comment by yaron2** [comment]
@benc-uk currently the placement service is only used to place actors in hash tables; for the future, we might leverage the placement service for more general purpose uses..

**Comment by msfussell** [comment]
I updated the overview diagrams to show the Placement service https://github.com/dapr/docs/blob/master/overview.md#running-dapr-on-a-local-developer-machine-in-standalone-mode and also provided a description with a diagram on how the placement services for actors works in the actors overview here https://github.com/dapr/docs/blob/master/concepts/actor/actor_overview.md#distribution-and-failover

**Comment by msfussell** [comment]
Diagrams updated in latest docs

**Comment by greghoover** [comment]
Update links from above:
https://github.com/dapr/docs/tree/master/overview#running-dapr-on-a-local-developer-machine-in-self-hosted-mode
https://github.com/dapr/docs/tree/master/concepts/actors#distribution-and-failover

**Comment by jaypaddy** [comment]
Both these links are 404
https://github.com/dapr/docs/tree/master/overview#running-dapr-on-a-local-developer-machine-in-self-hosted-mode
https://github.com/dapr/docs/tree/master/concepts/actors#distribution-and-failover

However found this and it works and has a good description of the placement service
https://github.com/dapr/docs/blob/v0.6.0/concepts/actors/README.md#actor-placement-service

**Comment by zicjin** [comment]
> @benc-uk currently the placement service is only used to place actors in hash tables; for the future, we might leverage the placement service for more general purpose uses..

Excuse me, I want to know is this means that simply deploying serviceA and serviceB on two bare metals (without k8s) cannot invoke each other using "Service invocation"? Because their respective daprd cannot know the existence of the other's daprds.

Including up two unrelated docker-compose.yml on a single bare metal?
