### ISSUE TITLE
Add documentation for GCP Pub/Sub Message Ordering Configuration

### ISSUE THREAD

**Issue by LLKennedy** [dapr/docs#1742]
**What content needs to be created or modified?**

A feature is being added to dapr/components-contrib to allow configuration of message ordering in GCP Pub/Sub subscriptions. This new configuration option should be documented.

**Describe the solution you'd like**

The existence, usage and valid values of the configuration option should be added to the appropriate section of existing documentation for configuring the GCP Pub/Sub integration component.

**Where should the new material be placed?**

Reference -> Component Specs -> Pub/sub brokers -> GCP Pub/Sub

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/issues/1098

**Additional context**

**Comment by CodeMonkeyLeet** [comment]
Copying a documentation note from https://github.com/dapr/components-contrib/pull/1099:

The GCP pubsub [Subscription.Config](https://pkg.go.dev/cloud.google.com/go/pubsub#SubscriptionConfig) has the following comment on the use of `EnableMessageOrdering`:

>// When calling Subscription.Receive(), the client will check this
>// value with a call to Subscription.Config(), which requires the
>// roles/viewer or roles/pubsub.viewer role on your service account.
>// If that call fails, mesages with ordering keys will be delivered in order.

New docs should capture any additional permissions configuration on the GCP pubsub service when using this feature, if necessary.

**Comment by yaron2** [comment]
@LLKennedy can you please open a PR for this change? this is now merged in components-contrib.
