### ISSUE TITLE
Docs update for dapr/components-contrib#1104

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#1756]
**What content needs to be created or modified?**

> **Note: this issue depends on #1755. That needs to be addressed first.**

When https://github.com/dapr/components-contrib/issues/1104 is merged, we will need to update the following pages adding information on how to authenticate using the "common Azure auth layer" (which supports Azure AD auth), _in alternative_ to the current master key authentication.

Pages impacted:

- https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/
- https://docs.dapr.io/reference/components-reference/supported-bindings/cosmosdb/

**Describe the solution you'd like**

Those docs need to be updated to point out that authentication can happen in one of two ways:

- Using `masterKey` (current option)
- Using Azure AD -> this should link back to the docs on using the "common Azure auth layer"

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/issues/1104

**Comment by msfussell** [comment]
@ItalyPaleAle - Please verify whether this can be closed?

**Comment by ItalyPaleAle** [comment]
Yes thanks for checking.
