### ISSUE TITLE
Running powershell cmd requires TLS 1.2 (which is not enabled by default)

### ISSUE THREAD

**Issue by hansker8** [dapr/docs#1763]
**Describe the issue**
When running the powershell command to install Dapr CLI, you get an error "iwr : The request was aborted: Could not create SSL/TLS secure channel."

**URL of the docs**
https://v1-rc1.docs.dapr.io/getting-started/install-dapr-cli/

**Expected content**
Need to run powershell, the run: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
followed by breaking up the powershell command

**Screenshots**
See error message above in Describe the issue

**Additional context**

solution found here: https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

**Comment by hhunter-ms** [comment]
docs are correct for now - closing
