### ISSUE TITLE
v1.4 docs release endgame

### ISSUE THREAD

**Issue by orizohar** [dapr/docs#1764]
## v1.3 Branch

In pending PR:

- [x] Add v1.4 (latest) to nav bar
- [x] Archive notice
- [x] Update root README.md
- [x] Update URL in config.toml
- [x] Delete workflow file

Day of:
- [x] Push v1.3 PR

## v1.4 Branch

In a pending PR:

- [x] Update README.md
- [x] Update version dropdown in nav bar
- [x] Supported versions section
- [x] All output logs change 1.3 to 1.4
- [x] Update URL in config.toml
- [x] Update workflow for docs.dapr.io to v1.4 branch
- [x] Update quickstart page links to the latest release branch (requires quickstarts to cut a release branch)

Day of: 

- [x] Push v1.4 PR

## GitHub

- [x] Make v1.4 the default branch
- [x] One last upmerge
- [x] Create v1.5 branch

## Website

- [x] Create new website for v1.5
- [x] Add custom domain & generate SSL certificate

## DNS Portal

- [x] Add DNS entry for new website

## v1.5 Branch

- [x]  Update website workflow file
- [x]  Upmerge from release branch to preview branch

**Comment by willtsai** [comment]
Use PRs from v1.3 release as reference:
https://github.com/dapr/docs/pull/1683
https://github.com/dapr/docs/pull/1682

**Comment by willtsai** [comment]
PR for v1.3 branch - https://github.com/dapr/docs/pull/1775

**Comment by willtsai** [comment]
PRs for v1.4 branch - https://github.com/dapr/docs/pull/1776 & https://github.com/dapr/docs/pull/1773
