### ISSUE TITLE
Remove Codespaces Beta Alert

### ISSUE THREAD

**Issue by greenie-msft** [dapr/docs#1768]
**Describe the issue**
Collaboration with Codespaces docs refer to Codespaces being in beta (https://docs.dapr.io/contributing/codespaces/). Codespaces is now GA and that should be reflected in the docs. 

**URL of the docs**
https://docs.dapr.io/contributing/codespaces/

**Expected content**
Remove Codespaces beta language

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
FIXED
