### ISSUE TITLE
Wrong parameters in python invoke examples

### ISSUE THREAD

**Issue by espenairmine** [dapr/docs#1779]
**Describe the issue**
Example python invoke example is using the wrong variable name, **name** instead of **binding_name**:

`resp = d.invoke_binding(name='kafkaBinding', operation='create', data='{"message":"Hello World"}')
`

 https://docs.dapr.io/developing-applications/sdks/python/python-client/#interact-with-output-bindings

**Expected content**

resp = d.invoke_binding(**binding_name**='kafkaBinding', operation='create', data='{"message":"Hello World"}')

**Comment by msfussell** [comment]
@berndverst - Can you take a look at this?

**Comment by berndverst** [comment]
@msfussell @greenie-msft this was merged 10 days ago -- can you update the git submodule for Python and redeploy the docs?
