### ISSUE TITLE
Create the doc or sample for Dapr user app integration test

### ISSUE THREAD

**Issue by youngbupark** [dapr/docs#179]
## Describe the proposal

This is the issue to track the [Gitter conversation](https://gitter.im/Dapr/community?at=5dab95a50ac62f4acda2873b)

A user wants to know how to run integration test against Dapr user apps when he has multiple Dapr apps. Their integration tests must be run with Dapr to talk to the different dapr apps. 

There should be multiple ways to do integration test for dapr user apps in their local dev environment. It will be helpful to provide the docs and samples to run the integration tests for user apps.

**Comment by riezebosch** [comment]
Please, check out the example I crafted: https://github.com/riezebosch/dapr-tdd

**Comment by willtsai** [comment]
@riezebosch - thanks for sharing! Is this something you'd be interested to contribute to the Dapr project? 
https://docs.dapr.io/contributing/contributing-overview/
https://docs.dapr.io/contributing/contributing-docs/
