### ISSUE TITLE
Update gcp bucket binding

### ISSUE THREAD

**Issue by fjvela** [dapr/docs#1790]
**What content needs to be created or modified?**
Update gcp bucket binding, add documentation:

- update create operation: support upload files in base64, return location
- add get operation
- add delete operation
- add list operation

**Describe the solution you'd like**

**Where should the new material be placed?**

https://docs.dapr.io/reference/components-reference/supported-bindings/gcpbucket/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1128

**Additional context**

**Comment by greenie-msft** [comment]
Closing as https://github.com/dapr/docs/pull/1792 was merged
