### ISSUE TITLE
Typo in setup-sqlserver.md reference file

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/docs#1793]
**URL of the docs page**
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-sqlserver/

**How is it currently worded?**
> If you wish to use Redis as an actor state store, append the following to the yaml.

**How should it be worded?**
If you wish to use SQL server as an actor state store, append the following to the yaml.

**Comment by msfussell** [comment]
Fixed.
