### ISSUE TITLE
Missing simicolon in Python code example for state store  

### ISSUE THREAD

**Issue by ryou90** [dapr/docs#1803]
**Describe the issue**
Missing simicolon in the Python code example for state store, after metadata param tuple. So without the simicolon, dapr throws exeception:  _... too many values to unpack (expected 2) ..._

```
from dapr.clients import DaprClient

with DaprClient() as d:
    d.save_state(
        store_name="statestore",
        key="myFirstKey",
        value="myFirstValue",
        metadata=(
            ('ttlInSeconds', '120'), <-- missing
        )
    )
    print("State has been stored")
```

**URL of the docs**
https://github.com/dapr/docs/blob/v1.4/daprdocs/content/en/developing-applications/building-blocks/state-management/state-store-ttl.md

**Expected content**
Add simicolon after param tuple

**Comment by anneum** [comment]
Same for https://github.com/dapr/docs/blob/v1.4/daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-raw.md and the keyword argument is wrong (`topic_name` instead of `topic`)

```
from dapr.clients import DaprClient

with DaprClient() as d:
    req_data = {
        'order-number': '345'
    }
    # Create a typed message with content type and body
    resp = d.publish_event(
        pubsub_name='pubsub',
        topic='TOPIC_A',          <-- wrong keyword argument (
        data=json.dumps(req_data),
        metadata=(
                     ('rawPayload', 'true'), <-- missing
                 )
    )
    # Print the request
    print(req_data, flush=True)
```

**Comment by msfussell** [comment]
@berndverst  - Could you take a look at these examples?
