### ISSUE TITLE
Microsoft CDM

### ISSUE THREAD

**Issue by sing-ideas** [dapr/docs#1804]
**What content needs to be created or modified?**
We are learning Microsoft CDM and we like DAPR as a solution to avoid vendor lock-in, but we wish to use CDM to add custom entities.

**Describe the solution you'd like**
How can we use CDM to build our database via DAPR without vendor lock-in like Azure SQL or Datalake. 
We may use on-premise/cloud/hybrid infrastructure and we will be using MS SQL / MY SQL / Neo4J depending on the project

**Where should the new material be placed?**
in Microsoft CDM and DAPR

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
Best to have a discussion about this on discord alias or come with a proposal. Please open this issue is you have more information or questions to add.
