### ISSUE TITLE
docker images not running when init success

### ISSUE THREAD

**Issue by jwenjian** [dapr/docs#181]
## Expected Behavior

when `sudo dapr init` finished with success, the docker container `dapr` and `redis` are running as the doc said

## Actual Behavior
`sudo dapr init` finished with success, output `Success! Dapr is up and running`

but when I check the `sudo docker ps`, it shows no images are running

## Steps to Reproduce the Problem

OS: Ubuntu server, 1804
Virtual box on Win7

**Comment by jwenjian** [comment]
`sudo dapr uninstall` report below error:

```
Removing Dapr from your cluster...
Error removing Dapr: Dapr Placement Container may not exist
```

**Comment by yaron2** [comment]
The uninstall message makes sense as there's no placement container running.

Can you try running without sudo and report what happens?

**Comment by jwenjian** [comment]
I need to run my docker using sudo, so `dapr init` report below error:

```
Could not connect to Docker. Is Docker installed and running?
```

@yaron2

**Comment by yaron2** [comment]
Can you run docker ps -a and see if there are any exited containers?

**Comment by jwenjian** [comment]
no containers, @yaron2

**Comment by jwenjian** [comment]
ahhhh. I got it, my docker need to work behind a proxy, I must config proxy server to make docker can pull images from docker hub.

It now works.

Thanks for your help.

---
Would be better to update the doc if necessary: before `sudo dapr init`, need to make sure `sudo docker pull hello-world` works.

**Comment by jwenjian** [comment]
It still be weired that `dapr init` tells me success, would be better to check the `docker ps` output and report failed in my case.

**Comment by yaron2** [comment]
Yep you're right. I'll open an issue to track it.

**Comment by yaron2** [comment]
Tracked here: https://github.com/dapr/cli/issues/179
