### ISSUE TITLE
The source diagrams for the documentation are not available

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1812]
The source for the diagrams used in documentation need to be published into the docs repo, so that new diagrams can be added and existing one updated when needed. Currently these are only static images and are inconsistent.

**Comment by msfussell** [comment]
The added links here https://v1-7.docs.dapr.io/contributing/contributing-docs/#diagrams-and-images for the deck and images are broken

**Comment by greenie-msft** [comment]
Addressed in #2314

**Comment by greenie-msft** [comment]
@msfussell This PR fixes the issue: https://github.com/dapr/docs/pull/2333

**Comment by msfussell** [comment]
FIXED
