### ISSUE TITLE
Using pub/sub and bindings inside actors

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/docs#183]
Is it currently possible to use pub/sub and bindings inside of actors?

E.g. instead of a client needs to use an actor proxy, the client can publish a message on a topic and individual actors (or maybe all of a specific actor type) can subscribe to these messages > each message triggers an actor method. Same scenario with bindings...

If it's possible, the documentation is missing.
If not - this would be very helpful and eliminate the need to put a service between the topic/binding and an actor.

**Comment by yaron2** [comment]
This is on our roadmap, and indeed a very useful feature to add.

cc @amanbha

**Comment by amanbha** [comment]
Yes, its tracked with this issue https://github.com/dapr/dapr/issues/501 in dapr/dapr repo.
