### ISSUE TITLE
The tabs don't switch to instructions for different OS on the Install Dapr cli page

### ISSUE THREAD

**Issue by faysou** [dapr/docs#1831]
**Describe the bug**
The tabs don't switch to instructions for different OS on this page:
https://docs.dapr.io/getting-started/install-dapr-cli/

**Steps to reproduce**
Go to the page
Click on different tabs

**Expected behavior**
Different instructions for different OS

**Desktop (please complete the following information):**
Windows 10 (Chrome and Edge)

**Comment by aktxyz** [comment]
+1 just found this also

from chrome console for windows
```
$('#tabs-2-linux').hide();
$('#tabs-2-windows').show();
$('#tabs-2-windows').css('opacity','1.0');
```

**Comment by AaronCrawfis** [comment]
Thank you for reporting! Are you currently running a VPN? We're tracking this issue: #1245 (actually it's #900), which might cause this.

@willtsai could you take a look at overriding the script that controls tabs with one that works in all geos?

**Comment by willtsai** [comment]
@AaronCrawfis - I can help with this, assigned to myself.

**Comment by aktxyz** [comment]
@AaronCrawfis actually I am running a VPN

**Comment by hhunter-ms** [comment]
It looks like this was resolved. Closing this issue.
