### ISSUE TITLE
Doc complement for dapr/components-contrib#883

### ISSUE THREAD

**Issue by beiwei30** [dapr/docs#1834]
**What content needs to be created or modified?**

Need a doc to describe the behavior/configuration change in dapr/components-contrib#883

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by yaron2** [comment]
Assigned to `1.5`.

**Comment by greenie-msft** [comment]
Closing as https://github.com/dapr/docs/pull/1844 has been merged.
