### ISSUE TITLE
SP Role Assignment to access Key Vault lacks permission to retrieve secrets 

### ISSUE THREAD

**Issue by kendallroden** [dapr/docs#1837]
**Describe the issue**
In the Key Vault component docs, the role assignment suggested for the Azure AD application is “Key Vault Crypto Officer” which is described as having "broad access". The majority of users will use this assignment and make the assumption it is going to allow them to access secrets. However, this role does not allow you to access KV secrets. In order to prevent customers from running into 403 issues when trying to make use of the component, I believe a different role should be recommended. Another solution would be to provide a link to the official RBAC docs and tell them to choose the appropriate role based on what they are trying to accomplish.

**URL of the docs**
https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault/

**Expected content**
I assign a role to the Service Principal that allows it to read secrets from Key Vault i.e. Key Vault Secrets Officer vs. Key Vault Crypto Officer. I tested this via REST APIs and also made the respective change in role assignment for the SP to resolve the issue.

**Screenshots**
If I try to reference the Azure Key Vault component in a different component to retrieve a secret- I will get the following error using the recommended role. While it makes sense based on the role permissions, it isn't intuitive based on the docs to think that secrets would not be retrievable using the above role
<img width="1166" alt="Screen Shot 2021-10-04 at 3 37 15 PM" src="https://user-images.githubusercontent.com/22015135/136102178-1570d99a-8e2f-40f0-af1f-0661ca0111bc.png">
>
![Screen Shot 2021-10-05 at 4 04 30 PM](https://user-images.githubusercontent.com/22015135/136102534-5bb2fc78-32fb-4c10-9327-a1a20b73aa62.png)

**Comment by kendallroden** [comment]
For visibility @paulyuk @yaron2 @alicejgibbons

**Comment by msfussell** [comment]
Closed with this PR https://github.com/dapr/docs/pull/2256

**Comment by msfussell** [comment]
@kendallroden PTAL.
