### ISSUE TITLE
Actor idle timeout / actor scan interval

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/docs#184]
In the logs you can find
` msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"`

Questions:
- What means "actor scan interval"?
- How can actor idle timeout be configured?

In some scenarios, it would also be helpful to deactivate automatic Dapr Actors runtime garbage-collection at all

**Comment by amanbha** [comment]
@RicardoNiepel This is used for controlling the Actor deactivation behavior. Dapr runtime scans at "scan interval" to see if actor can be GC'd if its idle foe "idle timeout". You would be able to pass this information when Dapr runtime calls into Actor service to get  supported type. In this preview release its not supported, but eventually the settings would be provided when you register an Actor type what runtime. It would be configurable so you can increase the value.

**Comment by RicardoNiepel** [comment]
Is this already documented?

I could not find anything at https://github.com/dapr/docs/blob/master/reference/api/actors.md regarding the discovery and available options

**Comment by amanbha** [comment]
Discovery is mentioned here https://github.com/dapr/docs/blob/master/reference/api/actors.md#get-registered-actors , Its missing the example for what it shoudl return, we will add it, Thanks for reporting it.
cc @shalabhms
