### ISSUE TITLE
Description of DAPR_HOST_IP is missing in docs

### ISSUE THREAD

**Issue by YurasovDV** [dapr/docs#1852]
Environment variables list is incomplete
( https://docs.dapr.io/reference/environment/ )
Description of `DAPR_HOST_IP` is missing

**Comment by msfussell** [comment]
@YurasovDV Not sure that this is set by the CLI. Where did you see this used and set?

**Comment by YurasovDV** [comment]
@msfussell yes, it is not set by CLI. I found it mentioned on
https://docs.dapr.io/operations/troubleshooting/common_issues/#im-getting-timeoutconnection-errors-when-running-actors-locally

**Comment by msfussell** [comment]
Need to check this.

**Comment by msfussell** [comment]
This need updating the env var docs
DAPR_HOST_IP. Environment variable to override host's chosen IP address. Used by the Dapr sidecar. I would also point to the common issue above.

**Comment by sicoyle** [comment]
Environments variable documentation that needs updating can be found here: https://docs.dapr.io/reference/environment/
