### ISSUE TITLE
Dapr Run: auto generate `--app-port` if not set

### ISSUE THREAD

**Issue by anhldbk** [dapr/docs#1857]
## Overview

- Regarding to [dapr run's doc](https://docs.dapr.io/reference/cli/dapr-run/)
- We pass env `APP_PORT` to child apps. See [this PR]( [this discussion](https://github.com/dapr/docs/pull/1835/files#diff-9f9e12f8d2209c7923ddbfa2b753516d6c5598575da76406de45c24616c17ff7R14)
- While invoking `dapr run`, if users don't set argument `--app-port`, there's no such env `APP_PORT` to pass to apps.

## Proposal

If `--app-port` is NOT set, Dapr sidecar should generate a dynamic (valid) port instead.

## Why

- If we have multiple services, a Dapr sidecar must know its co-located application's port to work with.
- It will unify code for starting applications. Just use the port passed by the env (Still the app may NOT use the port)

**Comment by anhldbk** [comment]
@msfussell @yaron2 What do you think?

**Comment by yaron2** [comment]
Dapr doesn't require an application to open a port - an app can just use Dapr one way (calling into it), and thus we can't autogenerate it if missing. WDYT?

**Comment by anhldbk** [comment]
@yaron2 From my point of view, largely we don't write standalone service with no API exposed.

On the other hand, the port can be optional, right? Application can use it or not.

**Comment by Iekhasy** [comment]
> @yaron2 From my point of view, largely we don't write standalone service with no API exposed.
> 
> On the other hand, the port can be optional, right? Application can use it or not.

Yes, we do. Think of a cron job which query a db table every hour and then put a message to a kafka topic. It doesn't require a port.
The thing is if --app-port is provided, Dapr will wait for the app to listen on that port before it continues.
if --app-port is autogenerated, how can dapr know that should it wait or not?
There are a issue discuss on wheather or not that behavior make sense, you can read this one for more info:
https://github.com/dapr/dapr/issues/2918

Anyway, if your application needs a port, make sure you wire them up correctly, you only have to do it once.

**Comment by anhldbk** [comment]
@fpt-sylk-cr Thanks. I'm gonna follow your referenced issue. So close this one now.
