### ISSUE TITLE
Are Actor Timers and Reminders also counting as Usage?

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/docs#186]
"If an actor is not used for a period of time, the Dapr Actors runtime garbage-collects the in-memory object."
https://github.com/dapr/docs/blob/master/concepts/actor/actor_overview.md#actor-lifetime

Question: are Actor Timers and Reminders considered as Actor usage, thus the actor will not be deactivated?

**Comment by amanbha** [comment]
Actor Reminders resets the idle time, so reminder firing will keep actor active. Actor Reminders fire whether actor is active or inactive, if fired for inactive actor, it will activate the actor first.
Actor Timer doesn't reset the idle time, so timer firing will not keep actor active. Timers only fire while actor is active.
