### ISSUE TITLE
Create documentation for StateStore Query API

### ISSUE THREAD

**Issue by dmitsh** [dapr/docs#1863]
**What content needs to be created or modified?**

Need to create content for StateStore Query API

**Describe the solution you'd like**
The design and solution are described here: https://github.com/dapr/dapr/issues/3662

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1153
https://github.com/dapr/dapr/pull/3695

**Comment by greenie-msft** [comment]
Closing as https://github.com/dapr/docs/pull/1874 completed this issue.
