### ISSUE TITLE
Update Component Spec for Azure Service Bus Pubsub and Bindings

### ISSUE THREAD

**Issue by halspang** [dapr/docs#1867]
**What content needs to be created or modified?**
Both the Azure Service Bus pubsub and input/output binding components are being updated to use the new common auth library. This changed added several fields to the component specs.

**Describe the solution you'd like**
This change added the field:

*namespaceName* to both components. This was previously provided by the connection string.

It also adds the additional (and optional) fields for the common auth library.

**Where should the new material be placed?**
* [ServiceBus Pubsub](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/)
* [ServiceBus Binding](https://docs.dapr.io/reference/components-reference/supported-bindings/servicebusqueues/)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1201

**Additional context**
The common auth library has its own documentation page. It'll be referenced similarly to how [azure keyvault](https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault/) references it.

**Comment by msfussell** [comment]
@halspang - Do docs need to be updated here?

**Comment by halspang** [comment]
Yes, this still requires work. I'll take care of it for 1.7.

**Comment by msfussell** [comment]
Fixed.
