### ISSUE TITLE
Update new GA criteria and rename GA to Stable

### ISSUE THREAD

**Issue by artursouza** [dapr/docs#1879]
**What content needs to be created or modified?**

**Describe the solution you'd like**
Reflect decision from https://github.com/dapr/components-contrib/issues/1167

**Where should the new material be placed?**
 ```txt
        daprdocs/content/en/operations/components/certification-lifecycle.md
        daprdocs/content/en/operations/support/support-versioning.md
        daprdocs/content/en/reference/*
```

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/issues/1167

**Additional context**

**Comment by willtsai** [comment]
Searching the repo using regex `(\bGA\s)|(General Avail)|\[GA\]` with case insensitive option in VSCode, I see that the only remaining places in which there are references to General Availability or GA needing update are in the Chinese version of docs. I've created an issue against the Chinese docs repo for their maintainers to address, so I think this issue may now be closed @greenie-msft @msfussell 

CN docs Issue reference: https://github.com/dapr-cn/docs/issues/80

**Comment by greenie-msft** [comment]
This is closed as part of: https://github.com/dapr/docs/pull/1880
