### ISSUE TITLE
Add docs for Kafka pub/sub support of OAuth2

### ISSUE THREAD

**Issue by sthussey** [dapr/docs#1882]
**What content needs to be created or modified?**

Add documentation for how the Kafka pub/sub component can be configured to support OAuth2 authentication.

**Describe the solution you'd like**

Add a reference for the additional fields as well an example configuration

**Where should the new material be placed?**
daprdocs/content/en/reference/components-reference/supported-pubsub/setup-apache-kafka.md

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1229

**Comment by msfussell** [comment]
Resolved
