### ISSUE TITLE
feature: add routerchecker middleware

### ISSUE THREAD

**Issue by 1046102779** [dapr/docs#1894]
Add a routerchecker middleware to  block invalid http request routing, and prevent invalid request from reporting OpenTelemetry.

link:  https://github.com/dapr/docs/pull/1893

link: https://github.com/dapr/docs/pull/1893

**Comment by msfussell** [comment]
These docs are missing from here from the v1.5 release https://docs.dapr.io/reference/components-reference/supported-middleware/
Looks like this content did not get merged correctly https://github.com/dapr/docs/pull/1893/commits/04e9310266f28920672efe73cf5713c20a16180e

**Comment by msfussell** [comment]
@1046102779 - Could you provide the docs for this feature?

**Comment by 1046102779** [comment]
> @1046102779 - Could you provide the docs for this feature?

done.

**Comment by msfussell** [comment]
Merged
