### ISSUE TITLE
SNS/SQS PubSub: missing sqsDeadLettersQueueName info

### ISSUE THREAD

**Issue by amimimor** [dapr/docs#1899]
**What content needs to be created or modified?**

Support for SQS Dead Letter Queue was introduced in dapr 1.4 but the documentation is lacking that information in terms of "Spec metadata fields" missing the new `sqsDeadLettersQueueName` field and information about the dependency of setting this metadata field and `messageReceiveLimit`.

**Describe the solution you'd like**

- add description for the missing `sqsDeadLettersQueueName` metadata field spec
- add note about `messageReceiveLimit` that becomes mandatory if `sqsDeadLettersQueueName` is set
- add note about  `messageReceiveLimit` meaning in the context of specifying the `sqsDeadLettersQueueName` as it will be affecting the number of times a message is fetched before it is moved to the DeadLetters Queue, unlike when there is no DeadLetters Queue specified

**Where should the new material be placed?**

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
This is the docs PR https://github.com/dapr/docs/pull/2069
