### ISSUE TITLE
Update newly Stable components for 1.5

### ISSUE THREAD

**Issue by greenie-msft** [dapr/docs#1905]
The below components are targeting a Stable status as part of the v1.5 release. The Docs should reflect this status change: 
- Kafka pubsub
- Azure KeyVault secret store
- Azure SQL Server state store

**Comment by willtsai** [comment]
Making these changes to v1.5:
- [x] Kafka pubsub
- [x] Azure KeyVault secret store
- [x] Azure SQL Server state store

Adding a few more per the list in https://github.com/dapr/components-contrib/milestone/6?closed=1 and https://github.com/dapr/components-contrib/milestone/6
- [ ] ~RabbitMQ PubSub~
- [ ] ~Azure Service Bus Queues~

**Comment by artursouza** [comment]
> Making these changes to v1.5:
> 
> * [ ]  Kafka pubsub
> * [ ]  Azure KeyVault secret store
> * [ ]  Azure SQL Server state store
> 
> Adding a few more per the list in https://github.com/dapr/components-contrib/milestone/6?closed=1 and https://github.com/dapr/components-contrib/milestone/6
> 
> * [ ]  RabbitMQ PubSub
> * [ ]  Azure Service Bus Queues

RabbitMQ and ASB Q binding will not be in 1.5, we are moving those to 1.6.

**Comment by greenie-msft** [comment]
https://github.com/dapr/docs/pull/1910 - Closing as https://github.com/dapr/docs/pull/1910 was merged.
