### ISSUE TITLE
MQTT bindings doc is missing `backoffMaxRetries`

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/docs#1909]
**Describe the issue**
MQTT bindings was updated to have parity with the pubsub component in terms of configuration metadata a while back in https://github.com/dapr/components-contrib/pull/771, but the docs are missing the `backoffMaxRetries` property.

**URL of the docs**
https://docs.dapr.io/reference/components-reference/supported-bindings/mqtt/

**Expected content**

**Screenshots**

**Additional context**

More generally, the pubsub and bindings docs for MQTT should be refreshed and some common issues cleaned up, as it is being used as an example for other changes being added, such as https://github.com/dapr/docs/pull/1855

**Comment by greenie-msft** [comment]
Closing this issues. PR was merged: https://github.com/dapr/docs/issues/1909
