### ISSUE TITLE
Create the release version tag

### ISSUE THREAD

**Issue by youngbupark** [dapr/docs#191]
## Describe the proposal

Currently, we have not created the version tag for docs and contributors have changed the docs. then docs in master would be inconsistent with the latest dapr runtime release, which will make users confused. 

To resolve this issue, I proposed to add the tag version.

- [x] : Add tag version
- [x] : Add latest version link to README.md

**Comment by youngbupark** [comment]
cc/ @yaron2 @Haishi2016 @msfussell @amanbha

**Comment by amanbha** [comment]
LGTM
