### ISSUE TITLE
Add Version to the Kafka pubsub metadata fields

### ISSUE THREAD

**Issue by krutsko** [dapr/docs#1912]
**What content needs to be created or modified?**
Add description for a new `Version` field in metadata.

**Where should the new material be placed?**
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1275

**Comment by msfussell** [comment]
https://github.com/dapr/docs/pull/1913
