### ISSUE TITLE
Update documentation for the pubsub.pulsar component for dapr/components-contrib #1283

### ISSUE THREAD

**Issue by Taction** [dapr/docs#1915]
**What content needs to be created or modified?**
Docs for pr fix the Route of subscription API does not work on pubsub.pulsar

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1283

**Additional context**

**Comment by msfussell** [comment]
Resolved
