### ISSUE TITLE
configure-state-pubsub : Self-hosted slim mode

### ISSUE THREAD

**Issue by StefH** [dapr/docs#1916]
**URL of the docs page**
https://docs.dapr.io/getting-started/configure-state-pubsub/

**How is it currently worded?**
![image](https://user-images.githubusercontent.com/249938/140638525-668e1d20-10a8-4229-9f55-75be33db50a2.png)

**How should it be worded?**
If you initialized Dapr in <a href="https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-no-docker/">slim mode</a> (without Docker) you need to manually create the default directory, or always specify a components directory using <code>--components-path</code>.

The formatting is probably broken.

**Comment by yaron2** [comment]
Thanks, it'd be great to get a PR that fixes this.

**Comment by hhunter-ms** [comment]
@msfussell @greenie-msft It looks like this [has been resolved](https://github.com/dapr/docs/issues/2180)... can we close this issue?
