### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by whilelie** [dapr/docs#1917]
**Describe the issue**

**URL of the docs**

[https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/](url)
**Expected content**

`dapr --app-id myapp --dapr-http-port 3500 run`

**Screenshots**

![erre](https://user-images.githubusercontent.com/8661807/140697483-cf0a4819-a896-424d-99e6-c98961afb4cc.png)

**Additional context**

**Comment by msfussell** [comment]
Yes, this is a typo here https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/
![image](https://user-images.githubusercontent.com/11199644/155462769-fc15b4a1-674a-4fb3-aaaf-1c60035df13e.png)
