### ISSUE TITLE
Spec metadata fields for the azure storage queue binding doesn't explain what the decodebase64 field

### ISSUE THREAD

**Issue by rishabhsaha** [dapr/docs#1918]
**Describe the issue**
Spec metadata fields for the azure storage queue binding doesn't explain what the decodebase64 field is. It seems to be a copy and paste from the blob storage binding. 

**URL of the docs**
https://docs.dapr.io/reference/components-reference/supported-bindings/storagequeues/

**Expected content**
On the storage queue binding the setting of base64decode only works on the receiving side and not while publishing.

**Screenshots**

![image](https://user-images.githubusercontent.com/12716801/140768782-66261a22-c6c6-49c0-94c0-e7e8938876a9.png)

**Additional context**
On the storage queue binding it is confusing that the content is base64encoded by default. We set up a flow from azure blob-->azure event grid-->azure storage queue-->dapr binding-->java app. The content received by the java app was always base64encoded. We had to either set that setting on the component or decode it in the app. The documentation wasn't clear and seemed to suggest it's only on the publishing side.

**Comment by msfussell** [comment]
@rishabhsaha - Would you be able to push a PR for suggested changes here based on your experience?

**Comment by hhunter-ms** [comment]
resolved
