### ISSUE TITLE
add a .NET example for PubSub routing

### ISSUE THREAD

**Issue by willtsai** [dapr/docs#1920]
**What content needs to be created or modified?**
When the PubSub routing docs were originally added, there was a final comment in the [PR#1786](https://github.com/dapr/docs/pull/1786) to add a .NET example but this was not done before the PR got merged. Thus, this issue is to create that and add it to this documentation

**Describe the solution you'd like**
.NET example for pubsub routing added to docs

**Where should the new material be placed?**
daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-route-messages.md

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
N/A

**Additional context**
None

**Comment by msfussell** [comment]
@greenie-msft - Is this address by the quickstarts now?

**Comment by greenie-msft** [comment]
@msfussell  This scenario is not included in the quickstarts. Should this remain a how-to only?

**Comment by greenie-msft** [comment]
Closing as a C# example has been added to the how-to
