### ISSUE TITLE
Update docs with ASB metadata for bindings

### ISSUE THREAD

**Issue by mukundansundar** [dapr/docs#1942]
**What content needs to be created or modified?**
Update docs with ASB metadata for bindings

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
@mukundansundar - Can you create a PR for the docs? I would also include a link to the Community call demo that you showed.

**Comment by hhunter-ms** [comment]
@mukundansundar friendly bump?

**Comment by msfussell** [comment]
It was this video https://youtu.be/Uijl_t8uQNQ?list=PLcip_LgkYwzuF-OV6zKRADoiBvUvGhkao&t=79 but may be old now
