### ISSUE TITLE
Add docs for Azure Container Apps

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#1952]
Azure Container Apps now has first-class support for Dapr: https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash

We should add a hosting option listing Container Apps. Additionally any other offerings that support Dapr should also be added in the future.

**Comment by willtsai** [comment]
Suggestion - instead of adding a container apps specific page, maybe add a more generic/high level serverless cloud hosting page which will in turn house a listing of the various cloud providers who offer built-in Dapr support

**Comment by AaronCrawfis** [comment]
> Suggestion - instead of adding a container apps specific page, maybe add a more generic/high level serverless cloud hosting page which will in turn house a listing of the various cloud providers who offer built-in Dapr support

I like it!! Also helps keep things logically grouped. Just updated the PR

**Comment by yaron2** [comment]
> Suggestion - instead of adding a container apps specific page, maybe add a more generic/high level serverless cloud hosting page which will in turn house a listing of the various cloud providers who offer built-in Dapr support

+1

**Comment by msfussell** [comment]
> Suggestion - instead of adding a container apps specific page, maybe add a more generic/high level serverless cloud hosting page which will in turn house a listing of the various cloud providers who offer built-in Dapr support

Agreed. This keeps it more neutral
