### ISSUE TITLE
Dapr .NET SDK  error link to Dapr Self-Hosted with Docker Guide

### ISSUE THREAD

**Issue by fjvela** [dapr/docs#1958]
**Describe the issue**

Link error to https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/

**URL of the docs**

https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-development/dotnet-development-docker-compose/
https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-development/dotnet-development-dapr-cli/

**Expected content**

link to  https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/ is rendered

**Screenshots**

![image](https://user-images.githubusercontent.com/5806680/141849781-4fa090dc-7fcc-4f20-bed3-62d3ed0c5ec2.png)
![image](https://user-images.githubusercontent.com/5806680/141849804-a442e5d0-a0c8-47ea-bbb7-2a9177827b1b.png)

**Additional context**

**Comment by msfussell** [comment]
@fjvela  - Thanks for the contribution and help
