### ISSUE TITLE
Update how to run your own daprd.exe images with K8 Sidecar Injector service.

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1961]
In the annotation 
<html>
<body>

not supported | --image |   | dapr.io/sidecar-image | Dapr sidecar image. Default is daprio/daprd:latest
-- | -- | -- | -- | --

</body>
</html>

here https://docs.dapr.io/reference/arguments-annotations-overview/ update this to say that you can used this to run your own darpd.exe image. These word

<html>
<body>

not supported | --image |   | dapr.io/sidecar-image | Dapr sidecar image. Default is daprio/daprd:latest. One scenario this can be used is when building your own custom image of `darpd.exe` and you want this launched by the Kubernetes Sidecar Injector service rather than the latest supported version.
-- | -- | -- | -- | --

</body>
</html>

**Comment by chrisreddington** [comment]
@msfussell, @Flmstr - I'm looking through the GitHub issues for any good first issues. From what I can see, it looks like this issue should now be closed. Just wanted to check if that was right? Thanks!

**Comment by msfussell** [comment]
Looks like the PR above did not actually make it into the docs. This needs to be checked.

**Comment by msfussell** [comment]
merged
