### ISSUE TITLE
Dapr Docs should be also viewable on mobile

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/docs#1964]
**Describe the bug**
Dapr Docs should be also viewable on mobile.
If the view width is limited, both navigation panes are hidden.

The right navigation pane seems to be only optional, as there only internal links are display for quick navigation.

But the left navigation pane is required to be able to navigate across the docs.

**Steps to reproduce**
Open https://docs.dapr.io/ on a mobile device.

**Expected behavior**
It should be possible to view the left navigation pane on mobile devices.

Maybe with a hamburger icon on the top.

**Smartphone (please complete the following information):**
 - Device: S21

**Comment by AaronCrawfis** [comment]
Huh yeah it should be there. Other sites with Hugo + Docsy I maintain all have it. Will investigate. Thanks for the tip!

**Comment by greenie-msft** [comment]
Closing as [Update website template to address issues #1983](https://github.com/dapr/docs/pull/1983) was merged
