### ISSUE TITLE
Drop-down link to v1.5 (latest) from v1.4 docs does not work.

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/docs#1968]
**Describe the bug**
Drop down link to v1.5 (latest) from v1.4 docs does not work.

**Steps to reproduce**
1. Navigate to https://v1-4.docs.dapr.io/ or its subpages.
2. In the navigation bar, click the version drop-down and select v1.5 (latest)
3. Link leads to https://v1-4.docs.dapr.io/# instead of v1.5 docs

**Expected behavior**
Link should point to latest docs (https://docs.dapr.io)

**Screenshots**

![image](https://user-images.githubusercontent.com/31784195/142292813-e4422e54-ea43-459d-aca2-7d9f3b1d8988.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge Dev
 - Version 97.0.1072.8 

**Additional Context**
Issue is specific to v1.4 version of the docs, earlier versions will point to latest https://docs.dapr.io (even if the expected number version is outdated in the drop-down for which is latest)

**Comment by willtsai** [comment]
fixed
