### ISSUE TITLE
Add documentation for new GCP pubsub reconnect loop configuration

### ISSUE THREAD

**Issue by yordan-pavlov** [dapr/docs#1970]
Add documentation for new GCP pubsub reconnect loop configuration metadata properties (`MaxReconnectionAttempts` and `ConnectionRecoveryInSec`) added in https://github.com/dapr/components-contrib/pull/1293

The content can be copied from the Azure Service Bus component documentation here: https://github.com/dapr/docs/blob/v1.5/daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-servicebus.md?plain=1#L82

**Comment by berndverst** [comment]
I merged #dapr/components-contrib#1293.

Please make the docs PR against release 1.7 to document the new metadata fields @yordan-pavlov

**Comment by msfussell** [comment]
Resolved
