### ISSUE TITLE
Add a blog for "How to integrate with Dapr to build Apache APISIX Gateway Controller"

### ISSUE THREAD

**Issue by yzeng25** [dapr/docs#1972]
Hi,

I am Yilin, from the Apache APISIX community. Apache APISIX is a Cloud-native API gateway, and it is the top-level project of the Apache Software Foundation. You can get more details from GitHub: https://github.com/apache/apisix.

We posted a blog "How to integrate with Dapr to build Apache APISIX Gateway Controller" on our blog website. I think the blog  is very meaningful for developers and the community. In addition, it will help Apache APISIX and Dapr publicize and let more developers and companies know about them.

I tried to find the blogs of Dapr and couldn't find them in this repository. So I am wondering if anyone could offer help here.

**What content needs to be created or modified?**

There should be a blog about Apache APISIX-Dapr integration in Dapr's blog site.
**Describe the solution you'd like**

Post the blog in n Dapr's blog site.
**Where should the new material be placed?**

Dapr's blog site.
**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

The contents are ready to be posted, please visit the link below for details:
https://apisix.apache.org/blog/2021/11/17/dapr-with-apisix/

I am also happy to submit a pull request, but I can find any blog materials in this repository though.

**Comment by omidb** [comment]
@yzeng25 I'm trying to follow the blog. Is it possible to add the APISIX Yaml configs in the repo. it's very hard to understand from the pictures as they are written in Mandarin. It would be great to have a directory for all the APISIX configs related to setting up the upstream.
Also, it will help if you can mention how one can configure it easily.
I also think, a better place for this can be in Dapr main repo.

**Comment by juzhiyuan** [comment]
> it's very hard to understand from the pictures as they are written in Mandarin

Agree, it could be better to use English here 🤔 cc @yzeng25

**Comment by yzeng25** [comment]
Hi guys,

The blog is posted in Dapr's blog page[1]. Thank @greenie-msft  and @msfussell for reviewing it!

[1] https://blog.dapr.io/posts/2022/01/13/enable-dapr-with-apache-apisix-ingress-controller/
