### ISSUE TITLE
MalyKhash

### ISSUE THREAD

**Issue by Ma2lik** [dapr/docs#1995]
**Describe the bug**

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by AaronCrawfis** [comment]
Hi @Ma2lik, please reopen if you have any specific website troubles. Thanks!
