### ISSUE TITLE
List the specific software dependencies tested for a given Dapr release

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1998]
Today we list the version of Kubernetes that is support for a Dapr release.  However with this issue https://github.com/dapr/docs/issues/1997 there needs to be an explicit list of other software that has been tested for a particular version of the Dapr runtime. This includes.

1) Kubernetes - https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/#supported-versions
2) Open Telemetry Collector (OTEL)
3) Prometheus
4) FluentD

**Comment by msfussell** [comment]
2. OTEL  - Is covered in this Issue. https://github.com/dapr/docs/issues/1997 - Current version is 0.4.0 -https://github.com/dapr/docs/pull/2075/files
3. Prometheus version ??
4. FluentD version??

**Comment by dmitsh** [comment]
With regards to Prometheus, Dapr uses Prometheus Golang client (github.com/prometheus/client_golang). The currently used version of the client is v1.11.0. 
The earliest version of Prometheus with this version of the client is v2.28. The current version of Prometheus is v2.32.1.
However, it does not mean that Prometheus versions v2.27 and below are not compatible.
By looking at the latest go.sum of Prometheus, the minimal listed version of the client is v0.9.1. The earliest version of Prometheus with this client is v2.6.
That means that theoretically Dapr should work with Prometheus v2.6 and up.

**Comment by greenie-msft** [comment]
> With regards to Prometheus, Dapr uses Prometheus Golang client (github.com/prometheus/client_golang). The currently used version of the client is v1.11.0. The earliest version of Prometheus with this version of the client is v2.28. The current version of Prometheus is v2.32.1. However, it does not mean that Prometheus versions v2.27 and below are not compatible. By looking at the latest go.sum of Prometheus, the minimal listed version of the client is v0.9.1. The earliest version of Prometheus with this client is v2.6. That means that theoretically Dapr should work with Prometheus v2.6 and up.

@msfussell regarding this, would we just document v2.28 since that's the current version of Prometheus that the latest version of Dapr is tested against?

**Comment by msfussell** [comment]
The latest (supported) version Dapr is tested against. You should simply say that these are the supported versions that have been tested. If it works with previous, fine, but if an issue is raised and they are not using the supported version, we can ask them to update.

**Comment by greenie-msft** [comment]
Closing since https://github.com/dapr/docs/pull/2105 was merged
