### ISSUE TITLE
docs for secret cache (dapr/dapr#3941)

### ISSUE THREAD

**Issue by Taction** [dapr/docs#2004]
**What content needs to be created or modified?**

Add `cacheEnable` `cacheTTL` `cacheMemoryLimit` cache config metadata.
Add `refresh_cache` metadata in request.

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

Specify the URL to the associated pull request, if applicable

https://github.com/dapr/dapr/pull/3941

**Additional context**

**Comment by hhunter-ms** [comment]
closing until code PR is reopened and worked on
