### ISSUE TITLE
Why Chinese translation is put in a seperated repo called 'docs-zh'

### ISSUE THREAD

**Issue by tonyqus** [dapr/docs#2009]
**Describe the bug**
I'm trying to contribue to the official zh-cn docs. But I got 404 on your docs page while clicking 'Edit page' button

**Steps to reproduce**
A. Go to https://docs.dapr.io/zh-hans/concepts/
B. Click Edit page link on the right side
![image](https://user-images.githubusercontent.com/772561/143787785-069896e4-35f6-4a01-a4c2-6c16156899f1.png)

**Expected behavior**
I should see the following page as English version does
![image](https://user-images.githubusercontent.com/772561/143787812-f877260b-3199-4779-a36e-524d2f2c89f1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera
 - VPN enabled: Yes

**Comment by tonyqus** [comment]
I'm reading the comments in the original PR https://github.com/dapr/docs/issues/1057 about [docs-zh repo](https://github.com/dapr/docs-zh). 

I'm a bit confused that why using sub-module to connect to an external organization. This doesn't make sense. They can directly use docs-zh repo instead of creating a new organization. What's the purpose?

**Comment by AaronCrawfis** [comment]
> They can directly use docs-zh repo instead of creating a new organization. What's the purpose?

The goal with a separate repo was to give the zh translation maintainers a separate place to handle translation issues, PRs, etc., since it's handled by separate maintainers than the English site. It also lets them be versioned separately.

> I'm trying to contribue to the official zh-cn docs. But I got 404 on your docs page while clicking 'Edit page' button

This is a known issue of how Hugo and Docsy handles GitHub links in prior releases. They have released a fix that needs to be implemented in each submodule repo: https://www.docsy.dev/docs/adding-content/repository-links/#path_base_for_github_subdir-optional

I'll get a PR open soon to tackle this.

**Comment by tonyqus** [comment]
I'm checking the branches in https://github.com/dapr/docs-zh/branches. Even if you get hugo working for docs-zh, there are only 3 branches
![image](https://user-images.githubusercontent.com/772561/143788727-bff467c0-3174-4c61-9716-68e64c19fa79.png). 

Where is content for 1.3, 1.4 and 1.5? But I do see the Chinese translation of 1.3, 1.4, 1.5 on https://docs.dapr.io. How does it work? Is there a fallback strategy from Hugo?

**Comment by AaronCrawfis** [comment]
> Where is content for 1.3, 1.4 and 1.5? 

The maintainers of the zh-hans repo are in charge of keeping the content up to date with Dapr releases. 

> Is there a fallback strategy from Hugo?

As far as I know if you're on v1.5 English and switch to zh-hans, it will show the 1.2 version of the docs page if the page previously exists, and the English version of v1.5 if it doesn't.

**Comment by tonyqus** [comment]
> 

I agree that docs-zh repo is easy for them to maintain the Chinese content. But it's weird that the readme of the repo redirects potential contributors like me to an external organization.  You know I want to contribute to Dapr official instead of a local copycat organization. In this way, the real translation contributors will be not shown in contributors of docs-zh repo at all.  I don't think this is a good practice.

**Comment by newbe36524** [comment]
I think it may now be feasible to move the main repository for collaboration to https://github.com/dapr/docs-zh.
The main reason it was placed in an external repository was that the crowdin and github links required an owner's access.

But last month I tried a new way of collaborating via gitHub action, and it seems that owner access is no longer required.
In the next few days, I'll try to do this migration. Perhaps it will be possible to work directly at https://github.com/dapr/docs-zh without the need for an external organization.

**Comment by giovannism20** [comment]
I'm interested in starting work to bring the translation into portuguese and I have a question about this question of organization: should I open a branch with the translations or ask to create a repo ? @AaronCrawfis
