### ISSUE TITLE
[Question] How can i manager the Bindings and Pub Sub/Broadcast

### ISSUE THREAD

**Issue by liangyuanpeng** [dapr/docs#201]
## Ask your question here
How can i manager the Bindings and Pub Sub/Broadcast,

I have check the doc and do not found some doc,

If i missed something,remind me please! 

Thanks!

**Comment by jocko-wowza** [comment]
@liangyuanpeng I just got through a successful implementation of bindings.  Can you describe the workflow you're trying to engage, and maybe I can offer some insight?
