### ISSUE TITLE
simplify query JSON and fix typo in the nested label

### ISSUE THREAD

**Issue by dmitsh** [dapr/docs#2011]
**URL of the docs page**
https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-state-query-api/

**How is it currently worded?**
The current version contains unnecessary top-level label "query" in the query JSON and a nested label "pagination"

**How should it be worded?**
the top-level label "query" in the query JSON should be removed, and the nested label should be replaced with "page"

The Query JSON expects "page". See:
 https://github.com/dapr/components-contrib/issues/1343
 https://github.com/dapr/dapr/issues/3960

**Comment by msfussell** [comment]
@dmitsh - Can you get this docs updated to match the code?

**Comment by dmitsh** [comment]
> @dmitsh - Can you get this docs updated to match the code?

done
