### ISSUE TITLE
Add docs for in-memory state store

### ISSUE THREAD

**Issue by seeflood** [dapr/docs#2014]
**What content needs to be created or modified?**

Add docs for in-memory state store

**Describe the solution you'd like**

**Where should the new material be placed?**

component spec

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1326
**Additional context**

**Comment by yaron2** [comment]
@skyao @seeflood please create a PR in docs as the contrib component is now merged.

**Comment by seeflood** [comment]
ok.

**Comment by msfussell** [comment]
@seeflood - Can you submit the docs ASAP. Without docs the release cannot go out.

**Comment by seeflood** [comment]
@msfussell ok. Weekend todo list +1

**Comment by msfussell** [comment]
@seeflood PLEASE can you get this PRed ASAP?

**Comment by seeflood** [comment]
@msfussell Sorry for the delay! working on it now

**Comment by msfussell** [comment]
Resolved
