### ISSUE TITLE
Add document for making the grace period configurable

### ISSUE THREAD

**Issue by Taction** [dapr/docs#2024]
**What content needs to be created or modified?**

Add graceful shutdown duration config.

**Describe the solution you'd like**

**Where should the new material be placed?**

https://docs.dapr.io/reference/arguments-annotations-overview/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

- https://github.com/dapr/dapr/pull/3993

**Additional context**

**Comment by msfussell** [comment]
@Taction - Can you submit a Docs PR for this?

**Comment by Taction** [comment]
@msfussell It's pr is #2037, which has been merged.
