### ISSUE TITLE
Incorrect app id and pubsub in "Publish & Subscribe" > "How-To: Publish & subscribe" 

### ISSUE THREAD

**Issue by dlm** [dapr/docs#2029]
**Describe the issue**
The commands for "Publish a topic" using Dapr CLI and HTTP API publish to an app with app-id "testpubsub", but the example starts an app with app-id "orderprocessing".  Also, the pubsub that is being pubished to is "pubsub" but the examples are using a pubsub called "order_pub_sub".

**URL of the docs**
https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#step-3-publish-a-topic

**Expected content**
app-id should be "orderprocessing", pubsub should be "order_pub_sub"

**Screenshots**
NA

**Additional context**
I have a fix for the docs https://github.com/dapr/docs/pull/2027.  This is my first PR for this this project.  I am a huge fan of it and very happy to help.  Please, let me know if there is anything else I can do!

**Comment by chrisreddington** [comment]
Hey @msfussell and @dlm - I'm looking through the GitHub issues for any good first issues. From what I can see, it looks like this issue should now be closed. Just wanted to check if that was right? Thanks!

**Comment by dlm** [comment]
Ah, good catch.  Thanks.  Yep, it was closed by PR #2027.   I will close this one as well.
