### ISSUE TITLE
Unable to Persist State with CosmosDB Setup because of PartitionKey

### ISSUE THREAD

**Issue by goh-chunlin** [dapr/docs#203]
## Expected Behavior

Save to persist state with CosmosDB setup using the following CURL as mentioned in the doc.
```
curl -X POST http://localhost:3500/v1.0/state -H "Content-Type: application/json" -d '[ { "key": "nihilus", "value": "darth" } ]'
```

## Actual Behavior

Unable to save to persist state with CosmosDB setup.

Following the documentation, when using CURL as following
```
curl -X POST http://localhost:3500/v1.0/state -H "Content-Type: application/json" -d '[ { "key": "nihilus", "value": "darth" } ]'
```

It returns 
```
{
    "errorCode": "ERR_SAVE_REQUEST",
    "message": "BadRequest, Message: {\"Errors\":[\"PartitionKey extracted from document doesn't match the one specified in the header\"]}\r\nActivityId: 3742fbb9-7aa6-4ab7-aa17-84bafa927e58, Request URI: /apps/ad2e8bf3-dc98-4198-91d0-bac5753d314e/services/980cbd10-15a8-4aa0-9e7f-6dddb1fa2f7a/partitions/5344132a-3102-4d19-a400-b81f47fa132b/replicas/132167064011059557p/, RequestStats: \r\nRequestStartTime: 2019-10-28T11:16:25.7756255Z, RequestEndTime: 2019-10-28T11:16:25.7856312Z,  Number of regions attempted:1\r\nResponseTime: 2019-10-28T11:16:25.7856312Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-southeastasia1-fd2.documents.azure.com:16762/apps/ad2e8bf3-dc98-4198-91d0-bac5753d314e/services/980cbd10-15a8-4aa0-9e7f-6dddb1fa2f7a/partitions/5344132a-3102-4d19-a400-b81f47fa132b/replicas/132167064011059557p/, LSN: 4, GlobalCommittedLsn: 4, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 1001, RequestCharge: 1.24, ItemLSN: -1, SessionToken: 4, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Upsert\r\n, SDK: Microsoft.Azure.Documents.Common/2.7.0"
}
```

## Steps to Reproduce the Problem

using CURL as following
```
curl -X POST http://localhost:3500/v1.0/state -H "Content-Type: application/json" -d '[ { "key": "nihilus", "value": "darth" } ]'
```

**Comment by yaron2** [comment]
Hey @goh-chunlin, thanks for reporting.

A few questions:

1. What's your OS?
2. Did you use `/id` as the partition key on the CosmosDB collection?

**Comment by goh-chunlin** [comment]
> Hey @goh-chunlin, thanks for reporting.
> 
> A few questions:
> 
> 1. What's your OS?
> 2. Did you use `/id` as the partition key on the CosmosDB collection?

Hi, @yaron2

1. I am using macOS Mojave.
2. Nope, I am using `nihilus` as the partition key on CosmosDB collection as suggested by the documentation.

Thank you for looking into the problem. =)

**Comment by yaron2** [comment]
Ah, well this is the problem.. nihilus is the actual key that's being sent, but when creating the Cosmos container, the pk needs to be `/id`.

We've updated our docs:
https://github.com/dapr/docs/blob/master/howto/setup-state-store/setup-azure-cosmosdb.md#creating-an-azure-cosmosdb-account

**Comment by goh-chunlin** [comment]
Thanks for the clarification.

However, why would the last two sentences in the documentation states that "The Azure CosmosDB state store will use the key property provided in the requests to the Dapr API to determine the partition key. For example, the following operation will use the key `nihilus` as the partition key"?

Which "partition key" does these two lines refer to?

**Comment by yaron2** [comment]
The doc refers to the value of the partition key that will be used. we'll make the docs more explicit about this.

**Comment by goh-chunlin** [comment]
Thanks for explaining.

So we shall look forward to the updated documentation and close this issue only after the documentation is updated?

**Comment by yaron2** [comment]
Hi @goh-chunlin, I've updated the docs with this PR:

https://github.com/dapr/docs/pull/240

Feel free to close this issue if you believe it's fixed.
