### ISSUE TITLE
PubSub AWS SnsSqs - disableEntityManagement feature documentation

### ISSUE THREAD

**Issue by amimimor** [dapr/docs#2035]
**What content needs to be created or modified?**
new PubSub AWS SNS/SQS metadata field `disableEntityManagement` should be described and added

**Describe the solution you'd like**
`disableEntityManagement` should be added to the metadata fields table (see below)

**Where should the new material be placed?**
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/#spec-metadata-fields

Essentially it has the same functionality as described in https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus/#spec-metadata-fields thus copying of the same `disableEntityManagement` description can be done

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
@amimimor - Could you create a Docs PR for these changes for v1.6 release? Thanks
