### ISSUE TITLE
Remove app-protocol from gRPC proxying

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#2048]
gRPC proxying does not necessitate the usage of `app-protocol grpc` and is redundant in this example: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/.

**Comment by msfussell** [comment]
@yaron2  - Is it just this command that needs to be update from
dapr run --app-id server --app-protocol grpc --app-port 50051 --config config.yaml -- go run main.go
to
dapr run --app-id server --app-port 50051 --config config.yaml -- go run main.go

**Comment by greenie-msft** [comment]
@yaron2, can you please address this issue?

**Comment by yaron2** [comment]
> @yaron2 - Is it just this command that needs to be update from dapr run --app-id server --app-protocol grpc --app-port 50051 --config config.yaml -- go run main.go to dapr run --app-id server --app-port 50051 --config config.yaml -- go run main.go

Correct

**Comment by greenie-msft** [comment]
PR to address this has been merged: https://github.com/dapr/docs/pull/2116
