### ISSUE TITLE
Add API reference documentation for Dapr to User Service Code Method invocation

### ISSUE THREAD

**Issue by shalabhms** [dapr/docs#205]
Add API reference documentation for Dapr to User Service Code Method invocation API

**Comment by msfussell** [comment]
What specifically needs updating here?

**Comment by amanbha** [comment]
@shalabhms IS this still relevant or it has been fixed, please close if its addressed by docs improvements over past few months.

**Comment by msfussell** [comment]
@shalabhms Any update?

**Comment by shalabhms** [comment]
This was done.
