### ISSUE TITLE
endpoint field in s3 binding is missing

### ISSUE THREAD

**Issue by lizzzcai** [dapr/docs#2050]
**Describe the issue**

endpoint field in s3 binding is missing
**URL of the docs**

https://docs.dapr.io/reference/components-reference/supported-bindings/s3/#spec-metadata-fields
**Expected content**

[endpoint](https://github.com/dapr/components-contrib/blob/master/bindings/aws/s3/s3.go#L46) field
**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
Closed with this merged PR https://github.com/dapr/docs/pull/2049. Thanks for the contribution
