### ISSUE TITLE
Pub/Sub subscriptions need to be revised

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#2052]
The current information on declarative/programmatic subscriptions is disjoint and conflicts.

Overview here: https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#message-subscription

Points to https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#step-2-subscribe-to-topics. This page has no information on programmatic subscriptions

This page does: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-route-messages/#programmatic-subscription. And it says to use a different API version for declarative subscriptions.

We need to reorganize and unify these docs.

**Comment by msfussell** [comment]
Since the articles above achieve different things I would a add examples here https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#step-2-subscribe-to-topics on how to programmatically subscribe to topics to make this complete.

**Comment by hhunter-ms** [comment]
Resolved in #2414 
https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods
