### ISSUE TITLE
Wrong %USERPROFILE% path being informed in docs

### ISSUE THREAD

**Issue by jr-araujo** [dapr/docs#2057]
Hi there, I'm new in dapr ecosystem and I'm walking through the documentation, trying to learn a little bit more about how could I use this amazing cloud-native platform.

**Describe the issue**

Trying to follow all the step-by-step in the **Initialize Dapr in your local environment** instructions I tried to run this command here: 

`explorer "%USERPROFILE%\.dapr\"`

but if this command is run using PowerShell, it will outcome without anything.

**URL of the docs**

[Initialize Dapr in your local environment](https://docs.dapr.io/getting-started/install-dapr-selfhost/)

**Expected content**

This would be the expected result:
![This is an image](https://docs.dapr.io/images/install-dapr-selfhost-windows.png)

**Screenshots**

**Additional context**

So, to achieve the expected result from this part of the documentation, the docs should be fixed to add the instruction below:

`explorer $env:USERPROFILE\.dapr`

**Comment by yaron2** [comment]
Thanks @jr-araujo and welcome to the Dapr community!

Would you be willing to submit a PR to fix the docs?

**Comment by msfussell** [comment]
@jr-araujo - Windows has PS and CMD options. The setup process in the docs on Windows uses CMD for the initialization. If we do add PS, then this should really be added and tested for the https://docs.dapr.io/getting-started/install-dapr-cli/ and the https://docs.dapr.io/getting-started/install-dapr-selfhost/ topics. Is this the only place this failed in PS for you in the setup?

**Comment by hhunter-ms** [comment]
closing for now - feel free to reopen if other commands fail in PS as well
