### ISSUE TITLE
Provide documentation on OCI ObjectStorage State Store 

### ISSUE THREAD

**Issue by lucasjellema** [dapr/docs#2070]
**What content needs to be created or modified?**

There should be docs on the State Store implementation based on OCI ObjectStorage service that instruct application operators on how to configure state store components of type state.oci.objectstorage.

**Describe the solution you'd like**

Once the code for this component is (close to being) accepted, I will provide the documentation as prescribed in this repository.

**Where should the new material be placed?**

a new file called setup-oci-objectstorage.md should be created under daprdocs/content/en/reference/components-reference/supported-state-stores/.

It will be quite similar to setup-azure-tablestorage.md

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1401

**Additional context**

**Comment by greenie-msft** [comment]
Closing as https://github.com/dapr/docs/pull/2073 has been merged.
