### ISSUE TITLE
New documentation on AlibabaCloud Parameter Store secret component

### ISSUE THREAD

**Issue by ceshihao** [dapr/docs#2071]
**What content needs to be created or modified?**

There should be docs on secret stores implementation based on AlibabaCloud Parameter Store.

**Describe the solution you'd like**

If [PR](https://github.com/dapr/components-contrib/pull/1402) is accepted, i will provide related documents.

**Where should the new material be placed?**

daprdocs/content/en/reference/components-reference/supported-secret-stores

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1402

**Additional context**

**Comment by yaron2** [comment]
@ceshihao the PR is merged into components-contrib, please create a corresponding PR in docs.

**Comment by ceshihao** [comment]
> @ceshihao the PR is merged into components-contrib, please create a corresponding PR in docs.

Thanks, I have submitted the docs PR.

**Comment by greenie-msft** [comment]
Closing issue since https://github.com/dapr/docs/pull/2111 was merged
