### ISSUE TITLE
Support enable/disable placement component in Kubernetes cluster

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#2074]
This is to document this issue https://github.com/dapr/dapr/issues/3761
This PR - https://github.com/dapr/dapr/pull/4094.

Documentation should include
- Update this table https://docs.dapr.io/reference/arguments-annotations-overview/
- It would also be good to ensure that we are clear when this used with an example. If you put an example into this issue, @msfussell will take a look at say where best to put this into the docs. I want this to be clear that when you are not using Actors, you can turn this off and make this discoverable in the docs. I suggest editing this doc https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#optional-components with an example

**Comment by CrazyHZM** [comment]
Sorry for forgetting this issue, I found out that 1.7 is about to be released, I wait for the 1.8 branch to be created, and then update it on the 1.8 branch, right?
@msfussell

**Comment by msfussell** [comment]
@CrazyHZM - Yes. Wait for the v1.8 release for this now.

**Comment by CrazyHZM** [comment]
@msfussell 
I have a question, where should the example be placed in https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#optional-components, I have not found a particularly suitable location.

**Comment by msfussell** [comment]
> @msfussell I have a question, where should the example be placed in https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#optional-components, I have not found a particularly suitable location.

Yes, this is a fine place to include an example, but you should say that this is a setting on the Dapr sidecar not to confuse people to think this is a setting on K8s cluster. 

Also whilst you are in this doc can you remove this statement on Sentry, since Sentry cannot be optional for K8s.
 "Sentry - Needed for mTLS for service to service invocation"

**Comment by msfussell** [comment]
Closed. Resolved.
