### ISSUE TITLE
Add documentation about configuration API method - Java SDK

### ISSUE THREAD

**Issue by amulyavarote** [dapr/docs#2077]
**What content needs to be created or modified?**
Add information about the configuration API method for java sdk. 

**Describe the solution you'd like**

**Where should the new material be placed?**
Under sdk documentation

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by greenie-msft** [comment]
PR addressing this issue has been merged: https://github.com/dapr/java-sdk/pull/676
