### ISSUE TITLE
Add documentation about configuration API (get configuration method) - Python SDK 

### ISSUE THREAD

**Issue by amulyavarote** [dapr/docs#2079]
**What content needs to be created or modified?**
Add information about the configuration API (get configuration method) for python sdk.

**Describe the solution you'd like**

**Where should the new material be placed?**
Under sdk documentation

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by greenie-msft** [comment]
PR addressing the issue has been merged: https://github.com/dapr/docs/pull/2127
