### ISSUE TITLE
Update troubleshooting guide for tracing

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#208]
Current troubleshooting guide for tracing doesn't reflect latest changes.

https://github.com/dapr/docs/blob/master/best-practices/troubleshooting/tracing.md

**Comment by msfussell** [comment]
Do we need to add any more to this guide? http://localhost:1313/operations/troubleshooting/setup-tracing/ This is very zipkin specific for some reason.

**Comment by tcnghia** [comment]
This is fixed by the changes we checked in for #1182
