### ISSUE TITLE
Docs for new feature: autogenerate component imports at build time

### ISSUE THREAD

**Issue by willtsai** [dapr/docs#2085]
**What content needs to be created or modified?**
Documentation needs to be created for the new feature "Autogenerate component imports at build time" planned for release v1.6

**Describe the solution you'd like**
Author Dapr Documentation for "Autogenerate component imports at build time" feature, as described in https://github.com/dapr/dapr/issues/3271

**Where should the new material be placed?**
Add to [Dapr Docs](https://github.com/dapr/docs)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/issues/3271

**Additional context**

**Comment by msfussell** [comment]
This issue can be closed. Flavors of Dapr is not currently on the roadmap
