### ISSUE TITLE
Misleading/incorrect diagram

### ISSUE THREAD

**Issue by olitomlinson** [dapr/docs#2088]
**Describe the issue**
Diagram is misleading / incorrect

**URL of the docs**
https://docs.dapr.io/operations/components/setup-pubsub/pubsub-namespaces/

**Expected content**
1) I expected the redis icon to be in the `namespace-a` part of the diagram as that is where it is described to be installed in the docs

2) part of this sentence is wrong. the subscribers are in namespace-b as per the instructions. Only the publisher is in `namespace-a`.

![image](https://user-images.githubusercontent.com/4224880/148651323-71a54e31-363c-4b0f-a5ec-1c86e2eb38d6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/4224880/148651223-bb3e21cd-a53b-49cc-b181-2a6e421a34ac.png)

**Additional context**
It's also not helpful to have both `namespace-a` and `namespace-b` on the left of the diagram  - I would recommend redrawing the diagram keeping `namespace-a` to the left and `namespace-b` to the right to aid readability.

**Comment by msfussell** [comment]
@olitomlinson - I will look into this and update the diagram

**Comment by msfussell** [comment]
Resolved
