### ISSUE TITLE
Redis Output Binding: metadata format documentation missing

### ISSUE THREAD

**Issue by sjwaight** [dapr/docs#2091]
## In what area(s)?

/area docs
/area bindings

## What version of Dapr?

1.5.1

## Expected Behavior

When invoking an output binding configured to use Redis I am unsure how to supply additional metadata about the item I am sending to the binding. There are no samples / documentation showing how to supply the metadata. Consequently I tried the following and expect the data to be handled.

```
POST http://127.0.0.1:5380/v1.0/bindings/receipts.binding
Content-Type: application/json

{
    "data": {
        "storeId": "12234",
        "customerName": "Simon W",
        "loyaltyId": "42",
        "orderItems": [
            {
                "menuItemId": 1,
                "quantity": 1
            },
            {
                "menuItemId": 2,
                "quantity": 1
            },
            {
                "menuItemId": 3,
                "quantity": 3
            }
        ]
    },
    "metadata": {
        "fileName" : "12234.json"
    },
    "operation": "create"
}
```

## Actual Behavior

When I submit this call I receive back:

```
{
  "errorCode": "ERR_INVOKE_OUTPUT_BINDING",
  "message": "error when invoke output binding test.binding: redis binding: missing key on write request metadata"
}
```

As there is no documentation or samples for this binding I have no idea how to achieve the outcome I expect. After digging around I stumbled across https://github.com/dapr/dapr/issues/772 but the links from that are broken. In a pair programming session I randomly tried `key` instead of `fileName` in the `metadata` block and the request succeeded.

## Steps to Reproduce the Problem

See above.
 
Additional documentation around bindings and their message formats would probably help avoid these types of issues.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Moving to docs repo.

**Comment by msfussell** [comment]
@sjwaight - Would be great to have a suggestion here on a doc update and/or a PR.

**Comment by sjwaight** [comment]
I think the biggest help would be to clearly document which pieces of a binding configuration declaration can be overridden at runtime, and when using specific bindings what properties must be supplied. Even just full samples of each would be beneficial.

In the sample request I posted in the original report, the JSON that is sent to the DAPR sidecar contains an invalid metadata property for a redis service binding, while also missing a required property of `key`.

From a debugging standpoint, even though the error message tells you a property is missing, the way the error message is displayed makes it too subtle to realise that you must include 'key' in the metadata you send. Perhaps the error message could be rewritten:

`"error when invoke output binding test.binding: redis binding: missing 'key' property in write request metadata"`

**Comment by msfussell** [comment]
This applies to https://docs.dapr.io/reference/components-reference/supported-bindings/redis/ which needs several updates including
1) Updating the example of the metadata usage in this example https://docs.dapr.io/reference/components-reference/supported-bindings/redis/#component-format
2) As per the above, given an example of how to write an entry to the binding.

@sjwaight - If you would like to contribute to the docs, that would be very helpful

**Comment by sjwaight** [comment]
I will see what I can do. Some of the bindings probably require original author input to enumerate the examples, but I'm happy to see what I can do specifically with Redis.

**Comment by greenie-msft** [comment]
@sjwaight any update on this? Can you help provide some examples?

**Comment by sjwaight** [comment]
Let me put it on the list for next week. Apologies for laggard response.

**Comment by msfussell** [comment]
@sjwaight - Following up here. Any updates?

**Comment by msfussell** [comment]
@sjwaight - Following up here. Any updates?
