### ISSUE TITLE
Add documentation about configuration API (get configuration method) - Dotnet SDK

### ISSUE THREAD

**Issue by amulyavarote** [dapr/docs#2094]
**What content needs to be created or modified?**
Add information about the configuration API (get configuration method) for dotnet sdk.

**Describe the solution you'd like**

**Where should the new material be placed?**
Under sdk documentation

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by greenie-msft** [comment]
Closing issue as PR was merged: https://github.com/dapr/docs/pull/2128
