### ISSUE TITLE
The Preview Features Table needs to have the release version included

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#2098]
This table https://docs.dapr.io/operations/support/support-preview-features/ needs to have the release Dapr version added, so that we can tell when the feature was added. For example Actor reentrancy was done in v1.1.0 release. Currently this is only in the release notes.

**Comment by adityaagnihotri1** [comment]
will work on this issue

**Comment by adityaagnihotri1** [comment]
@msfussell do we need to change the content of page to add release version?

**Comment by msfussell** [comment]
This issue has been fixed.
