### ISSUE TITLE
state store: client-side encryption and query api are mutually excluded

### ISSUE THREAD

**Issue by dmitsh** [dapr/docs#2100]
**What content needs to be created or modified?**

Add information about state store: client-side encryption and query api are mutually excluded.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/4127

**Comment by greenie-msft** [comment]
Closing since PR that addresses this was merged: https://github.com/dapr/dapr/pull/4127
