### ISSUE TITLE
Provide documentation for new State Store component for Oracle Database 

### ISSUE THREAD

**Issue by lucasjellema** [dapr/docs#2109]
**What content needs to be created or modified?**

PR https://github.com/dapr/components-contrib/pull/1448 proposes the implementation of an Oracle Database backed state store component (as described in issue https://github.com/dapr/components-contrib/issues/1444). Documentation on this component should be provided. 

**Describe the solution you'd like**
Once the code for this component is (close to being) accepted, I will provide the documentation as prescribed in this repository.

**Where should the new material be placed?**

a new file called setup-oracledatabase.md should be created under daprdocs/content/en/reference/components-reference/supported-state-stores/.

It will be quite similar to setup-postgresql.md

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
[](https://github.com/dapr/components-contrib/pull/1448)

**Additional context**

**Comment by msfussell** [comment]
Resolved
