### ISSUE TITLE
Missing etag at actor API spec

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/docs#211]
Concerns (https://github.com/dapr/docs/blob/master/reference/api/actors.md)

Related to dapr/dapr#677 it seems, that the actor endpoint also as an optional etag for some operations which is not document, but should.

**Comment by amanbha** [comment]
Etag will not be exposed for Actors as runtime ensures their single threadedness. Haishi has fixed the issue for reminders with etags.
