### ISSUE TITLE
New translation in zh_hans for v1.0 - v1.5

### ISSUE THREAD

**Issue by newbe36524** [dapr/docs#2137]
Everything is verified, please help me to merge that PRs. Thanks.
I think the link in ./daprdocs/content/en/developing-applications/middleware/supported-middleware/middleware-oauth2.md is broken since the source content in English is broken too.

PRs

https://github.com/dapr/docs/pull/2131
https://github.com/dapr/docs/pull/2132
https://github.com/dapr/docs/pull/2133
https://github.com/dapr/docs/pull/2134
https://github.com/dapr/docs/pull/2135
https://github.com/dapr/docs/pull/2136

**Comment by newbe36524** [comment]
@AaronCrawfis Could you please help me to merge that PRs, thanks

**Comment by yaron2** [comment]
cc @msfussell

**Comment by AaronCrawfis** [comment]
Created #2170 to track middleware issue

**Comment by AaronCrawfis** [comment]
> Created #2170 to track middleware issue

Actually this was resolved in the 1.5/1.6 branches. We'll merge with the broken link in branches <= 1.4 since we don't support those docs

**Comment by newbe36524** [comment]
Close, since all PRs have been merged. Thank you.
