### ISSUE TITLE
Update Azure CosmosDBGremlinAPI binding spec

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#2138]
**What content needs to be created or modified?**
 Provide a sample format for payload and username in the document

**Describe the solution you'd like**

request payload sample - 
``` json
{ 
  "data": {
    "gremlin": "g.V().count()"
    },
  "operation": "query"
}
```
Ussername sample - 
`"/dbs/<database_name>/colls/<graph_name>"`

**Where should the new material be placed?**
https://docs.dapr.io/reference/components-reference/supported-bindings/cosmosdbgremlinapi/

**Comment by msfussell** [comment]
resolved
