### ISSUE TITLE
How to glue Input and Output bindings?

### ISSUE THREAD

**Issue by abhirockzz** [dapr/docs#214]
## Ask your question here

In the [Dapr Azure Friday episode](https://youtu.be/mPVnu4W0xzQ?t=150),  @yaron2 showed a demo that uses Input and Output bindings in a single Dapr app using a specific format of the response (pretty cool!)

Questions/comments:

1. I looked up the samples and how-to but did not find a reference to such an example
2. Is there documentation on the same (in bindings section)?
3. Are there any other patterns/techniques which can be used to "glue" components together? e.g. is it possible to get an event via Input binding and push it to a state store?
4. Also, can I get a reference to the part of code (in Dapr runtime I am assuming) which accomplishes this (sorry for being lazy!)

I found this to be really powerful and it would be great to capture this (and other patterns) in the docs

**Comment by yaron2** [comment]
Hi,

We have an [input bindings How To](https://github.com/dapr/docs/tree/master/howto/trigger-app-with-input-binding) and [output bindings How To](https://github.com/dapr/docs/tree/master/howto/send-events-with-output-bindings).

It should be fairly easy to connect the two - just one app that listens on an endpoint (for input bindings) and that sends an HTTP message to invoke an output binding.

There's also a sample here for bindings:
https://github.com/dapr/samples/tree/master/5.bindings

Let us know if there's any more specific help you think is needed.

**Comment by abhirockzz** [comment]
Thanks @yaron2 . Yes I did check the how-tos as well as the sample. What I was referring to is this technique (which you showcased in the Azure Friday demo) to glue the bindings together in one app

```
...
app.post('/eventhubs', (req, resp) =>){
  console.log(req.body)
  res.json({to: ['storage'], data: req.body})
})
...
```
If I understand correctly, this means

- get the message using `eventhubs` input binding
- send it to `storage` output binding (which in this example was Azure Blob)

**Comment by yaron2** [comment]
Oh that!

You understand correctly.

Yeah that's a neat trick we have that's not documented at all right now. We'll work on that.

You can dispatch the same message to multiple outputs, with either ordered delivery or you can fan out in parallel by adding another property: 

`concurrency: parallel`

**Comment by yaron2** [comment]
Oh and to your question in .3, yes it's possible.. you can also send the data to a store using a response format.

**Comment by abhirockzz** [comment]
Exactly! It was really cool and would be great to have documentation and the input/output combinations with which this is possible (maybe all of them)

**Comment by RicardoNiepel** [comment]
Can work on an initial documentation, pls assign

**Comment by yaron2** [comment]
Done, thanks.

**Comment by amanbha** [comment]
@RicardoNiepel Are you still planning to work on it?

**Comment by RicardoNiepel** [comment]
Yes - planned for Monday :)

**Comment by GrailSeeker** [comment]
> Hi,
> 
> We have an [input bindings How To](https://github.com/dapr/docs/tree/master/howto/trigger-app-with-input-binding) and [output bindings How To](https://github.com/dapr/docs/tree/master/howto/send-events-with-output-bindings).
> 
> It should be fairly easy to connect the two - just one app that listens on an endpoint (for input bindings) and that sends an HTTP message to invoke an output binding.
> 
> There's also a sample here for bindings:
> https://github.com/dapr/samples/tree/master/5.bindings
> 
> Let us know if there's any more specific help you think is needed.

@yaron2  these links are no longer valid - need update?
