### ISSUE TITLE
JS-SDKs doc page points to repo instead of SDK docs

### ISSUE THREAD

**Issue by paulyuk** [dapr/docs#2142]
**Describe the bug**
SDKs doc page points to repo instead of SDK docs

**Steps to reproduce**
1. start on https://docs.dapr.io/developing-applications/sdks/
2. click javascript link
--> links to repo: https://github.com/dapr/js-sdk

**Expected behavior**
--> links to javascript SDK docs which already exist: 
https://docs.dapr.io/developing-applications/sdks/js/

**Comment by msfussell** [comment]
resolved
