### ISSUE TITLE
Doc: Query and Filtering API (Alpha) feature now available for Python, Javascript, Go and .NET.

### ISSUE THREAD

**Issue by paulyuk** [dapr/docs#2143]
**What content needs to be created or modified?**
We need to doc the How To for the 4 new languages supporting Query API.  Python Javascript, go and .NET.  This should go here.
https://v1-6.docs.dapr.io/developing-applications/building-blocks/state-management/howto-state-query-api/

**Comment by msfussell** [comment]
Once the new quickstarts are in place, this can be added

**Comment by hhunter-ms** [comment]
closing until this is a thing
