### ISSUE TITLE
Contradicting information

### ISSUE THREAD

**Issue by bugra-derre** [dapr/docs#2152]
**Describe the issue**
Information from the dapr docs are contradicting at two different places. More advise is appreciated.

Case A: When the pod "dapr-operator" is crashing....
https://docs.dapr.io/operations/troubleshooting/common_issues/#the-dapr-operator-pod-keeps-crashing
Quint essence: "Reduce number of running "dapr-operator" pods (replicaset) to one"

Case B: When running in production with the high availability mode enabled
https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#highly-available-mode
Quint essence: "Have the number of running "dapr-operator" pods (replicaset) in HA mode to three (default)"

**URL of the docs**
A: https://docs.dapr.io/operations/troubleshooting/common_issues/#the-dapr-operator-pod-keeps-crashing
B: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#highly-available-mode

**Expected content**
A clear and concise description of what is expected here. Several (subjective) assumptions can be implicated from my personal point of view.

1. The dapr cli needs to set the replicaset of dapr-operator to one only ..... or
2. The docs need to desribe how to handle a HA cluster that has crashes with the dapr-operator pod

**Screenshots**
-

**Additional context**
-

**Comment by msfussell** [comment]
@bugra-derre - Yes, point A is wrong and needs to be removed from the docs. For point B, when Dapr is in HA mode, then is will retain 3 running instances even in the event of dapr-operator pod failure.
