### ISSUE TITLE
Query API feature now available PostgreSQL StateStore

### ISSUE THREAD

**Issue by r-c-correa** [dapr/docs#2159]
**What content needs to be created or modified?**
Add support for Query in PostgreSQL StateStore documentation.

**Describe the solution you'd like**
Show Query support for PostgreSQL in features table for StateStores.

**Where should the new material be placed?**
Inside StateStore features table: https://docs.dapr.io/reference/components-reference/supported-state-stores/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
Issue: dapr/components-contrib/issues/1456
PR: dapr/components-contrib/pull/1457

**Additional context**
![image](https://user-images.githubusercontent.com/73140039/151272419-46d0e72e-fd40-4b78-ab6e-df2f01056bd0.png)

**Comment by msfussell** [comment]
Resolved
