### ISSUE TITLE
Docs for OCI ObjectStorage state store incorrectly suggest ~/ prefix is supported

### ISSUE THREAD

**Issue by lucasjellema** [dapr/docs#2162]
**Describe the issue**

The documentation for the OCI ObjectStorage state store states that the configuration file path can be defined using the ~/ prefix. This is not correct and should be modified 

**URL of the docs**

https://github.com/dapr/docs/blob/v1.7/daprdocs/content/en/reference/components-reference/supported-state-stores/setup-oci-objectstorage.md
**Expected content**

Remove all references to ~/ as suggested syntax; in fact: state explicitly that this notation is not supported
**Screenshots**

**Additional context**

The code that explicitly fails with appropriate error message when ~/ is used is introduced with https://github.com/dapr/components-contrib/pull/1430

**Comment by msfussell** [comment]
Resolved
