### ISSUE TITLE
examples of using a Redis state store should use `apiVersion: dapr.io/v1Stable`

### ISSUE THREAD

**Issue by nunofilipecosta** [dapr/docs#2175]
**Describe the issue**
All examples of using a Redis state store use an out of date `dapr.io/v1alpha1`

Not really sure if it has an impact 

**URL of the docs**
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/
https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/#step-1-setup-a-state-store

**Expected content**
`apiVersion: dapr.io/v1Stable`

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
It is slightly confusing but `dapr.io/v1alpha1` is correct as this refers to the Dapr API version that the component conforms to. Read https://docs.dapr.io/operations/support/support-versioning/
And when you look at a table like this  https://docs.dapr.io/reference/components-reference/supported-state-stores/ and see Alpha is it referring to the component certification testing, not to the Dapr API version. Both of the versions in the doc above only change if there required breaking change, which we try hard to avoid.

**Comment by msfussell** [comment]
Closing as not an issue to fix
