### ISSUE TITLE
Update Actor Runtime Configuration Examples to Include Per Type Config

### ISSUE THREAD

**Issue by halspang** [dapr/docs#2176]
**What content needs to be created or modified?**
Actor Configuration is being updated to handle per-type configuration. The documentation should be updated to reflect this.

**Describe the solution you'd like**
Update the example with new fields and discuss the new behavior which is Actors can now have their own configuration, but if they do not they will still default to the old default values/base level config.

**Where should the new material be placed?**
https://docs.dapr.io/developing-applications/building-blocks/actors/howto-actors/#actor-runtime-configuration
https://docs.dapr.io/reference/api/actors_api/#get-registered-actors

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/4201

**Comment by greenie-msft** [comment]
Closing as #2334 addresses this issue.
