### ISSUE TITLE
Actors API typo

### ISSUE THREAD

**Issue by derrickburns** [dapr/docs#2179]
**URL of the docs page**
[](https://docs.dapr.io/reference/api/actors_api/)

**How is it currently worded?**
You can provided the

**How should it be worded?**
You can provide the

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
@derrickburns - which page is this? And it would be great if you could submit a PR for these that you are reviewing

**Comment by msfussell** [comment]
@derrickburns - Ping?

**Comment by hhunter-ms** [comment]
> @derrickburns - which page is this? And it would be great if you could submit a PR for these that you are reviewing

FYI @msfussell page: https://docs.dapr.io/reference/api/actors_api/
