### ISSUE TITLE
PubSub API typo

### ISSUE THREAD

**Issue by derrickburns** [dapr/docs#2180]
**URL of the docs page**
https://docs.dapr.io/reference/api/pubsub_api/

**How is it currently worded?**
If you want to send your own custom CloundEvent, use the application/cloudevents+json value for the Content-Type header.

**How should it be worded?**
If you want to send your own custom CloudEvent, use the application/cloudevents+json value for the Content-Type header.

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
Typo "custom CloundEvent,". @derrickburns - would be great if you could submit a PR for this. Thanks

**Comment by hhunter-ms** [comment]
@msfussell do you mind closing this?

**Comment by hhunter-ms** [comment]
This issue has been resolved - thank you!
