### ISSUE TITLE
Overview grammatical error

### ISSUE THREAD

**Issue by derrickburns** [dapr/docs#2181]
**URL of the docs page**
https://docs.dapr.io/concepts/overview/

**How is it currently worded?**
In [self-hosted mode](https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-overview/) Dapr runs as a separate sidecar process which your service code can call via HTTP or gRPC

**How should it be worded?**
In [self-hosted mode](https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-overview/) Dapr runs as a separate sidecar process that your service code can call via HTTP or gRPC

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
The use of which here is correct. It is a non-defining clause and does not add any more context about the sentence. Which and that are not interchangeable. Try these examples https://www.writersdigest.com/write-better-fiction/which-vs-that

**Comment by derrickburns** [comment]
Ah, agree . Then the problem is a missing comma!
