### ISSUE TITLE
overview grammatical error #2

### ISSUE THREAD

**Issue by derrickburns** [dapr/docs#2182]
**URL of the docs page**
https://docs.dapr.io/concepts/overview/

**How is it currently worded?**
Each running service has a Dapr runtime process (or sidecar) which is configured to use state stores, pub/sub, binding components and the other building blocks.

**How should it be worded?**
Each running service has a Dapr runtime process (or sidecar) that is configured to use state stores, pub/sub, binding components and the other building blocks.

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
The use of which here is correct. It is a non-defining clause and does not add any more context about the sentence. It just can have these attributes, it is not required to have them.
