### ISSUE TITLE
dapr non-admin install instructions don't match the description

### ISSUE THREAD

**Issue by dalkoran** [dapr/docs#2183]
**Describe the issue**
Copy/pasting the provided PowerShell commands to install as non-admin doesn't match the description. The text says the script provided will install to an alternate location specified by DAPR_INSTALL_DIR, but it will actually attempt to install to $HOME\dapr. The text should suggest to replace "$HOME\dapr" with your preferred path, or keep the instructions as they are and change the script to actually use the $env:DAPR_INSTALL_DIR instead of $HOME\dapr.

**URL of the docs**
https://docs.dapr.io/getting-started/install-dapr-cli/

**Evidence**
This text is output if I run the script as-is:
```
Exception:
Line |
  68 |      throw "Cannot create $DaprRoot"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot create C:\Users\<user name>/dapr
```
Note that my <user name> contains an embedded space (e.g. "John Smith")
If I change the argument specified by $HOME\dapr to my preferred folder, e.g. "H:\Development\Tools" then it works fine.

Final thoughts... IMHO "C:\dapr" is a terrible default choice, do you really install all your development tools to individual folders on your system drive?

**Comment by msfussell** [comment]
There also seems to be a bug here. 
Running in either Admin or non-Admin PS mode, this non-admin script did not work for me https://docs.dapr.io/getting-started/install-dapr-cli/#install-without-administrative-rights 

Specifically this 

$script=iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1; $block=[ScriptBlock]::Create($script); invoke-command -ScriptBlock $block -ArgumentList "", "$HOME/dapr"
@dalkoran  - Are you seeing this install successfully

Regardless of the above I suggest changing the docs code block to have this, is you want to install to a different into a different path

``ps code
$Env:DAPR_INSTALL_DIR = "C:\mydevelopment\tools"
echo $Env:DAPR_INSTALL_DIR
$script=iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1; $block=[ScriptBlock]::Create($script); invoke-command -ScriptBlock $block -ArgumentList "", "$env:DAPR_INSTALL_DIR"
``end ps code

@dalkoran @mukundansundar  - Would like to hear your thoughts

**Comment by pravinpushkar** [comment]
@msfussell The script worked just fine for me in both admin/non-admin mode.

**Comment by msfussell** [comment]
Resolved
