### ISSUE TITLE
Documentation for Kubernetes "Create State store component" does not contain "actorStateStore" parameter

### ISSUE THREAD

**Issue by prodmitry** [dapr/docs#2184]
**Describe the issue**
The article "Create State store component" does not include the "actorStateStore" parameter, so Dapr cannot initialize the state store and results in unclear errors

**URL of the docs**
https://docs.dapr.io/getting-started/configure-state-pubsub/#create-state-store-component

**Expected content**
Should contain the following metadata parameter:
`  - name: actorStateStore
    value: "true"`

**Additional context**
When calling actors, the following error appears:
`{
"errorCode": "ERR_ACTOR_RUNTIME_NOT_FOUND",
"message": "actor runtime is not configured"
}`

**Comment by hhunter-ms** [comment]
This issue has been resolved in the PRs attached to this dapr/dapr issue: https://github.com/dapr/dapr/issues/4273
