### ISSUE TITLE
Instructions on how to rotate self-generated mTLS root cert

### ISSUE THREAD

**Issue by artursouza** [dapr/docs#2185]
**What content needs to be created or modified?**
Instructions on how to rotate self-generated cert

**Describe the solution you'd like**
Current instructions are only applicable for bring your own certs.

Add instructions to rotate certificate that is auto-generated from sentry:

	1.	Delete the current certificate record: ` kubectl delete secret dapr-trust-bundle -n dapr-system`
	2.	Restart sentry:  `kubectl rollout restart -w deployment/dapr-sentry -n dapr-system` 
	3.	Restart other control plane services: ` kubectl rollout restart deployment/dapr-operator -n dapr-system && kubectl rollout restart deployment/dapr-sidecar-injector -n dapr-system && kubectl rollout restart deployment/dapr-placement -n dapr-system`
	4.	Once step 3 is completed, do a rollout restart for your applications.

Please, validate these steps DO NOT cause an outage.

**Where should the new material be placed?**
https://docs.dapr.io/operations/security/mtls/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
N/A

**Additional context**

- [ ] Validate these steps DO NOT cause an outage.

**Comment by yaron2** [comment]
> **What content needs to be created or modified?** Instructions on how to rotate self-generated cert
> 
> **Describe the solution you'd like** Current instructions are only applicable for bring your own certs.
> 
> Add instructions to rotate certificate that is auto-generated from sentry:
> 
> ```
> 1.	Delete the current certificate record: ` kubectl delete secret dapr-trust-bundle -n dapr-system`
> 2.	Restart sentry:  `kubectl rollout restart -w deployment/dapr-sentry -n dapr-system` 
> 3.	Restart other control plane services: ` kubectl rollout restart deployment/dapr-operator -n dapr-system && kubectl rollout restart deployment/dapr-sidecar-injector -n dapr-system && kubectl rollout restart deployment/dapr-placement -n dapr-system`
> 4.	Once step 3 is completed, do a rollout restart for your applications.
> ```
> 
> Please, validate these steps DO NOT cause an outage.
> 
> **Where should the new material be placed?** https://docs.dapr.io/operations/security/mtls/
> 
> **The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos** N/A
> 
> **Additional context**
> 
> * [ ]  Validate these steps DO NOT cause an outage.

The steps here are no longer true since we moved to mount the secret in Sentry rather than getting it through the Kubernetes API.

The steps should now be:

### Rotating a cert with the same private key - applicable to bring your own cert

This method will not incur downtime when the sidecars are issued rolling updates.

1. Generate a new root CA cert, issuer key and issuer cert from the existing private key.
2. Update the `dapr-trust-bundle` secret with the new values
3. Rollout restart Sentry
4. Rollout restart Control Plane
5. Rollout restart apps

### Rotating a cert with a new private key - applicable to bring your own cert / dapr managed certs

This method will see potential downtime for service invocation scenarios when rolling updates are issued.

1. Generate a private key, new root CA cert, issuer key and issuer cert
2. Update the `dapr-trust-bundle` secret with the new values
3. Rollout restart Sentry
4. Rollout restart Control Plane
5. Rollout restart apps

**Comment by yaron2** [comment]
## Update:

To get Dapr to rotate the cert, apply the following YAML:

```
apiVersion: v1
kind: Secret
metadata:
  name: dapr-trust-bundle
  namespace: dapr-system
  labels:
    app: dapr-sentry
data:
```

And rollout restart Sentry.

Change `namespace` to whatever namespace the control plane is deployed to.

**Comment by artursouza** [comment]
Steps to rotate auto-generated root cert:

1.	Clear (not delete) the current trust bundle: kubectl apply -f - (then paste the following yaml):
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: dapr-trust-bundle
  namespace: dapr-system
  labels:
    app: dapr-sentry
data:
```

2.	Restart sentry: `kubectl rollout restart deployment/dapr-sentry -n dapr-system`

3.	Restart other control pane services: `kubectl rollout restart deployment/dapr-operator -n dapr-system && kubectl rollout restart deployment/dapr-sidecar-injector -n dapr-system && kubectl rollout restart statefulset/dapr-placement-server -n dapr-system`

Rotate apps, if mTLS is enabled for apps.

**Comment by yaron2** [comment]
> Steps to rotate auto-generated root cert:
> 
> 1. Clear (not delete) the current trust bundle: kubectl apply -f - (then paste the following yaml):
>    apiVersion: v1
>    kind: Secret
>    metadata:
>    name: dapr-trust-bundle
>    namespace: dapr-system
>    labels:
>    app: dapr-sentry
>    data:
> 2. Restart sentry: kubectl rollout restart deployment/dapr-sentry -n dapr-system
> 3. Restart other control pane services (correted): kubectl rollout restart deployment/dapr-operator -n dapr-system && kubectl rollout restart deployment/dapr-sidecar-injector -n dapr-system && kubectl rollout restart statefulset/dapr-placement-server -n dapr-system
> 
> Rotate apps, if mTLS is enabled for apps.

Please use YAML and code formatting

**Comment by fabistb** [comment]
Just for my understanding would a dapr update also trigger a certificate rotate?

**Comment by yaron2** [comment]
> Just for my understanding would a dapr update also trigger a certificate rotate?

Nope

**Comment by msfussell** [comment]
Updated.
