### ISSUE TITLE
Add information about setting content type for objects in the state store

### ISSUE THREAD

**Issue by dmitsh** [dapr/docs#2186]
**What content needs to be created or modified?**
This is an [old ask](https://github.com/dapr/dapr/issues/2892) to differentiate content types of stored objects in the state store.
This will allow to properly store, retrieve, and query data.

**Describe the solution you'd like**

The solution is described in https://github.com/dapr/dapr/issues/2892, https://github.com/dapr/dapr/pull/4210

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/4210

**Additional context**

**Comment by msfussell** [comment]
Resolved.
