### ISSUE TITLE
Query API for Redis state store

### ISSUE THREAD

**Issue by dmitsh** [dapr/docs#2187]
**What content needs to be created or modified?**

Support for statestore query API in Redis requires additional components and steps.

**Describe the solution you'd like**

Details are [here](https://github.com/dapr/components-contrib/issues/1211)

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1488

**Additional context**

**Comment by msfussell** [comment]
Resolved
