### ISSUE TITLE
statestore query API: remove 'value' prefix from key names in query JSON

### ISSUE THREAD

**Issue by dmitsh** [dapr/docs#2191]
**What content needs to be created or modified?**

There is a minor change in statestore query API syntax.
The details are here: https://github.com/dapr/components-contrib/issues/1490

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1491

**Additional context**

**Comment by msfussell** [comment]
Merged
