### ISSUE TITLE
How to: Pub Sub Java example execution misleading

### ISSUE THREAD

**Issue by jakesmolka** [dapr/docs#2193]
**Describe the issue**

When following the how to on the pub/sub mechanics and using the Java examples, the given `dapr` commands aren't working.

The `checkout` app should be run with
``` bash
dapr run --app-id checkout --app-port 6002 --dapr-http-port 3602 --dapr-grpc-port 60002 mvn spring-boot:run
```

I have set up a simple example repo showing what I composed from going though the documentation page. (Maybe it did something wrong, too...): https://github.com/jakesmolka/dapr-pubsub-java-example

Utilizing the given info from the doc I tried running the `checkout` service with:
```bash
dapr run --app-id checkout --app-port 6002 --dapr-http-port 3602 --dapr-grpc-port 60002 --components-path ../my-components mvn spring-boot:run
```

But the Spring Boot app is listening on 8080. Thus running with works: 
```bash
dapr run --app-id checkout --app-port 8080 --dapr-http-port 3602 --dapr-grpc-port 60002 --components-path ../my-components --log-level debug mvn spring-boot:run
```

The other `orderprocessing` app appears to run correctly. But a quick discussion with @yaron2  on the community discord (see link below) showed that the given `--app-id` parameter might be wrong here too:
> Your other app, unless listening to 6001, is probably also blocking, but the sidecar might have finished the init pub/sub step to allow it to work. btw, if you're not expecting Dapr to App communications on this app, just drop the --app-port alltogether

I don't understand Dapr well enough yet to actually evaluate what's correct here.

**URL of the docs**

https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/

**Expected content**

Correct snippets and correct commands to execute them. Otherwise this is very confusing for newcomers.

The alternative might be to add a note stating how those commands are just hints and need to be customized, but I don't see how that would help people trying to learn Dapr much 🙂 

**Additional context**

Source of comment from @yaron2 https://discord.com/channels/778680217417809931/901141467840524289/941070144069845042

**Comment by msfussell** [comment]
@amulyavarote @greenie-msft - Given that we are updating the Quickstarts, can you take a look at this issue?

**Comment by hhunter-ms** [comment]
This issue has been resolved
