### ISSUE TITLE
Permissions for AWS IAM Policy do not suffice to let Dapr auto provision AWS resources for SQS/SNS pub sub

### ISSUE THREAD

**Issue by ianbeemsterboerr** [dapr/docs#2206]
**Describe the issue**
These example permissions do not suffice for letting Dapr auto provision the required AWS resources. So far I found that these permissions are missing:
- sns:TagResource
- sqs:SendMessage
- sqs:TagQueue

There is a duplicate permission entry for sns:ListSubscriptionsByTopic permission. (minor)

**URL of the docs**
[url](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/)

**Expected content**
The required permissions, including sns:TagResource. Even with this permission it still gives me a Unauthorized response through Dapr logs, but it remains unclear through the response or CloudTrail that the missing permission is.

**Screenshots**
When I boot up the app and the sidecar I get the following logs:
`level=error msg="failed to subscribe to topic mws-messages-some-events-initialphoneverificationcompletedevent: error getting topic ARN for mws-messages-some-events-initialphoneverificationcompletedevent: error while creating an SNS topic: AuthorizationError: User: arn:aws:iam::************:user/dapr-local-sqs-test is not authorized to perform: SNS:TagResource on resource: arn:aws:sns:eu-west-1:************:mws-messages-some-events-initialphoneverificationcompletedevent because no some-based policy allows the SNS:TagResource action\n\tstatus code: 403, request id: 3c510feb-18f8-5ad8-8fc5-6665ab783b80" app_id=mws-some-webapp instance=589cb03abcfc scope=dapr.runtime type=log ver=1.6.0`

**Additional context**
From the IAM control panel my permissions look like these:
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl",
                "sns:ListSubscriptionsByTopic",
                "sqs:ChangeMessageVisibility",
                "sns:GetTopicAttributes",
                "sqs:ReceiveMessage",
                "sns:CreateTopic",
                "sqs:GetQueueAttributes",
                "sns:UntagResource",
                "sns:Publish",
                "sns:Subscribe",
                "sqs:CreateQueue",
                "sqs:SetQueueAttributes"
            ],
            "Resource": [
                "arn:aws:sns:eu-west-1:************:*",
                "arn:aws:sqs:eu-west-1:************:*"
            ]
        }
    ]
}
```

**Comment by msfussell** [comment]
Resolved. FIxed and added to docs
