### ISSUE TITLE
Add documentation to show how api-log-level flag can be used

### ISSUE THREAD

**Issue by amulyavarote** [dapr/docs#2220]
**What content needs to be created or modified?**
dapr docs to be modified to show the examples

**Describe the solution you'd like**
Add examples to show how the newly added flag can help debug.

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/4288
https://github.com/dapr/cli/pull/903

**Additional context**

Issue associated with this is 
https://github.com/dapr/dapr/issues/4119

**Comment by msfussell** [comment]
Added to docs
