### ISSUE TITLE
Squiggly lines in screenshots/diagrams

### ISSUE THREAD

**Issue by e-St** [dapr/docs#2222]
**URL of the docs page**
https://docs.dapr.io/concepts/overview/

**How is it currently worded?**
Squiggly lines under some words in screenshots/diagrams.

**How should it be worded?**
Remove red squiggly lines from screenshots/diagrams.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/10636497/156431437-383b713c-0707-4973-beaf-b46b23e802e1.PNG)
This is one example, but there are many more cases on the page.

**Additional context**
The diagrams should be fixed not to include squiggly lines or the squiggly lines should be replaced by solid underlines.

**Comment by msfussell** [comment]
PR #2313

**Comment by msfussell** [comment]
Resolved
