### ISSUE TITLE
text shows up as code

### ISSUE THREAD

**Issue by duglin** [dapr/docs#2226]
On: https://docs.dapr.io/getting-started/configure-state-pubsub/
I see this:
![image](https://user-images.githubusercontent.com/1944671/156637755-49fe999a-6239-4498-8c26-cee1a62d5659.png)

I'm pretty sure the "Self-hosted slim mode" section should be normal text, not a code snippet. I tried to see why the md turned it into code but I couldn't figure it out, otherwise I would have submitted a PR.  I'm wondering if it's the presence of the back-tick text in there.

**Comment by hhunter-ms** [comment]
@msfussell @duglin it looks like this was resolved at some point and not linked to a PR... ok to close? https://docs.dapr.io/getting-started/tutorials/configure-state-pubsub/#step-3-apply-the-configuration

**Comment by duglin** [comment]
yup I'll close it. I assume that the original link https://docs.dapr.io/getting-started/configure-state-pubsub/ is supposed to return a 404 now, right?
