### ISSUE TITLE
Missing mTLS diagram?

### ISSUE THREAD

**Issue by duglin** [dapr/docs#2229]
On: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-overview/
it says:

- - -
[](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-overview/#service-to-service-security)Service-to-service security

All calls between Dapr applications can be made secure with mutual (mTLS) authentication on hosted platforms, including automatic certificate rollover, via the Dapr Sentry service. The diagram below shows this for self hosted applications.
- - -
However there is no diagram following this text. There are other diagrams later in the page, but none of them relate to mTLS. I think we're either missing a picture or that last sentence should be removed. I can PR the "remove" if wanted, but I suspect a picture might be more helpful.

**Comment by msfussell** [comment]
I would just remove the sentence. The security concept article has a diagram.
