### ISSUE TITLE
StateStore for CockroachDB now available

### ISSUE THREAD

**Issue by r-c-correa** [dapr/docs#2236]
**What content needs to be created or modified?**
Add support for CockroachDB StateStore on documentation.

**Describe the solution you'd like**
Show StateStore support for CockroachDB on documentation.

**Where should the new material be placed?**
Inside StateStore table: https://docs.dapr.io/reference/components-reference/supported-state-stores/
New page on supported state stores: https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-cockroachdb/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
Issue: dapr/components-contrib/issues/1556
PR: dapr/components-contrib/pull/1559

**Additional context**
![image](https://user-images.githubusercontent.com/73140039/157152783-bc164970-77f6-492f-b099-001b8d722c0b.png)

**Comment by msfussell** [comment]
Closing. Added to docs.
