### ISSUE TITLE
Error Installing in WSL

### ISSUE THREAD

**Issue by ajaysingh77** [dapr/docs#224]
## Expected Behavior

dapr should be installed in WSL 

## Actual Behavior

As mentioned in dapr installations doc, I am able to download the dapr in WSL but when I am running "dapr initi" command after few mintues I am getting the following error
"Error moving dapr binary to path: open /usr/local/bin/daprd: permission denied"
I have opened the command (WSL) in admin mode.

To verify this when I insatlled dapr and dapr init in windows command prompt it works without any error. 
Do't know whether I am missing something or dapr is currently not supported in WSL.

**Comment by yaron2** [comment]
Did you try with sudo?

**Comment by ajaysingh77** [comment]
@yaron2 I also with sudo for e.g.
sudo dapr init
[sudo] password for ABC:
⌛  Making the jump to hyperspace...
❌  Could not connect to Docker.  Is Docker installed and running?

To verify the last error, I tried the command "sudo docker images" but it is giving
"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

while command "docker images" is working.
So actually I am not able to execute the "sudo dapr init" command

**Comment by jplane** [comment]
Having the same issue... any resolution for this yet?

**Comment by yaron2** [comment]
This PR should mitigate the issue:
https://github.com/dapr/cli/pull/213

**Comment by xewn** [comment]
sudo vi /lib/systemd/system/docker.service
ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375
sudo service docker restart

**Comment by xewn** [comment]
`
sudo ./dapr init
docker [run --name dapr_placement --restart always -d --entrypoint ./placement -p 50005:50005 daprio/dapr] failed with: exit status 125
`

**Comment by pankajthakare-mb** [comment]
C:\WINDOWS\System32>dapr init
Making the jump to hyperspace...
Downloading binaries and setting up components...
docker [run --name dapr_redis --restart always -d -p 6379:6379 redis] failed with: exit status 125

Any luck with this?

**Comment by msfussell** [comment]
@orizohar The issue with WSL is lack of docker support. This issue would have to be addressed with https://github.com/dapr/cli/issues/301

**Comment by orizohar** [comment]
Seems like [Docker will be supported in WSL2](https://www.docker.com/blog/docker-hearts-wsl-2/) that will be available mid May in Windows build 2004 (already available now for Windows Insider users). Regardless, the point about `dapr init` depending on Docker is still valid.

**Comment by AaronCrawfis** [comment]
@orizohar @yaron2 has this been resolved with WSL2?

**Comment by orizohar** [comment]
> @orizohar @yaron2 has this been resolved with WSL2?

Yes, this works is WSL2. Also we now support a Dapr init with no docker dependency (slim) https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-no-docker/
