### ISSUE TITLE
Installing NATs Jetstream into K8s requires additional params for Jetstream Enabled

### ISSUE THREAD

**Issue by espinm2** [dapr/docs#2247]
**Describe the issue**

On here:
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-jetstream/

```
helm repo add nats https://nats-io.github.io/k8s/helm/charts/
helm install my-nats nats/nats
```

This however does the default install. To enable jet stream you need to set this flag mentioned here.
https://github.com/nats-io/k8s/tree/main/helm/charts/nats#jetstream

**URL of the docs**

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-jetstream/

**Expected content**

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
@espinm2 - Could you submit a suggest PR for this change? That would be the best way to get this updated. Thanks

**Comment by greenie-msft** [comment]
@espinm2, can you please see @msfussell's comment above? It would be helpful if you could submit the PR for updating the content.
