### ISSUE TITLE
Invalid resource name used in example resources

### ISSUE THREAD

**Issue by jjcollinge** [dapr/docs#2251]
**Describe the issue**
Throughout the https://v1-7.docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/ doc the name used for resources (`Component` and `Subscription`)  is `order_pub_sub` is invalid.
I appreciate this is only meant as a reference but I think it makes sense to use a valid resource, the current one results in the following error:
```
The Component "order_pub_sub" is invalid: metadata.name: Invalid value: "order_pub_sub": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**URL of the docs**
https://v1-7.docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/

**Expected content**
Example resources should be valid resources.

**Comment by msfussell** [comment]
Fixed
