### ISSUE TITLE
Missing 'to' in sentence

### ISSUE THREAD

**Issue by jorimvanhove** [dapr/docs#2254]
**URL of the docs page**
https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-development/

**How is it currently worded?**
However, developing microservices challenges you think about your local development process for more than one at a time.

**How should it be worded?**
However, developing microservices challenges you to think about your local development process for more than one at a time.

**Screenshots**
n.a.

**Additional context**
n.a.

**Comment by aujoiner241** [comment]
I will work on this and submit a PR.

**Comment by msfussell** [comment]
Fixed
