### ISSUE TITLE
Add disableTls to pubsub kafka example config

### ISSUE THREAD

**Issue by Taction** [dapr/docs#2255]
**What content needs to be created or modified?**

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/

**Describe the solution you'd like**

Add the following to example config yaml.
```
  - name: disableTls
    value: "true"
```

**Additional context**

The default value of `disableTls` is false. There are some users, who use Kafka without tls, have trouble using it. 
such as https://github.com/dapr/dapr/issues/3766

**Comment by Taction** [comment]
Please help add a good-first-issue label.

**Comment by Taction** [comment]
This needs to be added since v1.6

**Comment by yaron2** [comment]
> This needs to be added since v1.6

Is this also true for the Kafka binding? What causesd this change?

**Comment by Taction** [comment]
> Is this also true for the Kafka binding?

No, Kafka binding currently does not support tls.

> What causesd this change?

This config is introduced from
https://github.com/dapr/components-contrib/pull/1229
It was automatically set according to the tls-related configuration configured or not, but now is configured from metadata with default value false.
Users who do not use tls, especially for test purposes may miss this config.

**Comment by msfussell** [comment]
@Taction - What specifically are you looking for here given this example https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/#none? Are you wanting to add some more words about TLS usage? Can you clarify this issue?

**Comment by Taction** [comment]
@msfussell Sorry for the delay. I agree with adding more words about TLS usage. In fact, the example config is not using TLS the default config of which is true. So some users may miss this configuration and causes an error unless they read the document carefully. I've noticed that several issues are related to that, so I think it would be useful adding to the example config.
I'll submit a pr for that.
