### ISSUE TITLE
Error word in rethinkdb state store docs

### ISSUE THREAD

**Issue by wwbweibo** [dapr/docs#2258]
**URL of the docs page**
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-rethinkdb/#component-format

**How is it currently worded?**
If you wish to use Redis as an actor store, append the following to the yaml.

**How should it be worded?**
If you wish to use RethinkDB as an actor store, append the following to the yaml.

**Screenshots**
<img width="642" alt="image" src="https://user-images.githubusercontent.com/20398347/158053436-04c2a5a0-8cf3-4c47-9d8e-1a66fb1ec8cf.png">

**Additional context**

**Comment by ghost** [comment]
I will make changes regarding this issue.
