### ISSUE TITLE
S3 binding: document how to use Minio

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2268]
**Describe the issue**

When connecting to Minio as S3 server, there are a few differences:

1. `forcePathStyle` needs to be set to `true`
1. Region should be set to `us-east-1`
2. Endpoint needs to be the address of the Minio server (with optional port)
3. In some cases it may be desirable to set `disableSSL: true` (Note that this will be available in 1.7) or `insecureSSL: true` (https://github.com/dapr/components-contrib/pull/1593)

**URL of the docs**

https://docs.dapr.io/reference/components-reference/supported-bindings/s3/

**Expected content**

A section on configuring the S3 binding for Minio.

**Additional context**

This morning, a customer was very confused on how to set up Minio with Dapr via Discord chat.

**Comment by msfussell** [comment]
Closing. Resolved and fixed
