### ISSUE TITLE
Quickstarts NET commands have some typo

### ISSUE THREAD

**Issue by uy-andrew** [dapr/docs#2274]
**URL of the docs page**
https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/
https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/

**How is it currently worded?**
In Publish and Subscribe:
dapr run --app-id checkout --components-path ../../components -- dotnet run
dapr run --app-id order-processor --components-path ../../components --app-port 5001 -- dotnet run

In Service Invocation:
dapr run  --app-id checkout --app-protocol http --dapr-http-port 3500 -- npm start
dapr run --app-port 6001 --app-id order-processor --app-protocol http --dapr-http-port 3501 -- npm start

**How should it be worded?**
In Publish and Subscribe:
dapr run --app-id checkout --components-path ../../../components -- dotnet run
dapr run --app-id order-processor --components-path ../../../components --app-port 7001 -- dotnet run

In Service Invocation:
dapr run  --app-id checkout --app-protocol http --dapr-http-port 3500 -- dotnet run
dapr run --app-port 7001 --app-id order-processor --app-protocol http --dapr-http-port 3501 -- dotnet run

**Screenshots**
![image](https://user-images.githubusercontent.com/37019607/159119309-b96036b8-7a33-4e3a-8873-94403dcb0c5a.png)
![image](https://user-images.githubusercontent.com/37019607/159119337-58492c37-fa14-4f7a-b057-d4645c2c4ec1.png)
![image](https://user-images.githubusercontent.com/37019607/159119360-ffd02c79-e4b3-42dc-a9aa-d1d30a5e926f.png)
![image](https://user-images.githubusercontent.com/37019607/159119378-bed8dfea-1a23-4d4e-8431-8248309e1cc9.png)

**Additional context**
Just wanted that command to be updated so that any new NET developer using dapr will have a flawless experience following the Quickstarts.

**Comment by msfussell** [comment]
Closing. FIxed
