### ISSUE TITLE
Quickstart: Publish and Subscribe error in starting .NET checkout command

### ISSUE THREAD

**Issue by vidarkongsli** [dapr/docs#2277]
**URL of the docs page**
https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/

**How is it currently worded?**
`dapr run --app-id checkout --components-path ../../components -- dotnet run`

**How should it be worded?**
`dapr run --app-id checkout --components-path ../../../components -- dotnet run`

**Additional context**
Currently, running the command results in the error `CreateFile ../../components: The system cannot find the file specified.`

**Comment by greenie-msft** [comment]
This has been addressed. Closing issue
