### ISSUE TITLE
New CLI mtls commands for renewing the generated root and issued certificates

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#2285]
Document the new CLI commands from this issue https://github.com/dapr/cli/issues/892 and this PR https://github.com/dapr/cli/pull/912

**Comment by mukundansundar** [comment]
@pravinpushkar Please add the docs for the command [here](https://github.com/dapr/docs/tree/v1.6/daprdocs/content/en/reference/cli) ...

**Comment by greenie-msft** [comment]
Addressed in #2293
