### ISSUE TITLE
Add content for recent changes to dapr init

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#2294]
**What content needs to be created or modified?**
Newly introduced flag and environment varible

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
Related pull requests- 
https://github.com/dapr/cli/pull/926
https://github.com/dapr/cli/pull/888

**Comment by greenie-msft** [comment]
Closing as #2295 addresses this issue.
