### ISSUE TITLE
Add documentation for component update behavior

### ISSUE THREAD

**Issue by shubham1172** [dapr/docs#2296]
**What content needs to be created or modified?**

It should be called out in the documentation that Dapr needs to be restarted whenever components are reloaded (for both k8s and standalone mode)

**Where should the new material be placed?**

TODO

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/4376

**Additional context**

None

**Comment by greenie-msft** [comment]
Closing as https://github.com/dapr/docs/pull/2297 addresses this
