### ISSUE TITLE
Dapr self hosted installer bundle

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#2299]
This is the documentation for the self hosted installer described in this issue https://github.com/dapr/cli/issues/731
These are the PRs
- Release workflow: https://github.com/dapr/installer-bundle/pull/1
 - Enhancing Dapr CLI: https://github.com/dapr/cli/pull/898

Docs that need to be update include
1) Adding a new article under Operations section on the why and how with examples. Let's discuss where. Maybe under hosting or may need a brand new heading.
2) Updating the Dapr CLI reference docs https://docs.dapr.io/reference/cli/ with an example
3) Mentioning this in the CLI Repo readme https://github.com/dapr/cli

**Comment by shivamkm07** [comment]
@msfussell Thanks for opening the issue. 

1. I think a new article under Operations/hosting/self-hosted should be fine, as the change is only for self-hosted case
2. Will update reference/cli/dapr-init.md, adding details about the new flag
3. Agreed, will do.
Anywhere else do we need to mention about this?

I have started work on PR, and will continue on Monday.

**Comment by shivamkm07** [comment]
> @msfussell Thanks for opening the issue.
> 
> 1. I think a new article under Operations/hosting/self-hosted should be fine, as the change is only for self-hosted case
> 2. Will update reference/cli/dapr-init.md, adding details about the new flag
> 3. Agreed, will do.
>    Anywhere else do we need to mention about this?
> 
> I have started work on PR, and will continue on Monday.

Btw JFYI https://github.com/dapr/installer-bundle/blob/main/README.md also details out the documentation regarding how to use the downloaded bundle in airgap environment.

**Comment by greenie-msft** [comment]
Closing as this is addressed in #2301
