### ISSUE TITLE
couldn't see redis container after dapr init

### ISSUE THREAD

**Issue by manjeetbhatia** [dapr/docs#232]
## Redis container not showing up after dapr init?
hey I'm running dapr on a virtual machine that has docker installed.
I don't see redis container show up after dapr init. what am I missing ?

Downloading binaries and setting up components...
✅  Success! Dapr is up and running
sudo docker ps (returns No container)
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by yaron2** [comment]
Is this a Linux machine?

Have you tried `sudo dapr init`?

**Comment by manjeetbhatia** [comment]
I used sudo.

**Comment by yaron2** [comment]
Do you see anything exited with `docker ps -a`?

**Comment by manjeetbhatia** [comment]
None same as sudo docker ps
sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by yaron2** [comment]
What OS? cloud provider?

**Comment by manjeetbhatia** [comment]
ubuntu xenial, a VM hosted via libvirt provider on ubuntu xenial host

**Comment by manjeetbhatia** [comment]
actually figured out, this is a bug in dapper and if docker fails to get image (due to firewall) dapr init still returns success.

**Comment by yaron2** [comment]
Alright, I'll open a bug in the CLI for this.

**Comment by yaron2** [comment]
Now tracked here: https://github.com/dapr/cli/issues/200

Can we close this issue?

**Comment by manjeetbhatia** [comment]
thanks !
