### ISSUE TITLE
Tabs not working (Docker CLi)

### ISSUE THREAD

**Issue by balloman** [dapr/docs#2323]
**Describe the bug**
The buttons to switch between os do not work on the cli installation website

**Steps to reproduce**
Go here: https://docs.dapr.io/getting-started/install-dapr-cli/
Click windows
**Expected behavior**
The windows tab activates along with the subsequent instructions

**Screenshots**
![image](https://user-images.githubusercontent.com/11762027/161402517-98fba0ef-675a-4812-b1a4-c9e3ec9d4515.png)
![image](https://user-images.githubusercontent.com/11762027/161402524-fcf9f495-f70a-409b-b457-416ed1296d35.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 99

**Comment by msfussell** [comment]
@balloman - Can you try this on another browser? I am not seeing this issue on Chrome.

**Comment by balloman** [comment]
Yeah, tried again today, and the issue seems to be fixed now, same browser and everything. Must have been a backend thing, I guess. Thanks anyway!
