### ISSUE TITLE
Cosmos DB state store docs need update with steps for creating stored procedures manually

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2325]
**What content needs to be created or modified?**

https://github.com/dapr/components-contrib/pull/1613 requires content updates to the page https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/ to include the manual steps for creating the stored procedures in the database, when using Azure AD to authenticate

**Describe the solution you'd like**
I need to write docs for creating the stored procedures manually

**Where should the new material be placed?**
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1613

**Comment by msfussell** [comment]
resolved
