### ISSUE TITLE
It seems that the API token doesn't need to be a JWT

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2329]
**Describe the issue**
I'm opening here because it seems primarily a documentation issue.

In the documentation for ["Enable API token authentication in Dapr"](https://docs.dapr.io/operations/security/api-token/), which is about using API tokens to authenticate calls from applications to the Dapr sidecars, the docs state:

> Dapr uses [JWT](https://jwt.io/) tokens for API authentication.

Looking at how the feature is implemented (both at the rest of the docs and in the source), it seems that the token doesn't need to be a JWT and any shared secret would work.

JWTs are self-contained tokens, which include a number of claims. Thanks to the use of digital signatures, an application can trust that the claims are valid and non-tampered with. They're mostly useful to exchange information between systems.

In the case of API tokens in Dapr, it seems that they are indeed treated as opaque strings and compared for equality. Dapr doesn't try to decode the JWT (and without the option to pass the expected issuer of the token, it has no way to validate the JWTs even if it did decode them).

Given that using JWTs does add to complexity, and given that it seems that there's no actual need for those tokens to be JWTs, should we change the docs to recommend using random shared secrets rather than JWTs?

**URL of the docs**
https://docs.dapr.io/operations/security/api-token/

**Comment by msfussell** [comment]
Yes, this is true, it can be any token
