### ISSUE TITLE
v1.7 docs release endgame

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#2343]
## v1.6 Branch - use this for reference: TBD **** https://github.com/dapr/docs/pull/1925/files

@msfussell @hhunter-ms @greenie-msft 

In pending PR:

- [x] Add v1.7 (latest) to nav bar
- [x] Archive notice
- [x] Update root README.md
- [x] Update URL in config.toml
- [x] Delete workflow file

Day of:
- [ ] Push v1.6 PR

## v1.7 Branch - use this for reference: TBD **** https://github.com/dapr/docs/pull/1926/files

@msfussell @hhunter-ms @greenie-msft 

In a pending PR:

- [x] Update README.md
- [x] Update version dropdown in nav bar
- [x] Supported versions section
- [x] All output logs change 1.6 to 1.7
- [x] Update URL in config.toml
- [x] Update workflow for docs.dapr.io to v1.6 branch
- [x] Update quickstart page links to the latest release branch (requires quickstarts to cut a release branch)

Day of: 

- [ ] Push v1.7 PR

## GitHub - After release
@greenie-msft 

- [ ] Make v1.7 the default branch
- [ ] One last upmerge

## Website
- [x] Create new website for v1.7, v1.8, v1.9 - @willtsai + @greenie-msft 
- [x] Add DNS entry for new website - @greenie-msft  to ask CNCF to create this. Let's as for v1-7.docs, v1-8.docs, v1-9.docs.
- [x] Add custom domain & generate SSL certificate - Needs to happen after the DNS entry is created - @willtsai + @greenie-msft 

## v1.8 Branch 

@msfussell @hhunter-ms @greenie-msft 

- [ ] Create v1.8 branch
- [ ]  Update website workflow file - See this PR https://github.com/dapr/docs/pull/2156 for the Nav bar
- [ ]  Upmerge from release branch to preview branch

## Release announcements
- [x] Release notes/blog  - @paulyuk 
- [x] Tweet release announcement - @greenie-msft 
- [x] Discord release announcement - @greenie-msft

**Comment by XavierGeerinck** [comment]
Note: JS SDK docs seems to be pointing to an old release, can this get updated as well? @greenie-msft

**Comment by msfussell** [comment]
Released
