### ISSUE TITLE
add jetstream pubsub example

### ISSUE THREAD

**Issue by calvin2021y** [dapr/docs#2353]
**What content needs to be created or modified?**

jetstream pubsub document need code example.

**Describe the solution you'd like**

code example for sub and pub with jetstream build block.

**Where should the new material be placed?**

should put into the link `components-reference/supported-pubsub/setup-jetstream/`

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

none

**Additional context**

none

**Comment by msfussell** [comment]
@calvin2021y - Would you be able to provide an example as a PR in the docs? Would REALLY appreciate this

**Comment by hhunter-ms** [comment]
closing until an example for this is created
