### ISSUE TITLE
Pub/Sub AWS SNS/SQS - document new concurrency mode metadata field

### ISSUE THREAD

**Issue by amimimor** [dapr/docs#2354]
**What content needs to be created or modified?**

Pub/Sub AWS SNS/SQS - document new `concurrencyMode` metadata field usage

**Describe the solution you'd like**

concurrency mode should be added to the metadata fields description of the component

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1651

**Additional context**

**Comment by msfussell** [comment]
Resolved
