### ISSUE TITLE
docker exec -it dapr_redis redis-cli did not return anything

### ISSUE THREAD

**Issue by peachblossomgame** [dapr/docs#2370]
**Describe the issue**
after` curl http://localhost:3500/v1.0/state/statestore/name`
it returns the following
`"Bruce Wayne"%`

then  `docker exec -it dapr_redis redis-cli`
did not return what expected, it says:
`127.0.0.1:6379>`
then run : `keys *`
it returns : `(empty array)`
**URL of the docs**

https://docs.dapr.io/getting-started/get-started-api/
**Expected content**

Output:
1) "`myapp||name"`
**Screenshots**

**Additional context**

**Comment by hhunter-ms** [comment]
Thanks for your feedback @peachblossomgame - the docs example here works for me and I'm getting the expected output. Could you provide any more details so we can help resolve this for you?

**Comment by msfussell** [comment]
@peachblossomgame  If you have more details here please add them and reopen this issues.

**Comment by white-label-development** [comment]
Same issue. On windows. 

Also went to running container in docker desktop, opened cli, ran redis-cli, and looked for keys. no keys. A powershell request to the state store returned "Bruce Wayne" so it must be stored somewhere! 

Solved: I had a non-containerized standalone redis-server already running on port 6379, the post to http://localhost:3500/v1.0/state/statestore had stored state there.
