### ISSUE TITLE
Customize 404 error page to remove Microsoft Azure reference

### ISSUE THREAD

**Issue by berndverst** [dapr/docs#2378]
The docs need a custom error page for pages that aren't found. Right now the page shows a banner related to Microsoft Azure which is very confusing for Dapr users not using Azure.

In `/daprdocs/staticwebapp.config.json` we should add the following:

```
{
  "responseOverrides": {
    "404": {
      "rewrite": "/404.html",
      "statusCode": 404
    }
  }
}
```

And then probably add our custom 404 page in `/daprdocs/content/en` which should resolve to the path `/404.html` in this case.

**Comment by berndverst** [comment]
@greenie-msft @paulyuk @msfussell FYI -- you'll probably agree this is needed. Go to [docs.dapr.io/doesnotexist](https://docs.dapr.io/doesnotexist) to see what I mean.

**Comment by msfussell** [comment]
I have no objections to fixing this. This is weird.
