### ISSUE TITLE
High Availability Mode

### ISSUE THREAD

**Issue by dagongzhe2** [dapr/docs#2379]
How to do HA deployment？

**Comment by dagongzhe2** [comment]
![image](https://user-images.githubusercontent.com/104132372/164577372-da5d7e6b-5f7c-4acd-a3fe-1d6e4ccb9033.png)
Does each pod start with 3?

**Comment by yaron2** [comment]
> ![image](https://user-images.githubusercontent.com/104132372/164577372-da5d7e6b-5f7c-4acd-a3fe-1d6e4ccb9033.png) Does each pod start with 3?

In HA mode, each deployment (Sentry, Operator, Placement, Injector) will have 3 pods instead of 1.

**Comment by yaron2** [comment]
You can see here how to install in HA mode: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/#install-in-highly-available-mode

**Comment by msfussell** [comment]
Closing this issue. Please open if the doc does not address your issue. Thanks.
