### ISSUE TITLE
Dapr API logs instructions for k8s typo - breaks deployment

### ISSUE THREAD

**Issue by tobiasoort** [dapr/docs#2380]
**Describe the issue**
The Kubernetes instruction is wrong; it cites
```
annotations:
  dapr.io/enable-api-logging: true
```

where it should be

```
annotations:
  dapr.io/enable-api-logging: "true"
```

This might be nitpicky but novice users will get a very unreadable splurge of error back from kubectl that's not really helping them find this.

**URL of the docs**
https://docs.dapr.io/operations/troubleshooting/api-logs-troubleshooting/

**Expected content**
```
annotations:
  dapr.io/enable-api-logging: "true"
```

**Comment by yaron2** [comment]
Thanks for reporting this. It'd be great to get a PR that fixes this!
