### ISSUE TITLE
Add content for PubSub dead letter support

### ISSUE THREAD

**Issue by Taction** [dapr/docs#2395]
**What content needs to be created or modified?**
Add content for PubSub dead letter support.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/4399

**Additional context**

**Comment by msfussell** [comment]
@Taction - Can you get these doc PR created soon. It is preferable to do this at the time of the code checkin. Thanks

**Comment by yaron2** [comment]
Actually I've been meaning to write the docs for this feature myself, If ok with @Taction.

**Comment by Taction** [comment]
@yaron2 Sure, it is ok.

**Comment by yaron2** [comment]
Closed via #2500.
