### ISSUE TITLE
Metrics Resiliency 

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#2401]
**What content needs to be created or modified?**
Doc issue for https://github.com/dapr/dapr/issues/4524

**Comment by yaron2** [comment]
@piotrkpc can you please update [this doc](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md) with the new metrics?

**Comment by msfussell** [comment]
Resolved. See https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md#resiliency
