### ISSUE TITLE
Dapr Init Failing

### ISSUE THREAD

**Issue by RajivDutt** [dapr/docs#2411]
**Describe the issue**

Dapr Init is not able to download the images and the error message is not very clear.

**URL of the docs**

https://docs.dapr.io/getting-started/install-dapr-selfhost/

**Expected content**

Some hint about the error what could be wrong here.
also in documentation, we can add extra step to check, if images are downloaded properly or not.

**Screenshots**

C:\Users\shanaya>dapr init
Making the jump to hyperspace...
Container images will be pulled from Docker Hub
Installing runtime version 1.7.2
Downloading binaries and setting up components...
docker: Error response from daemon: failed to start service utility VM (createreadwrite): hcsshim::CreateComputeSystem 1814ea22c1d05ef4a36af9bc72ea8159b76f0a630b52b80f7080040af706c8ea_svm: The virtual machine could not be started because a required feature is not installed.
See 'docker run --help'.

**Additional context**

**Comment by msfussell** [comment]
@RajivDutt - Can you provide any more information on why this occurred? What was the actually issue that you encountered?

**Comment by msfussell** [comment]
@RajivDutt  - Closing. If there is more information on this please reopen. Thanks
