### ISSUE TITLE
Application Insights Otel collector example version update

### ISSUE THREAD

**Issue by fabistb** [dapr/docs#2412]
**What content needs to be created or modified?**
The _open-telemetry-collector-appinsights.yaml_ example file in the open telemetry collector applinsights documentation uses _opentelemetry-collector-contrib:0.40.0_.

https://docs.dapr.io/operations/monitoring/tracing/open-telemetry-collector-appinsights/

**Describe the solution you'd like**
The [opentelementry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) has recently released version _0.50.0_. 

Can the example be updated to the newest version?

**Additional context**
Is a verification process required to ensure everything is still working as expected?

**Comment by msfussell** [comment]
@fabistb - Thanks for raising this. Would you be able to push a suggested PR change having tested this with the new OTEL version?

**Comment by fabistb** [comment]
> @fabistb - Thanks for raising this. Would you be able to push a suggested PR change having tested this with the new OTEL version?

@msfussell sure. I just need a couple of days to test the new OTEL version.

**Comment by msfussell** [comment]
Merged
