### ISSUE TITLE
Visual Studio Code debug configuration environment variables need to be set for non default ports

### ISSUE THREAD

**Issue by francotiveron** [dapr/docs#2417]
**What content needs to be created or modified?**
How-To: Debug Dapr applications with Visual Studio Code WHEN USING NON DEFAULT PORTS

**Describe the solution you'd like**
Add that env variables DAPR_HTTP_PORT and DAPR_GRPC_PORT need to be put in the debug configuration and match "httpPort" and
"grpcPort" in the daprd task

**Where should the new material be placed?**
Added to existing page

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

[Specify the URL to the associated pull request, if applicable](https://docs.dapr.io/developing-applications/ides/vscode/vscode-how-to-debug-multiple-dapr-apps/#step-1-configure-launchjson)
-->

**Additional context**

![image](https://user-images.githubusercontent.com/8280970/166623699-748ceecc-0508-4257-9975-183ed68161a9.png)

**Comment by msfussell** [comment]
@francotiveron - Thanks for this. Would you be open to creating a suggestion in a docs PR for the change?

**Comment by msfussell** [comment]
@hhunter-ms - Would you be open to looking at this issue? In effect this topic here in the launch.json file should say that you can also provide env-variables that can be used if you are using different ports than baked into the code and you set these via env-variables for debugging to work
