### ISSUE TITLE
Documentation about HuaweiCloud CSMS secret store component

### ISSUE THREAD

**Issue by ChenCong0207** [dapr/docs#2418]
**What content needs to be created or modified?**
There should be docs on secret store implementation based on HuaweiCloud CSMS.

**Describe the solution you'd like**
The document should be ready after PR ([1703](https://github.com/dapr/components-contrib/pull/1703)) is accepted.

**Where should the new material be placed?**
daprdocs/content/en/reference/components-reference/supported-secret-stores

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
[secret stores support HuaweiCloud CSMS](https://github.com/dapr/components-contrib/pull/1710)
[doc](https://github.com/dapr/docs/pull/2428)
**Additional context**

**Comment by yaron2** [comment]
Closed via #2428
