### ISSUE TITLE
Provide Documentation for the Huawei OBS Dapr Bindings Component Implementation

### ISSUE THREAD

**Issue by jasonlica** [dapr/docs#2436]
**What content needs to be created or modified?**
There should be documentation for the new bindings component implementation for the Huawei OBS.

**Describe the solution you'd like**
Provide a complete user guide for setting up Dapr  bindings component for the Huawei OBS and its usage.

**Where should the new material be placed?**
daprdocs/content/en/reference/components-reference/supported-bindings

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
component-contrib PR: [#1724](https://github.com/dapr/components-contrib/pull/1724)
Docs PR: #2447

**Additional context**
N/A

**Comment by msfussell** [comment]
Merged
