### ISSUE TITLE
Wrong sketch

### ISSUE THREAD

**Issue by lbachelart** [dapr/docs#2451]
**URL of the docs page**
[](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/)

**How is it currently worded?**
On the left of the sketch, the arrow to the component configuration should be under DAPR and not under Cart. 

**How should it be worded?**
cf. above

**Screenshots**
<img width="629" alt="image" src="https://user-images.githubusercontent.com/92373676/170051829-da395978-8686-42f4-aa6f-fd043be48b88.png">

**Additional context**

**Comment by yaron2** [comment]
cc @msfussell

**Comment by hhunter-ms** [comment]
This issue has been resolved: https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/
