### ISSUE TITLE
Update documentation for code change in twilio sendgrid binding of components-contrib

### ISSUE THREAD

**Issue by arahja** [dapr/docs#2452]
**What content needs to be created or modified?**
Need to update documentation to reflect a code change to twilio sendgrid binding.

**Describe the solution you'd like**
Need to add documentation describing the new  email from name and email to name fields.

**Where should the new material be placed?**
[docs/daprdocs/content/en/reference/components-reference/supported-bindings/sendgrid.md](https://github.com/dapr/docs/blob/9739e97a952b76aa80d2f3a949cb4ab0e8be7039/daprdocs/content/en/reference/components-reference/supported-bindings/sendgrid.md)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1751
**Additional context**

**Comment by msfussell** [comment]
@arahja  -THANKs
