### ISSUE TITLE
Coming Soon

### ISSUE THREAD

**Issue by ebuljan** [dapr/docs#2453]
The Coming Soon placeholders are over a year old

**Comment by msfussell** [comment]
@ebuljan - Are you referring to the .NET Dapr SDK documentation?

**Comment by ebuljan** [comment]
Apologies, I had assumed the context would be added to my note.

Last year during Microsoft Build I noticed that most of the Quickstarts
said "coming soon":  Dapr Quickstarts | Dapr Docs
<https://docs.dapr.io/getting-started/quickstarts/>

I found them incredibly useful, so I'm looking forward to seeing the rest
of them completed!

**Comment by msfussell** [comment]
We are working through these. Secrets and Bindings are up next. It takes time due many languages and test!

**Comment by msfussell** [comment]
@ebuljan - I am going to close this issue for now, since we are tracking these quickstarts in another issue. Ok?

**Comment by ebuljan** [comment]
Sounds good, thanks!

**Comment by ebuljan** [comment]
Awesome, thanks!
