### ISSUE TITLE
message delivery in pubsub sns/sqs w/o subscribers

### ISSUE THREAD

**Issue by amimimor** [dapr/docs#2456]
**What content needs to be created or modified?**

Users should be aware that allowing the pubsub sns/sqs component to provision SNS topics, SQS queues and the subscription thereof behaves differently in situations where the component is operating on behalf of a message producer, when no subscriber app is deployed, than in situations where a subscriber app is present and no publisher is deployed

**Describe the solution you'd like**

it should be communicated, *in publisher only setup*, that due to how SNS works without SQS subscription, it behaves as a "classic" pub/sub system that relies on having subscribers listening to topic messages and without those, messages cannot be passed onwards and are effectively dropped, and also are not available for future subscribers (no replay of message when the subscriber finally subscribes). 

**Where should the new material be placed?**

AWS pubsub SNS/SQS component

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
@amimimor - Would you be able to submit a doc PR for this, given you understanding and clarity on this?
