### ISSUE TITLE
Add RocketMQ pubsub documentation

### ISSUE THREAD

**Issue by shubham1172** [dapr/docs#2467]
**What content needs to be created or modified?**

Add documentation for the RocketMQ pubsub component. It was added earlier in https://github.com/dapr/docs/issues/1403 and was removed later.

**Where should the new material be placed?**

Under supported-pubsubs

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/4675

**Additional context**

**Comment by msfussell** [comment]
Resolved
