### ISSUE TITLE
Sidecar: This will block until the app is listening on that port

### ISSUE THREAD

**Issue by geertdoornbos** [dapr/docs#2476]
**What content needs to be created or modified?**
It should be clear that the sidecar is only getting to the ready state when the application is accessible on it's configured port.
The application cannot access Dapr components during application startup/initialization.

**Describe the solution you'd like**
I think it's very important behaviour that should be clear for everyone; so this should be in the docs.

**Where should the new material be placed?**
[sidecar-health](https://docs.dapr.io/developing-applications/building-blocks/observability/sidecar-health/) could be a nice location for documentation?

**Comment by msfussell** [comment]
Another place to put this information is here https://docs.dapr.io/concepts/dapr-services/sidecar/ taking more about the sidecar lifecycle.  Writing down the sidecar lifecycle from initialization, to ready to shutdown would be interesting to cover
