### ISSUE TITLE
Add document for dubbo output binding

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [dapr/docs#2479]
**What content needs to be created or modified?**
A component spec for the dubbo output binding component

**Describe the solution you'd like**
A component spec with a table describing metadata; possibly a usage example

**Where should the new material be placed?**
https://docs.dapr.io/reference/components-reference/supported-bindings/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/tree/master/bindings/dubbo
https://github.com/dapr/components-contrib/pull/1768

**Additional context**
Also add to the partial doc so it shows up on Bindings component spec landing page, here: https://github.com/dapr/docs/blob/v1.11/daprdocs/data/components/bindings/generic.yaml

**Comment by msfussell** [comment]
@LaurenceLiZhixin - Can you do this soon, given the code PR has just been merged.

**Comment by msfussell** [comment]
@LaurenceLiZhixin - Ping?

**Comment by LaurenceLiZhixin** [comment]
I am sorry that I have no time to write documents due to the progress of the company's project recently, I expect to be free next week.
@msfussell

**Comment by nyemade-uversky** [comment]
@LaurenceLiZhixin wanted to check back on this. Do you have any availability this week to work on these docs?

**Comment by msfussell** [comment]
@LaurenceLiZhixin - We are about to release and need these docs. Can you add these?
If these cannot be added, then will exclude this component from the release notes and wait to announce this in the 1.9 release.

**Comment by sarsharma** [comment]
@yaron2

**Comment by berndverst** [comment]
This component is stable - but the documentation is still missing!

**Comment by berndverst** [comment]
cc @dapr/maintainers-docs

**Comment by hhunter-ms** [comment]
@LaurenceLiZhixin I opened a PR ^^ to take a stab at this, but might be easier if you contributed this doc -  would you be able to do this for 1.11, by the end of the month?

**Comment by msfussell** [comment]
@ItalyPaleAle @berndverst  - As components contrib maintainers can you one of you please write these docs?

**Comment by ItalyPaleAle** [comment]
Please note that there are 4 maintainers for contrib, also @artursouza and @yaron2  :) I'm not familiar with this binding at all, I can take a look if I have some time in the next weeks...

**Comment by hhunter-ms** [comment]
@msfussell @artursouza @yaron2 @ItalyPaleAle @berndverst - there was discussion around removing this component since no one knows about it to document it and the contributor is giving radio silence... are we planning on doing that?

**Comment by hhunter-ms** [comment]
closing bc no one can document this.
