### ISSUE TITLE
Clarify supported "integrations"

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#248]
## Describe the proposal
I saw redis mentioned in the samples, but it's very hard to get a complete overview of the supported "integrations". There should be a list, and for each item in the list, list a configuration, with (important) optional and required params. 

For example, I have no idea if both `redisHost` and `redisPassword` are required for the `state.redis` integration (is that what it's called?). I would assume that password is optional, but there's no easy way to find out.

**Comment by trondhindenes** [comment]
After submitting this, I realize that theres kindof an existing list already, but under "howtos", for example there's a list of supported state store backends here: https://github.com/dapr/docs/tree/master/howto/setup-state-store. Imho, this is not the best way to organize this documentation (relates to #249 I guess)

**Comment by RicardoNiepel** [comment]
@yaron2 I can work on this, I've recognized the same situation with https://github.com/dapr/components-contrib - pls assign if suitable

**Comment by RicardoNiepel** [comment]
@trondhindenes I would be interested in your feedback.

Currently, we're listing all supported "integrations" inside components-contrib, e.g. for [components-contrib/bindings](https://github.com/dapr/components-contrib/blob/master/bindings/Readme.md).

We are also duplicating this information inside docs and also provide detail information how you need to configure this, e.g. [docs/concepts/bindings/](https://github.com/dapr/docs/blob/master/concepts/bindings/README.md) and [docs/concepts/bindings/specs/kafka](https://github.com/dapr/docs/blob/master/concepts/bindings/specs/kafka.md).

You are correct - this is missing for the other components, like state etc.
I can clean this up / align it, but maybe you have another idea?

**Comment by trondhindenes** [comment]
Thanks @RicardoNiepel 

I would maybe do something like this:

| What  | Input Binding | Output Binding             | State Store                | Pub-Sub                    |
|-------|---------------|----------------------------|----------------------------|----------------------------|
| Redis | No            | Yes (link to instructions) | Yes (link to instructions) | Yes (link to instructions) |
| Kafka | Yes (link to instructions)    | Yes (link to instructions)                 | No                         | No                         |
|       |               |                            |                            |                            |

I would give a nice overall view of other tech that can be used together with dapr, and could also serve as a "main page" from where to point all setup instructions that are specific to each "technology" such as Redis etc.

Just a thought.

**Comment by msfussell** [comment]
@trondhindenes  - Can we close this issue, given that now we have all the components with a single format layout. For example see https://v1-0.docs.dapr.io/operations/components/setup-bindings/supported-bindings/

**Comment by trondhindenes** [comment]
yes I believe we can :-)
