### ISSUE TITLE
Metadata API - Document Component's capabilities related information

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#2482]
**What content needs to be created or modified?**

Modify docs to have newly added components capabilities information

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/4696

**Additional context**

**Comment by msfussell** [comment]
The metadata API is not well documented today and is hidden to most developers. Adding to this reference https://docs.dapr.io/reference/api/metadata_api/ is necessary, however writing a usage article would be preferrable to include examples of why this is useful.

**Comment by pravinpushkar** [comment]
> The metadata API is not well documented today and is hidden to most developers. Adding to this reference https://docs.dapr.io/reference/api/metadata_api/ is necessary, however writing a usage article would be preferrable to include examples of why this is useful.

@msfussell Where should we put a reference for Metadata API.  Do we have any reference for other APIs at some place else?

**Comment by msfussell** [comment]
Leaving this open for v1.8 since I am going to update a diagram to show the metadata API on the side car

**Comment by msfussell** [comment]
@pravinpushkar - I updated the diagram, but this now needs a new Code and docs PR since this is invalid now. 
Pub/Sub | TTL

**Comment by pravinpushkar** [comment]
@msfussell We need a new doc PR for the changes done for `Pub/Sub`. I will create a new PR and will link to this issue only.

**Comment by msfussell** [comment]
Resolved
