### ISSUE TITLE
Change the docs for configuration API  for response from an array to dictionary

### ISSUE THREAD

**Issue by amulyavarote** [dapr/docs#2484]
**What content needs to be created or modified?**

The existing configuration API docs needs to be changed to use dictionary based on the new change in dapr runtime and sdks.

Main issue in dapr/dapr in pasted here.
https://github.com/dapr/dapr/issues/4556

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by sicoyle** [comment]
Linking docs for Configuration overview and API reference:
https://docs.dapr.io/reference/api/configuration_api/

Please update here.

**Comment by srilasya02** [comment]
Could you assign this to me? @hhunter-ms

**Comment by sicoyle** [comment]
@artursouza to confirm if we can close this out due to potential doc updates. So moving back a column.

**Comment by artursouza** [comment]
This is the correct result as per the latest runtime (it means the docs needs update):
```json
{
    "myConfigKey": {
        "value":"myConfigValue"
    }
}
```
