### ISSUE TITLE
publish docs at dapr.io

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#249]
## Describe the proposal
it would be good if docs navigation was cleaned up, and docs were built and published to dapr.io or something. Reading docs in the form of github markdowns is a very subpar nav experience. It would be a lot easier to navigate with a nice sidebar and improved site structure.

**Comment by yaron2** [comment]
That's definitely something that we need to do, have discussed it but didn't get around to doing it yet.
We want to have versioned docs on the website generated off of the tagged Github docs.

cc @msfussell @flynnduism

**Comment by trondhindenes** [comment]
yup, that's a really good idea. There's probably loads of repos you can borrow from: Traefik has really nice versioned docs, looks like they build it using mkdocs: https://github.com/containous/traefik/tree/master/docs. Probably quite easy to build off of what they've done or similar.

**Comment by orizohar** [comment]
Planning to assess Hugo for this (https://gohugo.io/) as it is used by Helm, Knative and others. Would be good to get this before v1.0

**Comment by AaronCrawfis** [comment]
The hugo-docs branch has been created with a hugo project and Actions CI/CD pipeline to an Azure static site. I'll work on the governance model and timeline to make this the primary docs experience going forward and update this thread with more information soon.
