### ISSUE TITLE
Instructions of "How to Get Save State" are not clear

### ISSUE THREAD

**Issue by mattmazzola** [dapr/docs#2494]
**Describe the issue**

The instructions say

> Navigate to the directory containing the above code, then run the following command to launch a Dapr sidecar and run the application:

but it is not clear where the code should be. I didn't see any clone instruction on that page, and the dapr-quickstarts doesn't have any similar code. 

**URL of the docs**
https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/

**Expected content**
I expect the tutorial to ensure consistent environment before starting. When it says "Navigate to the directory" it should say which directory.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by msfussell** [comment]
@hhunter-ms - Include this as part of the state management refresh
