### ISSUE TITLE
CLI - Content for dapr init through privately hosted helm chart

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#2501]
**What content needs to be created or modified?**
Content has to be added for new Env variables introduced for supporting `dapr init` from privately hosted helm chart repo.

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/cli/pull/895/files

**Additional context**

**Comment by hhunter-ms** [comment]
this has been resolved in the docs - closing
