### ISSUE TITLE
serverless dapr running in a container.

### ISSUE THREAD

**Issue by masters3d** [dapr/docs#2502]
**What content needs to be created or modified?**

I see that we have Azure ACA as one of the supported serverless offerings. Can you add a generic way that dapr could be run in a serverless environment. Azure ACI groups that are deployed to private vnet come to mind but I am sure there are other services that have similar offerings where dapr could be deployed as a container. 

**Describe the solution you'd like**

**Where should the new material be placed?**

https://github.com/dapr/docs/tree/v1.7/daprdocs/content/en/operations/hosting/serverless

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

I am looking into using ACA but I already have ACI groups so if I could progressivity adopt dapr in these deployments then I could show value of dapr earlier.

**Comment by msfussell** [comment]
Any serverless platform, like ACA,  needs to explicitly decide to support Dapr, whether that is ACI, AWS Lambda or GCP Cloud Run. I suggest reaching out the product owners for ACI and ask them if this is something they are interested in doing.

**Comment by masters3d** [comment]
I imagine a good subset of dapr runs just fine as a sidecart even with out explicit support from the platform. I think this is worth documenting or if it’s not recommended for production then that would also be worth documenting

**Comment by paulyuk** [comment]
Hi @masters3d.  ACA in our minds is the more finished container service that provides scalers (with KEDA), revisions and Dapr built in.  These were features holding back a number of production multi-container workloads.  

I would like to help you show the value faster to your goal.

A container app environment can be created in your existing VNET right next to your container group, with Dapr enabled (providing a managed sidecar that works at scale).  At that point your existing ACI containers and services can call the sidecar, until the time you're ready to graduate those containers to be ACA also.  We'd be happy to discuss this and other options more on Discord.

**Comment by msfussell** [comment]
Closing unless there is a desire for someone MS to write a guide on ACI + Dapr.
