### ISSUE TITLE
Remove Pub/Sub routing from Preview feature list

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#2509]
**What content needs to be created or modified?**

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

dapr/dapr issue link - https://github.com/dapr/dapr/issues/4742

**Comment by pravinpushkar** [comment]
PR link - https://github.com/dapr/dapr/pull/4777
@msfussell Could you please assign this to @CrazyHZM

**Comment by greenie-msft** [comment]
Closing issue as this has been addressed: https://github.com/dapr/docs/pull/2547
