### ISSUE TITLE
Multiple app instances in standalone mode?

### ISSUE THREAD

**Issue by rschiefer** [dapr/docs#251]
Sorry if this is a dumb question but ...

Does the standalone mode support running multiple instances of an app? I have scoured the docs and can't find that.  

If supported, should probably add these details to the docs.  I'll be happy to add given more details.

**Comment by LMWF** [comment]
@rschiefer - Are you asking if you run, for example, 3 instances of an app in standalone mode using a single invocation of `dapr run`?  If so, no.

However, it can be achieved by running `dapr run` in different terminals with different -app-ids and different ports.

Is there a particular scenario you're interested in?

**Comment by Abhith** [comment]
If we run the same app in different app-ids & ports in standalone mode, can we make a cluster like in Orleans?

I am more interested in such a setup where the Dapr sidecar of the same app running in multiple machines, forming a cluster. Is that possible with Dapr?

**Comment by yaron2** [comment]
> If we run the same app in different app-ids & ports in standalone mode, can we make a cluster like in Orleans?
> 
> I am more interested in such a setup where the Dapr sidecar of the same app running in multiple machines, forming a cluster. Is that possible with Dapr?

Yes, you can. Dapr is designed to run in clustered mode.

**Comment by Abhith** [comment]
> Yes, you can. Dapr is designed to run in clustered mode.

Do we have any docs/how-to's explaining the same?

**Comment by msfussell** [comment]
This is covered in the overview. https://github.com/dapr/docs/blob/master/overview.md#running-dapr-on-a-local-developer-machine-in-self-hosted-mode
If there is more that you would like to see open a new issue.

**Comment by mnsrulz** [comment]
Link is broken? Can you update?

**Comment by LMWF** [comment]
https://github.com/dapr/docs/tree/master/overview#running-dapr-on-a-local-developer-machine-in-self-hosted-mode

**Comment by kfrajtak** [comment]
The link is still broken and there's no mention on how to run multiple instances locally.

**Comment by satishviswanathan** [comment]
@yaron2 do you have any documentation for running multiple instances of app in standalone mode ?

**Comment by dystopiandev** [comment]
Months I've been back here, still looking.
