### ISSUE TITLE
Capability map per SDK

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/docs#2526]
**What content needs to be created or modified?**

Currently while using a Dapr SDK in any language, it is hard to see which features of the Dapr sidecar it supports as well as which protocols.

**Describe the solution you'd like**

 I would like to propose a capability map on a single docs page that is easily reachable that displays the different Dapr sidecar features and if the corresponding SDK supports them or not.

**Where should the new material be placed?**

SDK Overview and on the Dapr main repo

**Additional context**

This could be simple and look like the below

✅ = Supported
⚠️ = Partly Supported
❌ = Not Supported
* = Not Supported in the Dapr Sidecar

|Feature|Protocol|C#|JS|Go|Python|...|
|-|-|:-:|:-:|:-:|:-:|:-:|
|Configuration API|HTTP*|❌|❌|❌|❌|❌|
||gRPC|✅|⚠️|✅|✅|✅|
|Lock API|HTTP|❌|❌|❌|❌|❌|
||gRPC|✅|❌|✅|✅|✅|
|Actors|HTTP|✅|✅|✅|✅|✅|
||gRPC*|❌|❌|❌|❌|❌|
|...|HTTP|✅|✅|✅|✅|✅|
||gRPC|✅|✅|✅|✅|✅|

**Comment by XavierGeerinck** [comment]
@shubham1172 @amulyavarote @greenie-msft @paulyuk and @yaron2

**Comment by msfussell** [comment]
See this PR as the approach to take for this https://github.com/dapr/docs/pull/2499 which is then making this also data driven
