### ISSUE TITLE
improve documentation for "dapr run" standalone

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#254]
## Describe the proposal
I'm testing out the `1. hello world`sample.

I notice that when I run `dapr run` it auto-creates a 'components' folder and places some files in it. From what I can see, it looks like it defaults to a redis state store and a redis pubsub. I'm assuming these are "builtin defaults" since I can't find any config files telling dapr to set itself up that way. 
I tried editing one of those files to be using NATS instead of redis, and I could, as long as the _name of the file_ remains `redis_messagebus.yaml`. this struck me as weird. (like, what decides the name of that file? Or even that it should default to redis if it doesn't exist?)

Needless to say, I'm having a hard time understanding how this pieces together. It would be really good to have robust documentation explaining in detail what happens when `dapr run` is executed, what the defaults are, what files dapr looks for, and how to control the behavior of it (I see there's a `dapr run --config` flag, but I can't find any information about the type of config this pertains to)

Sorry about all the doc issues I'm posting. Dapr looks _really_ promising, I'm just having a hard time figuring out stuff whenever I stray a little bit from the "hello world" exxamples.

**Comment by yaron2** [comment]
Don't be sorry, docs are what make or break a project.

I'll respond later about the question at hand, and we'll issue more docs about `dapr run`.

**Comment by codeputer** [comment]
Totally agree... I started my journey with actors as I'm familiar with Service fabric. I'm not familiar with redis, node, javascript, go, rust, Linux, python, or whatever else is in the startup examples.  I get it that you want a open environment, but from a sample perspective very few understand that scope of tech.

**Comment by trondhindenes** [comment]
For me its not a problem that its using redis and python etc, those are the tools I work with every day. But I need to understand how dapr behaves when `dapr run` is executed, and how I can adjust the default functionality.

**Comment by LMWF** [comment]
>I tried editing one of those files to be using NATS instead of redis, and I could, as long as the name of the file remains redis_messagebus.yaml. this struck me as weird. (like, what decides the name of that file? Or even that it should default to redis if it doesn't exist?)

Yes, today in standalone (local) mode, the dapr CLI reads in component configurations from 
`[dir you're running the CLI from]\components`  

If `\components` is not present, it creates it and creates 2 default yamls:
- a state store component (redis - redis.yaml)
- a pubsub component (again redis - redis_messagebus.yaml).

The names of the files in `\components` are not inspected, only the contents of the files.  So, as you described, if you simply overwrite the contents of `redis_messagebus.yaml` with that of a different type of pubsub (e.g. NATS), but keep the file name, it will use NATs instead of Redis.

If these files are already present, they are not overwritten on a `dapr run`.  If any are not present, then the missing ones are recreated.

See https://github.com/dapr/cli/blob/eeea3d5a1b9042974731294c5d10d4829706f01b/pkg/standalone/run.go#L273 for the beginning of where the code described above begins.

**Comment by LMWF** [comment]
I've assigned this to myself to add some docs on what happens on a `dapr run`.

**Comment by jjcollinge** [comment]
> If these files are already present, they are not overwritten on a dapr run. If any are not present, then the missing ones are recreated.

@LMWF this was bizzarre behaviour for me - when I was working on the Azure Service Bus PubSub provider - if I had `redis.yaml` and a `servicebus_messagebus.yaml` and ran `darp run ...` it would automatically create the missing `redis_messagebus.yaml` and load it as a message bus even when I don't want or need it. This also seems to conflict with the "use what you want" principle of dapr - if `dapr run` requires atleast a `redis` connection and will automatically configure a state store and a message bus, we are not giving a path to iteratively adopt features i.e. service invocation only.

**Comment by trondhindenes** [comment]
> this was bizzarre behaviour for me
I completely agree. It would be much less confusing if the filenames were more generic. The fact that I have to have a file called "something something redis" even if I use some other pubsub technology is just.... bizarre.

**Comment by LMWF** [comment]
We've created a doc describing what happens on a `dapr run` for a local cluster.  Please let us know if this helps or what can be clarified:
https://github.com/dapr/docs/blob/master/walkthroughs/darprun.md

**Comment by trondhindenes** [comment]
looks good!!

**Comment by amanbha** [comment]
@trondhindenes I am closing this one, please feel free to reopen if still have questions
