### ISSUE TITLE
Add "how-to" doc for using NATS pubsub with Dapr

### ISSUE THREAD

**Issue by abhirockzz** [dapr/docs#257]
## Describe the proposal

Add a how-to document to demonstrate how to use NATS pubsub with Dapr

**Comment by abhirockzz** [comment]
I will take this up

**Comment by yaron2** [comment]
Have you seen this?

https://github.com/dapr/docs/blob/master/howto/setup-pub-sub-message-broker/setup-nats.md

**Comment by abhirockzz** [comment]
> Have you seen this?
> 
> https://github.com/dapr/docs/blob/master/howto/setup-pub-sub-message-broker/setup-nats.md

No I had not 😄 Thanks for pointing this out. Closing....

**Comment by yaron2** [comment]
We could use help with NATS streaming support in components-contrib :)
