### ISSUE TITLE
Documentation for installing custom certificates in sidecar containers

### ISSUE THREAD

**Issue by shubham1172** [dapr/docs#2570]
**What content needs to be created or modified?**

Inform the users how to make the Dapr sidecar trust custom certificates. This can be useful when a self-signed certificate is required to make sidecar to external-world calls, e.g., when using HTTP bindings, using a proxy, etc. The document should explain the steps needed to configure the same for both Windows and Linux containers and some things-to-note (for e.g., Windows container will use Administrator permissions to install the root certs).

**Describe the solution you'd like**

Add this to a new documentation page.

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/4741

**Additional context**

**Comment by msfussell** [comment]
Resolved
