### ISSUE TITLE
How to connect to any authenticated rest endpoint via Dapr Http bindings 

### ISSUE THREAD

**Issue by Akshay-Khule** [dapr/docs#2571]
How to connect to any authenticated rest endpoint via Dapr Http bindings .

**Comment by Akshay-Khule** [comment]
We want to call API of Azure Data factory via Http bindings , need to know how is approach

**Comment by hhunter-ms** [comment]
Here is the [list of supported binding specs](https://docs.dapr.io/reference/components-reference/supported-bindings/) - it doesn't look like an Azure Data Factory component has been contributed yet.
