### ISSUE TITLE
Add docs for Sidecar Injection watchdog

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2581]
**What content needs to be created or modified?**
Need to document what the sidecar injection watchdog is and how it can be enabled.

**Where should the new material be placed?**
Perhaps here: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/4764

**Comment by msfussell** [comment]
Resolved
