### ISSUE TITLE
"Last modified" on every page shows the same date and commit

### ISSUE THREAD

**Issue by jlian** [dapr/docs#2597]
**Describe the bug**
When you go to dapr docs, at the bottom it shows you a "last modified" line along with a date. It doesn't seem to be working properly because *every* page on dapr docs shows the same commit and last modified time.

As of today (July 3, 2022), I see the same exact line no matter which page on dapr docs. In this example it points to this commit https://github.com/dapr/docs/commit/31f641f829f0cfe59babd2915818b9d26ef8a05c which, while being the latest commit on the branch, doesn't modify any of those pages. I'm pretty sure this is a bug because Docsy, the upstream project, doesn't have this issue on their website. 

![image](https://user-images.githubusercontent.com/2320572/177064387-c17c799d-77c1-47d1-8566-9c9f4013a1ed.png)
![image](https://user-images.githubusercontent.com/2320572/177064410-7635d142-2ef5-4ebe-98c4-75cdaf2bcef5.png)
![image](https://user-images.githubusercontent.com/2320572/177064423-f54f1126-7c64-4d60-95ba-6f4757da4a87.png)
![image](https://user-images.githubusercontent.com/2320572/177064641-bf716945-dad5-443d-b5d3-9a18e6c3294b.png)

**Steps to reproduce**
1. Go to any dapr doc page
2. Scroll down to see the "last modified" line 
3. Note that every page has the same exact last modified info

**Expected behavior**
The last modified line should point to a commit that actually modified that specific page, not just the entire project

**Desktop (please complete the following information):**
Tested on Windows, mac, with Edge and Safari 

**Smartphone (please complete the following information):**
Tested on iOS

**Comment by jlian** [comment]
I think I found info on the fix https://discourse.gohugo.io/t/problems-with-gitinfo-in-ci/22480/2

Tried it on my own Docsy website hosted in SWA, worked.

**Comment by msfussell** [comment]
@jlian - Would you be able to submit a PR for this?

**Comment by jlian** [comment]
It's fixed!

![image](https://user-images.githubusercontent.com/2320572/177850889-fcf641e4-7897-4fde-98c1-50db6f222ecc.png)
