### ISSUE TITLE
Include a sample Pod configuration yaml

### ISSUE THREAD

**Issue by thuwas** [dapr/docs#2607]
**What content needs to be created or modified?**
I created pod deployment with the correct dapr annotations. After deployment, it worked correctly without the 'aadpodidbinding' label. When I restarted the pod, the connection to the KeyVault started to fail. 

**Describe the solution you'd like**
After talking to MS Support for AKS, we identified the pod deployment template has to have the 'aadpodidbinding'.

**Where should the new material be placed?**
Include a statement at the end of the document or attach a sample yaml file for pod deployment.

**Additional context**
I just found a sample from a google search:
(https://github.com/RicardoNiepel/dapr-docs/blob/master/howto/setup-secret-store/azure-keyvault-managed-identity.md) [move to the end of the page]

Another concern is since we are independent of the backing services, should we attach the label  'aadpodidbinding' to the application container? It should be a part of the Dapr component yaml right??

**Comment by hhunter-ms** [comment]
@berndverst @ItalyPaleAle `aadpodidbinding` is now deprecated, right?

**Comment by alicejgibbons** [comment]
It has been replaced with workload identity that similarly needs to be annotated with `azure.workload.identity/use: "true"`

See docs here: https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster#deploy-your-application
