### ISSUE TITLE
[1.9] Review metadata keys for all Azure Storage components

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2611]
**What content needs to be created or modified?**

In <= 1.8, Azure Storage components use an inconsistent set of metadata keys for the same things. In 1.9 that is being standardized to keys such as `accountName`, `accountKey`, etc (old keys are still supported as aliases for backwards-compatibility but are now deprecated).

The docs for these components need to be updated:

- bindings.azure.storagequeues
- bindings.azure.blobstorage
- state.azure.blobstorage
- state.azure.tablestorage

**Describe the solution you'd like**
Standardize the names of metadata keys so values are consistent.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1837

**Comment by msfussell** [comment]
Resolved
