### ISSUE TITLE
[1.9] Document support for Azure AD auth in Azure Storage Queue and Azure SignalR bindings

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2613]
**What content needs to be created or modified?**
These components are gaining support for AAD auth in 1.9:

- bindings.azure.storagequeues
- bindings.azure.signalr

Additionally, there have been a few more small changes:

- bindings.azure.storagequeues: the way custom endpoints are specified changed slightly, so it's consistent with Azure Blob Storage (does not use "production-style" URLs anymore)
- bindings.azure.signalr: added a few more (optional) metadata keys

The docs for those bindings need to be updated to reflect the new metadata keys

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1842
https://github.com/dapr/components-contrib/pull/1852

**Comment by msfussell** [comment]
Resolved
