### ISSUE TITLE
How to run dapr in on-premise clusters

### ISSUE THREAD

**Issue by kencharos** [dapr/docs#263]
## Ask your question here

Accoding to https://github.com/dapr/dapr/wiki/FAQ#how-does-dapr-relate-to-orleans-and-service-fabric-reliable-actors, dapr run in on-premise with out k8s.

I want to know how to run dapr in many on-premise or VM hosts.

**Comment by Abhith** [comment]
I have a similar question.

We are using Orleans, where silo's running in multiple VM's (under the same subnet) and using Azure storage to form the cluster. Client load is distributed between these silos by Orleans.

Can we set up a similar cluster using Dapr standalone mode?
i.e Dapr sidecar for the same actor types running in different machines (like silos in Orleans).

**Comment by msfussell** [comment]
This doc describes how to setup up Dapr on self-hosted mode on VMs. https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md
Dapr's name resolution will also uses multi-cast DNS to resolve services that are networked across a set of machines, meaning it will  run on many VMs host.

**Comment by hotfirewire** [comment]
> This doc describes how to setup up Dapr on self-hosted mode on VMs. https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md
> Dapr's name resolution will also uses multi-cast DNS to resolve services that are networked across a set of machines, meaning it will run on many VMs host.

That link is broken.  Can you provide an updated link?
