### ISSUE TITLE
.NET steps for programmatic subscription to pub/sub missing subscription info

### ISSUE THREAD

**Issue by negativeeddy** [dapr/docs#2649]
**Describe the issue**
The .NET example for programmatic subscription to pub/sub only shows the code for receiving the messages. It does not include how to create the subscriptions i.e. the call to MapSubscribeHandler(). So if someone follows the example they will not receive any messages

**URL of the docs**
https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#programmatic-subscriptions

**Expected content**
Should include instructions on calling MapSubscripterHandler() or mapping the subscribe endpoint (similar to the JS example)

**Comment by hhunter-ms** [comment]
@halspang do you mind taking a look at this?
