### ISSUE TITLE
Helm 3 support

### ISSUE THREAD

**Issue by nmeisenzahl** [dapr/docs#265]
## Expected Behavior

Installation documentation to work with Helm 3 (https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#installing-dapr-on-a-kubernetes-cluster)

## Actual Behavior

Syntax errors with Helm 3

## Steps to Reproduce the Problem

Follow the Kubernetes steps with Helm 3

**Comment by youngbupark** [comment]
Closing with https://github.com/dapr/docs/pull/307
