### ISSUE TITLE
Create docs for Azure Configuration Service component

### ISSUE THREAD

**Issue by cmendible** [dapr/docs#2660]
**What content needs to be created or modified?**
Create docs for Azure Configuration Service component

Documentation should also describe the behavior described here: https://github.com/dapr/components-contrib/pull/1874#discussion_r919242001

**Where should the new material be placed?**
/daprdocs/content/en/reference/components-reference/supported-configuration-stores

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/1874

**Comment by greenie-msft** [comment]
@cmendible, can you please submit a PR for this? We'll need the docs in order to release this in 1.9.

**Comment by msfussell** [comment]
Resolved
