### ISSUE TITLE
Dapr init issue

### ISSUE THREAD

**Issue by WILLEM-LENS** [dapr/docs#2674]
**Describe the issue**

Error with Dapr initialization using "dapr init".
Error = Failed to get runtime version: 'Get "https://api.github.com/repos/dapr/dapr/releases": dial tcp: lookup api.github.com: no such host'.
**URL of the docs**
https://docs.dapr.io/getting-started/install-dapr-cli/
**Expected content**

"dapr init" should be replaced with:
1. Instruction 1; Get "https://api.github.com/repos/dapr/dapr/releases"
2.  Instruction 2: "dapr init --runtime-version=<desired_version>".  
**Screenshots**

![Screenshot 2022-07-26 153216](https://user-images.githubusercontent.com/7847982/181018705-54a9778b-fa42-469a-901e-699f875ccab1.png)

**Additional context**

**Comment by BjoernAtBosch** [comment]
Hi,
I'm getting a similar (same?) issue.

Seems to be wrong repo to report this. Created a new bug ticket: https://github.com/dapr/cli/issues/1043

**Comment by hhunter-ms** [comment]
Closing, as this was resolved in dapr/cli
