### ISSUE TITLE
Azure SignalR binding update

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#268]
Update /concepts/bindings/spec and Readme with the latest Azure SignalR binding.

**Comment by msfussell** [comment]
Does this https://github.com/dapr/docs/blob/master/concepts/bindings/specs/signalr.md cover all the   doc requirements?

**Comment by msfussell** [comment]
@yaron2 Please confirm that this issue can be closed

**Comment by yaron2** [comment]
It can.
