### ISSUE TITLE
install.sh doesn't work

### ISSUE THREAD

**Issue by wxbty** [dapr/docs#2695]
**Describe the issue**
When using install.sh to install the cli in the linux environment, it prompts “Error opening archive: Unrecognized archive format”. After investigation, there is a problem with the download url of the package.
https://github.com/dapr/cli/releases/download//dapr_darwin_amd64.tar.gz prompt 404 not found. The correct address should be https://github.com/dapr/cli/releases/download/v1.8.0/dapr_darwin_amd64.tar.gz. That is to say, the path is missing the version

**URL of the docs**
https://docs.dapr.io/getting-started/install-dapr-cli/

**Expected content**
Provide the correct install.sh

**Screenshots**
![image](https://user-images.githubusercontent.com/38374721/182313070-2a010d89-07fc-4f3e-af35-b57c898a05cc.png)

**Additional context**
Temporary solution 1: Download install.sh locally, modify the url of download, increase the path, and execute sh install.sh manually.
The wget download may still fail, then try method 2 again.
Temporary solution 2: 1. wget download the correct address, such as https://github.com/dapr/cli/releases/download/v1.8.0/dapr_linux_amd64.tar.gz 2. Put the downloaded file in the temporary folder 3. Replace the download by copying the file in install.sh, such as
![image](https://user-images.githubusercontent.com/38374721/182314119-6d07d3d4-d11e-40fb-bae6-f7384a13afc2.png)

**Comment by hhunter-ms** [comment]
@shivanisinghnitp friendly bump - were you able to reproduce? do we need to update the command in the docs?

**Comment by hhunter-ms** [comment]
Closing as there is no action and it seems to not be a bug. Feel free to open a new issue if this occurs again.
