### ISSUE TITLE
Event grid input binding example with ASP.NET Core

### ISSUE THREAD

**Issue by adeliab** [dapr/docs#2696]
**What content needs to be created or modified?**
Event grid input binding example with ASP.NET Core
The [documentation](https://docs.dapr.io/reference/components-reference/supported-bindings/eventgrid/) of event grid input binding is not very clear to me
- What are the clientId and clientSecret?
- The documentation mentioned that "Event Grid Binding creates an [event subscription](https://docs.microsoft.com/azure/event-grid/concepts#event-subscriptions) when Dapr initializes". Does this mean I cannot bind to an existing subscription?
- Will a new subscription be created every time I run the application?
- How can I configure additional features (filters, retry policy, etc) from the newly created subscription?
- How can I receive the event in an ASP.NET controller? what should be the parameter type?
- Does it support both event grid and cloud event schema?

**Describe the solution you'd like**
A code sample on event grid input binding implementation with ASP.NET Core. The subscription configuration (filter, retry, etc) should be available in the example

**Where should the new material be placed?**
https://docs.dapr.io/reference/components-reference/supported-bindings/eventgrid/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
-

**Additional context**
-

**Comment by adeliab** [comment]
Seems that I misunderstood, I thought dapr would create a listener to event grid but actually it provides an endpoint for event grid webhook. this article explains it better https://medium.com/polarsquad/building-an-event-driven-net-core-app-with-dapr-58cc83ab120b

it would be nice to have more implementation examples in the official documentation

**Comment by hhunter-ms** [comment]
> it would be nice to have more implementation examples in the official documentation

@adeliab We provide a binding .NET example in our quickstart documentation. Could you take a look and let me know your feedback?
Quickstart: https://docs.dapr.io/getting-started/quickstarts/bindings-quickstart/

**Comment by hhunter-ms** [comment]
Closing as this seems to be resolved. Feel free to create a new issue if necessary.
