### ISSUE TITLE
Add documentation for pubsub/jetstream tls configuration

### ISSUE THREAD

**Issue by NickLarsenNZ** [dapr/docs#2697]
> **Note**: maybe there needs to be a new issue template (or reword an existing template) for simple updates?

**What content needs to be created or modified?**

Document new fields for TLS Client Authentication.

**Describe the solution you'd like**

N/A

**Where should the new material be placed?**

Existing

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/1924

**Additional context**

N/A

**Comment by greenie-msft** [comment]
Closing issue in favor of https://github.com/dapr/docs/issues/2872
