### ISSUE TITLE
Declarative Subscription of Dead Letter Topic does not exist but is in docs

### ISSUE THREAD

**Issue by xTriad** [dapr/docs#2699]
**Describe the issue**
The [Configuring a dead letter topic with programmatic subscription](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-deadletter/#configuring-a-dead-letter-topic-with-a-declarative-subscription) section doesn't work because the [Subscription CRD doesn't support it yet](https://github.com/dapr/dapr/blob/master/charts/dapr/crds/subscription.yaml) (no field for `deadLetterTopic`).

**URL of the docs**
https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-deadletter/#configuring-a-dead-letter-topic-with-a-declarative-subscription

**Expected content**
Content is correct, but the declarative version isn't available in 1.8. As of now, you have to define `/dapr/subscribe` in code to use the `deadLetterTopic` feature.

**Screenshots**
![image](https://user-images.githubusercontent.com/3374673/182478140-5911f4ac-baba-482a-a74a-4ebd3b01da86.png)

**Additional context**

**Comment by yaron2** [comment]
You're right. This will be fixed for 1.9: https://github.com/dapr/dapr/pull/4997.

**Comment by yaron2** [comment]
@xTriad would you like to submit a PR against the v1.8 branch and update it to remove dead letter topics for declarative subscriptions?
