### ISSUE TITLE
Some middleware links are broken

### ISSUE THREAD

**Issue by jakesmolka** [dapr/docs#2707]
**Describe the bug**

Context: https://docs.dapr.io/reference/components-reference/supported-middleware/

In the list of middleware components some don't have direct links to Dapr docs (left column). Instead it looks like they "want" to redirect to the official definition of the component, e.g. the OpenID Connect website. Looking into this repo shows there are specific docs available, which should be linked.

Example: OpenID Connect has the hyperlink `https://docs.dapr.io/reference/components-reference/supported-middleware/https://openid.net/connect//`

But this specific doc is available: https://github.com/dapr/docs/blob/v1.8/daprdocs/content/en/reference/components-reference/supported-middleware/middleware-bearer.md (which also wasn't just added recently)

(It looks like all the links in the left column are broken, when there are links in the middle column description text.)

PS: Once posted, the automatically added tag made it look like I used the wrong issue category. Sorry, if that's the case.

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by yaron2** [comment]
Closed via #2781
