### ISSUE TITLE
Unwanted content in the footer which exposes the commit in the URL

### ISSUE THREAD

**Issue by yash-nisar** [dapr/docs#2715]
**URL of the docs page**

https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-deadletter/

**How is it currently worded?**

Last modified July 6, 2022: [add demo videos (#2612) (940dd4ed)](https://github.com/dapr/docs/commit/940dd4ed13f242c02a8688adef3817305d6000bf)

**How should it be worded?**

Last modified July 6, 2022

**Screenshots**

<img width="517" alt="image" src="https://user-images.githubusercontent.com/14862976/184068805-5e58eff1-d6ea-4cad-9110-324a146093dc.png">

**Additional context**

**Comment by hhunter-ms** [comment]
@shivanisinghnitp friendly bump

**Comment by hhunter-ms** [comment]
closing for now. feel free to reopen when you start working on this.
