### ISSUE TITLE
Java SDK version not up to date

### ISSUE THREAD

**Issue by jakesmolka** [dapr/docs#2716]
**Describe the issue**

The occurrences of the Java SDK version are `1.5.0.` while the newest version is `1.6.0`. It would be a better experience for people to get on the newest version directly.

**URL of the docs**

https://docs.dapr.io/developing-applications/sdks/java/

**Expected content**

Replace SDK version to newest one.

**Screenshots**

**Additional context**

**Comment by hhunter-ms** [comment]
Resolved with this PR: #2814
