### ISSUE TITLE
Clearly explain traces in chained calls

### ISSUE THREAD

**Issue by DanielYWoo** [dapr/docs#2733]
**What content needs to be created or modified?**
Traces are only collected by sidecars without instrument in your main container, so the traces are broken in chained API calls. e.g., if A calls B and then B calls C, you see A->B and B-C in zipkin, you will not see A->B->C. 

**Describe the solution you'd like**
I think we should put this into the document to give users correct expectations.

**Where should the new material be placed?**
known limitations in the tracing document

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
N/A

**Additional context**
N/A

**Comment by hhunter-ms** [comment]
@msfussell would you say this is a known limitation? if so, I can add to docs in #3607

**Comment by msfussell** [comment]
@DanielYWoo - Are you using an SDK for your calls, if so which one?
This is about that some SDKs still require you to copy the header although since this issue several of them (like .NET) have started to do this for you.

**Comment by hhunter-ms** [comment]
@DanielYWoo friendly bump
