### ISSUE TITLE
Need docs for App Health Check feature

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2734]
**What content needs to be created or modified?**
Need docs for this new feature: https://github.com/dapr/dapr/pull/4990

Also note that this requires documenting the new feature flag `AppHealthCheck`

**Where should the new material be placed?**
TBD

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/4990

**Comment by msfussell** [comment]
The following docs need to change for this issue.

1. Conceptually - https://docs.dapr.io/concepts/observability-concept/
2.  New howto on using this endpoint on your app here https://docs.dapr.io/developing-applications/building-blocks/observability/. 
   - Use the template here https://v1-9.docs.dapr.io/contributing/docs-contrib/docs-templates/howto-template/
   - This also need a diagram to help illustrate. @hhunter-ms can help.
4. Adding the new annotations here https://docs.dapr.io/reference/arguments-annotations-overview/ 
5. Updating Preview features - https://docs.dapr.io/operations/support/support-preview-features/

**Comment by msfussell** [comment]
Resolved
