### ISSUE TITLE
AWS DynamoDB  IAM policy requirements missing

### ISSUE THREAD

**Issue by sjwl** [dapr/docs#2736]
**Describe the issue**
The `AWS DynamoDB` docs are missing the minimum IAM policy needed to integrate DynamoDB.  As a reference, the AWS SNS/SQS has such information here: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/

**URL of the docs**
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-dynamodb/

**Expected content**
An example IAM policy with the minimal access needed for dapr to function with DynamoDB statestore component.

**Comment by hhunter-ms** [comment]
@sjwl would you be able to contribute a docs PR for this?
