### ISSUE TITLE
Document removal of `http-stream-request-body`

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2737]
**What content needs to be created or modified?**
Update existing docs to remove `http-stream-request-body` per https://github.com/dapr/dapr/pull/5048

**Describe the solution you'd like**
References to that CLI option and annotation need to be removed.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/5048

**Comment by msfussell** [comment]
Resolved
