### ISSUE TITLE
Podman support in cli

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#2743]
**What content needs to be created or modified?**
- `dapr int` and `dapr uninstall` can now have additional parameter to pass a container runtime. Earlier there was hard dependency on docker.
```
    dapr init --container-runtime podman
    dapr uninstall --container-runtime podman
```

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/cli/pull/1041

**Comment by msfussell** [comment]
Resolved
