### ISSUE TITLE
Mariner support in CLI

### ISSUE THREAD

**Issue by mukundansundar** [dapr/docs#2747]
**What content needs to be created or modified?**

Mariner support in CLI, `--image-variant` flag and usage.
**Describe the solution you'd like**

Add docs for the new flag.
**Where should the new material be placed?**

CLI references section.
**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/cli/pull/1029

**Comment by greenie-msft** [comment]
Closing PR was merged: https://github.com/dapr/docs/pull/2752#pullrequestreview-1133719488
