### ISSUE TITLE
Overview and HowTos for OpenTelemetry Protocol

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#2760]
**What content needs to be created or modified?**
This  OpenTelemetry PR https://github.com/dapr/dapr/pull/4808#issuecomment-1195044887 added OTel as a protocol. 

**Describe the solution you'd like**
The docs need to have OTEL across them. Work with @msfussell  and @greenie-msft on updating topics here https://docs.dapr.io/operations/monitoring/tracing/

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/4808

**Additional context**
Other docs issues need to be reviewed 
https://github.com/dapr/docs/issues/1606
https://github.com/dapr/docs/issues/2727

**Comment by juazasan** [comment]
@msfussell excuse me, wondering if you are taking care of this already (I have seen you assigned this to yourself) or still need some help.

**Comment by msfussell** [comment]
@juazasan @yaron2 - I need help on this. Would you be able make suggestions on the changes.

**Comment by juazasan** [comment]
@msfussell Sure!! Will take a look at report back here.

**Comment by greenie-msft** [comment]
Closing as https://github.com/dapr/dapr/pull/4808 was merged
