### ISSUE TITLE
Adding details to debugging dapr on kubernetes docs.

### ISSUE THREAD

**Issue by darren-wang** [dapr/docs#2764]
**What content needs to be created or modified?**
How to start a remote debug session from external IDE, e.g. VS Code.

**Describe the solution you'd like**
Add missing contents.

**Where should the new material be placed?**
Append to currently existing doc:  https://docs.dapr.io/developing-applications/debugging/debug-k8s/debug-dapr-services/

and the doc: https://docs.dapr.io/developing-applications/debugging/debug-k8s/debug-daprd/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by hhunter-ms** [comment]
@darren-wang would you be able to contribute a docs PR for this?
