### ISSUE TITLE
Document how to add {namespace} option to set consumerID for Pub/Sub namespace scoping

### ISSUE THREAD

**Issue by greenie-msft** [dapr/docs#2769]
**What content needs to be created or modified?**
Document how to add {namespace} option to set consumerID for Pub/Sub namespace scoping
These images would be valuable to add:
<img width="952" alt="Screen Shot 2022-09-07 at 3 25 00 PM" src="https://user-images.githubusercontent.com/56556602/188994333-1a409c26-60a4-4ef8-9f79-62b6a50f3084.png">
<img width="889" alt="Screen Shot 2022-09-07 at 3 27 46 PM" src="https://user-images.githubusercontent.com/56556602/188994586-2f23926a-cec0-4702-9e39-a0cbef370e00.png">

**Describe the solution you'd like**
Under the pub/sub building block, consider a new how-to for namespace scoping with pub/sub

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/5112

**Comment by msfussell** [comment]
@hhunter-ms - Would you be able to take this issue. This video explains the features. https://www.youtube.com/watch?v=eK463jugo0c

This should be updated in the following topic
1) Add namespacing support as a new feature into overview here https://v1-9.docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#dapr-pubsub-api-features
2) Create a new HowTo topic (use a template!!) based on this video https://www.youtube.com/watch?v=eK463jugo0c as an example. Does not have to have code. However should include diagrams and links to this video
In this article reference https://docs.dapr.io/operations/components/setup-pubsub/pubsub-namespaces/ as another topic to be aware of.

(only as FYI, you will see there is namespacing in Service Invocation also today. See https://v1-9.docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-namespaces/. At the same time can you fix up this article to say "How To" at the start to make it consistent.

**Comment by greenie-msft** [comment]
Closing since PR has been merged https://github.com/dapr/docs/pull/2864
