### ISSUE TITLE
Incorrect sentence - async vs sync

### ISSUE THREAD

**Issue by farcasclaudiu** [dapr/docs#2782]
**Describe the issue**
not correct
Service Invocation | Asynchronous communication between two services using HTTP.

**URL of the docs**
https://docs.dapr.io/getting-started/quickstarts/

**Expected content**
Service Invocation | Synchronous communication between two services using HTTP or gRPC.

**Additional context**
[Service Invocation](https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/)	Asynchronous communication between two services using HTTP.

**Comment by yaron2** [comment]
Thanks! It'd be great to get a PR that fixes this :)
