### ISSUE TITLE
Update SecretStore API documentation to account for `Features` feature

### ISSUE THREAD

**Issue by tmacam** [dapr/docs#2787]
## What content needs to be created or modified?

dapr/components-contrib#2069 adds the to screate stores the ability to advertise/expose the features they support. This new ability needs to be reflected in Dapr documentation.

## Describe the solution you'd like

TBD

## Where should the new material be placed?

* API reference on https://docs.dapr.io/reference/api/secrets_api/ should be updated (pending exposure of this new API on daprd)

* Components table on https://docs.dapr.io/reference/components-reference/supported-secret-stores/ along with each individual component documentation should be updated

## The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos

* dapr/components-contrib#2069

**Comment by hhunter-ms** [comment]
@tmacam Have you already created docs for this milestone issue? If so, could you add the link?

**Comment by msfussell** [comment]
@tmacam - More explicitly this needs a PR from you.

**Comment by tmacam** [comment]
Closed by PR  https://github.com/dapr/docs/pull/2863
