### ISSUE TITLE
Incorrect API path for Configuration API Unsubscribe Operation 

### ISSUE THREAD

**Issue by sarsharma** [dapr/docs#2796]
**Describe the issue**

The unsubscribe endpoint in the docs is 
`http://localhost:<daprPort>/v1.0-alpha1/configuration/<subscription-id>/unsubscribe
`

**URL of the docs**

https://docs.dapr.io/reference/api/configuration_api

**Expected content**

The actual endpoint is 
`http://localhost:<daprPort>/v1.0-alpha1/configuration/<storename>/<subscription-id>/unsubscribe`

**Screenshots**

**Additional context**

**Comment by yaron2** [comment]
Closed via #2797
