### ISSUE TITLE
Workflow API Documentation

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/docs#2798]
**Description:** This issue will be used to track the documentation needed for the Workflow API feature targeted for 1.10

**Documentation Needed:**

1.) How to use the Workflow API

- [ ] Prerequisites for using workflow API
- [ ] How to set up a workflow with the API
- [ ] Code samples for set up process
- [ ] Invoking a workflow with HTTP vs. gRPC

2.) Updates made in existing docs to accommodate new feature

- [ ] Entry into [quickstart table](https://docs.dapr.io/getting-started/quickstarts/) 
- [ ] Entry into [Component specs ](https://docs.dapr.io/reference/components-reference/) - new docs page to track Workflow API component compatibility and status (alpha, beta, stable etc.)

**Additional context**

**Comment by hhunter-ms** [comment]
@nyemade-uversky just curious, is there a difference between this issue and the [Workflow Engine Documentation](https://github.com/dapr/docs/issues/2933) issue? or are they duplicates?
