### ISSUE TITLE
Dapr Helm repo has http 404

### ISSUE THREAD

**Issue by daneel3001** [dapr/docs#280]
Hello

Currently trying to run Dapr samples over Ubuntu/WSL2 and hitting issue with Redis install.
The quick start doc mentions using Helm repo at https://daprio.azurecr.io/helm/v1/repo but as of now it's not responding.
I have tried bitnami repo but failing to install on my cluster created with KIND.

Thanks

**Comment by yaron2** [comment]
Is this command not responding?
`helm repo add dapr https://daprio.azurecr.io/helm/v1/repo`

**Comment by daneel3001** [comment]
Hello

Yes the command works but the Helm repo at url  https://daprio.azurecr.io/helm/v1/repo isn't working.
```
helm repo add dapr https://daprio.azurecr.io/helm/v1/repo
helm repo update
helm install redis stable/redis
Error: failed to download "stable/redis" (hint: running `helm repo update` may help)
```

**Comment by daneel3001** [comment]
Hello

I think I got confused because Helm 3 doesn't have the stable charts repo auto installed. I am now in the process of installing Redis onto the cluster.
Though the point remains that  https://daprio.azurecr.io/helm/v1/repo is no longer up.

**Comment by daneel3001** [comment]
Dapr Helm repo is functional. I managed to install Dapr on Microk8s.
