### ISSUE TITLE
MQTT Binding with TLS needs more details

### ISSUE THREAD

**Issue by mandarj123** [dapr/docs#2803]
I am trying to use MQTT binding and documentation is providing no guidance on how to use TLS certificates for subscribing to MQTT topic.

It says use it as follows {{ myLoadedCACert }} 

What does this mean, I have no idea? how to use this to make mqtt subscription work is not clear.

https://docs.dapr.io/reference/components-reference/supported-bindings/mqtt/

**Comment by hhunter-ms** [comment]
@mandarj123 the MQTT3 binding documentation has been updated since you opened this issue - do the updates clear this up? https://v1-11.docs.dapr.io/reference/components-reference/supported-bindings/mqtt3/

**Comment by hhunter-ms** [comment]
closing as this seems to have been resolved. feel free to comment if I need to reopen.
