### ISSUE TITLE
Add code coverage criteria to certification tests

### ISSUE THREAD

**Issue by rabollin** [dapr/docs#2806]
Describe the issue

To maintain the stable components are highly stable and robust by having a detailed certification test, introducing the code coverage measure for certifications tests might help. So, recommend to add a measure of Certification Tests should cover 60% of the code.

**Comment by rabollin** [comment]
https://github.com/dapr/docs/pull/2805

**Comment by hhunter-ms** [comment]
@rabollin friendly bump

**Comment by hhunter-ms** [comment]
closing for now - reopen if necessary
