### ISSUE TITLE
Add Unix Domain Socket documentation

### ISSUE THREAD

**Issue by shubham1172** [dapr/docs#2815]
**What content needs to be created or modified?**

There should be a documentation to tell when Unix Domain Socket can/should be used with Dapr, and how to use it in self-hosted and Kubernetes modes.

**Where should the new material be placed?**

Probably under https://docs.dapr.io/operations/configuration/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/3529
https://github.com/dapr/dapr/pull/4348

**Comment by hhunter-ms** [comment]
@shubham1172 would you be able to contribute a docs PR for this?

**Comment by shubham1172** [comment]
Hi @hhunter-ms I am not super familiar with this, maybe @daixiang0 can help.

**Comment by daixiang0** [comment]
I am busy recently, if someone post PR I can help review :)
