### ISSUE TITLE
Missing Quickstarts

### ISSUE THREAD

**Issue by WallucePinkham** [dapr/docs#2816]
**What content needs to be created or modified?**
Quickstarts for Actors, et al.

**Describe the solution you'd like**
Dapr was announced on October 16, 2019. It's now September 2022. We still have Quickstarts saying "coming soon!!".

**Where should the new material be placed?**
With the other quickstarts.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by hhunter-ms** [comment]
Resiliency quickstart #2935

**Comment by hhunter-ms** [comment]
Configuration quickstart #3009
