### ISSUE TITLE
Kafka bulk support documentation

### ISSUE THREAD

**Issue by shubham1172** [dapr/docs#2825]
**What content needs to be created or modified?**

TODO: add more details, to be triaged for v1.9

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by shubham1172** [comment]
@mukundansundar can you please assign this to yourself?

**Comment by mukundansundar** [comment]
closed by #3071
