### ISSUE TITLE
K8s Secret store is marked as stable but it lacks certification tests

### ISSUE THREAD

**Issue by tmacam** [dapr/docs#2835]
**Describe the issue**

In [Supported Secret Stores](https://docs.dapr.io/reference/components-reference/supported-secret-stores/) k8s is described as a stable component but there are no tests targeting k8s secrets certification on https://github.com/dapr/components-contrib/tree/master/tests/certification/secretstores

**URL of the docs**
https://docs.dapr.io/reference/components-reference/supported-secret-stores/

**Expected content**
 K8s Secrets marked as Beta as [it has Conformance tests](https://github.com/dapr/components-contrib/blob/f15a50581d679341b2368131d0e6b3b6299eff98/.github/workflows/conformance.yml) but lacks certification tests.

**Screenshots**

**Additional context**

**Comment by yaron2** [comment]
We do not retroactively mark components as beta. The certification test criteria applies to all new components after the policy was applied.

**Comment by tmacam** [comment]
Got it. Should I close this issue then?

**Comment by yaron2** [comment]
Please
