### ISSUE TITLE
How to push CustomEvents to Azure Application Insights using DAPR observability

### ISSUE THREAD

**Issue by VamseeInala** [dapr/docs#2837]
**What content needs to be created or modified?**
Steps on how to push application telemetry events to Azure App Insights using DAPR observability

**Where should the new material be placed?**
https://github.com/dapr/quickstarts/blob/master/tutorials/observability/README.md

**Comment by hhunter-ms** [comment]
@vamseelnala closing as there is a doc for this: https://docs.dapr.io/operations/monitoring/tracing/otel-collector/open-telemetry-collector-appinsights/

If you'd like this added to the [quickstarts repo](dapr/quickstarts), please open a new issue there - thanks!
