### ISSUE TITLE
Update docs to include the newly added `time` field for CloudEvent

### ISSUE THREAD

**Issue by yash-nisar** [dapr/docs#2845]
**What content needs to be created or modified?**

The newly added time field should be added on https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-cloudevents/

**Describe the solution you'd like**

Since dapr now also has a `time` field, https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-cloudevents/#cloudevents-example should be updated to include it.

**Where should the new material be placed?**
https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-cloudevents/#cloudevents-example

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/2123

**Comment by msfussell** [comment]
Resolved
