### ISSUE TITLE
MSI/Winget Installer Documentation

### ISSUE THREAD

**Issue by shivamkm07** [dapr/docs#2848]
**What content needs to be created or modified?**
Documentation for msi/winget installer added in 1.9 release

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/cli/pull/1065, https://github.com/dapr/cli/pull/1068
**Additional context**

**Comment by greenie-msft** [comment]
Closing as https://github.com/dapr/docs/pull/2860 completes this issue
