### ISSUE TITLE
Please package complete solution and post link.

### ISSUE THREAD

**Issue by jackbond** [dapr/docs#2850]
Describing all the steps is nice, but if you miss just one line, it can be completely impossible to get a sample working.

This is in response to this page...

https://v1-9.docs.dapr.io/developing-applications/sdks/dotnet/dotnet-actors/dotnet-actors-howto/#running-the-code

**Comment by hhunter-ms** [comment]
@halspang - is this something we can do?

**Comment by jackbond** [comment]
Sorry, but it doesn't help at all. I can't stress this enough, the DAPR team needs a docker compose example with a service talking to an actor. When someone sits down to write that, they'll quickly discover, you've got a bug.

https://github.com/dapr/dapr/issues/4891

**Comment by hhunter-ms** [comment]
@jackbond - Thank you for the dapr/dapr issue context. We're working on testing it out.

**Comment by hhunter-ms** [comment]
Closing as it has been addressed in dapr/dapr#4891
Will document once has been added as an example to dotnet-sdk (@halspang )
