### ISSUE TITLE
Update HashiCorp Vault status to Beta/Stable

### ISSUE THREAD

**Issue by tmacam** [dapr/docs#2857]
**What content needs to be created or modified?**

With https://github.com/dapr/components-contrib/issues/1926, HashiCorp Vault has both conformance and certifications tests and is ready to be promoted to Beta and, on the next release, to Stable status.

**Describe the solution you'd like**

HashiCorp Vault promoted to stable

**Where should the new material be placed?**

`daprdocs/data/components/secret_stores/generic.yaml`

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

* https://github.com/dapr/components-contrib/pull/2140
* https://github.com/dapr/components-contrib/issues/1926

**Additional context**

**Comment by msfussell** [comment]
Resolved
