### ISSUE TITLE
Expand Jetstream TLS configuration documentation

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#2872]
**What content needs to be created or modified?**
Create a separate a sample config for Jetstream TLS configuration. 

**Describe the solution you'd like**
Use example in [doc for Azure EventHubs](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/). Have the fields in the table for the description with a separate sample configure under a heading of using TLS or similar.

Could use tabs for better readability, like:

- Basic
- Decentralized JWT Authentication
- TLS Client Authentication
- Durable Consumers
- Queue Group
- Consumer Offset

**Where should the new material be placed?**
[Jetstream pub/sub component doc](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-jetstream/)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
Post-release enhancement stemming from discussion in this PR: dapr/docs#2698
Related issue: dapr/docs#2697
Code issue: dapr/components-contrib#1924

**Comment by hhunter-ms** [comment]
@NickLarsenNZ

**Comment by hhunter-ms** [comment]
@NickLarsenNZ just a friendly bump; per [this PR comment](https://github.com/dapr/docs/pull/2698#issuecomment-1272060111), do you think you'll be able to work this in for the 1.10 release?

**Comment by NickLarsenNZ** [comment]
Hi @hhunter-ms, apologies for the delay, I will try to get to this soon.
When is the 1.10 release scheduled for? I'm unsure where to find the date.

**Comment by hhunter-ms** [comment]
@NickLarsenNZ - You can find the v1.10 release dates in the [planning issue](https://github.com/dapr/dapr/issues/5373). We're trying to get docs into draft PRs by code freeze. Thanks!

**Comment by hhunter-ms** [comment]
@NickLarsenNZ We're in Dapr v1.10 release endgame now - would you be able to have these docs in by 2/8?

**Comment by NickLarsenNZ** [comment]
Apologies @hhunter-ms, it doesn't look like I'm going to get to this in time.
Can it be added some time after, or will it have to wait until 1.11?

**Comment by hhunter-ms** [comment]
No worries, @NickLarsenNZ - for sure, this doesn't have to be tied to a release milestone. If you have bandwidth to pull this together sooner than 1.11, go for it!

**Comment by hhunter-ms** [comment]
@NickLarsenNZ just checking in on this issue - is this something you can work on in the next few weeks?
