### ISSUE TITLE
AD authorization - explicit warning re Workload identity not currently supported

### ISSUE THREAD

**Issue by VaclavK** [dapr/docs#2894]
**What content needs to be created or modified?**
The current doco re Azure AD points to service principal. In principle, this would also cover Workload Identity injected principal. However, Discord DAPR channel points to this mode not yet supported due to Go language Identity SDK support not yet present.

It may be good idea to explicitly warn re this and provide link to tracking issue so that this may be followed upon.

the link to the doco where the linkage would make sense

https://docs.dapr.io/developing-applications/integrations/azure/authenticating-azure

**Comment by hhunter-ms** [comment]
this has been resolved
