### ISSUE TITLE
How to declare method body of Actor?

### ISSUE THREAD

**Issue by leenux** [dapr/docs#290]
## Ask your question here
Or where declare the method of task body? Only tell us how to invoke method or timer or reminders,it is no enough.
We will finally execute the task code. Where are these codes defined?

**Comment by amanbha** [comment]
@leenux  Could you explain your question in more detail? Is it related to dotnet-sdk? Please see the usage here: https://github.com/dapr/dotnet-sdk/blob/master/samples/Actor/DemoActor/DemoActor.cs

**Comment by amanbha** [comment]
@leenux I am closing it due to inactivity, please feel free to reopen if you have any further questions.

**Comment by leenux** [comment]
@amanbha yes it is enough,thank you very much!
