### ISSUE TITLE
`.dapr\\bin\\daprd.exe file does not exist` Win11 + Kubernetes

### ISSUE THREAD

**Issue by kennedy** [dapr/docs#2907]
**Describe the issue**

I installed DAPR using [scoop.sh](https://scoop.sh/#/apps?q=dapr&s=0&d=1&o=true), then installed the DAPR helm chart with `dapr init -k` onto my local kube cluster (rancher desktop) with success. I can see all the pods, and even able to spin up the `dashboard`. However, the dapr "runtime" is n/a:

```
$ dapr status -k
  NAME                   NAMESPACE    HEALTHY  STATUS   REPLICAS  VERSION  AGE  CREATED
  dapr-dashboard         dapr-system  True     Running  1         0.11.0   50m  2022-10-17 22:11.42
  dapr-placement-server  dapr-system  True     Running  1         1.9.0    50m  2022-10-17 22:11.42
  dapr-sentry            dapr-system  True     Running  1         1.9.0    50m  2022-10-17 22:11.42
  dapr-operator          dapr-system  True     Running  1         1.9.0    50m  2022-10-17 22:11.42
  dapr-sidecar-injector  dapr-system  True     Running  1         1.9.0    50m  2022-10-17 22:11.42
```

```
$ dapr version
CLI version: 1.9.1
Runtime version: n/a
```

When I try to run the [quickstart/pubsub/python](https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/#step-3-subscribe-to-topics), it says daprd.exe does not exist

```
$ dapr run --app-id order-processor --components-path ../../../components/ --app-port 5001 -- python3 app.py
Starting Dapr with id order-processor. HTTP Port: 52401. gRPC Port: 52402
exec: "C:\\Users\\Kennedy\\.dapr\\bin\\daprd.exe": file does not exist
```

**URL of the docs**

https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/#step-3-subscribe-to-topics

**Expected content**

I am not sure, but I assume dapr will run the python app in the background, then I can proceed to the next step and publish to the topic

**Screenshots**

**Additional context**

- Win11 x64
- installed dapr via scoop.sh
- kubernetes via rancher desktop
- kubectl is pointing to rancher desktop cluster
- dapr chart did not fail with positive health checks

**Comment by hhunter-ms** [comment]
@msfussell do you have any suggestions here?
