### ISSUE TITLE
How to set MinIO Blob Object MetaData 

### ISSUE THREAD

**Issue by flaussmann** [dapr/docs#2910]
**What content needs to be created or modified?**

There is no description on how to set custom MinIO object MetaData in a KeyValue format.

**Describe the solution you'd like**
I would like a extended Create Example with a custom MetaData key. For example: x-amz-meta-test : test.

**Where should the new material be placed?**

https://docs.dapr.io/reference/components-reference/supported-bindings/s3/#create-file

**Comment by hhunter-ms** [comment]
@flaussmann would you be able to contribute a docs PR for this?
