### ISSUE TITLE
[1.10] Add docs for `pubsub.azure.servicebus.queues` component and update metadata for all other Service Bus components

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2912]
The pages for the Service Bus components need to be updated:

- dapr/components-contrib#2211 is adding a new component `pubsub.azure.servicebus.queues`, and renaming the existing `pubsub.azure.servicebus` to `pubsub.azure.servicebus.topics` (old name remains as alias)
- dapr/components-contrib#2203 changed the metadata options for the 3 Service Bus components (the two above and `bindings.azure.servicebusqueues`)

**Comment by hhunter-ms** [comment]
Looks like this was resolved - closing
