### ISSUE TITLE
[Actors] Missing properties in Reminder and Timer API spec

### ISSUE THREAD

**Issue by olitomlinson** [dapr/docs#2926]
There is no documentation about the `data` and `ttl` properties that can be set on Reminders and Timers. It appears `dueTime` and `period` are the only properties that are documented.

Please update this table and review the rest of the page to ensure sufficient examples of using these properties are available.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/4224880/199107075-bd042c39-9b22-40af-9686-91a4eeaaec61.png">

**Comment by hhunter-ms** [comment]
#3257
