### ISSUE TITLE
Incorrect image src in zh-cn docs

### ISSUE THREAD

**Issue by magixsource** [dapr/docs#2927]
**Describe the issue**
Incorrect image src 

**URL of the docs**
https://docs.dapr.io/zh-hans/concepts/overview/

**Expected content**
https://docs.dapr.io/images/overview-standalone.png

**Screenshots**
![36742395-5C3D-4540-ADC7-74A4CC1BDFFA](https://user-images.githubusercontent.com/1000432/199149314-409c4fa1-844d-4378-bb83-e15032532369.png)

**Additional context**
Correct image src should not be 'https://docs.dapr.io/images/overview_standalone.png'

**Comment by hhunter-ms** [comment]
@skyao do you mind taking a look at this?

**Comment by magixsource** [comment]
I can fix in technical, but i don't know "HOW TO", dapr docs in Chinese does not write in offical dapr org. You can point me HOW TO, I can fix it as i can.      : )

**Comment by kendallroden** [comment]
@hhunter-ms can you close this or remove the good first issue? looks like it was fixed
