### ISSUE TITLE
Workflow Documentation

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/docs#2933]
# Workflow Docs
### Global Changes across all docs
- [ ] Swap all references of "Built-in" engine with just Dapr Workflows

### Concepts/FAQ
- [ ] @hhunter-ms/ @nyemade-uversky Explain HL differences between Dapr Workflows, authoring APIs 
- [ ] @cgillum Durable task framework vs dapr workflows - what's the relationship

### Concepts Section
- [x] Building Blocks Concepts page
- [ ] Components Concepts page
   -  @nyemade-uversky Missing link to Workflow implementation – temporal.go

### Developing Applications/API Building Blocks/Workflow
- [ ] Workflow Overview
   - [ ] @RyanLettieri Need to add Ryan’s Diagram to this page
   - [ ] @RyanLettieri Need to add Ryan’s description of diagram to this page
   - [ ] @nyemade-uversky  Remove current “Features” section with workflow engine specific features and replace this with a new feature list specifically for the workflow API

- [ ] How To
   - @RyanLettieri  Need high level diagram explaining difference between the built in engine and an external workflow component
   - [ ] @RyanLettieri Need steps/commands for registering user’s temporal component 
   - [ ] @RyanLettieri Specify path to temporal yaml 
   - [ ] @RyanLettieri Need code example for this
   - [ ] Registration step for component + link to details in reference section
   - [ ] @RyanLettieri What the management SDK is 
   - [ ] @RyanLettieri  How to use management SDK for external workflows
   - [ ] @RyanLettieri  Languages supported for the management SDK
   - [ ] @hhunter-ms Update links under “Next Steps” section so they link to appropriate sections. 

### Developing Applications/Components/Workflow
📢📢📢 _NET NEW DOC – needs to be created_
- [ ] @cgillum Document for how to author a workflow for built in engine
   - [ ] What the authoring SDK is
   - [ ] Supported SDK languages for authoring
   - [ ] Code sample of workflow
   - [x] @hhunter-ms  “Features” section from workflow engine overview should be moved to this doc
   - [x] @hhunter-ms  Add new section “Workflow Patterns” section. Use patterns 1-4 from [this page](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp) as reference. Re-work the pattern diagrams to fit dapr look/feel and change wording so it’s not an exact copy.
   
### Developing application/sdks/.NET
   - [ ] @cgillum How to write a workflow for the workflow engine for .NET
   - [ ] @RyanLettieri How to manage workflows in .NET

### Operations/Components/Workflow-engine
- [ ] @cgillum Operational doc for workflow engine. Repurpose existing workflow-engine.md file for operational doc

### Operations/Support/Preview Features
- [x] @hhunter-ms  Workflow needs to be added to table

### Reference/Component Specs/Workflows
Github location: docs/daprdocs/content/en/reference/components-reference/supported-workflows at issue_2798b · hhunter-ms/docs · GitHub
- [x] @hhunter-ms  Create table for supported external components – just create/add Temporal
- [x] @nyemade-uversky Remove Logic apps from section
- [x] @nyemade-uversky Remove built in engine from section (dtfx)

### Reference/Component Specs/Workflows/Temporal.io
- [ ] @nyemade-uversky  Edit code tabs – remove them and re-work page so it makes more sense

### Reference/Dapr API/Workflow API reference
- [x] @nyemade-uversky Add a generic yaml file into a generic template without real values. Similar to this state store yaml template
- [ ] @hhunter-ms Update links for the workflow patterns doc under “Next Steps” section. Need to link to the new Authoring doc which will touch on patterns. 
- [ ] @hhunter-ms Update link in table to direct user to list of supported workflow components information. Should link to “How To” doc which talks about supported workflow components.

**Comment by nyemade-uversky** [comment]
@msfussell Putting this checklist on your radar. This is just a brain dump of all the sections we need to touch, and documentation we still need before we're in a good place with workflow documentation. 

Feel free to start leaving reviews in the workflow draft PR (#2915 ). The PR is still in draft since we're still making large changes and all docs needed aren't added yet but it should still be ok to start looking through it you'd like.

**Comment by msfussell** [comment]
I reviewed the PR and we need to be clear on the doc structure. This is my proposed Workflow doc structure. Just a note there is only a Workflow API, and SDKs and the main emphasis is on Dapr Workflows.

Concepts->Building Blocks
Concepts->Components

Quickstarts->Dapr-workflows-quickstart (This need this Quickstart code issue to be done first) https://github.com/dapr/quickstarts/issues/733

Developing Applications->Building blocks->Workflow
Developing Applications->Building blocks->Workflow overview
Developing Applications->Building blocks->Architecture
Developing Applications->Building blocks->How to: Write and run Dapr workflows
Developing Applications->Building blocks->How to: Write and run Temporal workflows

Operations->support->support-preview-features

Reference->Api->workflow_api (This needs examples and error handling)
Components-reference->supported-workflows->temporal-io

**Comment by hhunter-ms** [comment]
> Quickstarts->Dapr-workflows-quickstart (This need this Quickstart code issue to be done first) [dapr/quickstarts#733](https://github.com/dapr/quickstarts/issues/733)

@RyanLettieri @nyemade-uversky @cgillum can you confirm again if the quickstart will be included with 1.10?

**Comment by hhunter-ms** [comment]
> I reviewed the PR and we need to be clear on the doc structure. This is my proposed Workflow doc structure which is quite simply (outside of all the diagram that are needed)
> 
> Concepts->Building Blocks Concepts->Components
> 
> Quickstarts->Dapr-workflows-quickstart (This need this Quickstart code issue to be done first) [dapr/quickstarts#733](https://github.com/dapr/quickstarts/issues/733)
> 
> Developing Applications->Building blocks->Workflow Developing Applications->Building blocks->Workflow overview Developing Applications->Building blocks->How to: Write and run Dapr workflows Developing Applications->Building blocks->How to: Write and run Temporal workflows
> 
> Operations->support->support-preview-features
> 
> Reference->Api->workflow_api (This needs examples and error handling) Components-reference->supported-workflows->temporal-io

@msfussell I agree - I think this doc structure simplifies Workflows better. I think we were getting a little lost in the weeds. Also need to include docs in the .NET SDK repo.

**Comment by cgillum** [comment]
Where does the workflow engine overview go in this proposal? Previously it was in the Operations section.

**Comment by hhunter-ms** [comment]
@cgillum @msfussell I think it can go under Developing Applications/Building Blocks/Workflows as a conceptual doc

**Comment by msfussell** [comment]
Yes, it should go under Developing Applications/Building Blocks/Workflows. When you say "workflow engine" are you referring to Dapr Workflows or the Workflow API or both. Generally we should talk about:

- Dapr Workflows
- Workflow API
- Workflow Components

In the Workflow Overview topic, here is where you can talk about that Dapr has an included (built-in) workflow engine (or maybe say runtime), with any of the architectural docs that describe that is is built with Dapr actor. We just need to be careful that  "workflow engine" is a term that is an implementation detail for Dapr Workflows, just as "actor runtime" is an implementation detail for Dapr Actors.

**Comment by cgillum** [comment]
> When you say "workflow engine" are you referring to Dapr Workflows or the Workflow API or both

I'm specifically talking about the workflow engine and information about how it leverages actors, the state store, network connectivity requirements, etc. To me, it didn't seem appropriate as a "developing applications" topic because, as you said, this is purely an implementation detail for developers. I considered this a topic that architects and operators would be primarily interested in.

**Comment by msfussell** [comment]
Operations doesn't contain this either today, it focuses on the Ops role and set up requirements. We tried to stay away from API background here, since it was more developer focused. The closest to providing this background today is the Actor overview https://docs.dapr.io/developing-applications/building-blocks/actors/actors-overview/ which discusses the Placement service for example. It was put here, since we have API specific topics like State Management etc. We could create and Architecture section and have this information there.

**Comment by hhunter-ms** [comment]
Closing this issue in favor of smaller issues, and since we've resolved the question of workflow documentation structure
