### ISSUE TITLE
[Question] Is there a Dapr icon library?

### ISSUE THREAD

**Issue by philliphoff** [dapr/docs#2934]
Is there a collection of official Dapr icons for use in related products?  We're using an early icon for the VS Code Dapr extension but it has been [noted](https://github.com/microsoft/vscode-dapr/issues/252) to not work well in dark-themed settings.  Is there a Dapr icon that might work better in those settings?

**Comment by msfussell** [comment]
Dapr logos can be found here https://github.com/cncf/artwork/blob/master/examples/incubating.md#dapr-logos
If not, they are also in the Website repo in the Dapr org.

**Comment by hhunter-ms** [comment]
@philliphoff Closing this issue as it appears to have been resolved - feel free to reopen if necessary
