### ISSUE TITLE
Document minimum requirement of K8s 1.22

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2936]
Now that dapr/dapr#5371 is merged, that is raising the minimum version requirement of Kubernetes for running Dapr.

The PR depends on a feature that was added in K8s 1.21 as preview, but was made GA only in 1.22. Although technically Dapr should be able to run on 1.21 too (and in fact we still have E2E tests on KIND that use 1.21), given how core the feature we depend on, we should raise the minimum version to 1.22.

(Good news is that K8s 1.22 has been EOL'd months ago, so hopefully this doesn't impact many users)

**Comment by msfussell** [comment]
Resolved
