### ISSUE TITLE
Ensure that page-feedback events are usable with Google Analytics 4

### ISSUE THREAD

**Issue by chalin** [dapr/docs#2943]
- Related to #2861
- The Docsy [page feedback](https://www.docsy.dev/docs/adding-content/feedback/#user-feedback) feature has been enabled since [v1.4 of the docs](https://v1-4.docs.dapr.io/)
- There's feature interaction with GA4. For details, see the upstream issue: https://github.com/google/docsy/issues/1302

If there's a feeling of urgency to collected page-feedback events in GA4, then the local partial [layouts/partials/feedback.html](https://github.com/dapr/docs/blob/v1.9/daprdocs/layouts/partials/feedback.html) will at least need to be updated to use the [gtag.js] library, and an event-modification rule implemented. For an example of how this has been implemented, see:

- https://github.com/kubernetes/website/issues/37657

Specifically, https://github.com/kubernetes/website/issues/37657#issuecomment-1301548361.

If there is no feeling of urgency in gathering this data under GA4, then I'd suggesting waiting for the upstream fix and then updating Hugo.

[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs

**Comment by chalin** [comment]
I went ahead and created an event-modification rule, in case we get local changes into the project-local feedback-partial override before the Docsy fix lands:

> <img width="702" alt="image" src="https://user-images.githubusercontent.com/4140793/200649573-f0113228-49e2-4cca-bd19-01e8676a73e1.png">

**Comment by hhunter-ms** [comment]
@chalin would you say this issue is resolved?

**Comment by chalin** [comment]
Hi @hhunter-ms - yes in that I created the necessary event-modification rule, _but_ it will only work for v1.7+ of the docs. I didn't close this issue at the time because I wasn't sure how far back in the doc versions you wanted analytics support for. 

According to https://github.com/dapr/docs/issues/2861#issuecomment-1349504800, v1.7+ is good enough. Closing!
