### ISSUE TITLE
Docs for new component KubeMQ PubSub (beta) & Binding (beta)

### ISSUE THREAD

**Issue by berndverst** [dapr/docs#2947]
Need docs for new component KubeMQ PubSub and KubeMQ Binding (New in v1.10)

These components are Beta because they have conformance tests.

https://github.com/dapr/components-contrib/pull/2215

**Comment by berndverst** [comment]
@kubemq please complete the docs or no Dapr user will be aware of your components.

**Comment by hhunter-ms** [comment]
Looks like this was resolved with #3149 - closing
