### ISSUE TITLE
Add jetstream pubsub component token based auth docs

### ISSUE THREAD

**Issue by siredmar** [dapr/docs#2960]
**What content needs to be created or modified?**

Jetstream pubsub component docs need adaptions for token based auth.

**Describe the solution you'd like**

Add description on the new token setting

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/2295

**Additional context**

**Comment by hhunter-ms** [comment]
closing this issue as it's been resolved
