### ISSUE TITLE
Update reference for state.postgres

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#2966]
The reference for the [Postgres state store](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-postgresql/) needs to be updated for 1.10 because of dapr/components-contrib#2302 and dapr/components-contrib#2379

In particular:

- Add note that TTLs are now supported (in an emulated way). Similar to how it's documented for the [Oracle DB state store](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-oracledatabase/)
- Document new metadata option `cleanupIntervalInSeconds` for the background "garbage collector" that removes expired records. The default value is 3600 seconds (1hr), and a value <= 0 means that no GC is performed (useful if the user knows they'll never use TTLs)
- Document new metadata option `timeoutInSeconds` for timeouts for network operations. The default value is 20 (seconds)
- Document missing metadata options, that were added in the past but not documented:
   - `tableName`, which defaults to `"state"` (can be in the format `table` or `schema.table`)
   - `connectionMaxIdleTime`, which causes connections to be closed automatically if idle for N seconds (default is 0, which means connections are not closed)

**Comment by ItalyPaleAle** [comment]
One thing that will need to be documented.

The TTL column does not have an index, which means that all garbage collection operations require a full-table scan. This is generally OK unless the table has a lot of records (tens of thousands of records).

If the table is big, users who use a TTL may want to manually add an index. We will document the query.

**Comment by msfussell** [comment]
Completed
