### ISSUE TITLE
Does Kubernetes Events Component support Output Binding as stated in the Generic table ? 

### ISSUE THREAD

**Issue by martencassel** [dapr/docs#2970]
**Describe the issue**
Does Kubernetes Events Component support Output Binding as stated in the Generic table ? 

**URL of the docs**
](https://docs.dapr.io/reference/components-reference/supported-bindings/)

**Expected content**
I expected it to state that it only supports the Input bindings.

**Additional context**
I cannot find any output info at https://docs.dapr.io/reference/components-reference/supported-bindings/kubernetes-binding/

**Comment by msfussell** [comment]
No, it does not. This is a mistake. Will get this fixed to only show input. Thanks!
![image](https://user-images.githubusercontent.com/11199644/214227646-5b2b65ac-d50e-456c-bbb1-ae64ad78e568.png)
