### ISSUE TITLE
Remove mentions of `backoff` from RabbitMQ component documentation

### ISSUE THREAD

**Issue by renatolfc** [dapr/docs#2977]
**Describe the issue**

https://github.com/dapr/dapr/issues/1798 removed backoff support from the RabbitMQ pubsub component, but the docs still mention backoff support.

**URL of the docs**

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/

**Expected content**

There shouldn't be any `backoff`s there.

**Comment by msfussell** [comment]
Completed
