### ISSUE TITLE
Add dapr bot documentation

### ISSUE THREAD

**Issue by shubham1172** [dapr/docs#2979]
**What content needs to be created or modified?**

Add what commands are supported by dapr bot across runtime and contrib repos.

**Describe the solution you'd like**

Add the commands, what they do, and who can use them.

**Where should the new material be placed?**

https://docs.dapr.io/contributing/contributing-overview/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

NA

**Additional context**

**Comment by msfussell** [comment]
Completed
