### ISSUE TITLE
Event Hubs namespace and event hubs (topic) clarity in binding sample 

### ISSUE THREAD

**Issue by agowdamsft** [dapr/docs#298]
## Describe the proposal
https://github.com/dapr/docs/blob/master/concepts/bindings/specs/eventhubs.md#azure-eventhubs-binding-spec document needs to clarify to use the keys to the event hub itself and not the namespace. However its ideal to have event hubs namespace connection string with event hub (topic) itself as another variable in yaml e.g. apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myEHevents
spec:
  type: bindings.azure.eventhubs
  metadata:
  - name: connectionString # event hubs namespace connection string
    value: Endpoint=Endpoint=sb://dapranrwxwtest.servicebus.windows.net/;SharedAccessKeyName=...........
  - name: topic  # Event Hubs name
    value: daprtest
  - name: consumerGroup  # Optional
    value: test1

**Comment by AaronCrawfis** [comment]
Documentation PR submitted to address eventhubs vs. namespace.

I agree though it would make more sense to use the namespace and then specify the eventhub name in the yaml file.

@yaron2 thoughts?

**Comment by yaron2** [comment]
> Documentation PR submitted to address eventhubs vs. namespace.
> 
> I agree though it would make more sense to use the namespace and then specify the eventhub name in the yaml file.
> 
> @yaron2 thoughts?

Looks good.

**Comment by yaron2** [comment]
Closed by #347
