### ISSUE TITLE
Update HashiCorp Vault status to Stable

### ISSUE THREAD

**Issue by tmacam** [dapr/docs#2982]
**What content needs to be created or modified?**

With https://github.com/dapr/components-contrib/issues/1926 and https://github.com/dapr/components-contrib/pull/2316, HashiCorp Vault has both conformance and certifications tests and is ready to be promoted to Stable.

**Describe the solution you'd like**

HashiCorp Vault promoted to stable

**Where should the new material be placed?**

`daprdocs/data/components/secret_stores/generic.yaml`

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

* https://github.com/dapr/components-contrib/pull/2316
* https://github.com/dapr/docs/pull/2981

**Additional context**

**Comment by msfussell** [comment]
Completed
