### ISSUE TITLE
Pluggable Components' "Define the component" has wrong information

### ISSUE THREAD

**Issue by tmacam** [dapr/docs#2985]
**Describe the issue**

It reads:

> Define your component using a [component spec](https://docs.dapr.io/operations/components/component-schema/). Your component’s `type` is derived from the socket name, without the file extension.

But that is not really the case. Filename has a impact on the component name, not on its type.

**URL of the docs**

https://docs.dapr.io/operations/components/pluggable-components/pluggable-components-registration/#define-a-component

**Expected content**

TBD

**Screenshots**

**Additional context**

**Comment by hhunter-ms** [comment]
@tmacam let me know if you'd like me to help out with updating this doc

**Comment by tmacam** [comment]
Hey @hhunter-ms . If you have the docs ready and could update that I would appreciate. Otherwise I will tackle this later this week.

**Comment by hhunter-ms** [comment]
@tmacam ok! I don't have anything ready, just offering support!
