### ISSUE TITLE
Docs for `components-path` changed to `resources-path`

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#2998]
Please refer issues - 
https://github.com/dapr/cli/issues/953
https://github.com/dapr/cli/issues/1148

**Comment by pravinpushkar** [comment]
draft PR already there.

**Comment by hhunter-ms** [comment]
PR: #2999

**Comment by hhunter-ms** [comment]
dapr/quickstarts#781

**Comment by hhunter-ms** [comment]
Closing bc resolved in docs for 1.10
