### ISSUE TITLE
`topic_name` keyword argument is wrong in the docs (Python SDK)

### ISSUE THREAD

**Issue by Zizico2** [dapr/docs#3001]
**Describe the issue**
As mentioned in https://github.com/dapr/docs/issues/1803#issuecomment-957758553, the examples' `topic` keyword argument is wrong. It should be `topic_name`.

**URL of the docs**
[https://docs.dapr.io/developing-applications/sdks/python/python-client/#publish-messages](https://docs.dapr.io/developing-applications/sdks/python/python-client/#publish-messages)

**Comment by yaron2** [comment]
Thanks, would you like to submit a PR that fixes this?

**Comment by Zizico2** [comment]
Yep I can do it

**Comment by Zizico2** [comment]
Now that I look into it, should we look at this as a documentation problem or bad naming conventions? Because `@dapr_app.subscribe` uses `pubsub_name` and `topic` whereas `.publish_event` uses `pubsub_name` and `topic_name`.

**Comment by Zizico2** [comment]
Anyway, here goes the PR

https://github.com/dapr/python-sdk/pull/497

**Comment by msfussell** [comment]
Resolved
