### ISSUE TITLE
PubSub routing filter cloud event with topic

### ISSUE THREAD

**Issue by federicocodo** [dapr/docs#3017]
During my tests of the pubsub routing using the CEL expression I notice after, a few days of unsuccessfully tests, that the documentation of [How-To: Route messages](https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-route-messages/#common-expression-language-cel) in the CEL expressions section the following command is wrong:
```cs
event.type == "deposit" && event.data.amount > 10000
```
shoul it be replaced with:
```cs
event.type == "deposit" && int(event.data.amount) > 10000
```
Because as it say the [CEL documentation](https://github.com/google/cel-spec/blob/master/doc/langdef.md#numeric-values):
> Note that currently there are no automatic arithmetic conversions for the numeric types (int, uint, and double). The arithmetic operators typically contain overloads for arguments of the same numeric type, but not for mixed-type arguments

**Comment by msfussell** [comment]
@federicocodo - You are correct. Thanks for spotting this. Greatly appreciate this. Would you like to push a docs PR?

**Comment by federicocodo** [comment]
Of course, I haven't created a PR yet so I try to understand the guidelines first
