### ISSUE TITLE
Invoke HTTP service

### ISSUE THREAD

**Issue by federicocodo** [dapr/docs#3018]
During my tests of the HTTP service invoke using the `DaprClient`, I notice that the `Dotnet` code sample in the [Invoke HTTP service](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#invoke-the-service),  is wrong because the last parameter isn't the `CancellationToken` as written in the doc but is a `TRequest` class for performing POST mothods and as it say the method parameter:
> The data that will be JSON serialized and provided as the request body

The code should be updated with the following code, removing the `cancellationToken`:
```cs
var result = client.CreateInvokeMethodRequest(HttpMethod.Get, "checkout", "checkout/" + orderId);
```

**Comment by msfussell** [comment]
@federicocodo - You are correct. The code should be this

 ```
   class Program
    {
        static async Task Main(string[] args)
        {
           while(true) {
                System.Threading.Thread.Sleep(5000);
                Random random = new Random();
                int orderId = random.Next(1,1000);
                using var client = new DaprClientBuilder().Build();

                //Using Dapr SDK to invoke a method
                var result = client.CreateInvokeMethodRequest(HttpMethod.Get, "checkout", "checkout/" + orderId);
                await client.InvokeMethodAsync(result);
                Console.WriteLine("Order requested: " + orderId);
                Console.WriteLine("Result: " + result);
		    }
        }
    }
```
