### ISSUE TITLE
Documentation mentions wrong flag `container-runtime`

### ISSUE THREAD

**Issue by herao67** [dapr/docs#3030]
I tried to init dapr with Podman. The page https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-podman/ mentions the command `dapr init --container-runtime podman`.

When I run this command, I get back:
`Error: unknown flag: --container-runtime`

https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-podman/

**Comment by msfussell** [comment]
@herao67 - I presume podman was install onto the machine, correct? Anytime else to help repo the issue?

**Comment by pravinpushkar** [comment]
@herao67 Please verify if you are using CLI version 1.9.0. `Podman` support was added in v1.9.0 only.
Please provide more information if you are already on v1,.9.0 and podman is present in you machine.

**Comment by msfussell** [comment]
@herao67 - Pinging again for an update on this issue?

**Comment by herao67** [comment]
Sorry for the late answer, I'm swamped at work. 

Thanks for the suggestion, right, I had an old version of the CLI. After the update I now get Podman errors:

`Error: short-name resolution enforced but cannot prompt without a TTY`

I understand that I need a `registries.conf` file and I have tried creating one, but I find the Podman manual page too badly described to make any sense of it.

**Comment by msfussell** [comment]
@herao67  - Can you be more specific on what you are having difficulty with?

**Comment by pravinpushkar** [comment]
@herao67 Is your error is specific to setting up `Podman` in your environment ?
Having podman up and running is the pre-requisite to use this feature. Kindly share your `discord` handle if you have, we can talk there if there is a need.

**Comment by hhunter-ms** [comment]
@pravinpushkar It looks like this issue may have been addressed for 1.10... it also looks like the documentation might not need updated. Can I close this issue?

**Comment by hhunter-ms** [comment]
@pravinpushkar @msfussell friendly bump

> It looks like this issue may have been addressed for 1.10... it also looks like the documentation might not need updated. Can I close this issue?

**Comment by pravinpushkar** [comment]
@herao67 Would you be able to verify this with latest CLI RC release?

**Comment by herao67** [comment]
Am currently 3 weeks in holiday, will take some time.

**Comment by pravinpushkar** [comment]
> Am currently 3 weeks in holiday, will take some time.

No worries. Please feel free to re-open this thread if you face the issues again.

@hhunter-ms We can close this as fix has been provided in above linked PR - https://github.com/dapr/cli/issues/1090
