### ISSUE TITLE
[AWS DynamoDB] Documentation for Partition Key Metadata Field

### ISSUE THREAD

**Issue by robertojrojas** [dapr/docs#3037]
**What content needs to be created or modified?**
Documentation for the AWS DynamoDB Partition Key Metadata Field.

**Describe the solution you'd like**
Explain the behavior of the component when the Partition Key Metadata field is added.

**Where should the new material be placed?**
The documentation should be placed under the [DynamoDB Setup](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-dynamodb/)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
[components-contrib PR - Adds Support for Partition Key Metadata Field](https://github.com/dapr/components-contrib/pull/2389) 

**Additional context**

**Comment by msfussell** [comment]
Resolved
