### ISSUE TITLE
 Run multiple dapr apps using dapr run -f documentation

### ISSUE THREAD

**Issue by greenie-msft** [dapr/docs#3047]
**What content needs to be created or modified?**
Documentation for running multiple Dapr apps using dapr run -f

**Describe the solution you'd like**
- Scenario - why is this useful? When should I use it?
- How can I use this capability?

**Where should the new material be placed?**
Developing Applications > Local development > Dapr Run

**Comment by hhunter-ms** [comment]
@mukundansundar FYI I can help with this - I'll use info from the community call today and the proposal to get started and will reach out if I have questions or need a review
