### ISSUE TITLE
Document how to return errors when developing pluggable components

### ISSUE THREAD

**Issue by mcandeia** [dapr/docs#3049]
**What content needs to be created or modified?**
Documentation for how to return semantic state store errors when implementing a pluggable component.

**Describe the solution you'd like**
We should have a table indicating which gRPC statuscode maps to which Dapr error. Currently we only have three errors to be documented, they are:

1) ETag Mismatch error
2) ETag Invalid error
3) Bulk Delete row mismatch error

They are all from statestores and the respective gRPC error code can be found [here](https://github.com/dapr/dapr/pull/5734/files#diff-2236fa00ff0a7fa17999b95db985f32551ab33f34b9f1ba0df6bbcc3d47123ceR45-R47)

For each error the component must include specific details that helps to identify the root cause and to not mix up with others errors with the same status code, meaning that good examples would be extremely useful. 

**Where should the new material be placed?**
Somewhere close to [here](https://docs.dapr.io/operations/components/pluggable-components/), I was thinking about a section "developing pluggable components" ? It's been talking about it for a while, needs to double check.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/5734

**Additional context**

**Comment by hhunter-ms** [comment]
@mcandeia are you thinking of adding a new doc for Developing pluggable components and including how to return errors in that new doc? or just adding a section to the existing how-to/overview?

**Comment by hhunter-ms** [comment]
> @mcandeia are you thinking of adding a new doc for Developing pluggable components and including how to return errors in that new doc? or just adding a section to the existing how-to/overview?

I checked with Mark and I'll put it in the how-to for now - will tag you in PR 😄
