### ISSUE TITLE
dapr cil问题

### ISSUE THREAD

**Issue by 24KChunXiaoChen** [dapr/docs#3056]
dapr cil 在做什么呢？我看了dapr的文档，使用过程中需要使用cil此类进行程序的生命周期控制，dapr sidecar能否和主程序一同交给用户控制呢？或者dapr sidecar能否交给主程序控制生命周期，例如兼容springboot的方式，而不是现在提供的dapr java sdk一样，仅仅是进行简单封装，给每个语言独立活力使用dapr

**Comment by skyao** [comment]
Hi, @24KChunXiaoChen, 我无法完全理解你所说的事情，我们可以聊一下吗？请给我你的联系方式如电话/邮件/微信，我可以使用中文和你联系。或者通过我的手机号码 139-2220-9152 联系我，你也可以通过使用这个号码搜索到我的微信。另外我们有一个中国社区，你也可以加入进来和其他国人一起讨论。更多信息请见 https://cn.dapr.io  

非常感谢你有兴趣参与dapr。请和我取得联系。

Hi, @24KChunXiaoChen , I can't totally understand what you are talking with, so can we have a talk? Please give me your connectiion information like mobile / email / wechat, I will connect with you with Chinese. Or you can connect me by mobile 139-2220-9152, or add me wechat by searching with this mobile. And we have a Chinese Community, you can join it and discuss with Chinese people. Pleae see https://cn.dapr.io for more details.

Thank you for your interesting on Dapr. Please contact with me.

**Comment by msfussell** [comment]
Closing. Please create a new issue if needed.
