### ISSUE TITLE
Configuration Quickstart uses the --resources-path flag

### ISSUE THREAD

**Issue by marcduiker** [dapr/docs#3057]
**Describe the issue**
The Configuration Quickstart uses the `--resources-path` flag which is not yet available in Dapr 1.9 (it is part of release 1.10). 

Step 2 and Step 3 mention `--resources-path` when running the order-processor but it results in an error:

``` 
dapr run --app-id order-processor-http --resources-path ../../../components/ --app-port 7001 -- dotnet run --project .

Error: unknown flag: --resources-path
```

The incorrect flag is used across all languages of the Quickstart.

**URL of the docs**
https://docs.dapr.io/getting-started/quickstarts/configuration-quickstart/

**Expected content**
The code snippet should use the `--components-path` flag.

```
dapr run --app-id order-processor-http --components-path ../../../components/ --app-port 7001 -- dotnet run --project .
```

**Comment by msfussell** [comment]
@hhunter-ms - Looks like this crept in to 1.9 docs

**Comment by hhunter-ms** [comment]
@msfussell yep that was me, I'll fix it

**Comment by marcduiker** [comment]
@hhunter-ms There's a PR for this 😊 #3058

**Comment by hhunter-ms** [comment]
@marcduiker awesome, thanks!

**Comment by hhunter-ms** [comment]
Resolved
