### ISSUE TITLE
Update mqtt pubsub

### ISSUE THREAD

**Issue by shivamkm07** [dapr/docs#3072]
**What content needs to be created or modified?**

MQTT pubsub had `maxRetriableErrorsPerSec` metadata removed. Also mosquitto broker is not supported. This needs to be updated in docs.
**Describe the solution you'd like**

**Where should the new material be placed?**

daprdocs/content/en/reference/components-reference/supported-pubsub)/setup-mqtt.md

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/2446

**Additional context**

**Comment by msfussell** [comment]
@ItalyPaleAle - Given that you recently update the MQTT docs, could you also review this docs issue?

**Comment by ItalyPaleAle** [comment]
Also need to update the docs per https://github.com/dapr/components-contrib/pull/2467
