### ISSUE TITLE
Need other language SDK examples for state TTL usage

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3119]
In this article https://docs.dapr.io/developing-applications/building-blocks/state-management/state-store-ttl/ there needs to be examples for .NET, Java, Go and JS. Currently there is only Python example.

**Comment by shubham1172** [comment]
FYI it is still an open issue in JS-SDK, the functionality is currently unsupported https://github.com/dapr/js-sdk/issues/439

We can triage it for the upcoming release.
