### ISSUE TITLE
event type filtering with pub sub 

### ISSUE THREAD

**Issue by tunminster** [dapr/docs#3120]
There is not enough example how the pubsub route filtering works.  I try to create one. but it doesn't work.  Here is the code:

```
        [Route("orderclearing")]
	[Topic("order-pubsub", "order-create" , "event.type ==\"orderclearing\"", 1)]
	[HttpPost]
	public async Task<IActionResult> CorpartClearingAsync([FromBody]CloudEvent<Order> order)
	{
		Console.WriteLine(order.ConvertToJson());

		return Ok(await Task.FromResult(order.ConvertToJson()));
	}
```

`curl -X POST http://localhost:3501/v1.0/publish/order-pubsub/order-create -H "Content-Type: application/json" -d '{"topic":"corpart-partners","pubsubname":"corpart-pubsub","traceid":"00-113ad9c4e42b27583ae98ba698d54255-e3743e35ff56f219-01","tracestate":"","data":{"orderId":1},"id":"5929aaac-a5e2-4ca1-859c-edfe73f11565","specversion":"1.0","datacontenttype":"application/json; charset=utf-8","source":"api","type":"orderclearing","time":"2020-09-23T06:23:21Z","traceparent":"00-113ad9c4e42b27583ae98ba698d54255-e3743e35ff56f219-01"}'
`

The message doesn't arrive to the endpoint.  If I don't do event type filtering, it is working fine.   Where does it go wrong in this case?

**Comment by hhunter-ms** [comment]
@msfussell do you have any insight on this?

**Comment by ryou90** [comment]
Hi,
I have the same problem using the python sdk with grpc server. Is there any information about this?
Also missing examples (e.g. Python) how to publish a event by using a custom event type.

It looks like overriding the metadata key "cloudevent.type" will be ignored.

**Comment by hhunter-ms** [comment]
@msfussell friendly bump for insight
