### ISSUE TITLE
Update metadata for RabbitMQ Pub/Sub

### ISSUE THREAD

**Issue by shubham1172** [dapr/docs#3127]
**What content needs to be created or modified?**

The metadata for RabbitMQ must be updated with new options and deprecation notice for `host`.

**Where should the new material be placed?**

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/2129

**Additional context**

**Comment by msfussell** [comment]
This issue was missed since it was not tagged v1.10 release

**Comment by hhunter-ms** [comment]
Looks like this was resolved - closing
