### ISSUE TITLE
Wrong filepath in dapr command in quickstarts/statemanagement-quickstart/

### ISSUE THREAD

**Issue by aclevername** [dapr/docs#3156]
**Describe the issue**

Running through the steps in the quickstart section for state management https://docs.dapr.io/getting-started/quickstarts/statemanagement-quickstart/

![Screenshot 2023-02-09 at 11 21 56](https://user-images.githubusercontent.com/19669095/217799166-dcbc3dbf-7815-463f-82c8-a3b847bbe28e.png)

the last command `dapr run --app-id order-processor --components-path ../../../components -- go run .` fails, the `components` directory does not exist. I believe its meant to be the `resources` directory

![Screenshot 2023-02-09 at 11 23 12](https://user-images.githubusercontent.com/19669095/217799441-6b307286-6592-4563-a295-40bb29c22cae.png)

**URL of the docs**
https://docs.dapr.io/getting-started/quickstarts/statemanagement-quickstart/

**Expected content**
The command should reference the `resources` directory instead of the non-existing `components` directory

**Screenshots**
see above

**Additional context**
running it with `resources` instead worked:

![Screenshot 2023-02-09 at 11 24 19](https://user-images.githubusercontent.com/19669095/217799637-9ebcddff-5604-451c-a8b4-6ccd61ea30a3.png)

**Comment by hhunter-ms** [comment]
@aclevername Closing this issue as it looks like this was resolved in a PR for the 1.10 release last week: #3175
