### ISSUE TITLE
Make explicit that failing App Health Check won't remove a pod from Service Discovery

### ISSUE THREAD

**Issue by olitomlinson** [dapr/docs#3161]
https://docs.dapr.io/developing-applications/building-blocks/observability/app-health/#app-health-checks-vs-platform-level-health-checks

Make explicit here that a failing App Health check won't remove a pod from Service Discovery, and that this remains the responsibility of the kubernetes liveness probe, and NOT Dapr.

**Comment by msfussell** [comment]
Complete
