### ISSUE TITLE
graphql output binding query variable support

### ISSUE THREAD

**Issue by chadgpt-o1** [dapr/docs#3165]
**What content needs to be created or modified?**

the graphql output binding documenation needs to be modified

**Describe the solution you'd like**

i've proposed the feature to add query variables to the graphql binding in: https://github.com/dapr/components-contrib/issues/2517

and i'm required to update the documentation to detail its changes as part of the pr i've made for it:

**Where should the new material be placed?**

in the existing file

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/2522

**Comment by ItalyPaleAle** [comment]
Can you re-open this please?

**Comment by chadgpt-o1** [comment]
fyi: we had to add one more commit because the rebase against 1.11 had a bug with the binding init
