### ISSUE TITLE
Need to surface note regarding auto-generating port in the CLI documentation

### ISSUE THREAD

**Issue by davlinski** [dapr/docs#32]
Currently, the following note regarding the port parameter is in the doc for Hello World; it should also be made available in the CLI documentation.

---

**Note**:  The Actions `--port` parameter with the `run` command is optional, and if not supplied, a random available port is used.

---

**Comment by amanbha** [comment]
Closing it as this has been added https://github.com/dapr/cli/blob/master/docs/reference/dapr-run.md#flags
