### ISSUE TITLE
Document the Azure Table store 

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#320]
Azure State Table component needs documentation on usage in the contrib repot
https://github.com/dapr/components-contrib/tree/master/state/azure/tablestorage

Here
https://github.com/dapr/components-contrib/blob/master/state/Readme.md
and add new file here
https://github.com/dapr/docs/tree/master/howto/setup-state-store

**Comment by aloneguid** [comment]
I'm on it

**Comment by yaron2** [comment]
Closed by #332 and #323
