### ISSUE TITLE
Broken link in workflow architecture doc

### ISSUE THREAD

**Issue by cgillum** [dapr/docs#3203]
**URL of the docs page**
https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-architecture/#state-store-usage

**How is it currently worded?**
There is a link which wasn't rendered correctly (see below screenshot)

**How should it be worded?**
We just need to fix the link.

**Screenshots**
![image](https://user-images.githubusercontent.com/2704139/220749766-5cc094f6-763a-4343-88c6-ae426e36ddfb.png)

**Additional context**
Not sure exactly why this link didn't work correctly. Maybe because of some whitespace or use of quotes?

**Comment by hhunter-ms** [comment]
patch fix: https://github.com/dapr/docs/commit/d62bf561b354199b8781bc64ed0c4ffde0838143

**Comment by hhunter-ms** [comment]
This has been resolved
