### ISSUE TITLE
Binding quickstarts for golang says Flask 

### ISSUE THREAD

**Issue by wolvever** [dapr/docs#3207]
**Describe the issue**

Binding quickstarts for golang step3 says "The binding trigger looks for a route called via HTTP POST in your Flask application"

**URL of the docs**

https://docs.dapr.io/getting-started/quickstarts/bindings-quickstart/

**Expected content**

"The binding trigger looks for a route called via HTTP POST in your application"

**Screenshots**

**Additional context**

**Comment by berndverst** [comment]
Can you make a PR to fix it @wolvever ? :)
