### ISSUE TITLE
IDE support / Rider and Visual Studio 

### ISSUE THREAD

**Issue by laurentkempe** [dapr/docs#3214]
**What content needs to be created or modified?**
The [IDE support](https://docs.dapr.io/developing-applications/local-development/ides/) with new content for Rider and Visual Studio.

**Describe the solution you'd like**
I propose to use a part of the content I created on my blog post [Debugging Dapr applications with Rider or Visual Studio: A better way](https://laurentkempe.com/2023/02/27/debugging-dapr-applications-with-rider-or-visual-studio-a-better-way/) to create some new content.

**Where should the new material be placed?**
In https://docs.dapr.io/developing-applications/local-development/ides/

**Comment by hhunter-ms** [comment]
Hey @laurentkempe - thanks for this suggestion! Would you be able to open a PR for this?

**Comment by laurentkempe** [comment]
Hey @hhunter-ms sure thing, I will do so then when I get the time

**Comment by laurentkempe** [comment]
I think this can be closed, today I would recommend using .NET Aspire to ease debugging.
