### ISSUE TITLE
Link to preview 1.11 is broken

### ISSUE THREAD

**Issue by espenairmine** [dapr/docs#3227]
**Describe the bug**
Dropdown on front page, top right leads to broken empty page when selecting 1.11 preview

**Steps to reproduce**
See attached screenshot

**Expected behavior**
Link should go to new page

**Screenshots**

**Desktop (please complete the following information):**
Chome, Win11, Desktop

**Additional context**

![Screenshot 2023-03-02 231039](https://user-images.githubusercontent.com/51234981/222570471-480051b8-ef7b-49f8-9c46-5a537938fae7.png)
![Screenshot 2023-03-02 231144](https://user-images.githubusercontent.com/51234981/222570690-13facbec-6766-474d-86fb-2caf44afcb08.png)

**Comment by hhunter-ms** [comment]
Resolved with dapr/docs#3234
