### ISSUE TITLE
Duplicate content in workflow doc

### ISSUE THREAD

**Issue by XiaoyuanDu** [dapr/docs#3228]
**URL of the docs page**

https://docs.dapr.io/developing-applications/building-blocks/workflow/howto-author-workflow/#author-workflows-as-code

**How is it currently worded?**

The Dapr sidecar doesn’t load any workflow definitions. Rather, the sidecar simply drives the execution of the workflows, leaving all the workflow activities to be part of the application. The Dapr sidecar doesn’t load any workflow definitions. Rather, the sidecar simply drives the execution of the workflows, leaving all the workflow activitie to be part of the application.

**How should it be worded?**

The Dapr sidecar doesn’t load any workflow definitions. Rather, the sidecar simply drives the execution of the workflows, leaving all the workflow activities to be part of the application. 

**Screenshots**

**Additional context**

Duplicate Content

**Comment by hhunter-ms** [comment]
Resolved with dapr/docs#3223
