### ISSUE TITLE
Add reconnectWaitInSeconds metadata for rabbitmq binding

### ISSUE THREAD

**Issue by Taction** [dapr/docs#3235]
**Describe the solution you'd like**
Add reconnectWaitInSeconds metadata for rabbitmq binding.

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/2565

**Additional context**

**Comment by ItalyPaleAle** [comment]
This can be clsed as completed
