### ISSUE TITLE
ConsumerID is missing from the metadata for each pub/sub component

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3241]
**What content needs to be created or modified?**
By default when using a pub/sub component a consumer ID is created for a component based on the appID. However there are times when you have an existing queue or broker and you want to use that name instead. 
This is set via the `ConsumerID` metadata field. This should be included into each of the pub/sub doc.

For example for AWS SQS

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: snssqs-pubsub
spec:
  type: pubsub.snssqs
  version: v1
  metadata:
    - name: accessKey
      value: "AKIAIOSFODNN7EXAMPLE"
    - name: secretKey
      value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    - name: region
      value: "us-east-1"
    - name: ConsumerID
      value: "MyQueue1"

**Describe the solution you'd like**
Ensure the ConsumerID is described in each pub/sub component and that ConsumerID is the metadata table for each component

**Where should the new material be placed?**
Ensure the ConsumerID is described in each pub/sub component here https://docs.dapr.io/reference/components-reference/supported-pubsub/ Although we can also do the approach of describing it here 
https://docs.dapr.io/operations/components/setup-pubsub/ in the overall component file. However this will still be hidden.

**Comment by alicejgibbons** [comment]
ConsumerID should work for all components but Kafka v1 has deprecated it in favour of `ConsumerGroup` as per [docs](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/#spec-metadata-fields).

Setting `ConsumerID` in the component will give the following deprecation warning (Dapr 1.10.2):

``` bash
ConsumerID is deprecated, if ConsumerID and ConsumerGroup are both set, ConsumerGroup is used" app_id=order-service component="oms.pubsub (pubsub.kafka/v1)"
```

**Comment by hhunter-ms** [comment]
this has been resolved
