### ISSUE TITLE
Need clarification about what are considered "retryable" errors.

### ISSUE THREAD

**Issue by darraghjones** [dapr/docs#3244]
**What content needs to be created or modified?**
The docs say that "Dapr provides default retries for certain request failures and transient errors."
However, I cannot find any documentation about that are considered "retryable" errors.

**Describe the solution you'd like**
Clarification on what types of errors are automatically retried by Dapr, and which errors I need to handle myself in application code.

**Where should the new material be placed?**
https://docs.dapr.io/operations/resiliency/policies/#retries

**Additional context**
I'm using the .Net SDK if that's relevant.

**Comment by hhunter-ms** [comment]
@darraghjones I'll clarify in the docs as well, but wanted to respond here: at the moment, retry-able errors are considered any non-successful request.
