### ISSUE TITLE
Add to the PubSub Pulsar Component a paragraph about storing sensitive information, such as tokens, in Kubernetes Secrets

### ISSUE THREAD

**Issue by hugosmitter** [dapr/docs#3250]
**What content needs to be created or modified?**

The PubSub Pulsar Component 

**Describe the solution you'd like**

Add a warning like the one shown in [Azure Service Bus Topics](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-topics/) for the "token" parameter and any other sensitive parameter added in the future indicating that this Component supports storing that sensitive data as Kubernetes Secrets.

**Where should the new material be placed?**

[Pulsar Detailed documentation on the Pulsar pubsub component](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-pulsar/)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by hhunter-ms** [comment]
@hugosmitter take a look at my PR and let me know if this works?
