### ISSUE TITLE
Add document for  kitex  output binding

### ISSUE THREAD

**Issue by songoow** [dapr/docs#3266]
**What content needs to be created or modified?**
 
add document to describes how to use kitex output binding

**Describe the solution you'd like**
 

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

 https://github.com/dapr/components-contrib/pull/2563

**Additional context**

**Comment by berndverst** [comment]
@liu-song can you open the documentation PR for the Kitex binding please?

**Comment by songoow** [comment]
Okay, I will complete the introduction of the Kitex binding PR within a week.
 
5.10 : update,will submit a PR this weekend .
