### ISSUE TITLE
Wrong info on pub/sub for .NET

### ISSUE THREAD

**Issue by roozbehid-ic** [dapr/docs#3268]
**Describe the issue**
Code sample for .NET does not make sense.
Topic is about programmatic way of subscribing but code is about `checkout` endpoint.
Based on python code, it seems it should be an endpoint like `subscription` that implements a way to return name of topics.
Also initially reading this I get the feeling that it is also dynamic (as programmatic ways are usually dynamic). But it seems it is only read once during application startup(? or maybe not...I dont know...).
I think those details should be noted here too.

**URL of the docs**
[Subscription methods](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/)

**Expected content**
Fix code samples. Seems only python code is correct and others are wrong.

**Screenshots**

**Additional context**

**Comment by halspang** [comment]
@roozbehid-ic - Thanks for opening this issue.

The .NET SDK does describe how to make that endpoint, it's the last part of the code snippet:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/70976921/225749671-1d745a7c-8478-495b-91ab-4ad5c9e54863.png">

Each of the SDKs implements this behavior with the paradigms appropriate to that language. In .NET, this is using attributes which are examined by the SDK and compiled into that endpoint at runtime.

> But it seems it is only read once during application startup

This is true and is part of the Dapr runtime design. In this case programmatic simply means defined in code as opposed to set in a CRD.

@hhunter-ms, if this isn't clear it should be captured in the overall docs for pubsub, not in the language specific sections so I think it would warrant a separate issue.

**Comment by hhunter-ms** [comment]
closing due to opening separate issue - let me know if I should reopen this one
