### ISSUE TITLE
Add document for etcd state store

### ISSUE THREAD

**Issue by taenyang** [dapr/docs#3270]
**What content needs to be created or modified?**
Add document to describe how to use etcd state store

**Describe the solution you'd like**
* [x] CRUD
* [x] Transactional
* [x] ETag
* [x] TTL
* [x] Actors
* [ ] Query

**Where should the new material be placed?**
https://github.com/dapr/docs/tree/v1.11/daprdocs/content/en/reference/components-reference/supported-state-stores

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/2671

**Comment by msfussell** [comment]
Added https://v1-11.docs.dapr.io/reference/components-reference/supported-state-stores/setup-etcd/
