### ISSUE TITLE
Dotnet SDK needs documentation on the use of DataContractSerializer

### ISSUE THREAD

**Issue by MattCosturos** [dapr/docs#3276]
**What content needs to be created or modified?**
An explanation of how Dapr dotnet sdk is serializing data for actor to actor invocations.
 
**Describe the solution you'd like**
A documentation page stating that dotnet sdk is using DataContractSerializer. bonus points if there are examples on how to make a custom DataContractSerializer for a complex model.

**Where should the new material be placed?**
Somewhere on the dotnet sdk documentation pages.

**Additional context**

**Comment by hhunter-ms** [comment]
this is in the .NET SDK docs - closing
