### ISSUE TITLE
Install Dapr CLI page, dapr command does nothing by default

### ISSUE THREAD

**Issue by riverar** [dapr/docs#3287]
**URL of the docs page**
https://docs.dapr.io/getting-started/install-dapr-cli/

**How is it currently worded?**
Verify the CLI is installed by restarting your terminal/command prompt and running the following:
`dapr`

**How should it be worded?**
Verify the CLI is installed by restarting your terminal/command prompt and running the following:
`dapr -h`

**Screenshots**
![image](https://user-images.githubusercontent.com/475132/227380381-57020925-9cf0-4502-8172-a1ea86416960.png)

**Comment by msfussell** [comment]
Fixed
