### ISSUE TITLE
Bing is returning archived versions of Dapr Docs

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#3288]
## Steps to recreate

1. Search bing for "dapr vscode extension"
2. See v1.2 result as first option
<img width="514" alt="image" src="https://user-images.githubusercontent.com/54363786/227623249-1cfcad91-878a-4a9c-8269-745b2273de63.png">

Doesn't appear to be an issue with Google

## Recommended steps

Add a robots.txt to the root of the site, with:

```txt
User-agent: *
Allow: /$
Disallow: /
```

This will allow searches to "Dapr v1.2" but nothing else within the site

**Comment by hhunter-ms** [comment]
closing - resolved
