### ISSUE TITLE
Quickstart: Service Invocation using .NET does not show expected results

### ISSUE THREAD

**Issue by xtu** [dapr/docs#3296]
**Describe the issue**
Following the Quickstart: Service Invocation using .NET samples, the `order-processor` does not print any message.

**URL of the docs**
https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/

**Expected content**
The `order-processor` should print out messages like `Order received: { order: 1 }`

**Screenshots**
![image](https://user-images.githubusercontent.com/264364/228375556-33139e01-b4e5-4d20-a7d0-bdfaa47f372e.png)

**Additional context**
Note the Javascript example works fine.

**Comment by xtu** [comment]
Found the root cause. The command to run Dapr specifies 7001 as the app port

![image](https://user-images.githubusercontent.com/264364/228377565-38858c5f-8cde-4074-8e1b-3b49f976858b.png)

But the app is configured to listen to port 7006 in properties/launchSettings.json.

![image](https://user-images.githubusercontent.com/264364/228377637-59ae03d1-e924-4030-86cc-a128d6c0595b.png)

**Comment by hhunter-ms** [comment]
closing - resolved by @JaimeStill in the quickstart and quickstart runs successfully
