### ISSUE TITLE
Install the Dapr CLI for Windows, Step 2 argument missing.

### ISSUE THREAD

**Issue by VladimirTitkovEpam** [dapr/docs#3298]
**Describe the issue**
In text

> Step 2: Verify the installation
> Verify the CLI is installed by restarting your terminal/command prompt and running the following:
> 
> dapr
> 

It should be `dapr --help` instead of `dapr`

**URL of the docs**
https://docs.dapr.io/getting-started/install-dapr-cli/

**Expected content**

> Step 2: Verify the installation
> Verify the CLI is installed by restarting your terminal/command prompt and running the following:
> 
> dapr --help

**Screenshots**
![image](https://user-images.githubusercontent.com/118997978/228505593-75f6fade-8306-4a4a-b15c-e2d931f785ef.png)

![image](https://user-images.githubusercontent.com/118997978/228505758-d59d9f13-dde4-4940-bd47-cf9f5ce0e432.png)

**Additional context**
n/a

**Comment by msfussell** [comment]
Complete
