### ISSUE TITLE
Not able to add custom environment variables in Multi-App Run template

### ISSUE THREAD

**Issue by sebastianwessel** [dapr/docs#3304]
**Describe the issue**
The example mentioned, how to add environment variables in Multi-App Run template.

```yaml
env:
      - DEBUG: false
```

This is not working: `Incorrect type. Expected "string".yaml-schema`

**URL of the docs**
[https://docs.dapr.io/developing-applications/local-development/multi-app-dapr-run/multi-app-template/](https://docs.dapr.io/developing-applications/local-development/multi-app-dapr-run/multi-app-template/)

**Expected content**
It should be possible to add custom environment variables via config

**Comment by msfussell** [comment]
@mukundansundar - Could you take a look at this?

**Comment by hhunter-ms** [comment]
@mukundansundar friendly bump

**Comment by mukundansundar** [comment]
@sebastianwessel This is currently possible. 
But the value should be given as 
```
env:
  DEBUG: false
```
see #3778

**Comment by sebastianwessel** [comment]
Ahhh, yes.
I've seen the linked issue.
I was stupidly copy&paste the example.
Than you can close the issue.

Thanks @mukundansundar

**Comment by mukundansundar** [comment]
closing in favor of #3778
