### ISSUE TITLE
[Bulk Subscribe] Need Python non-SDK code snippet

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3321]
**What content needs to be created or modified?**
Python SDK example of bulk subscribe

**Where should the new material be placed?**
https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-bulk/#example-1

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
dapr/python-sdk#464

**Comment by hhunter-ms** [comment]
@berndverst would you be able to provide a python example for bulk subscribe?

**Comment by hhunter-ms** [comment]
updated title to reflect that the bulk publish example in the linked how-to is non-SDK python, so will try and provide a bulk subscribe non-SDK python example as well.

**Comment by hhunter-ms** [comment]
@DeepanshuA since you worked on the Bulk Subscribe docs for 1.10, would you be able to provide a non-SDK Python example for bulk subscribe?

**Comment by alicejgibbons** [comment]
To clarify, we currently do not support the bulk pubsub feature in the python sdk and so these docs are for the HTTP version of the bulk pubsub feature.
