### ISSUE TITLE
Wrong helm value for disable PV for prometheus alertmanager

### ISSUE THREAD

**Issue by owenchenxy** [dapr/docs#3324]
**Describe the issue**
There was a mistake in the docs about prometheus installation without PV
```
helm install dapr-prom prometheus-community/prometheus -n dapr-monitoring
 --set alertmanager.persistentVolume.enable=false --set pushgateway.persistentVolume.enabled=false --set server.persistentVolume.enabled=false

```

**URL of the docs**
https://docs.dapr.io/operations/monitoring/metrics/prometheus/#install-prometheus

**Expected content**
the value to control PV of alertmanager should be `alertmanager.persistence.enabled` rather than `alertmanager.persistentVolume.enable`
```
helm install dapr-prom prometheus-community/prometheus -n dapr-monitoring
 --set alertmanager.persistence.enabled=false --set pushgateway.persistentVolume.enabled=false --set server.persistentVolume.enabled=false
```

**Comment by owenchenxy** [comment]
I raised a PR for this issue https://github.com/dapr/docs/pull/3325

**Comment by msfussell** [comment]
Resolved
