### ISSUE TITLE
Update docs for HTTP binding for HTTPS support

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/docs#3330]
**What content needs to be created or modified?**

-> Add content for HTTPS binding using metadata option
-> Modify document to include secret store reference for fetching certs

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
@pravinpushkar - Can you add details and a link to the issue here? What is this issues referring to?

**Comment by pravinpushkar** [comment]
Related Issue - https://github.com/dapr/components-contrib/issues/2765
Feature PR is merged

I will create the docs PR shortly.

**Comment by pravinpushkar** [comment]
milestone should be 1.11 @msfussell  ?

**Comment by msfussell** [comment]
Complete
