### ISSUE TITLE
Update Configuration API to stable

### ISSUE THREAD

**Issue by shivamkm07** [dapr/docs#3342]
**What content needs to be created or modified?**
With Dapr 1.11, Dapr Configuration API is moving to stable.https://github.com/dapr/dapr/issues/5522
And so the docs need to be updated with all the required changes. This issue is to track all the required items:
1. Update API endpoints from `v1.0-alpha1` to `v1.0`
    a. https://github.com/dapr/dapr/pull/6251
3. Mark Configuration Store components `Redis` and `Postgres` as stable
   a. https://github.com/dapr/components-contrib/pull/2744
   b. https://github.com/dapr/components-contrib/pull/2431
4. Update postgres component spec:
    a. For `table` metadata specify that table must be lowercased table name: https://github.com/dapr/components-contrib/pull/2740
5. Update redis component spec:
    a. `redisDB` metadata is added: https://github.com/dapr/components-contrib/pull/2415
    b. Generic Redis metadata is added: https://github.com/dapr/components-contrib/pull/2807
4. https://github.com/dapr/docs/blob/v1.10/daprdocs/content/en/developing-applications/building-blocks/configuration/howto-manage-configuration.md Update to include Get, subscribe and unsubscribe using HTTP
6. In case of multiple versions in config store, `Get` returns the latest `numeric` version. It needs toe be added in documentation: https://github.com/dapr/components-contrib/pull/2740

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by shivamkm07** [comment]
@dapr/maintainers-docs This issue needs to be added to 1.11 milestone

**Comment by msfussell** [comment]
@shivamkm07 - Please check this is complete and then close this issue. Thx
