### ISSUE TITLE
Documented "Getting Started" dapr commands are incorrect in Windows 11

### ISSUE THREAD

**Issue by BillEisenman** [dapr/docs#3345]
**Describe the issue**
Many of the commands specified do not work on Windows 11.
Specifically,
(1) The command: dapr -h should be the following: .\dapr -h
(2) The command: dapr int should be the following: .\dapr init
(3) Many other commands which expect the dapr.exe need the .\ preceding the dapr command call, i.e. .\dapr --version
**URL of the docs**
https://docs.dapr.io/getting-started/install-dapr-cli/ 
and
https://docs.dapr.io/getting-started/install-dapr-selfhost/

**Expected content**
I expected the Listed Commands to Work as Written, which is not the case.

**Screenshots**
(1) ![image](https://user-images.githubusercontent.com/51295461/232965658-3fe5c405-2b83-4c47-9f30-6ff642ed6fb8.png)
(2) ![image](https://user-images.githubusercontent.com/51295461/232966045-9aff5a30-aee2-4a5d-9ebb-5236214765bf.png)

**Additional context**

**Comment by msfussell** [comment]
@BillEisenman - When you say Windows 11 you are running this with WSL correct? This is a Linux command prompt rather than a Windows command prompt correct? Which way did you install Dapr onto you machine?

**Comment by hhunter-ms** [comment]
@BillEisenman friendly bump

**Comment by hhunter-ms** [comment]
closing for now. let me know if we should reopen.
