### ISSUE TITLE
Update Actor Types in WF Docs

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/docs#3346]
**What content needs to be created or modified?**
Need to update Actor Types used in Workflow after https://github.com/dapr/dapr/pull/6192: https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-architecture/#internal-workflow-actors

**Describe the solution you'd like**
It should specify the Actor Types for WF and Activity, as per the dapr PR, once it is merged.

**Where should the new material be placed?**
https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-architecture/#internal-workflow-actors

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/6192

**Additional context**

**Comment by hhunter-ms** [comment]
Addressed in #3372

**Comment by cgillum** [comment]
Can this issue be closed now that #3372 is merged?
