### ISSUE TITLE
Can't connect to postgresql

### ISSUE THREAD

**Issue by martur-miarczynski** [dapr/docs#3348]
I followed the steps from the tutorial and I can connect to Postgres SQL using Postrges CLI as described in the tutorial but when I run the application with:
dapr run --app-id batch-sdk --app-port 7002 --resources-path ../../../components -- dotnet run
It fails when it tries to open a connection to db with the following error:
== APP == Processing batch..
== APP == insert into orders (orderid, customer, price) values (1, 'John Smith', 100.32);
== APP == fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
== APP ==       An unhandled exception has occurred while executing the request.
== APP ==       Dapr.DaprException: Binding operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==        ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="error invoking output binding sqldb: error executing insert into orders (orderid, customer, price) values (1, 'John Smith', 100.32); with error executing insert into orders (orderid, customer, price) values (1, 'John Smith', 100.32);: failed to connect to `host=localhost user=postgres database=orders`: failed to receive message (AuthTypeSSPI is unimplemented): error executing insert into orders (orderid, customer, price) values (1, 'John Smith', 100.32);: failed to connect to `host=localhost user=postgres database=orders`: failed to receive message (AuthTypeSSPI is unimplemented)")
== APP ==          at Dapr.Client.DaprClientGrpc.MakeInvokeBindingRequestAsync(String name, String operation, ByteString data, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==          --- End of inner exception stack trace ---
== APP ==          at Dapr.Client.DaprClientGrpc.MakeInvokeBindingRequestAsync(String name, String operation, ByteString data, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==          at Dapr.Client.DaprClientGrpc.InvokeBindingAsync[TRequest](String bindingName, String operation, TRequest data, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==          at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in C:\Pety\Dapr\quickstarts\bindings\csharp\sdk\batch\program.cs:line 48
== APP ==       --- End of stack trace from previous location ---
== APP ==          at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
== APP ==          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

**Comment by msfussell** [comment]
@martur-miarczynski - Any updates on this? A better place is to ask this on the state management Discord channel. Thx
@ItalyPaleAle  - Could you take a look?

**Comment by msfussell** [comment]
@martur-miarczynski - Closing this isssue. Please reopen if you have new information. Thx
