### ISSUE TITLE
v1.11: HTTP Binding: Document `mtlsRenegotiation` metadata option

### ISSUE THREAD

**Issue by berndverst** [dapr/docs#3368]
Please document `mtlsRenegotiation` metadata option (and allowed values) for the HTTP Binding. This must be done in the v1.11 branch of the docs.

PR Author: @mdarii
PR: https://github.com/dapr/components-contrib/pull/2822

Should be done here:
https://github.com/dapr/docs/blob/v1.11/daprdocs/content/en/reference/components-reference/supported-bindings/http.md

**Comment by msfussell** [comment]
Completed
