### ISSUE TITLE
State Time-to-Live (TTL) - sample for .Net not correct and misplaced

### ISSUE THREAD

**Issue by thuwas** [dapr/docs#3371]
**Problem**
1. The C# .Net code sample is misplaced 
2. The dictionary key ("metadata.ttlInSeconds") is not correct

**URL of the docs**
[](https://docs.dapr.io/developing-applications/building-blocks/state-management/state-store-ttl/)

**Expected content**
`
using Dapr.Client;

// code

await client.SaveStateAsync(storeName, stateKeyName, state, metadata: new Dictionary<string, string>() { 
    { 
        "ttlInSeconds", "120" 
    } 
});`

**Screenshots**
![image](https://user-images.githubusercontent.com/41892235/235558870-03c137c5-1511-420b-aba2-45ccd5d4f4e6.png)
![image](https://user-images.githubusercontent.com/41892235/235559055-efb2fcef-42f4-43ce-acaf-bc0c428f805f.png)

**Additional context**

Related to https://github.com/dapr/docs/issues/3442

**Comment by msfussell** [comment]
@thuwas - Would you be able to push a PR suggestions?
For 1) this has been fixed here it looks like https://docs.dapr.io/developing-applications/building-blocks/state-management/state-store-ttl/
For 2 you are referring to the position of the brackets correct? The code still compiles, this is just a formatting issue, yes?

This would also be an alternative way for this code. Would this be better?

```
using Dapr.Client;
public class Program
{
    static async Task Main(string[] args)
    {
        using var client = new DaprClientBuilder().Build();
        var metadata = new Dictionary<string, string>
        {
            { "key1", "value1" },
            { "key2", "value2" }
        };
        await client.SaveStateAsync(storeName, stateKeyName, state, metadata);
    }
}
```

**Comment by hhunter-ms** [comment]
@thuwas friendly bump - would Mark's alternative example above be better for the docs?

**Comment by thuwas** [comment]
@hhunter-ms @msfussell 
Issue 1 is fixed.

Issue 2, could you please change line 80 to        ` "ttlInSeconds", "120" ` in  the following file: https://github.com/dapr/docs/blob/v1.11/daprdocs/content/en/developing-applications/building-blocks/state-management/state-store-ttl.md

I am unable to push the changes from my side.

**Comment by hhunter-ms** [comment]
@thuwas thanks for your clarification! could you review my PR to fix this? ^^

**Comment by thuwas** [comment]
review done
