### ISSUE TITLE
More examples around Publishing your own CloudEvents

### ISSUE THREAD

**Issue by opinionmachine** [dapr/docs#3373]
**What content needs to be created or modified?**
![image](https://user-images.githubusercontent.com/1327518/235685204-dd2caf0d-1d15-4cbe-85a0-ceea584650bd.png)
So - the json payload in the CLI example above is not a CloudEvent payload. 

What do you mean with the text 
> If you want to use your own CloudEvent, make sure to specify the [datacontenttype](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#setting-message-content-types) as application/cloudevents+json

Let's say I want to boil the ocean to maintain DAPR compat and bin ApplicationProperties in Azure ServiceBus and instead start publishing CloudEvents with Extensionattributes so that I can consume those in DAPR instead.

How/what do I do then? 

**Describe the solution you'd like**

I would like a paragraph on how you publish a CloudEvents payload that can be consumed by a subscriber including ExtensionAttributes so that I can know how to publish cloudevents properly using DAPR. 

**Where should the new material be placed?**

It could replace the bit I screenshotted. 
**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by hhunter-ms** [comment]
This has been resolved. If you feel this needs more work, feel free to reopen or open a new issue.
