### ISSUE TITLE
Broken link to distributed_tracing.md (from best-practices/troubleshooting/tracing.md)

### ISSUE THREAD

**Issue by davlinski** [dapr/docs#34]
Inside of `best-practices/troubleshooting/tracing.md` there is a link to `https://github.com/dapr/docs/blob/master/best-practices/distributed_tracing.md`

I don't see this doc (distributed_tracing.md) anywhere in this repository.

**Comment by shaggygi** [comment]
Looks like this was fixed with https://github.com/dapr/docs/pull/54.  Can now close?
