### ISSUE TITLE
Need Dapr Resources Reference section

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3400]
Based on adding the new HTTPEndpoint resource type being added as part of this docs PRhttps://github.com/dapr/docs/pull/3384 , there need to be a resources schema section under reference that describe the resources available. These

1) Resiliency Policy Schema
2) Subscription Schema
3) HTTPEndpoint Schema
4) Configuration Schema

Each of these can reference their sections, but there needs to be a clear schema on what can be applied (just like the component schema here https://v1-11.docs.dapr.io/operations/components/component-schema/)

**Comment by hhunter-ms** [comment]
#3434 - related issue
