### ISSUE TITLE
Kubernetes installation of Prometheus lacks information about pre-requisites for using the DAPR dashboards for Grafana

### ISSUE THREAD

**Issue by alexmarshall132** [dapr/docs#3409]
**What content needs to be created or modified?**

The Grafana Dashboards for DAPR are extremely useful and they leverage metrics stored in Prometheus. Documentation around the pre-requisites for successfully using the Dashboards is lacking and should be added to improve the user's experience when getting started with monitoring DAPR-ized application.

**Describe the solution you'd like**

Information about the following should be added:
* Explicit listing of the requirements for getting the Grafana Dashboards for DAPR working, specifically (but limited to):
  * The requirement for a Prometheus datasource in Grafana named "Dapr". The existing walkthrough steps name the Prometheus datasource `Dapr`, but don't call out the requirement for this name in order to be able to use the Grafana Dashboards out of the box.
  * The requirement for either of the following in a Kubernetes-based installation:
    * For the traditional Prometheus install, the presence of Pod and Service scrapers (with examples) that will ensure the DAPR pods and services get scraped for metrics to be collected in Prometheus.
    * For the Operator install of Prometheus, the presence of `PodMonitor`s and `ServiceMonitor`s for monitoring DAPR pods and services.

**Where should the new material be placed?**

* [The Prometheus installation page in the DAPR docs](https://docs.dapr.io/operations/monitoring/metrics/prometheus/)
* [The Grafana Dashboards page in the DAPR docs](https://docs.dapr.io/operations/monitoring/metrics/grafana/)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

N/A

**Additional context**

**Comment by alexmarshall132** [comment]
Examples of Pod and Service scrapers can be found here with the names `kubernetes-pods` and `kubernetes-services`:

https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-kubernetes.yml

**Comment by msfussell** [comment]
@alexmarshall132 Would you consider pushing a docs PR to help with this content? Thx

**Comment by observability-guy** [comment]
I would endorse @alexmarshall132 's comment. 

When creating a new Prometheus Data Source in Grafana the name defaults to 'Prometheus' and I think it would be useful to add some detail as to the rationale for changing this to 'Dapr' - which, at first sight, appears to be a less intuitive option.

**Comment by hhunter-ms** [comment]
@alexmarshall132 following up to see if you can work on a docs PR for this?

**Comment by alexmarshall132** [comment]
> @alexmarshall132 following up to see if you can work on a docs PR for this?

@hhunter-ms Yes, I'll work on a docs PR for this, as soon as I've familiarized myself with this project's branching and PR processes.

**Comment by hhunter-ms** [comment]
> > @alexmarshall132 following up to see if you can work on a docs PR for this?
> 
> @hhunter-ms Yes, I'll work on a docs PR for this, as soon as I've familiarized myself with this project's branching and PR processes.

@alexmarshall132 let me know if you have any questions, I'm happy to help!

**Comment by alexmarshall132** [comment]
New material has already been added, closing this issue.
