### ISSUE TITLE
What is "insecure SSL"?

### ISSUE THREAD

**Issue by JohnVottero** [dapr/docs#3414]
**Describe the issue**
The documentation says:

"If your app uses an SSL connection, you can tell Dapr to invoke your app over an insecure SSL connection with the app-ssl: "true" annotation (full list [here](https://docs.dapr.io/reference/arguments-annotations-overview/))"

What is an "insecure SSL connection"? Does that mean not using SSL? If so, isn't this statement backwards? I think app-ssl: "true" tells Dapr to use SSL which would be secure, right?

**URL of the docs**
https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/

**Expected content**

I think that using app-ssl: "true" means to use SSL which is secure and app-ssl: "false" means don't use SSL which is insecure.

**Comment by yaron2** [comment]
It means communications happen on an encrypted channel (with `app-ssl: true`) however certificate verification is disabled.

**Comment by JohnVottero** [comment]
Isn't an encrypted channel secure? The documentation says "...over an insecure SSL connection...". Shouldn't that be "...over a secure SSL connection..." (secure instead of insecure)?

**Comment by yaron2** [comment]
> Isn't an encrypted channel secure? The documentation says "...over an insecure SSL connection...". Shouldn't that be "...over a secure SSL connection..." (secure instead of insecure)?

Well, it's more about the skipped certificate verification that makes this insecure, not the encryption on the wire. I agree this text could use a refinement.

**Comment by ItalyPaleAle** [comment]
I've included tweaked wording on #3428 since it was touching those sentences already.

**Comment by msfussell** [comment]
Completed
