### ISSUE TITLE
Add docs for configurable destination of logs multi-app run

### ISSUE THREAD

**Issue by mukundansundar** [dapr/docs#3424]
**What content needs to be created or modified?**

Based on https://github.com/dapr/cli/pull/1258

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
Update
- https://docs.dapr.io/developing-applications/local-development/multi-app-dapr-run/multi-app-overview/
- https://docs.dapr.io/developing-applications/local-development/multi-app-dapr-run/multi-app-template/

And this Quickstart including the code
https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/#step-5-use-with-multi-app-run

**Comment by hhunter-ms** [comment]
@mukundansundar friendly bump

**Comment by msfussell** [comment]
Fixed
