### ISSUE TITLE
Incomplete step by step solution to deploy RabbitMQ with Dapr to kubernetes

### ISSUE THREAD

**Issue by andv15** [dapr/docs#3436]
**Describe the issue**
The documentation is incomplete. I tried to setup a .NET consumer and publisher using DAPR and RabbitMQ deployed to Kubernetes, but the exchange is not created and the communication is broken. However I managed to test in standalone mode locally.

**URL of the docs**

**Expected content**

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
@andv15 - Can you add some more details on what issues you ran into, which docs topic and where we can make this better? You input would be appreciated here. Thanks

**Comment by hhunter-ms** [comment]
@andv15 Following up on this - is this in reference to the [How to: Publish & Subscribe](https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe) doc? How can we help resolve this in the docs?

**Comment by msfussell** [comment]
@andv15 - Please reopen with any new details to help debug this issue
