### ISSUE TITLE
Cryptography overview diagram

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3455]
Need a diagram for cryptography overview doc.

**Comment by hhunter-ms** [comment]
#3216 
#3319

**Comment by ItalyPaleAle** [comment]
Attached a proposed diagram 
[Dapr crypto building block diagram v1.pptx](https://github.com/dapr/docs/files/11578528/Dapr.crypto.building.block.diagram.v1.pptx)

**Comment by msfussell** [comment]
Also need to update the Overview component diagram in this issue based on feedback on the Crypto PR https://github.com/dapr/docs/pull/3319

**Comment by hhunter-ms** [comment]
Added this diagram to #3319 and updated the JWKS logo
