### ISSUE TITLE
Include a list of the alpha APIs and when they were introduced

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3458]
This table should be included into a new topic called "Alpha APIs" under the support topic https://docs.dapr.io/operations/support/ after preview features topic

| API | Description | Documentation | Version introduced |
| ------------------ | --- | --- | --- |
| v1.0-alpha1/state/statestore/query | The state query API, enables you to retrieve, filter, and sort the key/value data stored in state store components. **This API will deprecated in a future release** | [query state API]({{<ref "howto-state-query-api/" >}}) |  v1.5 |
| /v1.0-alpha1/lock| The distributed lock API enables you to take a lock on a resource | [distributed lock API]({{<ref "distributed-lock-api-overview" >}}) |  v1.8 
| /v1.0-alpha1/workflow | The workflow API enables you to define long running, persistent processes or data flows | [workflow API]({{<ref "workflow-overview/" >}}) |  v1.10 |
| v1.0-alpha1/publish/bulk | The bulk publish and subscribe API allows you to publish multiple messages to a topic in a single request | [bulk publish and subscribe API]({{<ref "pubsub-bulk/" >}}) |  v1.10 |
| v1.0-alpha1/crypto | The cryptography API enables you to perform operations for encrypting and decrypting messages | [cryptography API]({{< ref "cryptography-overview.md" >}})) |  v1.11 |

**Comment by mukundansundar** [comment]
This is only including HTTP APIs. Should we instead include the Building Block/API name and the APIs for both gRPC and HTTP?

**Comment by msfussell** [comment]
Yes, feel free to add a gRPC column into the table.
