### ISSUE TITLE
With the removal of the dashboard Helm examples needed

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3483]
Need docs for https://github.com/dapr/dapr/issues/4724

Need to
1) Update the CLI docs https://docs.dapr.io/reference/cli/dapr-dashboard/ to add the `init` command
2) Add an example with the `dapr init -k` cli to add the dashboard here https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/#install-dapr-from-an-official-dapr-helm-chart
3) Add an example to install dashboard with Helm here https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/#add-and-install-dapr-helm-chart

Anything else that should be included in the docs that people should know about?

**Comment by artursouza** [comment]
Dashboard is installed automatically via Dapr cli init. Cli Will install dashboard with the new helm automatically.

Only when using helm that the dashboard needs to be installed separately. Same steps as for Dapr, but the helm chart is called dapr-dashboard instead of dapr.
