### ISSUE TITLE
[Workflow] Add python to patterns doc

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3496]
**What content needs to be created or modified?**
Add Python tab to patterns doc

**Where should the new material be placed?**
https://v1-11.docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/

**Comment by msfussell** [comment]
@hhunter-ms Also need to update the supported SDKs here https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#workflow-sdks to include python

**Comment by hhunter-ms** [comment]
> @hhunter-ms Also need to update the supported SDKs here https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#workflow-sdks to include python

looks like this was already added for 1.11: https://v1-11.docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#supported-sdks

**Comment by hhunter-ms** [comment]
Just noticed the python-sdk doc PR - reopened to track that

**Comment by hhunter-ms** [comment]
dapr/python-sdk#575

**Comment by cgillum** [comment]
https://github.com/dapr/python-sdk/pull/575 has been merged. I think we're good to close this now.

**Comment by msfussell** [comment]
@cgillum - Thanks. Closing
