### ISSUE TITLE
Broken links in concepts/actor/enable_actor_pattern.md

### ISSUE THREAD

**Issue by davlinski** [dapr/docs#35]
There is a link to `../concepts/actor/actor_pattern.md` should be `actor_pattern.md`

Ther is another link to: `[reliable messaging](TBD)` which needs to be defined.

**Comment by RicardoNiepel** [comment]
concepts/actor/actor_pattern.md not there anymore - closing this one?

**Comment by yaron2** [comment]
Yes, thanks.
