### ISSUE TITLE
[RabbitMQ] use metadata from request as header of the published message

### ISSUE THREAD

**Issue by robert-oh** [dapr/docs#3503]
**What content needs to be created or modified?**
RabbitMQ message header values can be used to set additional metadata on a message, e.g. a label or message id like in Azure ServiceBus' message properties. The metadata can already be defined when creating the message, but till these values are not set on the enqueued message and only define e.g. the priority, TTL ...

**Describe the solution you'd like**
The passed in metadata values should also be available on the message's header values.

**Where should the new material be placed?**
In the RabbitMQ bindings section.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/2895

**Additional context**

**Comment by hhunter-ms** [comment]
@robert-oh now that the 1.11 dust has settled, can you work on a PR for this?

**Comment by robert-oh** [comment]
> @robert-oh now that the 1.11 dust has settled, can you work on a PR for this?

@hhunter-ms, the PR is already approved and merged to master. Is there still something missing?

**Comment by hhunter-ms** [comment]
> @hhunter-ms, the PR is already approved and merged to master. Is there still something missing?

@robert-oh ope, sorry, I meant a docs PR? I didn't see a docs PR tracked for this, so if it's already been added to docs, let me know and I can close this issue!

**Comment by robert-oh** [comment]
@hhunter-ms, I checked the docu repository and to be honest I don't think it's worth to mention it in the documentation as it's a really small extension.
What do you think?

**Comment by msfussell** [comment]
@robert-oh - Always worth mentioning this as a sentence in the docs, given that often people look for these sorts of things. You can always add a sentence here and we will include this, but small PR better.

**Comment by robert-oh** [comment]
Makes sense, right.
The description of this PR:
When a new RabbitMQ message gets published, all values from the associated metadata will be added to the message's header values.
