### ISSUE TITLE
[1.12] Update metadata for router alias middleware

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#3525]
The metadata for the component is changing in 1.12 to make it more consistent with the rest of Dapr.

Rather than passing each route as a metadata key-value pair, there's a single metadata property `routes` which is a JSON-encoded or YAML-encoded string with the key-value pairs of the routes.

See: dapr/components-contrib#2903

**Comment by hhunter-ms** [comment]
@ItalyPaleAle friendly bump
