### ISSUE TITLE
Duplicate PosgreSQL entry on menu

### ISSUE THREAD

**Issue by sangauit** [dapr/docs#3533]
**Describe the bug**

Duplicate the PostgreSQL entry on Menu

**Steps to reproduce**

1. Go to  https://docs.dapr.io/reference/components-reference/supported-configuration-stores

**Expected behavior**
Single entry of PostgreSQL

**Screenshots**
![image](https://github.com/dapr/docs/assets/121513740/904af7f9-09c3-46ed-a220-6bb2aa10a0e2)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser Firefox
 - Version 102.12.0 ESR

**Comment by hhunter-ms** [comment]
opened PR that includes this change: #3532

**Comment by hhunter-ms** [comment]
resolved - closing
