### ISSUE TITLE
No SQL Server State Store in Generic section

### ISSUE THREAD

**Issue by sangauit** [dapr/docs#3534]
**Describe the bug**

No SQL Server State Store in Generic section

**Steps to reproduce**

1. Go to https://docs.dapr.io/reference/components-reference/supported-state-stores/

**Expected behavior**
See the SQL Server in the Generic section

**Screenshots**
![image](https://github.com/dapr/docs/assets/121513740/8805371d-0104-44dc-bf00-4cb09df42551)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser Firefox
 - Version 102.12.0 ESR

**Comment by hhunter-ms** [comment]
Hey @sang-au - it looks like SQL Server was moved to the Microsoft Azure section:

![image](https://github.com/dapr/docs/assets/94493363/d702704a-a53b-4395-b1a9-743a2780659b)

**Comment by sangauit** [comment]
Hello @hhunter-ms thank you, but it no-sense because on the Menu bar don't include the Azure word. And the question is how about the self manage instance of SQL Server, so I think the word must be corrected or the Generic section must be updated.

**Comment by hhunter-ms** [comment]
@sang-au ah ok thanks for clarifying! I'll look into this

**Comment by msfussell** [comment]
@sang-au - So your point is that this is a Microsoft SQL Server, not just Azure SQL Server. This is still Microsoft and not generic, so we can clarify this.

**Comment by hhunter-ms** [comment]
@sang-au can you review my PR for this?

**Comment by sangauit** [comment]
@hhunter-ms this PR look good, thank you so much!
