### ISSUE TITLE
Docker Desktop requires socket setting before using Dapr CLI

### ISSUE THREAD

**Issue by artursouza** [dapr/docs#3540]
**What content needs to be created or modified?**
We need doc to mention that CLI needs this setting in DockerDesktop: "Allow the default Docker socket to be used"

Reproduced this on M1 Mac.

<img width="1581" alt="image" src="https://github.com/dapr/docs/assets/130954/3a3ecddc-e7c1-4492-9060-03ee20592e55">

Without this, users get this error:
```
$ dapr init
⌛  Making the jump to hyperspace...
❌  could not connect to docker. docker may not be installed or running
```

Even though `docker ps` works just fine.

**Describe the solution you'd like**
Mention the setting as a requirement for using Dapr CLI - OR mention in troubleshooting guide

**Where should the new material be placed?**
https://docs.dapr.io/getting-started/install-dapr-cli/
OR here: https://docs.dapr.io/operations/troubleshooting/common_issues/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
None - it seems to be a situation I ran into in Docker Desktop itself.

**Additional context**
DOES NOT seem to be a breaking change in Docker Desktop.

**Comment by artursouza** [comment]
I would appreciate if other users confirm this or if this is something that only happened to me for some reason.

**Comment by JoshVanL** [comment]
On a fresh vanilla docker desktop install on an M1, these are my default options.

![image](https://github.com/dapr/docs/assets/15893072/26a014ee-e757-4db3-bc68-dd04dc875213)

**Comment by shubham1172** [comment]
> I would appreciate if other users confirm this or if this is something that only happened to me for some reason.

I also had to enable it a few days back IIRC.
