### ISSUE TITLE
How to implement state multi-operation requests? 

### ISSUE THREAD

**Issue by pacodelacruz** [dapr/docs#355]
## Ask your question here

The [state management documentation ](https://github.com/dapr/docs/blob/master/concepts/state-management/state-management.md#bulk-operations) mentions the possibility of implementing multi-operation requests, i.e. atomic transactions. However, I couldn't find how to do this. 

Could you please provide an example of how to do it?

**Comment by orizohar** [comment]
Does [this doc](https://docs.dapr.io/reference/api/state_api/#state-transactions) address your issue? If not please reopen and provide more details on the requested missing content
