### ISSUE TITLE
Add missing properties to the metadata API - Subscriptions, runtimeVersion, appConnectionProperties

### ISSUE THREAD

**Issue by shubham1172** [dapr/docs#3557]
**What content needs to be created or modified?**

There are some new properties being introduced in the metadata API, add them to the API reference docs.
1. runtimeVersion
2. appConnectionProperties
3. Subscriptions

**Where should the new material be placed?**

https://docs.dapr.io/reference/api/metadata_api/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/6524
https://github.com/dapr/dapr/pull/6537

Missing subscription information from this 1.10 issue https://github.com/dapr/dapr/issues/5510

**Additional context**

**Comment by msfussell** [comment]
For Subscription. It is available [here](https://github.com/dapr/dapr/blob/master/dapr/proto/runtime/v1/dapr.proto#L606) now in the [metadata API](https://docs.dapr.io/reference/api/metadata_api/)

Example call to `http://localhost:<DAPR_HTTP_PORT>/v1.0/metadata` with a programmatic subscription is as follows:

``` json
{
    "id": "loyalty-service",
    "actors": [],
    "extended": {
        "cliPID": "11737",
        "daprRuntimeVersion": "1.10.7"
    },
    "components": [
        {
            "name": "oms.pubsub",
            "type": "pubsub.redis",
            "version": "v1",
            "capabilities": []
        },
        {
            "name": "oms.state.loyalty",
            "type": "state.redis",
            "version": "v1",
            "capabilities": [
                "ETAG",
                "TRANSACTIONAL",
                "QUERY_API",
                "ACTOR"
            ]
        }
    ],
    "subscriptions": [
        {
            "pubsubname": "oms.pubsub",
            "topic": "orders",
            "deadLetterTopic": "",
            "metadata": null,
            "rules": [
                {
                    "match": "%!s(<nil>)",
                    "path": "orders"
                }
            ]
        }
    ]
}
```

**Comment by shubham1172** [comment]
Thanks @msfussell, I created #3682 to add subscriptions to the examples as well, the structure was already present. We can close this issue once that PR is merged.

**Comment by msfussell** [comment]
Complete
