### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by opinionmachine** [dapr/docs#3575]
**What content needs to be created or modified?**
There needs to be an additional step in the troubleshooter.

**Describe the solution you'd like**
If the controller is accessible. i.e. dapr publish will correctly identify the correct controller, then the troubleshooter assumes all is well, but I get "incorrect content type", but... it's DAPR SDK setting the content type, so... how is it wrong? 

**Where should the new material be placed?**
As the next step in the troubleshooter

**Additional context**
If I knew what the fix was. I would suggest it.

**Comment by msfussell** [comment]
@opinionmachine - Can you provide more context here on which topic are you reading in the docs? I would suggest asking questions on the Dapr Discord alias, that are more open, docs is not always the best place for questions.

**Comment by opinionmachine** [comment]
Never mind, I thought the link to the issues page would retain some context. Its a troubleshooting step missing from a troubleshooter page, but I can’t be bothered to go look it up.
