### ISSUE TITLE
Docs for pubsub rabbitmq connection_name

### ISSUE THREAD

**Issue by Taction** [dapr/docs#3578]
**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/2933

**Additional context**

**Comment by alicejgibbons** [comment]
Documentation for the new rabbitmq `clientName` and `heartBeat` metadata properties need to be added here.

**Comment by Taction** [comment]
Duplicated with #3710, this can be safely closed.
