### ISSUE TITLE
[crypto] Other SDK support

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3584]
**What content needs to be created or modified?**
Support for JS SDK needs to be documented once ready.

**Describe the solution you'd like**
Code examples and instructions for quickstarts

**Where should the new material be placed?**
https://docs.dapr.io/developing-applications/building-blocks/cryptography/
https://docs.dapr.io/getting-started/quickstarts/cryptography-quickstart/

**The associated issues from dapr/dapr**
dapr/js-sdk#474

**Comment by alicejgibbons** [comment]
Now that the [Javascript SDK supports cryptography ](https://github.com/dapr/quickstarts/tree/master/cryptography/javascript/sdk) we should add documentation around to this page: https://docs.dapr.io/getting-started/quickstarts/cryptography-quickstart/
