### ISSUE TITLE
Update service invocation examples

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#3599]
All examples [here](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#invoke-the-service) will be better changed to using HTTP clients as these are consistent with our gRPC experience, need users to make less code changes to adopt Dapr and don't limit users in things like dealing with headers and other HTTP specific settings.

**Comment by yaron2** [comment]
This is for v1.10, v1.11 and onwards.

**Comment by msfussell** [comment]
Also see this issue https://github.com/dapr/quickstarts/issues/888

**Comment by yaron2** [comment]
All of our quickstarts today show usage of http clients and not the `InvokeX` methods that are listed on the docs - so guidance is confusing. We should consolidate.
