### ISSUE TITLE
Dapr error codes

### ISSUE THREAD

**Issue by adrobson** [dapr/docs#3601]
**What content needs to be created or modified?**
Error messages

**Describe the solution you'd like**
What causes the error message eg the scenario in dapr which generates the error message 

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by hhunter-ms** [comment]
@adrobson Could you provide some more context? Is there an error message/scenario/solution we should add to the [Troubleshooting guides](https://docs.dapr.io/operations/troubleshooting/)?

**Comment by hhunter-ms** [comment]
addressed in #3907
