### ISSUE TITLE
[1.12] Update Postgres components reference

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#3602]
Update the Postgres components reference: state store, binding, config store.

Need to add:

- Support for Azure AD
- New/updated metadata properties
- Support for parametrized queries in binding

Code PRs:

- dapr/components-contrib#2970
- dapr/components-contrib#2971
- dapr/components-contrib#2972

**Comment by hhunter-ms** [comment]
@ItalyPaleAle friendly bump

**Comment by mukundansundar** [comment]
closed by #3811
