### ISSUE TITLE
dapr --wait

### ISSUE THREAD

**Issue by EequalsMCsquare** [dapr/docs#3616]
**URL of the docs page**
https://docs.dapr.io/zh-hans/operations/hosting/kubernetes/kubernetes-deploy/#wait-for-the-installation-to-complete

**How is it currently worded?**
您可以使用 --want 标志来等待安装完成。

**How should it be worded?**
您可以使用 --wait 标志来等待安装完成。

**Screenshots**
<img width="980" alt="图片" src="https://github.com/dapr/docs/assets/48718382/631bf19f-657e-49f9-8739-5e440b2cc131">

**Additional context**

**Comment by hhunter-ms** [comment]
@skyao is this something you can help fix?

**Comment by sakibian** [comment]
@hhunter-ms can I fix this typo? if yes please assign me to this.

**Comment by hhunter-ms** [comment]
@sakibian sorry for the delay - I've assigned you to this issue. thanks for your help!

**Comment by sakibian** [comment]
@hhunter-ms Seems I've lost the folder structure correctly or I should look for other Chinese versions of this repository I don't know about. 

If you look here:  
1. Edit on page clicked.
![image](https://github.com/dapr/docs/assets/40847839/9c7ec0da-5911-43b5-853e-2c97d43da1a7)
2. Page is not found.
![image](https://github.com/dapr/docs/assets/40847839/9c8c1cfb-b49d-4da1-8b6d-07f754d5b1e3)
3. If we go back to the content folder there is only EN version available.
![image](https://github.com/dapr/docs/assets/40847839/6bba2b77-42a2-4641-a152-7c2bc9d6deb9)

Did I miss something? or does it support the English version only?
Let me know, Thanks

**Comment by hhunter-ms** [comment]
@sakibian hm, good question - @msfussell thoughts?

**Comment by hhunter-ms** [comment]
@skyao checking back in on this - would you be able to take a look?

**Comment by hhunter-ms** [comment]
Closing per @skyao recommendation
