### ISSUE TITLE
Improved the service invocation building block concepts doc

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#362]
Service invocation docs currently cover direct method invocation as a scenario. Other benefits from Dapr Service Invocation Building block include; 

This is to improve this conceptual topic https://github.com/dapr/docs/tree/master/concepts/service-invocation which is far from complete.

1) Include how there is now mTLS between services when using the Dapr Sentry Service for secure encryption on the wire (implemented in v0.4 release)
2) Include that observability of calls traces and metrics 
3) Document the Retry logic  added by Yaron and what this actually does. People ask if there is a retry mechanism on Service Invocation and what is the behavior. 
4) Circuit breaker pattern with back-off (not yet implemented https://github.com/dapr/dapr/issues/777)
5) Need to add the concept of namespaces. Reference reference/api/service_invocation_api.md topic

**Comment by yaron2** [comment]
@msfussell all the bullet points here are either already addressed or not relevant. Closing this for now.
