### ISSUE TITLE
Docs for Redis transactions limitations

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3635]
- [ ] Update the docs to make it clear that Redis shouldn’t be used as transactional state store
- [ ] Update docs/screenshots, etc when this issue merges: dapr/cli#1328

**Comment by yaron2** [comment]
@hhunter-ms we should definitely not document that Redis shouldn't be used as a state store. On the contrary, it's one of the most stable, tested and widely used state stores. What needs to be documented is that it's not a fit for transactions unless you can accept the limitations imposed by Redis transactions (documented here https://redis.io/docs/interact/transactions/#what-about-rollbacks).

In the future we might deprecate the transactions capability on Redis but that decision hasn't been made yet.

**Comment by hhunter-ms** [comment]
> @hhunter-ms we should definitely not document that Redis shouldn't be used as a state store. On the contrary, it's one of the most stable, tested and widely used state stores. What needs to be documented is that it's not a fit for transactions unless you can accept the limitations imposed by Redis transactions (documented here https://redis.io/docs/interact/transactions/#what-about-rollbacks).

ah thanks for the clarification - I overheard this in the sync earlier but didn't totally catch the context
