### ISSUE TITLE
Update components schema

### ISSUE THREAD

**Issue by philliphoff** [dapr/docs#3638]
**What content needs to be created or modified?**

The [components schema](https://raw.githubusercontent.com/dapr/docs/v1.11/daprdocs/content/en/reference/resource-specs/component-schema.md) is out of date (e.g. missing several properties such as `auth` and `scopes`).

**Describe the solution you'd like**

Current (as of v1.11) properties should be added to the schema.

**Where should the new material be placed?**

The [existing schema doc](https://raw.githubusercontent.com/dapr/docs/v1.11/daprdocs/content/en/reference/resource-specs/component-schema.md) should be updated.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/dapr/pull/6728

**Additional context**

**Comment by msfussell** [comment]
@philliphoff - Where can we find the latest information.

**Comment by philliphoff** [comment]
The CRD that describes the schema (which is generate from type information in the Dapr runtime source files) is: https://github.com/dapr/dapr/blob/26e83522689cbb5cf3dd60eb25133e8f818d4412/charts/dapr/crds/components.yaml#L14-L15
