### ISSUE TITLE
Remove the term "CRD" from the docs and replace with "resource spec"

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3644]
Given that Dapr is platform agnostic, the docs stay away from the term "CRD" in the docs and use the term "resource spec" or just "resource". We have to be attentive to ensuring that nothing ties Dapr to Kubernetes as the only platform. This issue is to remove the term CRD from the few places in the docs like here https://docs.dapr.io/reference/resource-specs/component-schema/

**Comment by sakibian** [comment]
For better understanding -  CustomResourceDefinition/CRD words are mentioned in the docs, so we should replace those long form and short form of text with "Resource specifications" on the linked text and replace CRD with "Resource"? @msfussell

If my point of views are correct then can I get assign to this?

**Comment by msfussell** [comment]
> For better understanding - CustomResourceDefinition/CRD words are mentioned in the docs, so we should replace those long form and short form of text with "Resource specifications" on the linked text and replace CRD with "Resource"? @msfussell
> 
> If my point of views are correct then can I get assign to this?

@sakibian Correct. They are only in a couple of places.

**Comment by sakibian** [comment]
@msfussell Can I get assigned to this? 
Will look for those other places or you can point them out to me.
