### ISSUE TITLE
expected k8s secret store not found

### ISSUE THREAD

**Issue by jhulten** [dapr/docs#3647]
**Describe the issue**

Documentation states: "When Dapr is deployed to a Kubernetes cluster, a secret store with the name kubernetes is automatically provisioned."

A freshly installed dapr install (1.11.1) has no components installed.

```
❯ dapr components -k -A
⚠  In future releases, this command will only query the "default" namespace by default. Please use the --namespace flag for a specific namespace, or the --all-namespaces (-A) flag for all namespaces.
  NAMESPACE  NAME  TYPE  VERSION  SCOPES  CREATED  AGE  
❯ dapr version
CLI version: 1.11.0 
Runtime version: 1.11.1
```

**URL of the docs**

https://docs.dapr.io/reference/components-reference/supported-secret-stores/kubernetes-secret-store/

**Expected content**

Either content should match the system, or this issue needs to move over to dapr/dapr.

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
@jhulten - Let me get back to you on this. It is somewhat historical where this secret store was automatically provisioned for ease of development. You have a point here.

**Comment by msfussell** [comment]
This secret store is a bit of a special case, with no yaml file deploy for it. Hence it does not currently appear in the components list
