### ISSUE TITLE
Rename middleware to filters

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#366]
Update this https://github.com/dapr/docs/blob/master/concepts/middleware/middleware.md

also see
https://github.com/dapr/dapr/issues/1086
https://github.com/dapr/components-contrib/issues/231

Need to update diagrams

**Comment by amanbha** [comment]
Nack on the proposal

Middleware is a industry standard term that refers to software that's assembled into an app pipeline
to handle requests and responses

ASP.NETCore uses the term: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1
ASPNetCore Google auth middleware: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.google.googlemiddleware?view=aspnetcore-1.1

gRPC uses the term: https://godoc.org/github.com/grpc-ecosystem/go-grpc-middleware

**Comment by msfussell** [comment]
Having review the term and with the references to other recent technologies also using middleware, we are going to keep this terminology.
