### ISSUE TITLE
Update Dapr presentation slide deck

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/docs#3675]
**Purpose:**
In an effort to allow community members to more easily participate in the Dapr project, I'd like to update the dapr presentation slide deck to include features from 1.9.0. 

Additionally, I'd like to move the dapr presentation slide deck out of the daprdocs repo and into the community repo instead.

**Following would be changed in the community repo:**
- Updated dapr presentation slide added 
- Presentation moved from daprdocs repo and into community repo
- Running-dapr directory would include a sub-directory for presentations in addition to the releases sub-directory and the community call sub-directory. 

**Related PR**
dapr/community#241

**Comment by artursouza** [comment]
What is the advantage of moving to community repo? We don't get many contributors in the community repo compared to docs repo.

**Comment by hhunter-ms** [comment]
@nyemade-uversky is this for the diagrams slide deck or the slide deck with templates for presentations?
