### ISSUE TITLE
Note on which state stores are supported for Actors

### ISSUE THREAD

**Issue by sebader** [dapr/docs#369]
## Describe the proposal
I just banged my head for quite a while to get a simple Actor running until I finally came across the error message:

`level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs"`

I was using Cosmos DB as the state store but I didn't see any note anywhere that this one is not supported for Actors. 

So can we please add a note (maybe in the list of state stores? - howto/setup-state-store/supported-state-stores.md) which of those do support Actors?

**Comment by RicardoNiepel** [comment]
It's currently documented at [Actor State Management](https://github.com/dapr/docs/blob/master/concepts/actor/actors_features.md#actor-state-management)

Are you looking for something different?

**Comment by sebader** [comment]
Ah I missed it there. Thanks for pointing it out!
