### ISSUE TITLE
dapr.io/app-health-check-path description is not correct for version 1.11

### ISSUE THREAD

**Issue by xendren** [dapr/docs#3702]
**Describe the issue**
The Reference->Arguments and Annotations page needs to be updated for changes made in the latest 1.11 release for the "**dapr.io/app-health-check-path**" description in the table.  
It looks like the default value for the argument was changed from "_/health_" to "_/healthz_" between versions 1.10 and 1.11.

**URL of the docs**
https://docs.dapr.io/reference/arguments-annotations-overview/

**Expected content**
The last line of the description should state:  "**Default is /healthz.**"

**Screenshots**
![image](https://github.com/dapr/docs/assets/7947774/99672403-d065-4804-b91c-9833513f813b)

**Comment by yaron2** [comment]
@xendren would you like to submit a PR that fixes this?
