### ISSUE TITLE
Missing API in docs for `/v1.0/healthz/outbound`

### ISSUE THREAD

**Issue by olitomlinson** [dapr/docs#3704]
The API reference area of the docs does not cover the `/outbound` path, yet this is something that the dotnet SDK utilises.

https://docs.dapr.io/reference/api/health_api/

**Comment by hhunter-ms** [comment]
@olitomlinson do you know if this is exclusive to the .NET SDK?

**Comment by olitomlinson** [comment]
Hey @hhunter-ms - sorry for the delay

All I know is its used in the dotnet SDK and its [planned to be used in the Java SDK too](https://github.com/dapr/java-sdk/issues/898).

I would recommend that regardless of its usage in the SDKs, its available to be used directly, so it should be included in the API reference.
