### ISSUE TITLE
Azure Eventhubs Bulk Subscribe support

### ISSUE THREAD

**Issue by shivamkm07** [dapr/docs#3705]
**What content needs to be created or modified?**
Bulk subscribe support is added for azure eventhubs in 1.12. It also adds `CheckPointFrequencyPerPartition` in subscribe metadata for regulating checkpointing frequency. 

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/3011

**Additional context**

**Comment by msfussell** [comment]
Completed
