### ISSUE TITLE
缺少中文的内容同步

### ISSUE THREAD

**Issue by ywanbing** [dapr/docs#3724]
**Describe the issue**

SDK 语言 其中的特性并没有和英文的内容同步
**URL of the docs**

https://docs.dapr.io/zh-hans/developing-applications/sdks/
**Expected content**

**Screenshots**

![image](https://github.com/dapr/docs/assets/30226135/be3831e4-63f8-49a5-80e4-3fbe6fcd7a75)
![image](https://github.com/dapr/docs/assets/30226135/6c323384-2243-4212-ae31-5454ec63fb24)

**Additional context**

**Comment by hhunter-ms** [comment]
closing per @skyao recommendation
