### ISSUE TITLE
Clarify beta stage in the docs

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3728]
Add acceptance criteria to support docs, based on this: https://github.com/dapr/proposals/blob/main/templates/lifecycle.md#acceptance-criteria

Create new article, titled "API lifecycle" under Operations/Support
Modify content from GH template file to suit the docs site.

**Comment by cicoyle** [comment]
Idk if my PR fully addresses what you were wanting from this issue, as my PR was created from an unspoken rule existing, but not being documented on binding components not needing conformance tests. [It stems from this proposal](https://github.com/dapr/proposals/issues/37). It certainly does add clarity to the Beta stage tho, but not 100% sure it fully satisfies all the AC from your link above

**Comment by hhunter-ms** [comment]
@cicoyle true! I realized with your PR that this issue is redundant and the acceptance criteria already exists in the doc you edited... closing as resolved.
