### ISSUE TITLE
Document two optimization points for bulk pub/sub

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#3748]
1. App to Dapr (all pub/sub brokers)
2. Dapr to Pub/Sub (subset)

**Comment by mukundansundar** [comment]
related to #3587

**Comment by msfussell** [comment]
We already have this https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-bulk/#how-components-handle-publishing-and-subscribing-to-bulk-messages 
Maybe this just need a diagram. Mostly we have to decide whether we want to list the components that support Dapr->Pub/sub broker

**Comment by DeepanshuA** [comment]
We would also need to fix some hyperlinks:

<img width="475" alt="image" src="https://github.com/dapr/docs/assets/24491296/2d93ed33-ac1f-4e57-9d7d-43e170a81b5d">
