### ISSUE TITLE
DAPR QuickStarts are getting enhanced with Multi App Run as a default option, so does the change to DAPR docs too. 

### ISSUE THREAD

**Issue by rabollin** [dapr/docs#3749]
The DAPR Quickstart samples are narrated with DAPR run command. Since we are supporting Multi App Run with both Standalone and AKS modes on Linux and Windows operating systems, we are enhancing all Quickstarts to demonstrate multi app run scenario as the first point. We need to modify documentation as per the quickstart changes. 

@hhunter-ms FYA

**Comment by msfussell** [comment]
Completed
