### ISSUE TITLE
Update DaprBot Docs - Available Github Commands

### ISSUE THREAD

**Issue by cicoyle** [dapr/docs#3755]
The [daprbot documentation](https://docs.dapr.io/contributing/daprbot/) is a little behind. There are a few dapr/* repos that have the `/assign` Github command available that is not noted in the documentation. 

Please check all the repos: docs (yes, this one), quickstarts, cli, dapr, *-sdk. There will be a `dapr-bot.js` and/or a `dapr-bot.yml` in the `/.github/` probably in a `/.github/scripts` or `/.github/workflows`. Any repo that has the `/assign` should be noted in the documentation.

Also, please link to the [daprbot documentation](https://docs.dapr.io/contributing/daprbot/) in the `contributing.md` in this repo so users know what commands they may run in this repo.

**Comment by srilasya02** [comment]
Can you assign this to me?I  am joining from GHC OSD @hhunter-ms

**Comment by sicoyle** [comment]
Hey @srilasya02 Hope you are enjoying the Grace Hopper Conference Open Source Day event! Happy to have you here with us. Please let us know if you need any help along the way 😁
