### ISSUE TITLE
Dapr Run File (`dapr.yaml`) sample is incorrect for `env` property

### ISSUE THREAD

**Issue by philliphoff** [dapr/docs#3778]
**Describe the issue**
The sample related to the Dapr Run FIle (`dapr.yaml`) shows an incorrect syntax for the `env` property.

The sample shows:

```yaml
env:
  - DEBUG: false
```

...but should be:

```yaml
env:
  DEBUG: false
```

**URL of the docs**
https://docs.dapr.io/developing-applications/local-development/multi-app-dapr-run/multi-app-template/#template-file-structure

**Expected content**

```yaml
env:
  DEBUG: false
```
**Screenshots**
<img width="1179" alt="Screenshot 2023-10-03 at 10 22 26" src="https://github.com/dapr/docs/assets/6402946/bfee18fe-5c25-43a6-9b1c-63df8038cbba">

**Comment by msfussell** [comment]
Complete
