### ISSUE TITLE
dapr init -k --dev command needs more documentation

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3781]
To make setting up a development environment on Kubernetes easier, the [dapr init -k command](https://v1-12.docs.dapr.io/reference/cli/dapr-init/) now supports a --dev option which deploy Redis and Zipkin containers to Kubernetes identical to the self-hosted mode. 

- This Initialize Dapr in your local environment overview should be updated to make it clear that this option is now available for K8s. https://v1-12.docs.dapr.io/getting-started/install-dapr-selfhost/. Either create a new topic or maybe enhance this one to add Kubernetes
- Example needed for dapr init -k --dev in the examples section
Add an example here  https://v1-12.docs.dapr.io/reference/cli/dapr-init/#kubernetes-environment

**Comment by msfussell** [comment]
@mikeee - Will you be doing a PR for this?

**Comment by mikeee** [comment]
I'll pick this up today.
