### ISSUE TITLE
Deprecated flag

### ISSUE THREAD

**Issue by nelsonApraez** [dapr/docs#3794]
**Describe the issue**
In the document show the use a deprecated flag --app-ssl

**URL of the docs**
https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/

**Expected content**
a flag app-protocol

**Screenshots**
![image](https://github.com/dapr/docs/assets/145040044/fc0ddb88-ed65-40b9-a51c-31fdee08056d)
![image](https://github.com/dapr/docs/assets/145040044/4445a6cc-3c73-40aa-91bc-b1a502062a9a)

**Additional context**

**Comment by yaron2** [comment]
Thanks for reporting, it would be great if you opened a PR to fix this!
