### ISSUE TITLE
durable timers -> Actor reminders

### ISSUE THREAD

**Issue by oleksandr-bilyk** [dapr/docs#3805]
Please replace "Retries are internally implemented using durable timers." by "..internally implemented using Actor reminders".
That will demystify Workflow engine and will help to understand how it works.
Article https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/#workflow-determinism-and-code-constraints

**Comment by yaron2** [comment]
@oleksandr-bilyk please feel free to open a PR to fix this, it would be highly appreciated
