### ISSUE TITLE
Dapr Control Plane Operator as a way to deploy Dapr control plane

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3828]
Need to mention in the docs that you can install the Dapr Control plane via this operator now
https://operatorhub.io/operator/dapr-kubernetes-operator

This can put here https://v1-11.docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/ as a new deployment choice. Will need to be need test that this deploys all service from the Dapr control plane.

Also suggest raise an issue on the https://github.com/dapr-sandbox/dapr-kubernetes-operator site to say this installs all the Dapr control plane services . Currently this is not clear.

**Comment by lburgazzoli** [comment]
> Need to mention in the docs that you can install the Dapr Control plane via this operator now https://operatorhub.io/operator/dapr-kubernetes-operator
>
> This can put here https://v1-11.docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/ as a new deployment choice. 

Should the the doc redirect to the `dapr-kuberpenets-operator` repo  ? or it should be a dedicated section with all the instructions ? Note that at this stage, the operator does not yet have branches and release channels that tracks dapr releases so the operator will install the dapr release it was built for.
  
> Will need to be need test that this deploys all service from the Dapr control plane.

At this stage we have a [minimal test ](https://github.com/dapr-sandbox/dapr-kubernetes-operator/blob/main/test/e2e/operator/dapr_deploy_test.go#L28-L33) that check for the deployment of the following control plane components:
- dapr-operator
- dapr-sentry
- dapr-sidecar-injector


> Also suggest raise an issue on the https://github.com/dapr-sandbox/dapr-kubernetes-operator site to say this installs all the Dapr control plane services . Currently this is not clear.

Added some info here: https://github.com/dapr-sandbox/dapr-kubernetes-operator/pull/39

**Comment by hhunter-ms** [comment]
@msfussell friendly bump

**Comment by msfussell** [comment]
> Should the the doc redirect to the `dapr-kuberpenets-operator` repo ? or it should be a dedicated section with all the instructions ? Note that at this stage, the operator does not yet have branches and release channels that tracks dapr releases so the operator will install the dapr release it was built for.

@lburgazzoli - Apologies for the late reply here. I suggest that you keep this simple. Have a dedicated sub heading and just point to the repo, pulling out the overview of why/when you would use the operator. I would also embedded your intro video at this link Covered in this talk https://www.youtube.com/watch?v=d3ahz41I_Io&t=7s so people can see this in action
