### ISSUE TITLE
dapr run command incorrect for State Management Quickstart

### ISSUE THREAD

**Issue by GaTechThomas** [dapr/docs#3838]
**Describe the issue**
`dapr run -f` should be `dapr run -f .`

To be sure, the dot is missing at the end.

**URL of the docs**
https://docs.dapr.io/getting-started/quickstarts/statemanagement-quickstart/

**Comment by yaron2** [comment]
Thanks for reporting, it'd be great to get a PR that fixes this.

**Comment by hhunter-ms** [comment]
fixed in #3861
