### ISSUE TITLE
Update docs to add video demo of --app-channel-address

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3855]
This was shown by Yaron in Community call #92. 
Consider add a new topic under https://docs.dapr.io/developing-applications/local-development/ as a way to use this for local development and testing

**Comment by hhunter-ms** [comment]
@msfussell taking a look at this - the only presentation from Yaron during that call is for the STC election. Do you mean Jonas' presentation?

**Comment by hhunter-ms** [comment]
@msfussell friendly bump

**Comment by msfussell** [comment]
I could not find it.  However I found this to add. 
1) -  For Azure OpenAI component add this video https://www.youtube.com/watch?v=rTovKpG0rhY&t=1344s
