### ISSUE TITLE
[v1.13] Add docs for Azure Blob Storage v2 state store

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#3857]
Needs docs for https://github.com/dapr/components-contrib/pull/3203 which registers a v2 of the state.azure.blobstorage component. No changes in metadata, but it includes a bug fix that's not backwards-compatible

**Comment by elena-kolevska** [comment]
Are there any updates on this for the 1.13 release?

**Comment by hhunter-ms** [comment]
@ItalyPaleAle beyond changing `v1` to `v2` in Azure Storage Blob examples, what else would need updated in the docs for this? perhaps adding a note like this from your comment in the bug issue?:

> Note that the default keyPrefix (if unset) is "appid". So we should show a warning unless the keyPrefix is explicitly set to "none", because the component behaves as if it were set to "none".
