### ISSUE TITLE
Component Tutorial - "--resources-path" flag is incorrect when using Powershell

### ISSUE THREAD

**Issue by ptjhiram** [dapr/docs#3858]
**Describe the issue**
In Section 3: Run the Dapr Sidecar, the --resources-path flag in the dapr run command listed is incorrect when running in Powershell. The  flag should reaad "--resources-path ../" and not  "--resources-path ."

**URL of the docs**
https://docs.dapr.io/getting-started/tutorials/get-started-component/#step-3-run-the-dapr-sidecar

**Expected content**
dapr run --app-id myapp --dapr-http-port 3500 --resources-path ../

**Screenshots**
![image](https://github.com/dapr/docs/assets/130476323/e47e8ce3-1d48-4f4c-90fe-41b0d904c418)

should be 
![image](https://github.com/dapr/docs/assets/130476323/c77ba31c-b1de-4a3a-bc28-c89afc32a235)

**Additional context**

**Comment by yaron2** [comment]
Thanks! We'd appreciate a PR that fixes this if you're up for it.
