### ISSUE TITLE
Deficiencies in the steps updated with the multi-app run feature that comes with v12

### ISSUE THREAD

**Issue by baransonmez** [dapr/docs#3860]
I ran the java example in local environment. Since I ran this command for state management without installing dependencies and extracting a jar file, I get an error that there is no such file. In the previous step, when I did "mvn clean install", I can pass this error and run my code successfully. In this case, I think that either the documentation or the dapr.yaml file should be updated. I only had the opportunity to work on the java example. I don't know what the situation is for other examples, but I think it may be necessary to make an examination for other languages and other tutorials. 

related page: https://docs.dapr.io/getting-started/quickstarts/statemanagement-quickstart/

I'm volunteering to fix this problem if you see fit. But it might be good to discuss the method I should pursue.

**Comment by hhunter-ms** [comment]
@mukundansundar I'm also getting an error for multi-app run. If I run `dapr run -f` like in the docs, I get: 

> PS C:\Users\hannahhunter\GitHub\quickstarts\state_management\java\sdk\order-processor> dapr run -f
Error: flag needs an argument: 'f' in -f

if I run `dapr run -f .`, I get:

> PS C:\Users\hannahhunter\GitHub\quickstarts\state_management\java\sdk\order-processor> dapr run --run-file .
Failed to get run file path: error in validating the file path "dapr.yaml": error in getting the file info for dapr.yaml: CreateFile dapr.yaml: The system cannot find the file specified.

even with running `mvn clean install`, the `dapr run -f` and `dapr run -f .` commands don't work. 

meanwhile, running without multi-app run works just fine. 

@baransonmez is this what you're seeing as well?

**Comment by hhunter-ms** [comment]
@baransonmez after discussing with Mukundan, I've opened a PR in the quickstarts repo to update the `dapr.yml` location and its resource/app dir paths. thanks for catching this!

**Comment by baransonmez** [comment]
Yes, but I think we still need to run the `mvn clean install` command. I didn't see any improvement in the related pr. Could I be missing something? Can I make the related improvement?

**Comment by hhunter-ms** [comment]
> Yes, but I think we still need to run the `mvn clean install` command. I didn't see any improvement in the related pr. Could I be missing something? Can I make the related improvement?

@baransonmez 
To update the docs, here's what we need in the dapr/docs repo:

- State management quickstart
  - Add step for installing the dependencies to the multi-app run section under all languages (can use [dependencies step under Step 2 here](https://docs.dapr.io/getting-started/quickstarts/statemanagement-quickstart/#run-one-application-at-a-time) for reference)
  - Update `dapr run -f` to `dapr run -f .`

- Pub/sub, state management, and service invocation quickstarts:
  - Context: Windows doesn't support `python3`, as noted below the dapr run command under step 2, [like here](https://docs.dapr.io/getting-started/quickstarts/statemanagement-quickstart/#run-one-application-at-a-time). The `dapr.yml` file uses `python3`, which will cause an error for Windows users. 
  - Current solution: Add a note under the `dapr run -f .` command for Python suggesting that Windows users either:
    - Set an alias ([link to this doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/set-alias?view=powershell-7.3#example-1-create-an-alias-for-a-cmdlet)) before running `dapr run -f .`
    - Change `python3` to `python` in the dapr.yml file before running `dapr run -f .`
