### ISSUE TITLE
Updated docs for the 1.12.1, 1.12.2, 1.10.10 and 1.11.6 releases

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3871]
*Need to update the list of supported runtime versions with a link to the release notes here https://github.com/dapr/dapr/releases/tag/v1.12.1

**Comment by Meisamrzp** [comment]
oh my GOD!

**Comment by msfussell** [comment]
Add links to the release notes for each of the minor releases.

**Comment by JoshVanL** [comment]
Done, as above ^
