### ISSUE TITLE
dapr.msi on peut pas le telecharger

### ISSUE THREAD

**Issue by zaidtidjet** [dapr/docs#3890]
**What content needs to be created or modified?**

**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
The Dapr MSI installer is documented here https://docs.dapr.io/getting-started/install-dapr-cli/#install-using-msi-installer and available here https://github.com/dapr/cli/releases
