### ISSUE TITLE
Unexpected footer text on page

### ISSUE THREAD

**Issue by yash-nisar** [dapr/docs#3899]
**Describe the bug**
Unexpected footer text on this page: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-overview/

<img width="808" alt="image" src="https://github.com/dapr/docs/assets/14862976/1add5ac7-6baa-42b1-8cd8-1954d0fe55f7">

**Steps to reproduce**
1. Go to https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-overview/
2. Scroll down to the bottom of the page
3. See unexpected footer

**Expected behavior**
The `merge pull request...` should not exist.

**Comment by hhunter-ms** [comment]
the footer just shows the latest commit that has been pushed into the live branch - I don't think we can control what the latest commit is.

**Comment by yash-nisar** [comment]
@hhunter-ms In my opinion, the latest commit should not be exposed on the docs page. So, we should just show `Last modified February 2, 2024`
