### ISSUE TITLE
Valid workflow states needs update

### ISSUE THREAD

**Issue by philliphoff** [dapr/docs#3904]
**Describe the issue**
The workflow API docs have outdated/incomplete information about valid states of a workflow.

**URL of the docs**
[https://docs.dapr.io/reference/api/workflow_api/#response-content-6](https://docs.dapr.io/reference/api/workflow_api/#response-content-6)

**Expected content**
Valid values for `runtimeStatus` are:
 - `"RUNNING"`
 - `"COMPLETED"`
 - `"CONTINUED_AS_NEW"`
 - `"FAILED"`
 - `"CANCELED"`
 - `"TERMINATED"`
 - `"PENDING"`
 - `"SUSPENDED"`

**Screenshots**
<img width="857" alt="Screenshot 2023-12-14 at 12 01 02" src="https://github.com/dapr/docs/assets/6402946/6331317f-9ff2-474d-913d-49c0954d78d9">

**Additional context**

**Comment by msfussell** [comment]
@philliphoff - I presume this is "CANCELLED" and not "CANCELED"?

**Comment by philliphoff** [comment]
> @philliphoff - I presume this is "CANCELLED" and not "CANCELED"?

No, the runtime uses "CANCELED". See: https://github.com/dapr/dapr/blob/c91750643c2a751942154b59841e0308791c114b/pkg/runtime/wfengine/component.go#L38
