### ISSUE TITLE
Enhanced error message structure and format in Reference

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3907]
Create a reference section for error message format. The format is reference to each of the SDKs to reference

**Comment by elena-kolevska** [comment]
PR here: https://github.com/dapr/docs/pull/3908

**Comment by elena-kolevska** [comment]
**Done:**
- dapr docs: https://github.com/dapr/docs/pull/3908 @elena-kolevska 
- go-sdk: https://github.com/dapr/go-sdk/pull/482 @elena-kolevska 
- python-sdk: https://github.com/dapr/python-sdk/pull/659 @elena-kolevska 
- java-sdk: https://github.com/dapr/java-sdk/pull/998 @cicoyle

**Won't happen for 1.13:**. 
- dotnet: https://github.com/dapr/dotnet-sdk/issues/1227 @philliphoff 
- javascript-sdk: https://github.com/dapr/js-sdk/issues/567

**Comment by msfussell** [comment]
@cicoyle - Are you doing dapr/java-sdk#998 for v1.13?

**Comment by cicoyle** [comment]
java-sdk changes are done & merged 👍🏻

**Comment by elena-kolevska** [comment]
@msfussell , @hhunter-ms  can we close this?

**Comment by hhunter-ms** [comment]
I think we can - since we have doc issues for the last two in their respective sdk repos. Closing!
