### ISSUE TITLE
Local file-based name resolver w SQLite

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3914]
**What content needs to be created or modified?**
Docs corresponding with updates here dapr/dapr#7038

**Where should the new material be placed?**
- New component spec here: https://docs.dapr.io/reference/components-reference/supported-name-resolution/
- Might need to update CLI reference docs?

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
dapr/dapr#7038

**Comment by elena-kolevska** [comment]
Are there any updates on this for the 1.13 release?
