### ISSUE TITLE
[Workflow] Metrics

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3916]
**Where should the new material be placed?**
Workflow docs where applicable

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
dapr/dapr#7109
dapr/dapr#7152

**Comment by shubham1172** [comment]
Hi @hhunter-ms, metric typically go in this README https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md, is there any other place that this needs to be added in our docs?

**Comment by hhunter-ms** [comment]
Ahh ok, thanks for letting me know. @msfussell what do you think? Do we need this anywhere else?

**Comment by msfussell** [comment]
No..only needed in this one place

**Comment by shubham1172** [comment]
Shall we close the issue @hhunter-ms ?

**Comment by hhunter-ms** [comment]
@shubham1172 sure, it looks like dapr/dapr#7152 has this added to the docs, so we can close here.
