### ISSUE TITLE
[SDKs] DAPR_API_TOKEN env variable 

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3921]
**What content needs to be created or modified?**
Check and make sure this is documented across all the SDKs (open PRs in sdk repos)

**Where should the new material be placed?**
SDK docs

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
dapr/js-sdk#547

**Comment by hhunter-ms** [comment]
@msfussell ok to close this? or did we need this in other SDKs?

**Comment by elena-kolevska** [comment]
I just created an issue for it in python-sdk https://github.com/dapr/python-sdk/issues/653. 
Sending a PR in a bit.

**Comment by elena-kolevska** [comment]
Here's the PR: https://github.com/dapr/python-sdk/pull/654. It's a very small update.

**Comment by msfussell** [comment]
@elena-kolevska - Does this need to be done with other SDKs?

**Comment by elena-kolevska** [comment]
The only code change we did was in the JS sdk, all the other ones already had this feature, but not all of them had the docs properly updated. Here's a list:

- python-sdk - https://github.com/dapr/python-sdk/pull/654
- js-sdk - https://github.com/dapr/js-sdk/pull/548
- go-sdk - already had the feature documented
- dotnet-sdk - already had the feature documented
- java-sdk - https://github.com/dapr/java-sdk/pull/992

---

- php-sdk - Missing documentation - decided we're not doing it
- cpp-sdk - Doesn't support this feature
- rust-sdk - Doesnt support this feature

@cicoyle would you be able to help with the java-sdk docs for this? (I've never worked with this sdk and don't have the environment set up to test). I would suggest copying the [Initialising the client](https://github.com/dapr/python-sdk/blob/main/daprdocs/content/en/python-sdk-docs/python-client.md#initialising-the-client) section from the python-sdk docs and adapting the snippets to Java.

**Comment by elena-kolevska** [comment]
I added [this PR](https://github.com/dapr/java-sdk/pull/992) for the Java sdk, but since I'm not very familiar with the code I'm gonna rely on Cassie or someone else to confirm it's correct.

**Comment by cicoyle** [comment]
oops, I missed your ping on here. thanks @elena-kolevska

**Comment by elena-kolevska** [comment]
I think we can now consider this done.

**Comment by hhunter-ms** [comment]
@elena-kolevska sounds good - closing as resolved!
