### ISSUE TITLE
Add Kafka Pubsub Avro Schema Registry support doc

### ISSUE THREAD

**Issue by passuied** [dapr/docs#3930]
**What content needs to be created or modified?**
The Kafka.PubSub documentation needs to be updated to include the optional support for Avro + schema registry

**Describe the solution you'd like**
Document the metadata config in PR below

**Where should the new material be placed?**
Add to this [page](https://github.com/dapr/docs/blob/v1.12/daprdocs/content/en/reference/components-reference/supported-pubsub/setup-apache-kafka.md)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/pull/3292

**Additional context**
Supports publisher and subscribers including caching for latest schema

**Comment by hhunter-ms** [comment]
closing - looks like this has been resolved
