### ISSUE TITLE
Explicitly mention State Management API

### ISSUE THREAD

**Issue by marcduiker** [dapr/docs#3940]
**URL of the docs page**
https://docs.dapr.io/getting-started/get-started-api/

### The lead text under the h1

**How is it currently worded?**
Run a Dapr sidecar and try out the state API

**How should it be worded?**
Run a Dapr sidecar and try out the state management API

### The first sentence

**How is it currently worded?**
In this guide, you’ll simulate an application by running the sidecar and calling the API directly. 

**How should it be worded?**
In this guide, you’ll simulate an application by running the Dapr sidecar and calling the state management API directly. 

### Step 1: Run the Dapr sidecar

**How is it currently worded?**
The [`dapr run`](https://docs.dapr.io/reference/cli/dapr-run/) command launches an application, together with a sidecar.

**How should it be worded?**
The [`dapr run`](https://docs.dapr.io/reference/cli/dapr-run/) command normally runs your application and a Dapr sidecar. In this case, it will only run the sidecar since you will interact with the state management API directly.

**Comment by msfussell** [comment]
@dasanind - Any update on doing a PR for this issue?

**Comment by dasanind** [comment]
@msfussell I will raise the PR today
