### ISSUE TITLE
Update CLI flags and annotations for multiple versions of actors/reminders

### ISSUE THREAD

**Issue by mukundansundar** [dapr/docs#3948]
**What content needs to be created or modified?**

Docs for changes regarding dapr/dapr#7203
**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by yaron2** [comment]
I don't think this needs documentation beyond the standard Helm readme

**Comment by ItalyPaleAle** [comment]
We need to update the CLI flags page: https://docs.dapr.io/reference/arguments-annotations-overview/

**Comment by elena-kolevska** [comment]
Are there any updates on this for the 1.13 release?
