### ISSUE TITLE
[Workflow]Docs required for Cascade Terminate/Purge Workflow

### ISSUE THREAD

**Issue by shivamkm07** [dapr/docs#3949]
**What content needs to be created or modified?**
Cascade Terminate/Purge support for WF is being added to Dapr: https://github.com/dapr/dapr/pull/7340
Docs for same needs to be added
**Describe the solution you'd like**

**Where should the new material be placed?**

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by elena-kolevska** [comment]
Are there any updates on this for the 1.13 release?

**Comment by shivamkm07** [comment]
> Are there any updates on this for the 1.13 release?

PR created.

**Comment by JoshVanL** [comment]
Can we close this since https://github.com/dapr/docs/pull/3969 is merged?

**Comment by shivamkm07** [comment]
Closed by #3969
