### ISSUE TITLE
Instructions to add Kubernetes Metrics server to Kind 

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3951]
For many tools to work with Kind cluster the K8s metrics server should be enabled with mTLS disable. Effectively these steps  https://maggnus.com/install-metrics-server-on-the-kind-kubernetes-cluster-12b0a5faf94a should be added to the  https://docs.dapr.io/operations/hosting/kubernetes/cluster/setup-kind/ article

**Comment by prashantrewar** [comment]
Hey @msfussell, I would like to work on this, Is this issue still up for grabs?
