### ISSUE TITLE
Typo in Step 5: View the Pub/sub outputs

### ISSUE THREAD

**Issue by jhberge** [dapr/docs#3956]
**URL of the docs page**

https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/

**How is it currently worded?**

Notice, as specified in the code above, the publisher pushes a random number to the Dapr sidecar while the subscriber receives it.

**How should it be worded?**
Notice, as specified in the code above, the publisher pushes an order to the Dapr sidecar while the subscriber receives it.

**Screenshots**

**Additional context**

The numbers are not random, but 1 to 10.

**Comment by msfussell** [comment]
@jhberge I presume your are referring to this. https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/#step-5-view-the-pubsub-outputs
We will get this correct, or better still, would you like to get the credit for pushing a small PR? It is very easy to be a docs contributor now, just follow this video https://docs.dapr.io/contributing/docs-contrib/contributing-docs/

**Comment by jhberge** [comment]
Ok, I will try myself. Thank you.😊

Fra: Mark Fussell ***@***.***>
Sendt: tirsdag 23. januar 2024 07:29
Til: dapr/docs ***@***.***>
Kopi: jhberge ***@***.***>; Mention ***@***.***>
Emne: Re: [dapr/docs] Typo in Step 5: View the Pub/sub outputs (Issue #3956)


@jhberge<https://github.com/jhberge> I presume your are referring to this. https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/#step-5-view-the-pubsub-outputs
We will get this correct, or better still, would you like to get the credit for pushing a small PR? It is very easy to be a docs contributor now, just follow this video https://docs.dapr.io/contributing/docs-contrib/contributing-docs/
