### ISSUE TITLE
helm install redis stable/redis

### ISSUE THREAD

**Issue by larsoleruben** [dapr/docs#398]
## Expected Behavior

Making a Redis pod in my K cluster

## Actual Behavior

Fails with:  
error: failed to download "stable/redis" (hint: running `helm repo update` may help)
and 'helm repo update' fails with  
Error: no repositories found. You must add one before updating

## Steps to Reproduce the Problem

just run 'helm install redis stable/redis'

As a whole this instruction is a mess between the hello-world locally installation and the k8 installation. If you would like anybody to use this, the instructions has to be more concise than this. Basically it's not useable! One example, the instructions for hello-kubernetes wants you to use the files in the hello-world section. As a whole it is not very opaque

**Comment by AaronCrawfis** [comment]
Please try https://github.com/helm/hub/issues/208 and reopen if still persisting
