### ISSUE TITLE
[Workflow] Make sure all capabilities are documented (purge, etc)

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#4003]
**What content needs to be created or modified?**
Need more documentation about purge capability for workflow in the features/concepts doc. May also need to add other capabilities that haven't been documented.

**Describe the solution you'd like**
Section/paragraph, bullet list, cross linking

**Where should the new material be placed?**
[Workflow features and concepts](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
As mentioned in a comment here: #3969

**Comment by msfussell** [comment]
Specifically I would add the following
1) Before this section https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/#limitations add a title called "Purging" with text something like this
"Workflow state can be purged from a state store for which purges all its history and removes all metadata related to a specific workflow instance. This is typically used for workflows that have run to a COMPLETED or TERMINATED state. Purging is also performed when a workflow moves to a CONTINUED_AS_NEW state. There are of course other times that you may choose to purge a workflow history and reuse a workflow instance with new inputs, for example with a FAILED workflow instance"

2) In the https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-architecture/#state-store-usage section add that "Workflow state can be purged from a state store for which purges all its history. Purging removes all metadata related to a specific workflow instance"

I would get @cgillum to review this text suggestion.

**Comment by Hades32** [comment]
Just found that docs section and I'm more confused than before. Coming from Temporal, I had expected that there's some retention time after which workflow history would be purged automatically. Will dapr, by default, grow really indefinitely?
If so, then that definitely deserves a big mention in https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#limitations
