### ISSUE TITLE
OSS projects that integrate with Dapr

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#4025]
There are a number of other OSS project that have integrate with Dapr that need to be called out in the Dapr docs. 
This is to add a new topic in this section https://docs.dapr.io/developing-applications/integrations/ called "OSS Projects" that contains a list of other projects, notable

- Dapr K8s Operator https://operatorhub.io/operator/dapr-kubernetes-operator
- Dapr Kratix Marketplace https://github.com/syntasso/kratix-marketplace/tree/main/dapr
- Dapr Test Containers Module https://github.com/diagridio/testcontainers-dapr

**Comment by msfussell** [comment]
Close as a duplicate of https://github.com/dapr/docs/issues/3828

**Comment by salaboy** [comment]
I will keep track of this here: https://github.com/dapr/dapr/issues/7364
