### ISSUE TITLE
Provide concise example of declaring `HTTPEndpoint` yaml resource

### ISSUE THREAD

**Issue by olitomlinson** [dapr/docs#4029]
**What content needs to be created or modified?**

The docs here would benefit from a concise example of declaring a `HTTPEndpoint` resource in yaml

There already is the basis of an example here, but it requires clicking the link to see the verbose specification.

I think a concise resource inline in the doc would create a better first impression.

![image](https://github.com/dapr/docs/assets/4224880/ab45a35e-786e-4ef4-8205-2c843486db4b)

https://v1-13.docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-non-dapr-endpoints/#using-an-httpendpoint-resource-or-fqdn-url-for-non-dapr-endpoints

---

My recommendation here comes from a discord user who didn't spot this

**Comment by darraghjones** [comment]
actually my question was more related to the dotnet sdk docs here https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-client/#invoke-a-service

**Comment by hhunter-ms** [comment]
@darraghjones could you expound on what you'd like to have clarified in the docs?

**Comment by darraghjones** [comment]
I guess the only example of using the dotnet dapr client to invoke a service is by passing in the app-id. It wasn't clear to me that I can also invoke a non-dapr endpoint by passing in the FQDN as the app-id.
