### ISSUE TITLE
Document Actor Reminder Serializaiton

### ISSUE THREAD

**Issue by JoshVanL** [dapr/docs#4041]
Document:
~- What API level is, how to use it~
- Deprecation of JSON encoding of reminder state in v1.14
- The new protobuf storage format, and the performance benefits of using it
- Moving to protobuf cannot be reversed back into JSON
- Default is still JSON

Documentation guideline
~- These annotations need to be added here https://docs.dapr.io/reference/arguments-annotations-overview/~
- The description on how to use this feature and its importance needs to be added at the start of the topic https://docs.dapr.io/developing-applications/building-blocks/actors/actors-timers-reminders/ and reference the annotations. It is important to discuss 1) What the perf improvement is (~15%) and that once you go to protobuf you cannot move back to earlier releases

**Comment by yaron2** [comment]
Closed via #4058
