### ISSUE TITLE
Enable Outbox-pattern should show code performing transactions or link to relevant doc

### ISSUE THREAD

**Issue by salaboy** [dapr/docs#4053]
**Describe the issue**

This page in the docs, doesn't show explicitly that transactional methods need to be used, showing a code block on a transactional 

https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-outbox/

The same code block used here: https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/#perform-state-transactions 

can be used in the Howto-outbox pattern page for clarity. 

**URL of the docs**

https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-outbox/

**Expected content**

The same code block used here: https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/#perform-state-transactions 

can be used in the Howto-outbox pattern page for clarity.

**Comment by msfussell** [comment]
For this I would simply add as statement and a link to this page https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/#perform-state-transactions
for the code snippets

**Comment by salaboy** [comment]
@msfussell I've created this issue because I believe that we need to show the code as it will be more explicit than just a link that can be overlooked by readers. I know that we will be duplicating the code-snippets but I strongly feel that if we don't have the code right there, it will take extra time for people to figure out what they are missing.
