### ISSUE TITLE
StateStore transactions is not displayed using Go

### ISSUE THREAD

**Issue by salaboy** [dapr/docs#4059]
**What content needs to be created or modified?**

In the following section: https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/#perform-state-transactions "Go" examples are not shown. 
I found some examples by looking into the Go SDK: https://github.com/dapr/go-sdk/blob/5ef7aa2234d4d4c07769ad31cde223ef11c4e33e/Readme.md?plain=1#L157 

This should be displayed in the Docs.

**Describe the solution you'd like**
Having all the supported languages SDKs displayed in the examples for state trasactions

**Where should the new material be placed?**

https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-get-save-state/#perform-state-transactions

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

**Additional context**

**Comment by msfussell** [comment]
@salaboy - Can you review this PR for code accuracy?

**Comment by salaboy** [comment]
@msfussell I've reviewed the PR and added a few suggestions: https://github.com/dapr/docs/pull/4127#pullrequestreview-2037882523
