### ISSUE TITLE
Design Kibana dashboard templates for log

### ISSUE THREAD

**Issue by youngbupark** [dapr/docs#406]
## Describe the proposal

Create Kibana dashboard templates for log

**Comment by orizohar** [comment]
@tcnghia - can you take a look and see if we want to keep this issue?

**Comment by AaronCrawfis** [comment]
Should go here: https://docs.dapr.io/operations/monitoring/logging/

**Comment by hhunter-ms** [comment]
it looks like this has been documented - if not, feel free to reopen or open a new issue.
