### ISSUE TITLE
The Tracing docs imply that you should use a URL in tracing.otel.endpointAddress but it's looking for a hostname or hostname:port

### ISSUE THREAD

**Issue by andrejpk** [dapr/docs#4068]
**Describe the issue**

The [Setup Tracing docs](https://docs.dapr.io/operations/observability/tracing/setup-tracing/) imply that you should use a URL in tracing.otel.endpointAddress but it's looking for a hostname or hostname:port

**URL of the docs**

https://docs.dapr.io/operations/observability/tracing/setup-tracing/

**Expected content**
Should clarify this should be hostname or hostname:port and remove the `https:// ...` block

**Screenshots**

**Additional context**

**Comment by hhunter-ms** [comment]
This has been resolved - thank you for your contribution!
