### ISSUE TITLE
New dapr-slidedeck is not displayed correctly on MacBooks

### ISSUE THREAD

**Issue by marcduiker** [dapr/docs#4079]
**Describe the bug**
Several people mentioned that the new Dapr slidedeck on a Mac shows weird characters instead of the normal text.
[Source](https://x.com/rpcollette/status/1767540557721509903?s=20)

**Steps to reproduce**
Download the zip, unpack and open the PowerPoint file.

**Expected behavior**
The slide deck should show normal text, in the Space Grotesk font.

**Screenshots**
![image](https://github.com/dapr/docs/assets/4191277/11542ede-a8fe-4015-9d35-2ed02cf3ba95)

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by marcduiker** [comment]
Trying a different way to embed the fonts.

**Comment by gbaeke** [comment]
I installed the font used on MacOS with:

`brew install --cask homebrew/cask-fonts/font-space-grotesk`

This fixed it on my machine.

**Comment by marcduiker** [comment]
> I installed the font used on MacOS with:
> 
> `brew install --cask homebrew/cask-fonts/font-space-grotesk`
> 
> This fixed it on my machine.

Good to know this works, but I'm still puzzled that embedding the font does not seem to work. I'll investigate a bit more.

**Comment by marcduiker** [comment]
Closing, since there is a decent workaround mentioned in the docs. If someone in the community wants to create a Keynote presentation based on the pptx, that would be welcome!
