### ISSUE TITLE
Design Dashboard template for Azure monitor

### ISSUE THREAD

**Issue by youngbupark** [dapr/docs#408]
Deisgn dashboard templates for Azure monitor

- [ ] : export dashboard

**Comment by orizohar** [comment]
@tcnghia - can you look at this issue?

**Comment by AaronCrawfis** [comment]
Should be added to https://docs.dapr.io/operations/monitoring/metrics/azure-monitor/

**Comment by hhunter-ms** [comment]
it looks like this has been documented - if not, feel free to reopen or open a new issue.
