### ISSUE TITLE
Make it clear that Application Id Scopes and Namespaces apply to all Dapr resources

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#4117]
It should be made clear that  all resources today can be namespaced and all resources other than configuration can be scoped to a set of application IDs. These are the resources https://docs.dapr.io/reference/resource-specs/ and I suggest that this is pulled into each of the articles for each resource.

Configurations are different from other resources because there's only a 1:n relationship between an app and a configuration (an app can only have one configuration) so the app is scoping them by selecting the configuration explicitly

**Comment by hhunter-ms** [comment]
Note: say at the top of each resource spec that "any component/subscription/etc can be restricted to a particular namespace and also restricted access through scopes to any particular set of applications", except for Configurations spec

Also make sure namespace and scope properties are consistent between each spec.
