### ISSUE TITLE
[Actors] Namespaced actors

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#4118]
**What content needs to be created or modified?**
Add documentation covering support for cross-namespace actor invocation

**Where should the new material be placed?**
Add a couple of paragraphs to existing actors documentation, like the Features section of the overview

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
dapr/dapr#3786
dapr/dapr#7745

**Comment by elena-kolevska** [comment]
@hhunter-ms  can we please change the name to "Namespaced actors"?

**Comment by hhunter-ms** [comment]
> @hhunter-ms can we please change the name to "Namespaced actors"?

@elena-kolevska Done! I was just looking at this docs issue and the code PR. Will you be working on docs for this? I'm happy to provide support if necessary.
