### ISSUE TITLE
[Redis components] update for Azure Cache for Redis support

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#4120]
**What content needs to be created or modified?**
Update docs to clarify support for Azure Cache for Redis

**Where should the new material be placed?**
All Redis component specs will be impacted

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/components-contrib/issues/3088

**Comment by berndverst** [comment]
This is actually now completed @hhunter-ms.

See the new metadata field in https://github.com/dapr/components-contrib/pull/3470 -- `useEntraID` which needs to be set to true.

The redis server host name must be specified in the form of "server:port", and you have to enable TLS. See the linked PR for the full example.

Beyond that all standard Azure authentication options apply!
