### ISSUE TITLE
setup-dapr GitHub action recommended by docs is out of date and seemingly not maintained

### ISSUE THREAD

**Issue by DamianEdwards** [dapr/docs#4122]
**Describe the issue**
The **How to: Use the Dapr CLI in a GitHub Actions workflow** documentation page recommends using the [dapr/setup-dapr](https://github.com/dapr/setup-dapr) action to install the Dapr CLI in the context of a GitHub workflow, but `dapr/setup-dapr` is so out of date that it results in workflow warnings being produced, related to the minimum supported version of Node.js, and use of the `set-output` command:

```
Build & Test Samples (ubuntu-latest, sdk-baseline)Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dapr/setup-dapr@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Build & Test Samples (ubuntu-latest, sdk-baseline)The following actions uses node12 which is deprecated and will be forced to run on node16: dapr/setup-dapr@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
Build & Test Samples (ubuntu-latest, sdk-baseline)The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

This was [reported on the repo](https://github.com/dapr/setup-dapr/issues/106) way back in December 2022 but has not been acknowledged or acted upon, suggesting the workflow action is not maintained.

**URL of the docs**
[How to: Use the Dapr CLI in a GitHub Actions workflow](https://docs.dapr.io/developing-applications/integrations/github_actions/)

**Expected content**
The page should describe how to use the Dapr CLI in a GitHub workflow via a mechanism that is supported, or at the least, doesn't result in workflow warnings.

**Screenshots**
![image](https://github.com/dapr/docs/assets/249088/3049fbe0-6873-4756-9248-7b3fcd5deeec)

**Additional context**
https://github.com/dapr/setup-dapr/issues/106

/Cc @msfussell @paulyuk

**Comment by FlorentATo** [comment]
I've opened a separate issue to update dapr/setup-dapr to Node 20: https://github.com/dapr/setup-dapr/issues/141
