### ISSUE TITLE
Kubernetes deploy does not have the '--dev' option

### ISSUE THREAD

**Issue by guidoffm** [dapr/docs#4123]
https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/

**Comment by guidoffm** [comment]
This does not work:
```
dapr init -k --dev
```

**Comment by hhunter-ms** [comment]
@guidoffm Thanks for opening this issue - can you share more details about the issue you're running into? Is there an error message you receive when trying to run this?

**Comment by guidoffm** [comment]
The issue is gone.
