### ISSUE TITLE
Authenticate components to services using Dapr SPIFFE identity X.509 certificate

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#4130]
**What content needs to be created or modified?**
May need an explanation of this, and may need to update component specs to reflect this option

**Where should the new material be placed?**
[Components concept](https://docs.dapr.io/concepts/components-concept/)
[Component specs?](https://docs.dapr.io/reference/components-reference/)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/proposals/pull/51/files

**Comment by hhunter-ms** [comment]
@JoshVanL is this something that needs to be added to the docs? and if so, is it still targeting 1.15?

**Comment by JoshVanL** [comment]
Hey @sicoyle, would you be able to take this on?
