### ISSUE TITLE
[OTEL] Specify the version of OTEL that Dapr supports

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#4142]
**What content needs to be created or modified?**
Clear OTEL versions supported by Dapr

**Where should the new material be placed?**
https://docs.dapr.io/operations/support/support-release-policy/#supported-versions-of-dependencies

May need to add protocol and SDK versions

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
dapr/dapr#7703

**Comment by msfussell** [comment]
This should be to update from v0.4.0 to v0.101.0
