### ISSUE TITLE
Update otel-collector-contrib version in appinsights example and replace logging exporter with debug exporter

### ISSUE THREAD

**Issue by fabistb** [dapr/docs#4143]
**What content needs to be created or modified?**
https://github.com/dapr/docs/blob/v1.13/daprdocs/static/docs/open-telemetry-collector/open-telemetry-collector-appinsights.yaml

**Describe the solution you'd like**
The references image `otel/opentelemetry-collector-contrib:0.77.0` is a little bit older.
Version 0.100.0 has been released a couple of days ago. The version in the environment I'm using however is 0.99.0.

Additionally current template also features an additional logging exporter which however has been deprecated in favor of the debug exporter.
https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md

To not utilize any exporters which are marked for removal change it to the debug exporter.

**Comment by fabistb** [comment]
@msfussell , just out of curiosity.
Would an update here interfere with this issue #4142 ?

**Comment by alicejgibbons** [comment]
Confirming that 0.99.0 works @fabistb. 

@hhunter-ms an FYI if you are working on #4142!

**Comment by msfussell** [comment]
@fabistb - Please push a PR for these changes and I suggest that we move to the latest version of the OTEL collector in the docs which is [v0.101.0](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.101.0)
