### ISSUE TITLE
Incorrect instructions on how to run the Workflow quickstarts

### ISSUE THREAD

**Issue by grafvonb** [dapr/docs#4144]
**Describe the issue**
All language versions of the workflow quickstarts incorrectly state that to run the order processor app, one must navigate to the `sdk/order-processor` folder (Step 2) and execute `dapr run -f .` (Step 3). This results in an error: `Failed to get run file path: error in validating the file path "dapr.yaml": error in getting the file info for dapr.yaml: stat dapr.yaml: no such file or directory`. The error occurs because the `dapr.yaml` file is actually located in the `workflows/<lang>/sdk` folder, not within the `workflows/<lang>/sdk/order-processor` folder.

**URL of the docs**
https://docs.dapr.io/getting-started/quickstarts/workflow-quickstart/

**Expected content**
The documentation should be updated to instruct users to navigate to the `workflows/<lang>/sdk` folder in Step 2.

**Comment by yaron2** [comment]
Thanks, we'd very much appreciate a PR to make this right 🙏
