### ISSUE TITLE
Wrong instructions in How to: Use the Multi-App Run template file

### ISSUE THREAD

**Issue by bibryam** [dapr/docs#4153]
**Describe the issue**
The instructions to use multi-app run with kubernetes are wrong

**URL of the docs**
https://docs.dapr.io/developing-applications/local-development/multi-app-dapr-run/multi-app-template/

**Expected content**
The command to work with kubernetes cluster

**Screenshots**

**Additional context**

**Comment by hhunter-ms** [comment]
closing as resolved
