### ISSUE TITLE
the macos brew link points to a deprecated function: homebrew/cask-fonts was deprecated

### ISSUE THREAD

**Issue by michielhamers** [dapr/docs#4159]
**Describe the issue**

**URL of the docs**

**Expected content**

**Screenshots**

**Additional context**

**Comment by michielhamers** [comment]
https://docs.dapr.io/contributing/presentations/?_gl=1*cxbl3n*_ga*OTAwMTc5ODA3LjE3MTY5MDg3NDQ.*_ga_60C6Q1ETC1*MTcxNjkwODc0My4xLjAuMTcxNjkwODc0My4wLjAuMA..

**Comment by msfussell** [comment]
However looks like it is now `brew install --cask font-space-grotesk` instead of `brew install --cask homebrew/cask-fonts/font-space-grotesk`
Yes, just tried the above and it worked
