### ISSUE TITLE
docs.dapr.io is not working?

### ISSUE THREAD

**Issue by alkofahi** [dapr/docs#4176]
**Describe the bug**
I am unable to access any of the documentation on docs.dapr.io due to cert issues:

<img width="721" alt="image" src="https://github.com/dapr/docs/assets/58956796/bb6ef4f8-50e7-42c3-a522-e664c4c4f61c">

**Steps to reproduce**
1. Go to docs.dapr.io
2. You will see the issue I mentioned
3. I tried clearing browser cache and used incognito mode. It did not help. 

**Expected behavior**
I am able to browse the documentation

**Additional context**

**Comment by alkofahi** [comment]
I tried to reach the website on my mobile phone and ran into the same issue

**Comment by paulyuk** [comment]
Hi everyone, our docs website is currently experiencing issues. We expect it to be back to normal within the next 24 hours.

And yes - it's DNS.  

The workaround for tonight is to navigate directly here:
https://black-flower-04b2fe21e.5.azurestaticapps.net/

**Comment by paulyuk** [comment]
Hey - [http://docs.dapr.io](https://t.co/beiEdINbgW) and the current v1.13 docsite is back online.  the dns issue is mitigated.  We will have it 100% by tomorrow, but for now expect issues on other older versions.  The docs are mirrored from [http://github.com/dapr/docs](https://t.co/Ngs05yGKNF) if you need to look at older branches

**Comment by yaron2** [comment]
Docs site is up

**Comment by paulyuk** [comment]
Docs is 100% up in all versions.
