### ISSUE TITLE
Github deploy actions for 1.4-1.6 versions are broken

### ISSUE THREAD

**Issue by paulyuk** [dapr/docs#4185]
I notice that versions 1.4-1.6 have not CI'd for years.  I did a manual trigger of 1.4 and see that it is failing on what looks like some old actions and dependencies that need cleaning up.  For continuity I believe it's a good idea to get these fixed again just in case we need to do more pushes.  

Here is an example of a failed action:
https://github.com/dapr/docs/actions/runs/9328890186

**Comment by msfussell** [comment]
I would not deploy these docs.sites

**Comment by paulyuk** [comment]
Roger that
