### ISSUE TITLE
Doc sets for versions 1.4-1.6 need to be deployed to dapr.io tenant Static Web Apps

### ISSUE THREAD

**Issue by paulyuk** [dapr/docs#4186]
As a part of the migration last week I made new SWA apps for all versions including these.  But with CI actions broken per issue #4185 there is no site deployed.  We could either fix up 4185 or do quick manual pushes of the apps perhaps using the SWA cli.  

The usage is incredibly low since docs.dapr.io no longer lists these versions.  But this issue tracks that they will be down if maintainers do nothing.  

In terms of subscription information for deployment please speak with me directly.

**Comment by msfussell** [comment]
I would not deploy these docs sites. We took these down due to no traffic

**Comment by paulyuk** [comment]
OK.  I will leave the sites provisioned since they are free.  We can reopen if we change our minds.
