### ISSUE TITLE
Redis statestore field redisPassword incorrectly marked as required in docs

### ISSUE THREAD

**Issue by jake-engelberg** [dapr/docs#4193]
EDIT (contrib maintainer): The contrib repo metadata was correct. The docs are wrong. The docs instead need updating.

## Expected Behavior

`redisPassword` should be a required field in the statestore `.yaml` as per the docs:
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/
<img width="300" alt="Screenshot 2024-06-11 at 4 28 15 PM" src="https://github.com/dapr/components-contrib/assets/152900222/7fa83342-597f-4e49-a623-ed3cdca28e93">

## Actual Behavior

`redisPassword` is incorrectly set as `required: false`.
https://github.com/dapr/components-contrib/blob/787b23d5d0a3486fc14255f26b36cf365c9bd2bf/state/redis/metadata.yaml#L24-L29

## Steps to Reproduce the Problem

N/A

## Release Note

RELEASE NOTE: **FIX** Redis statestore field `redisPassword` now correctly marked as required.

**Comment by berndverst** [comment]
The docs are incorrect and the metadata file is actually correct. I'll transfer this issue to the docs repo and you can then update the docs there instead.

Thanks!

**Comment by hhunter-ms** [comment]
@jake-engelberg @berndverst it looks like the docs are already updated to show `redisPassword` as a required field in all Redis component specs.

**Comment by hhunter-ms** [comment]
> @jake-engelberg @berndverst it looks like the docs are already updated to show `redisPassword` as a required field in all Redis component specs.

ope, just realized what we're asking for. I'll update the docs to show as not required.
