### ISSUE TITLE
Adjust red squiggly lines in Secrets management overview page

### ISSUE THREAD

**Issue by RafaelJCamara** [dapr/docs#4208]
**URL of the docs page**
https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-overview/

**Screenshots**
Example image where you can find it:
![image](https://github.com/dapr/docs/assets/52082556/19d2c2a1-a017-4671-b6b7-4e7a503c3ac4)

**Additional context**
There are some red squiggly lines in the images showcased in the aforementioned doc page.

**Comment by RafaelJCamara** [comment]
@hhunter-ms Do you happen to know where I can find the editable diagram files? Is it open to the community? I can only find the current state of the images in _/images_, but I can't find anything suggesting how we can open the images as diagrams and fix them.

**Comment by marcduiker** [comment]
> @hhunter-ms Do you happen to know where I can find the editable diagram files? Is it open to the community? I can only find the current state of the images in _/images_, but I can't find anything suggesting how we can open the images as diagrams and fix them.

@RafaelJCamara the diagrams are located in this [PowerPoint file](https://github.com/dapr/docs/blob/v1.13/daprdocs/static/presentations/Dapr-Diagrams.pptx.zip). You can definitely contribute to this!

Note that the current diagrams in that PowerPoint are not matching the new style from the Dapr slide deck (located in the same folder). A larger effort is required to update all diagrams in this new style, see #4219 . Help is definitely appreciated.

**Comment by RafaelJCamara** [comment]
I've read about this PowerPoint info in the docs, but I was unable to do any modifications on my side (probably something I need to see due to the fact I'm using LibreOffice, not sure).

I'll take a look into trying to contribute for the diagrams, I'm really curious about that.

Thank you so much @marcduiker !
