### ISSUE TITLE
Wrong Java required version in documentation for Quickstart

### ISSUE THREAD

**Issue by ax-pdenti** [dapr/docs#4222]
**Wrong Java min version**

The documentation for the quickstart says "Java JDK 11 (or greater)". However the code for checkout and order processor requires Java 17

```
<java.version>17</java.version>
```

```
<maven.compiler.source>17</maven.compiler.source>
<maven.compiler.target>17</maven.compiler.target>
```

**URL of the docs**

https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/

**Expected content**

Java JDK 17
instead of
Java JDK 11 (or greater)

It cannot be "Java JDK 17 **(or greater)**" because the Lombok version included in spring boot 2.x is not compatible with Java 21 and it should be upgraded (upgrading manually the lombok version to 1.18.30, replacing the one in the spring boot BOM, it works with Java 21). This version is therefore locked to Java 17, not lower, not greater

**Comment by hhunter-ms** [comment]
Blocked on dapr/quickstarts#1042
