### ISSUE TITLE
[Pubsub RabbitMQ] Single Active consumer subscription parameter

### ISSUE THREAD

**Issue by DropSnorz** [dapr/docs#4226]
**What content needs to be created or modified?**

Add the `singleActiveConsumer` parameter to RabbitMQ PubSub Subscription metadata

**Describe the solution you'd like**

**Where should the new material be placed?**

https://github.com/dapr/docs/blob/v1.13/daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

https://github.com/dapr/components-contrib/pull/3437

**Additional context**

**Comment by msfussell** [comment]
@DropSnorz - Please complete this docs issue
