### ISSUE TITLE
Component resiliency example is using app resiliency example

### ISSUE THREAD

**Issue by bibryam** [dapr/docs#4262]
**URL of the docs page**
https://docs.dapr.io/getting-started/quickstarts/resiliency/resiliency-state-quickstart/

**How is it currently worded?**
Component resiliency doc is using app resiliency example

**How should it be worded?**
It should have component example

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
Closing. Resolved. Thanks for the contribution!
