### ISSUE TITLE
Add Python examples in How to: Use the cryptography APIs

### ISSUE THREAD

**Issue by KentHsu** [dapr/docs#4265]
**What content needs to be created or modified?**
Python examples should be added in the How to: Use cryptography page

**Describe the solution you'd like**
Add Python encrypt/decrypt examples in the how-to-cryptography file

**Where should the new material be placed?**
https://docs.dapr.io/developing-applications/building-blocks/cryptography/howto-cryptography/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/python-sdk/pull/719
https://github.com/dapr/python-sdk/pull/729

**Comment by msfussell** [comment]
@KentHsu - Looking forward to this indeed!!

**Comment by msfussell** [comment]
@KentHsu - The best way by far for people to appreciate you wonderful contribution is to provide a quickstart. Would you be able to take this issue on https://github.com/dapr/quickstarts/issues/1052?  @paulyuk  and others can provide guidance.

**Comment by KentHsu** [comment]
Hi @msfussell, I noticed there's already a [PR](https://github.com/dapr/docs/pull/4255) merged to v1.14 for adding Python examples in the how-to-cryptography page. I'll close this issue and turn to work on the issue in quickstart. Thank you for pointing this out. I'll reach out if I get stuck.
