### ISSUE TITLE
Google Analytics error running website locally

### ISSUE THREAD

**Issue by rochabr** [dapr/docs#4281]
**Describe the bug**

Following the steps to run the website locally, hugo returns the following error after `hugo server`:

```
ERROR render of "404" failed: "/Users/rocha/Developer/dapr-docs/daprdocs/themes/docsy/layouts/_default/baseof.html:4:7": execute of template failed: template: 404.html:4:7: executing "404.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:52:16: no such template "_internal/google_analytics_async.html"
ERROR render of "page" failed: "/Users/rocha/Developer/dapr-docs/daprdocs/themes/docsy/layouts/docs/baseof.html:4:7": execute of template failed: template: docs/single.html:4:7: executing "docs/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:52:16: no such template "_internal/google_analytics_async.html"
```

**Steps to reproduce**
Follow the instructions on https://github.com/dapr/docs/blob/v1.13/README.md#environment-setup without a dev container.

**Expected behavior**
The website is supposed to start on localhost:1313

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: Apple M3 Pro
 - OS: Sonoma 14.5

**Additional context**
I was able to fix the issue by:

1 - Update Hugo and docsy
2 - Remove the Google analytics reference from /daprdocs/themes/docsy/layouts/partials
3 - Fix URLs on pluggable-components-registration.md line 41 and nr-kubernetes.md  line 38

Since these were workarounds, they were not pushed to the upstream.

**Comment by salaboy** [comment]
I am hitting the same issues.

Ok for: 

`Remove the Google analytics reference from /daprdocs/themes/docsy/layouts/partials`

I removed in `head.html` the following code: 
```
{{/* To comply with GDPR, cookie consent scripts places in head-end must execute before Google Analytics is enabled */ -}}
<!--{{ if hugo.IsProduction -}}-->
<!--  {{ if hasPrefix .Site.GoogleAnalytics "G-" -}}-->
<!--    {{ template "_internal/google_analytics.html" . -}}-->
<!--  {{ else -}}-->
<!--    {{ template "_internal/google_analytics_async.html" . -}}-->
<!--  {{ end -}}-->
<!--{{ end -}}-->
```
