### ISSUE TITLE
Dapr and service meshes guidance is missing

### ISSUE THREAD

**Issue by CharlesNadolski** [dapr/docs#4319]
**Describe the bug**
When using to the latest version of the dapr docs, when I navigate to the "Dapr and service meshes" article at https://docs.dapr.io/concepts/service-mesh/ the guidance is missing with the error 
```
404: Not Found

We couldn’t find that page, please check the URL and try again.
```

**Steps to reproduce**
1. Search of "dapr vs service mesh" or use an existing bookmark of the "Dapr and service meshes" documentation
2. Navigate to https://docs.dapr.io/concepts/service-mesh/
3. See 404 error

**Expected behavior**
View a well-documented comparison of dapr and service meshes. Includes a nice Venn diagram showing the capabilities of dapr versus the capabilities of a service mesh, and where they overlap.

**Workaround**
You can still get to the information with many extra clicks by
1. navigating to https://docs.dapr.io/
2.  Selecting the prior version of the documentation such as v1.13
3. Selecting "Concepts"
4. Selecting "Service meshes"

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: greater or equal to v1.14

**Comment by msfussell** [comment]
This article has been moved to the FAQ section here https://docs.dapr.io/concepts/faq/service-mesh/ since it was not a core Dapr Concept more of FAQ

**Comment by CharlesNadolski** [comment]
Thanks for the new location, that works for me.
