### ISSUE TITLE
[Bindings][Azure BlobStorage] Multiple warning logs when uploading to Storage Account via BlobStorage output bindings

### ISSUE THREAD

**Issue by ssi-spyro** [dapr/docs#4399]
Hello. I am using storage account output bindings (https://docs.dapr.io/reference/components-reference/supported-bindings/blobstorage/#create-blob) and its create method via .Net SDK. After implementation I noticed a lot of warnings:
"metadata key dapr-grpc-accept-encoding contains disallowed characters, sanitized to daprgrpcacceptencoding".

Full log:
{
    "app_id": "<app-id>",
    "component": "<component-name> (bindings.azure.blobstorage/v1)",
    "instance": "<instance>",
   "level": "warning",
    "msg": "metadata key dapr-grpc-accept-encoding contains disallowed characters, sanitized to daprgrpcacceptencoding",
    "scope": "dapr.contrib",
    "time": "2024-09-24T14:13:51.758941621Z",
    "type": "log",
    "ver": "1.13.5"
}

Maybe someone knows how to eliminate these logs ? None of those keys in metadata are added by my app code. I found the proper DAPR source code where this log  is thrown: https://github.com/dapr/components-contrib/blob/main/common/component/azure/blobstorage/request.go#L85
It looks like these keys were added by DAPR (under the hood) and also sanitized by DAPR with warning.

I observed the same warning logs for the following keys: dapr-grpc-accept-encoding, request-context, request-id, content-type etc. (all with '-' sign).

Does anyone have any idea ? Thank you for support.

**Comment by ssi-spyro** [comment]
@yaron2 suggestion from Discord:
`yaron2 — 10/03/2024 5:54 PM
Thanks, I looked at the code and I think this shouldn't be a warning log. Feel free to open a PR to components-contrib that either makes this a Debug log or removes it entirely`

**Comment by hhunter-ms** [comment]
Thank you @ssi-spyro - I'll close this issue for now, since this doesn't seem to be a docs issue. Feel free to reopen if any changes do need to be made to docs.
