### ISSUE TITLE
Observability page YouTube timestamp link is set to secret management instead of observability

### ISSUE THREAD

**Issue by Jeroen-VdB** [dapr/docs#4434]
**Describe the issue**
The link on the observability page references the secret management section of the demo video instead of observability.

**URL of the docs**
[](https://docs.dapr.io/operations/observability/)

**Expected content**
The link should reference the Observability timestamp of the video.

**Screenshots**

**Additional context**

**Comment by hhunter-ms** [comment]
Closing as this was resolved - thank you!
