### ISSUE TITLE
Cannot view installation steps for anything but Linux

### ISSUE THREAD

**Issue by travis-leith** [dapr/docs#4454]
**Describe the bug**

The installation steps for anything but Linux is not viewable.

**Steps to reproduce**

Navigate to https://docs.dapr.io/getting-started/install-dapr-cli/#tabs-3-windows

Try to click on a non Linux tab for step 1.

**Expected behavior**

It should display the installation steps for the selected OS. Instead, nothing happens. It only displays Linux.

**Screenshots**

![image](https://github.com/user-attachments/assets/6299cbd4-0c9b-4ca2-9099-0d2731a6fa1e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Comment by hhunter-ms** [comment]
@msfussell I have the same OS and browser, but the tabs work for me. do the tabs work for you?

**Comment by travis-leith** [comment]
btw, I am able to use the tabs now. Not sure if anything changed at the website, or if something changed for me, but since this is working for me, I will close the issue.
