### ISSUE TITLE
AKS with virtual kubelet/ACI support for DAPR

### ISSUE THREAD

**Issue by raghavender7** [dapr/docs#463]
Are there plans to support DAPR for ACI instances?

**Comment by yaron2** [comment]
Check out this repo for Dapr and ACI:

https://github.com/mchmarny/dapr-demos/tree/master/dapr-aci

**Comment by mchmarny** [comment]
BTW, somewhat related, there is a series of interesting use-cases that Dapr as an API server in ACI enables. Here is a small demo of Dapr as a API server with token auth for any of its 70+ components available in Dapr. You can do that in ACI or directly in AKS.

https://github.com/mchmarny/dapr-demos/tree/master/component-api

**Comment by orizohar** [comment]
@RicardoNiepel @yaron2 - what is the status of this? is there a clear docs action here that we can track?

**Comment by yaron2** [comment]
> @RicardoNiepel @yaron2 - what is the status of this? is there a clear docs action here that we can track?

Dapr works with Virtual Kubelet (ACI) today, I don't think this needs special documentation, as the Kubernetes docs cover it.

In regards to ACI, considering we don't have other hosted platforms docs today outside of Kubernetes and Self-Hosted, I'd suggest to not insert ACI specific documentation as of now.

**Comment by AaronCrawfis** [comment]
Closing as we don't have any docs for AKS or other hosting providers. Will revisit later if needed
