### ISSUE TITLE
Improve FAQ example about actors

### ISSUE THREAD

**Issue by eNeRGy164** [dapr/docs#467]
The FAQ chapter [Differences between Dapr from an actor framework](https://github.com/dapr/docs/blob/master/FAQ.md#differences-between-dapr-from-an-actor-framework) has an example that is not making much sense to me.

### Current text

> Creating a new actor follows a local call like http://localhost:3500/v1.0/actors/<actorType>/<actorId>/meth... for example http://localhost:3500/v1.0/actors/myactor/50/method/getData to call the getData method on myactor with id=50

### Issues

1. It starts about creating a new actor, but the URL is resembling more calling a method.
1. The placeholders in the URL are not escaped so they don't end up in the rendered page.
1. The example describes calling a method on an instance of an actor, not just creating an actor.

### Solutions

It's not clear what the original intention was behind this example, as it is already this way in the original [wiki](https://github.com/dapr/dapr/wiki/FAQ). 
I see 3 possible solutions to fix this paragraph.

1. Change first sentence to make it about calling a method, escape placeholders and fix URL.
1. Escape placeholders, fix URL and change sample to only create an instance, remove mention of method.
1. Escape placeholders, fix URL and add sample about creating an instance of an actor. Add additional text and URI about calling a method on an actor fitting the existing example.

My suggestion is to pick the first one, as it's enough to prove the platform agnostic possibility to call actors. If one would need more details to work with actors, the FAQ is not the place to be.

If there is consensus, I like to put a PR in.

**Comment by yaron2** [comment]
Thanks for bringing this up.

As Dapr had Virtual Actors, calling an actor creates it automatically if it's not activated already, so there's no explicit activation.

With that in mind, it would be great if you fixed this with a PR.

**Comment by eNeRGy164** [comment]
Ah, that explains more the intention behind the example. I will pick this up.
