### ISSUE TITLE
Change Distributed tracing to Observability in concepts

### ISSUE THREAD

**Issue by youngbupark** [dapr/docs#470]
Since we introduced Metrics/Logs in 0.5.0 release, we need to change the list of building block concept in https://github.com/dapr/docs/tree/master/concepts#building-blocks.

Here is the options we discussed:
1. Remove distributed tracing concept and building block
2. Change Distributed tracing to Observability

**Comment by youngbupark** [comment]
@Haishi2016 @msfussell Any opinions ?

cc/ @yaron2 @amanbha

**Comment by Haishi2016** [comment]
Sounds fair.

**Comment by yaron2** [comment]
/cc @orizohar 

I would go for option 2, as Observability does not have a user facing API as required by other building blocks.

**Comment by msfussell** [comment]
Yes. We should change this to observability. I have already started this approach in the diagrams
