### ISSUE TITLE
Add namespace metadata to all deployment yaml example

### ISSUE THREAD

**Issue by youngbupark** [dapr/docs#501]
Problem:

Since we support namespace scoping for component config, the deployment yamls in some of documents specify the namespace metadata specifically, which makes user confused to configure component correctly.

**Comment by youngbupark** [comment]
cc/ @yaron2 @orizohar @msfussell

**Comment by orizohar** [comment]
By yaml examples you mean the yamls we ship with the samples?

**Comment by youngbupark** [comment]
> By yaml examples you mean the yamls we ship with the samples?

Not only for samples. For example, if you look at howto docs, there are some component config examples. We may need to add namespace metadata to all examples.

**Comment by mchmarny** [comment]
Going through all the `component` yaml samples in the how-to section of docs, I wonder if it may be cleaner to put a generic how-to after each example. Something like this

To apply the above component only to dapr instances running in a specific namespace you will need to append the `namespace` attribute to the component `metadata`:

```yaml
metadata:
  namespace: production
```

@youngbupark @msfussell thoughts?

**Comment by mchmarny** [comment]
BTW, since the component metadata `namespace` is diff from the k8s `namespace` how can we clearer the expected outcome when user `kubectl apply -f comp1.yaml -n dev` and `comp1.yaml` has `namespace: prod` metadata attribute?

**Comment by yaron2** [comment]
> BTW, since dapr runtime instance can only access components that have been deployed to the same `namespace` ([doc](https://github.com/dapr/docs/tree/master/howto/components-scopes)) and the dapr component metadata `namespace` collides with the k8s `namespace`, how can we make clearer the expected outcome when user `kubectl apply -f comp1.yaml -n dev` and `comp1.yaml` has `namespace: prod` metadata attribute on k8s?

The namespaces are the same

**Comment by mchmarny** [comment]
Ack on this being not specific to k8s. Just for clarity though... component in `comp1.yaml` with 

```yaml
metadata:
  namespace: prod
```
applied in k8s with

`kubectl apply -f comp1.yaml -n dev`

would be deployed into cluster namespace `dev` and accessible only to dapr instance running in cluster namespace `prod`. Even dapr running in the `dev` namespace would not be able to access this component. Correct?

**Comment by yaron2** [comment]
if the component is deployed into namespace `dev`, it will only be visible to pods from the `dev` namespace.

**Comment by mchmarny** [comment]
OK, so now back to the original issue. For components, should we go through all the examples and inject namespace or can we have something more generic like this?

> Optionally, component's namespace can be set using metadata (see example below). And, when deploying to Kubernetes, the namespace can also be specified using a flag (e.g. `kubectl apply --file comp1.yaml --namespace dev`) which will override the namespace specified in component's YAML. You can learn more about scoping components using namespaces [here](https://github.com/dapr/docs/tree/master/howto/components-scopes)

```yaml
metadata:
  namespace: production
```

**Comment by yaron2** [comment]
> OK, so now back to the original issue. For components, should we go through all the examples and inject namespace or can we have something more generic like this?
> 
> > Optionally, component's namespace can be set using metadata (see example below). And, when deploying to Kubernetes, the namespace can also be specified using a flag (e.g. `kubectl apply --file comp1.yaml --namespace dev`) which will override the namespace specified in component's YAML. You can learn more about scoping components using namespaces [here](https://github.com/dapr/docs/tree/master/howto/components-scopes)
> 
> ```yaml
> metadata:
>   namespace: production
> ```

lgtm

**Comment by mchmarny** [comment]
PR #552 in to address this in dapr/docs
