### ISSUE TITLE
Docs appear incorrect for using CLI with NATS

### ISSUE THREAD

**Issue by dwaynebradley** [dapr/docs#505]
## Ask your question here
In the How-To section for configuring Dapr with NATS (https://github.com/dapr/docs/blob/v0.6.0/howto/setup-pub-sub-message-broker/setup-nats.md), it appears that the docs may be a little out of date. In the `Running locally` section at the bottom of the page, it currently states:

"replace the contents of `messagebus.yaml` file"

When I run `dapr run` with v0.6.0, it is creating `pubsub.yaml` instead of `messagebus.yaml`. I believe the docs should state something similar to the following:

"replace the contents of `pubsub.yaml` (or `messagebus.yaml` for Dapr < 0.6.0) file"

The same thing appears true for several of the other pub/sub options as well. If this is the case, I'd be happy to create a PR for it.

**Comment by yaron2** [comment]
Hi, please create a PR to update this. Greatly appreciated, thanks!

**Comment by dwaynebradley** [comment]
Done. Just let me know if I need to tweak anything.
