### ISSUE TITLE
runtime questions?

### ISSUE THREAD

**Issue by manjeetbhatia** [dapr/docs#507]
I've deployed a sample app using dapr on local machine and have two question?
does it compile any code as well ? what all it covers in deployment? compilation/configuration etc?

what is cloud choice based on? is whatever user wants or based on metrics it makes decision?

**Comment by msfussell** [comment]
@manjeetbhatia Dapr is a side car that provides [capabilities](https://github.com/dapr/docs/tree/master/overview#microservice-building-blocks-for-cloud-and-edge) at runtime. It does not do any compilation on your code

For hosting environment, Dapr runs on [different hosting platforms](https://github.com/dapr/docs/tree/master/overview#any-language-any-framework-anywhere) although currently kubernetes is preferred and you can use this on any cloud (for example Azure AKS, AWS EKS, Google GKE). This is course is based on your choice of cloud provider.

**Comment by manjeetbhatia** [comment]
thanks for the answer, appreciate it. so basically pretty much middle ware stuff. it also mentions securely access secrets from application, does it create secrets for applications? does it use any encryption/compression libraries at all?

**Comment by msfussell** [comment]
You cannot create secrets currently and unlikely to, due to the large security threats this opens up.   when you say "does it use any encryption/compression libraries at all?" what scenario are you referring to?
