### ISSUE TITLE
[Pub-Sub] Id property mandatory for messages published to be transformed into cloud events format

### ISSUE THREAD

**Issue by corinaivanov** [dapr/docs#509]
Published events are not wrapped to cloud events unless they have Id property.

I noticed that messages published with dapr-cli into a certain topic must have an Id property in order to be wrapped into cloud event envelope. Otherwise payload is sent directly to the application but the content-type is still 'application/cloudevents+json'.
I think this should be stimulated in the documentation or otherwise changed in Dapr implementation.

**Comment by orizohar** [comment]
@wcs1only - can you take a look at this and recommend what is the right docs action needed here? (page to update plus blurb)

**Comment by AaronCrawfis** [comment]
@artursouza is this issue still valid? Or has the behavior changed?

**Comment by matthewgaim** [comment]
I'll be taking a look at this

**Comment by artursouza** [comment]
Dapr did not support raw payload until very recently and it must be enabled via metadata. The repro steps for this issues would help a lot to understand the problem first.

**Comment by matthewgaim** [comment]
I just ran through [this tutorial](https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/) when the ID was in the message and not in the message, it got wrapped in a CloudEvent envelope both times.

**Comment by hhunter-ms** [comment]
resolved in docs
