### ISSUE TITLE
Update docs for Azure Event Hubs pubsub component

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/docs#513]
## Describe the proposal

Azure Event Hubs is added as one of the pubsub components [here](https://github.com/dapr/components-contrib/pull/242). This should be added to the list of pubsubs [here](https://github.com/dapr/components-contrib/blob/master/pubsub/Readme.md) and docs should be updated wherever necessary. New doc with instructions to setup Azure Event Hubs for pubsub should be added [here](https://github.com/dapr/docs/tree/master/howto/setup-pub-sub-message-broker).

**Comment by pruthvidhodda** [comment]
cc: @msfussell @orizohar

**Comment by yaron2** [comment]
Closed with https://github.com/dapr/components-contrib/pull/320

**Comment by pruthvidhodda** [comment]
>New doc with instructions to setup Azure Event Hubs for pubsub should be added [here](https://github.com/dapr/docs/tree/master/howto/setup-pub-sub-message-broker).

@yaron2 shouldn't we also add this doc to setup Azure Event Hubs?

**Comment by yaron2** [comment]
Yes, I'm working on a PR
