### ISSUE TITLE
Actor Save State API Documentation is not consistent with the actual behavior

### ISSUE THREAD

**Issue by wenhzha** [dapr/docs#523]
I was following the [Actor .NET Sample code](https://github.com/dapr/dotnet-sdk/tree/916d552279add0c9745f625dc050cb7771eec4ca/samples/Actor) to verify the Actor API endpoints. I found the actual behavior for **Actor State Management**  is not consistent with the documentation. 

## Expected Behavior
[The documentation ](https://github.com/dapr/docs/blob/master/reference/api/actors_api.md#save-actor-state) is expecting the following endpoint and request format for **save actor state** operation. 

```http
POST/PUT http://localhost:<daprPort>/v1.0/actors/<actorType>/<actorId>/state
```
Value of the key is passed as request body:
```shell
{
  "key": "value"
}
```

To give a more concrete example for more clarity, suppose I intend to get back the following data when calling the GET endpoint, I need to save the state beforehand.

_GET endpoint to retrieve saved state:_
```http
GET http://localhost:<daprPort>/v1.0/actors/<actorType>/<actorId>/state/my_data
```
_Expected Returned Value:_ 
```shell
{ "PropertyA": "a", "PropertyB": "b"}
```

According to the documentation, for the save operation, the endpoint and request body I need to pass along is the following:

```http
POST/PUT http://localhost:<daprPort>/v1.0/actors/<actorType>/<actorId>/state
```
_Request body:_
```shell
{
  "my_data": { "PropertyA": "a", "PropertyB": "b"}  // my_data is the state key
}
```

## Actual Behavior
However, I found out the save request above returned `201 Created` but the state was not actually persisted. I played around with different requests, and the working model that can successfully persist the state is the following:

```http
POST/PUT http://localhost:<daprPort>/v1.0/actors/<actorType>/<actorId>/state/my_data
```
_Request body:_
```shell
{ "PropertyA": "a", "PropertyB": "b"}
```
I also tried to use the[ Actor State Transaction API ](https://github.com/dapr/docs/blob/master/reference/api/actors_api.md#actor-state-transactions) but ran into the same issue where `201 Created` is returned without successful state persistence. 

## Steps to Reproduce the Problem
Leveraging the sample Actor code, the above description should cover the repo steps required. Is there any behavior change on the actor state management feature left the documentation outdated or is there a tracked regression?

**Comment by amanbha** [comment]
@wenhzha State Transaction api is the only api to be used with actors for saving state. What state store are you using for Actors.

**Comment by wenhzha** [comment]
I am using the redis and configured it to be the actor state store following [this guide. ](https://github.com/dapr/dapr/blob/master/docs/decision_records/api/API-008-multi-state-store-api-design.md) 

So [Save Actor State API](https://github.com/dapr/docs/blob/master/reference/api/actors_api.md#save-actor-state) and   [Actor State Transaction API](https://github.com/dapr/docs/blob/master/reference/api/actors_api.md#actor-state-transactions) is no longer supported?

**Comment by amanbha** [comment]
the transaction api is still supported https://github.com/dapr/docs/blob/master/reference/api/actors_api.md#actor-state-transactions

**Comment by AaronCrawfis** [comment]
Closing an non-reproducible, please let us know if you face this again
