### ISSUE TITLE
Broken link in metrics.md

### ISSUE THREAD

**Issue by orizohar** [dapr/docs#524]
## Expected Behavior

In https://github.com/dapr/docs/blob/master/concepts/observability/metrics.md 
Metric list link should link to README listing the metrics collected by Dapr.

## Actual Behavior

Metrics list link is broken. Doesn't seem to be a README listing metrics under /pkg/diagnostics in the dapr repo.

## Steps to Reproduce the Problem

Click "Dapr runtime metric list" link

**Comment by orizohar** [comment]
@youngbupark - has the metric list doc moved to a new place?

**Comment by youngbupark** [comment]
> @youngbupark - has the metric list doc moved to a new place?

Yes. I missed to update the doc. I created the pr - https://github.com/dapr/docs/pull/525

Please review it :)
