### ISSUE TITLE
Dapr init is not working on  Ubuntu 18.04 Azure VM

### ISSUE THREAD

**Issue by heavenwing** [dapr/docs#526]
## Expected Behavior
Dapr init will run successfully.

## Actual Behavior
report error info : could not connect to Docker. Docker may not be installed or running
But docker is running actually. 

## Steps to Reproduce the Problem
1, Create a Ubuntu 18.04 VM in Azure
2, Install docker on this VM with this instruction:  https://docs.docker.com/engine/install/ubuntu/
3, Install dapr cli 0.6 on this VM

Docker info is below:
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-1035-azure
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.83GiB
 Name: vso-host
 ID: E6ZP:WDY5:YAEJ:YYDX:7IUM:JSQ4:QF6V:7QIK:Y4CL:NNHO:DXFN:KVHL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by AaronCrawfis** [comment]
Closing as stale. Please reopen if you are still experiencing this issue
