### ISSUE TITLE
Documentation on Health Observability

### ISSUE THREAD

**Issue by codeputer** [dapr/docs#527]
## Expected Behavior

Please document how to TURN off the health settings.   There is some documentation on the YAML file, but not where its locations, and the best practice to turn it way down or off.

## Actual Behavior

Noise to signal ratio is way too high - console scrolls without ability to view statements higher in log as the console resets each time - very frustrating!

## Steps to Reproduce the Problem

run my docker image via:
dapr run --port 3500 --app-id xxxxx --app-port 5000 dotnet run via a command line in windows
and the console is polluted with Health Check notifications...

**Comment by pkedy** [comment]
I do remember when these logs would fill up the console but I cannot find evidence that this is still an issue. In talking w/ @rynowak, he mentioned it could be that asp.net core could have been logging these health requests.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

It's all config driven. aspnet core will log each request if you set `Microsoft` to `Info`. The default for a new project is `Microsoft` is at `Warning`.

**Comment by orizohar** [comment]
Based on the above comment, seems like this behavior is no longer an issue. If this is incorrect issue can be reopened.
