### ISSUE TITLE
[Proposal] How To: Using PubSub across namespaces

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/docs#528]
## Describe the proposal

Add a How To for "Using PubSub across namespaces".

Using multiple K8s namespaces in production is a very common case, e.g.
- split a large system across multiple k8s namespaces (single namespace for each sub system, containing multiple microservices)
- each K8s namespace is handled by another team
- apply different resource limits etc. on k8s namespace level

On the same time development teams want to use the Dapr PubSub component for communicating between the sub systems.

This can be achieved with using the same PubSub component with the same topics in different namespaces.
Best practices and pitfalls, if any, should be documented in this HowTo.

**Comment by artursouza** [comment]
@RicardoNiepel , please check PR #541
