### ISSUE TITLE
Azure Storage Queue Binding Documentation

### ISSUE THREAD

**Issue by WillEastbury** [dapr/docs#532]
## Storage Secret Management
It's not necessarily clear that the storage key if placed into a secret in the K8S secret store, needs to be Base64 encoded again in the yaml manifest file, even though it is already in a base64 encoded format and the error isn't particularly intuitive.

In particular this refers to the storageAccessKey parameter under the spec/metadata path.

I'm happy to submit a minor PR to correct this.,.

**Comment by msfussell** [comment]
@WillEastbury - Yes, please, can you push a PR for this, that would be great.

**Comment by WillEastbury** [comment]
Done. https://github.com/dapr/docs/pull/676
