### ISSUE TITLE
Unable to setup AzureIdentity for Azure Key Vault

### ISSUE THREAD

**Issue by agdelarue** [dapr/docs#533]
## Expected Behavior

Ability to setup Azure Key Vault with Managed Identity according to docs here:
https://github.com/dapr/docs/blob/master/howto/setup-secret-store/azure-keyvault-managed-identity.md

The following command should properly deploy AzureIdentity to Kubernetes:
kubectl apply -f azure-identity-config.yaml

## Actual Behavior

error: error validating ".\\azure-identity-config.yaml": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false

## Steps to Reproduce the Problem

Follow the instructions on this page:
https://github.com/dapr/docs/blob/master/howto/setup-secret-store/azure-keyvault-managed-identity.md

See point 8. which has the yaml file for 'azure-identify-config.yaml', it doesn't have an apiVersion for the kind 'AzureIdentity' and kubectl apply fails on that.

**Comment by yaron2** [comment]
Thanks for reporting, I just merged a PR to fix this. There was a missing `apiVersion` field. Please re-open if you're having any more issues.
