### ISSUE TITLE
Update the getting started doc

### ISSUE THREAD

**Issue by arschles** [dapr/docs#568]
## Describe the proposal

Similar to the #567, I propose that we update the [getting started doc](https://github.com/dapr/docs/tree/master/getting-started) into the below sections. I believe this layout will provide an easier and more straightforward path to follow for a newcomer. I also believe it's easier to glance at to get an idea of how much work you'll need to do before  you can see code running.

---
# Getting Started

<same wording that's in this section already>

## Step 1: Core Concepts

Before you set up your local environment to run Dapr, it's important to understand Dapr's two core concepts:

- **Building blocks** are a collection of features that implement distributed system capabilities, such as pub/sub, state management, resource bindings, and distributed tracing.
- **Components** encapsulate the implementation for a building block API. For example, Dapr includes Redis, Azure Storage, Azure Cosmos DB, and AWS DynamoDB for implementations of the state management building block API. Many of the components are pluggable so that one implementation can be swapped out for another.

For detailed information on building blocks and components, see the [core concepts documentation](https://github.com/dapr/docs/tree/master/concepts)

## Step 2: Set up Your Development Environment

<same text that's already there>

## Step 3: Hello World for Dapr

Link to https://github.com/dapr/samples/tree/master/1.hello-world

## Additional Information

<same text as currently under [next steps](https://github.com/dapr/docs/tree/f52f554c85b7981c2b90b808a51f3843f3cb63af/getting-started#next-steps), except for the hello world link>

**Comment by AaronCrawfis** [comment]
@arschles we just pushed an update to our getting started guide at https://docs.dapr.io/getting-started/. Does this address your issue? The left nav bar also shows a "Concepts" item next to getting started to cover your step 1.

**Comment by arschles** [comment]
@AaronCrawfis wow, yes that's a much better layout and flow. Thanks :+1:
