### ISSUE TITLE
Provide clear info on optional vs required parameters in dapr spec files

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#584]
## Describe the proposal
For example, I would assume that the sqs binding is able to use implicit credentials and as such, the access key and secret shouldn't be required. Docs should list clearly which config are required and which are optional.

**Comment by trondhindenes** [comment]
I'd like to ping maintainers on this.
I'm ready to document the stuff needed after https://github.com/dapr/components-contrib/issues/339, but i _cant_ until there are some standards for documenting required vs optional variables. 

As far as I can see the big weak spot in dapr right now is its documentation, so hopefull the maintainers agree with me that it makes sense to get some structure around this so that the community can help improving the docs.

**Comment by yaron2** [comment]
Would specifying in the YAML examples for each binding spec the required fields make it more clear in your opinion?

Some of the binding specs have that today, for example: https://github.com/dapr/docs/blob/9d1919ef9485e140cfcdeebd676571e9a2cc0c0e/reference/specs/bindings/twilio.md

If we want to decide that's the way we want to communicate required fields, then we can go ahead and make the rest consistent.

**Comment by trondhindenes** [comment]
yes I think that's a very good way of indicating. Happy to follow the same for the aws stuff.
I'm also wondering about creating a "shared" doc for all the aws-related stuff (others might need this too): since we've standardized the way these bindings etc authenticate it makes sense to write a small piece of doc about that, so that each aws-related binding can just point to that page in order to explain how the auth flow works, when to use the "endpoint" attribute etc. Would it make sense to create a `providers/aws.md` or similar path in the docs repo where I can place this "shared" documentation?

**Comment by AaronCrawfis** [comment]
I think we should follow a format similar to #1018 where we use a table

**Comment by AaronCrawfis** [comment]
Example: https://v1-rc2.docs.dapr.io/operations/components/component-schema/

**Comment by trondhindenes** [comment]
Fixed by #1088
