### ISSUE TITLE
Are statestore and messagebus files needed?

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#586]
## Ask your question here
I wanted to try out the sqs binding. I configured a yaml file with the required stuff, and hit `dapr run...`. I noticed that dapr created two extra files in my `components` folder, `messagebus.yaml`and `statestore.yaml`. I don't need these (I think) but if I delete them they're just re-created.

I think this goes back to dapr still being a kind of black box regarding what components are actually needed, what needs to be set up etc. I know I've commented on this before, but I still think the project should take the time to properly document how everything fits together, including the "base setup" both for k8s-based and non-k8s based setup. For example, I can see that the non-k8s setup sets up a redis container but I have no idea what that container is used for or if I can delete it. 

I think dapr has potential to be something really great, but I'm finding it very difficult to get going because the documentation is still too thin and disorganized.

**Comment by trondhindenes** [comment]
There is some documentation here https://github.com/dapr/docs/blob/master/walkthroughs/darprun.md regarding the sequence of events when dapr run is issued, but it doesn't mention why I can't remove those files - why do I HAVE to have a state store if my app doesn't need one?

**Comment by yaron2** [comment]
> There is some documentation here https://github.com/dapr/docs/blob/master/walkthroughs/darprun.md regarding the sequence of events when dapr run is issued, but it doesn't mention why I can't remove those files - why do I HAVE to have a state store and a messagebus if my app doesn't need them?

This was talked about just 2 days ago in a maintainer meeting. We are making changes to the CLI that will not recreate the yaml components.

The purpose of the Dapr CLI is to provide an easy getting started for a local dev machine, using Docker and Redis. The CLI will be updated to allow a user to start minimally and add functionality as needed.

**Comment by trondhindenes** [comment]
gotcha. My 5 cents:
make the cli support 3 different flows:
`install` for setting up the environment (similar to the current `init`)
`init` for initializing the project. Init could create the `components` dir, default files etc, check that `install` has been run globally etc
`run` for running. Run would never create files, otherwise similar to the current functionality.

This would allow me to run `init` on a project, get rid of / adjust the files in `components` and then invoke `dapr run` without risking that any files got re-created.

**Comment by plaisted** [comment]
I've just started playing around with Dapr but found this confusing as well. The documentation led me to believe Dapr was as simple as a sidecar executable + configuration for the backend building blocks that your app will use. After downloading I see it requires docker (locally at least) and something about a placement service (how is this supposed to be run in a real environment?) and it created pubsub and statestore implementations (maybe they aren't needed if my app doesn't need them? or maybe they are used internally by the sidecar / placement service?).

**Comment by AaronCrawfis** [comment]
The original issue has been addressed in the CLI. The Dapr CLI will now create a components directory, and can be overridden with a custom components directory. More info here: https://docs.dapr.io/getting-started/install-dapr/
