### ISSUE TITLE
Add Docker Compose sample and docs

### ISSUE THREAD

**Issue by jjcollinge** [dapr/docs#589]
Once we've merged https://github.com/dapr/dapr/pull/1577 and https://github.com/dapr/components-contrib/pull/341 we should add a sample and some documentation for using dapr with Docker compose locally.

## Sample
I propose the sample is called `9.hello-docker-compose` and builds on the `1.hello-world` sample but uses docker compose.

<del>Something to decide is how best to run daprd + the apps in docker-compose. Do we run daprd as a separate container for each app (sidecar style without pods) or do we publish new docker images with daprd + dapr cli baked in and run both processes in the single container similar to how I did here: https://github.com/dapr/dapr/pull/1577#issuecomment-630643777. If we do it as separate containers we'd have to update the samples to use an ENV var to set the dapr hostname or use tunnels/redirects.</del>
*UPDATE*: I think being consistent with the container sidecar pattern is best, in docker-compose this can be achived using `network_mode: "service:<service-name>"`

## Docs
We should document usage and the user scenarios this enables, including:
- Standalone docker containers + docker networks (optionally docker-compose and/or docker-swarm) dapr deployments
- Multi-VM dapr deployments
- Multi-device (IoT) dapr deployments
- Additional orchestrators that support mDNS

> Note we should document the fact that mDNS is P2P and although its possible to register multiple instances under the same service entry the distribution of traffic across the instances is undefined (faster answer)

**Comment by youngbupark** [comment]
@yaron2 @orizohar @amanbha @msfussell 

@jjcollinge did great job to use host address for multicast dns for self-host mode, which allows user to run daprd via docker-compose. IMO, we need to extend our docs and samples to cover this change. Can you please review his proposal and give some comments on it ?

**Comment by databasedav** [comment]
@jjcollinge I think doing separate containers is better so multiple Dockerfiles don't have to be maintained during development before deploying to k8s; adding a bunch of daprd services to a compose file sounds much nicer and more modular.

**Comment by jjcollinge** [comment]
@databasedav I agree - I found a neat little way to mimic a sidecar pattern in docker compose and I've created a WIP PR: https://github.com/dapr/samples/pull/211
