### ISSUE TITLE
Describe how to visualize and query the stored state including actor state

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#6]
These articles describes how to view/query the state data for both Redis and CosmosDB whether the state is stored via the /state call or via actors. Many people have asked what the schema is like and how to do the query.

**Comment by amanbha** [comment]
Closing it as this is documented:
https://github.com/dapr/docs/blob/master/reference/api/actors_api.md#querying-actor-state-externally
https://github.com/dapr/docs/tree/master/concepts/state-management#querying-state-store-directly
