### ISSUE TITLE
One dapr container pr application code, or can it be shared? 

### ISSUE THREAD

**Issue by mslot** [dapr/docs#603]
I am reading the docs, and find this really exiting. I can't wait to get home and try this, but I can't seem to find any docs on if there is a 1:1 between the application code, and a dapr instance, or if a dapr instance can be shared between more than one piece of application code.

Put in another way: Should I create one dapr container pr container that runs my application code, or can the dapr container be shared between multiple containers that runs my application code? What are the best practices here?

**Comment by yaron2** [comment]
Hi @mslot, Dapr is designed to run 1:1 with your application, so a Dapr instance per process or container.

**Comment by mslot** [comment]
We need to to specify this in the concept readme. It is depictured somehow, but some words on it, would be better. Or am I not seeing it written?

**Comment by yaron2** [comment]
Is it not clear from the first sentence here?

https://github.com/dapr/dapr/blob/master/README.md#how-it-works

If not, how do you think we could rephrase it better?

**Comment by mslot** [comment]
@yaron2 I personally don't understand the word "compute unit". What level are we talking? Pod, container, node, VM? Maybe another word would be sufficient? I am not a native english speaker, so I am maybe not the right to decide, but I think "compute unit" doesn't quite pinpoint it. I will try to put some thought into it, and come back :)
