### ISSUE TITLE
Add a sample for TypeScript applications

### ISSUE THREAD

**Issue by subesokun** [dapr/docs#607]
## Describe the proposal

It'd be great if there is also a sample available for a TypeScript based Dapr application.

Currently I'm running the app via

```json
{
  "name": "my-app",
  ...
  "scripts": {
    "dapr": "dapr run --app-id my-app --app-port 3000 ts-node-dev lib/main.ts"
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    "ts-node-dev": "^1.0.0-pre.44",
    ...
  }
}
```

```bash
npm run dapr
```

but not sure if this is the most elegant / recommended way for running TS based Dapr applications locally.

Btw., having the samples repo and the `docs/howto` section (which again contains samples) is very confusing as I've to search always in two places.

**Comment by orizohar** [comment]
I apologize for the delay in providing guidance here. There were several decisions made on how these kind of contributions should be made. I know you were previously instructed to put this code example in the docs but there has been a recent reorg (see https://github.com/dapr/quickstarts/issues/280) of our samples repositories that makes a much better and natural place for this contribution. The right place for this is the dapr/samples repository, please open a PR there for this. Thank you!

**Comment by subesokun** [comment]
Ok, so we can close this issue here.
