### ISSUE TITLE
Add local secret store how to

### ISSUE THREAD

**Issue by cmendible** [dapr/docs#608]
Add JSON secret store how to as requested in: https://github.com/dapr/components-contrib/pull/328

**Comment by amanbha** [comment]
@cmendible please resurrect this reverted PR as well https://github.com/dapr/docs/pull/625

**Comment by amanbha** [comment]
@cmendible Could you please resurrect the docs PR for this.

**Comment by cmendible** [comment]
@amanbha it's here: https://github.com/dapr/docs/pull/647

**Comment by amanbha** [comment]
Thanks @cmendible .
@orizohar Could you please review PR #647 for local secret store. It has been reviewed earlier for 0.8, its renaming from json to local
