### ISSUE TITLE
Use "reference" documentation for all components/building blocks

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#631]
I just noticed that one of the reasons I have such a big problem navigating dapr docs, is that they're inconsistent:
the "bindings" are documented in the "reference" folder in a very clear and concise way. However, other "building blocks" (is that what they're called?) such as secrets are documented in the form of how-to docs - some in the `howto/get-secrets/README.md` and some in another folder, such as `howto/setup-secret-store/aws-secret-manager.md`. 

Again, I would urge the maintainers to spend some cycles getting dapr docs up to par. Dapr is such an awesome project and it's really a shame that the documentation makes it so hard to use it.

**Comment by trondhindenes** [comment]
just to add to this:
Also noticing that for `bindings`, there's a consice list of supported bindings:
`concepts/bindings/README.md`, which is awesome.    
However, there's no such list for the other building blocks, which there really should be.

IMHO it would be much easier to build a really good doc structure now while the project is relatively small instead of coming back to it later.

**Comment by yaron2** [comment]
@trondhindenes you're right, they have to be consistent. no argument there :)

**Comment by yaron2** [comment]
again, this is a top priority for us now. that and samples.

**Comment by trondhindenes** [comment]
awesome, glad to hear it. I'll stop nagging you with these issues then :-)

**Comment by AaronCrawfis** [comment]
https://docs.dapr.io/operations/components/ contains lists for each component type. Also addressing location as part of #917
