### ISSUE TITLE
Document how to run dapr across multi-machines in self-hosted mode

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#638]
https://github.com/dapr/dapr/issues/1506 issue introduced mDNS support that enables dapr instances on different machines to communicate with each other. One way this can be used is with Docker Compose. 

This topic is how to configure dapr hostname and ports on different machines for Service Invocation, pub/sub and other building blocks to work

**Comment by NexZhu** [comment]
+1 for this

**Comment by kevin100702** [comment]
I have this need. What do I do？

**Comment by AaronCrawfis** [comment]
See https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-overview/

**Comment by geekgao** [comment]
I think the doc is not clearly.
I have a question. Regarding debugging code among developers, for example, I want to debug my program locally line by line. How should I communicate with other Dapr services?

**Comment by bcraun** [comment]
I'm not finding any documentation for configuring cross-machine communication when **_not_** using self-hosted mode. I have a DAPR broker running in k8s which has topics that need to be accessible (both subscribe and publish) from a self-hosted DAPR service running on a different machine. Is this supported? 
```
10.0.0.1                           10.0.0.2
DAPR Pub/Sub Broker (k8s)   <-->   DAPR service (device)
```

**Comment by agaurav** [comment]
@AaronCrawfis  is the [above](https://github.com/dapr/docs/issues/638#issuecomment-963697550) even feasible right now and if yes then please provide an example

**Comment by bcraun** [comment]
@agaurav I got it sorted out. I am able to publish and subscribe between in-cluster and out-of-cluster DAPR apps so it is definitely possible with a Service Load Balancer to pass the external TCP traffic to Mosquitto, and ultimately to the subscriber app with a DAPR pubsub.mqtt component on each side.
