### ISSUE TITLE
APIs for non-actor state transactions

### ISSUE THREAD

**Issue by chinzhiweiblank** [dapr/docs#661]
## Describe the proposal

For this [PR](https://github.com/dapr/dapr/pull/1681), state transactions for non-actor apis are implemented.

Add documentation to 
https://github.com/dapr/docs/tree/master/howto/create-stateful-service
https://github.com/dapr/docs/blob/master/reference/api/state_api.md

**Comment by AaronCrawfis** [comment]
Documented here: https://docs.dapr.io/reference/api/state_api/#state-transactions
