### ISSUE TITLE
One Pod per Actor instance?

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/docs#663]
I'm currently working on a framework implementation on Dapr for Reinforcement Learning where I would require an isolated container per environment, but the ability of spinning up 100s of similar containers for this environment (thus having 100s of isolated environments that work independently).

Currently I'm using the Actor model for this since it's an ideal fit in my opinion (I could use some brainstorming here) since:
* It's completely isolated
* State store integration
* Placement service that automatically figures out where to place a new environment when I create it

Allowing me to do something like this:

```
for i in range(0, 10):
    env = env.make(i, 'MyEnv')
```

Where `i` would be the unique environment of type 'MyEnv' (aka: actorId), whereafter I can start manipulating the different environments.

Now my question here is: can actors be forced to run in independent pods through the placement servers? Aka: 1 pod has 1 environment (actor) and 1 Dapr Runtime.

The reason for this is since these Environments register themselves globally and start interfering with each other.

> Reference Document I have been reading for this: https://github.com/dapr/docs/blob/master/concepts/actors/README.md

**Comment by AaronCrawfis** [comment]
cc @yaron2

**Comment by XavierGeerinck** [comment]
@AaronCrawfis thanks a lot for following up, just as an FYI: I have recoded this to work with KEDA right now. The issue however is still relevant! I think Actors are easier to use in "dynamic allocation" use cases where you have 1 job coming in that needs exactly one pod for that task.

**Comment by orizohar** [comment]
cc @msfussell

**Comment by yaron2** [comment]
By definition, actor specific instances (with an ID, for example "123") always run in a single pod. a pod can host tens of thousands of actor instances. Pods can run multiple or single actor types (for example, "Dog" or "Cat").

**Comment by XavierGeerinck** [comment]
Closing this since an answer was provided :) thanks a lot
