### ISSUE TITLE
Document the logic around metadata

### ISSUE THREAD

**Issue by mchmarny** [dapr/docs#673]
Metadata, by convention, is viewed as an optional context and does not implicitly impacts the Dapr behaviour. Exception for that is bindings. We need a document that articulates the general principles for core primitives (state, pubsub, invocation)

**Comment by yaron2** [comment]
Not sure bindings are an exception, it needs a check.

**Comment by AaronCrawfis** [comment]
@yaron2 could you clarify the ask here that needs to be addressed?

**Comment by hhunter-ms** [comment]
@yaron2 would you say this has been addressed with the resource schemas https://docs.dapr.io/reference/resource-specs/
