### ISSUE TITLE
Pub/sub spec - document subscribe callback error codes

### ISSUE THREAD

**Issue by LMWF** [dapr/docs#674]
The pub/sub spec only mentions error behavior on the publisher side, it does not document behavior from the subscribe callback if the user returns an error.

https://github.com/dapr/docs/blob/master/reference/api/pubsub_api.md

**Comment by LMWF** [comment]
This how-to actually does state the behavior, but having it in the spec as well is better
https://github.com/dapr/docs/tree/master/howto/consume-topic

**Comment by AaronCrawfis** [comment]
Updated links:
- https://v1-rc2.docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#step-2-subscribe-to-topics
- https://v1-rc2.docs.dapr.io/reference/api/pubsub_api/

**Comment by AaronCrawfis** [comment]
Need to document what the user needs to write in order to subscribe to topics, including error codes. Need to document API behavior and requirements for the app.

**Comment by hhunter-ms** [comment]
looks like this has been resolved - closing. feel free to reopen as a new issue.
