### ISSUE TITLE
Add  dapr.io/api-token-secret annotation to the K8 reference doc 

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#677]
The  dapr.io/api-token-secret annotation described here https://github.com/dapr/docs/tree/master/howto/enable-dapr-api-token-based-authentication needs to be added to the reference doc here https://github.com/dapr/docs/tree/master/howto/configure-k8s

**Comment by AaronCrawfis** [comment]
Updated links:
- https://v1-rc2.docs.dapr.io/operations/security/api-token/
- https://v1-rc2.docs.dapr.io/operations/hosting/kubernetes/kubernetes-annotations/

**Comment by AaronCrawfis** [comment]
`dapr.io/api-token-secret` not in annotation list
