### ISSUE TITLE
HowTo & Troubleshoot: configure sidecar injector to run with multiple replicas

### ISSUE THREAD

**Issue by artursouza** [dapr/docs#683]
## Proposal

When installing Dapr via Helm, users need an HowTo so they can configure sidecar injector to have more than one instance. This is handy for when the AKS cluster is having restarts and some PODs get to be spun up without Dap sidecar. Create a Troubleshooting guide linking to HowTo.

**Comment by yaron2** [comment]
See this PR: https://github.com/dapr/docs/pull/709

**Comment by artursouza** [comment]
The Helm chart will do this going forward at 0.10 release.
