### ISSUE TITLE
Distributed Tracing with Jaeger

### ISSUE THREAD

**Issue by cecilphillip** [dapr/docs#693]
## Describe the proposal
Currently, there's a reference for setting up zipkin for tracing. It would be nice to have a document showing how to use jaeger as well via the OpenTelemetry support.

**Comment by msfussell** [comment]
This is a good idea. Now that OT is being integrated in the v1.0 RC releases, showing jaeger as an option makes sense

**Comment by tcnghia** [comment]
@wcs1only @artursouza can you please add `RELEASE_NOTE: *UPDATED* docs to add Jaeger instructions` ? I can't edit this issue. Thanks

**Comment by duncanworthy** [comment]
The original proposal was to add examples to show the use of Jaeger via OpenTelemetry support, however the completed PRs only showed how to configure Jaeger as a slot-in replacement for Zipkin using its support for the Zipkin API.
Is there any intent to address the original proposal of providing an example of setting up Jaeger via OpenTelemetry?
