### ISSUE TITLE
Update secret-reader to dapr-secret-reader under non-default namespace guidance

### ISSUE THREAD

**Issue by HansK-p** [dapr/docs#699]
## Describe the proposal
When following the description in https://github.com/dapr/docs/blob/master/concepts/secrets/component-secrets.md, one will end up with a default service account with read access to all secrets in the current namespace.

This is not needed as the Component only needs read access to specific secrets. It is also problematic as all (dapr enabled) pods in the same namespace will have access to the same secrets.

I propose the following change to the documentation

from:
<pre>
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: <NAMESPACE>
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
</pre>

to:
<pre>
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: <NAMESPACE>
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["secret-name-1", "secret-name-2"]
  verbs: ["get"]
</pre>

And probably a line  telling that the sample secret names should be substituted by actual secret names. It might also be an option to rename toe role from "secret-reader" to "dapr-secret-reader" as it will now only give read access to Dapr specific secrets.

This will reduce the attack surface.

I assume it's also an option to advice on creating dedicated service accounts when running more than one pod in the application namespace. The Daprd sidecar seems to work well also when not using the default service account (only slightly tested).

**Comment by AaronCrawfis** [comment]
New docs link in the new docs: https://docs.dapr.io/operations/components/component-secrets/

**Comment by AaronCrawfis** [comment]
Note was added on guidance regarding production resources. Renamed issue to tackle second issue of renaming CRD. Will be completed once work is done in the runtime to update the default namespace case.

**Comment by msfussell** [comment]
It seems that this advice is for Kubernetes and Dapr has abstacted this secret access into its own configuration with these topic
https://v1-rc3.docs.dapr.io/developing-applications/building-blocks/secrets/secrets-scopes/ and https://v1-rc2.docs.dapr.io/operations/configuration/secret-scope/  so it this issue needed? Can we update this issue to say that Dapr secret reference is preferred over plafform (k8s) settings?

**Comment by AaronCrawfis** [comment]
Addressed by https://docs.dapr.io/operations/components/component-secrets/#scoping-access-to-secrets
