### ISSUE TITLE
Write set-up doc for Azure Blob Storage state store

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#704]
/cc @ksivamuthu

**Comment by yaron2** [comment]
hey @ksivamuthu can you work on this please?

**Comment by ksivamuthu** [comment]
@yaron2 I'll work on the docs. Somehow I missed this conversation.

**Comment by yaron2** [comment]
Thanks!

**Comment by ksivamuthu** [comment]
@yaron2  Updated the docs. Let me know if it's good or any details to add.
