### ISSUE TITLE
Restructure the steps for setting up Prometheus and Grafana dashboard

### ISSUE THREAD

**Issue by shalabhms** [dapr/docs#706]
Restructure the steps for setting up Prometheus and Grafana dashboard

https://github.com/dapr/docs/blob/master/howto/setup-monitoring-tools/setup-prometheus-grafana.md

**Comment by mchmarny** [comment]
This can be fully automated during setup using the API server ([example](https://github.com/mchmarny/dapr-demos/blob/4d8125811aa4ff1034516c8c139b07acf7ecf574/setup/Makefile#L88-L120))
