### ISSUE TITLE
whether dapr componet implements the file transfer

### ISSUE THREAD

**Issue by moluzhui** [dapr/docs#746]
## Ask your question here
Test if service to Service sends Message successfully, then whether **file transfer** can be achieved.
Or there may be other components that implement this functionality

**Comment by msfussell** [comment]
@moluzhui  - Can you explain this some more for you scenario. Are you asking about the message size that can be send or you want to have a streaming protocol for a service endpoint?

**Comment by AaronCrawfis** [comment]
Marking as stale and closing. Please reopen with more information if needed
