### ISSUE TITLE
Add deployment and upgrade guidelines for self-hosted mode

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#760]
When running Dapr in a self-hosted environment such as IoT Edge, it's beneficial for users to know how to install and upgrade the following system components:

1. Sentry for mTLS
2. Placement service for actors

Install and upgrade instructions are needed for the following two modes of distribution:

1. Process
2. Container

It's important to remember that things like high availability and zero downtime upgrades are concerns of the hosting platform, and as such, general instead of specific guidelines need be given. (eg. to achieve high availability for Sentry, your should run 3 instances of the process/container behind a load balancer).

**Comment by AaronCrawfis** [comment]
Current doc is to uninstall and reinstall: https://v1-rc2.docs.dapr.io/operations/hosting/self-hosted/self-hosted-upgrade/

Needs to be updated for zero downtime

**Comment by AaronCrawfis** [comment]
Current page is here: https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-upgrade/, which still directs to do a full uninstall and reinstall. Need to write docs on zero-downtime upgrades (if possible)

**Comment by willtsai** [comment]
@yaron2 - I feel like this information is already covered (albeit implicitly) in the [self-hosted-with-docker](https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/) page. Do you think we need to be more specific/explicit about installing and upgrading the Sentry and Placement Service components?

(it also looks like relevant [docker images](https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/#docker-images) are provided per component/binary to allow users to selectively install the needed components)

(for reference too, here is some documentation we have on [high availability mode in Kubernetes](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production/#highly-available-mode)
