### ISSUE TITLE
Autogenerate cli reference docs 

### ISSUE THREAD

**Issue by mukundansundar** [dapr/docs#764]
## Describe the proposal
Autogenerate cli reference docs and make it part of the docs repo for v1.0. 
Cobra has an easy way to generate [docs](https://github.com/spf13/cobra/blob/master/doc/md_docs.md) for CLI using cobra package. 
Dapr CLI uses cobra and we can autogenerate CLI docs as seen [here](https://github.com/dapr/cli/pull/446).
Cobra also provides functionality to prepend an autogenerated doc with details to add front matter to documentation to be used with Hugo. 
https://github.com/spf13/cobra/blob/master/doc/md_docs.md#customize-the-output

The CLI reference documentation can be potentially be autogenerated along with the content needed for the documentation engine.

@orizohar @AaronCrawfis @msfussell

**Comment by AaronCrawfis** [comment]
Interesting. I'll have to look into how we get the generated CLI docs into the Hugo workstream when those docs are built out.

@mukundansundar do you have any pointers to docs that have been generated already, either Dapr or other?

**Comment by mukundansundar** [comment]
For Dapr CLI the reference docs have been manually updated. But the PR https://github.com/dapr/cli/pull/446 automates this process so that it is a simple make command. From the docs for the CLI docs generation, there is support for adding the headers necessary for [Hugo](https://github.com/spf13/cobra/blob/master/doc/md_docs.md#customize-the-output).

**Comment by AaronCrawfis** [comment]
Sounds good. Do you have an example of what the generated docs will look like? Either for Dapr or other projects who use this autogeneration?

**Comment by mukundansundar** [comment]
Yup can be seen in the PR. https://github.com/dapr/cli/pull/446

**Comment by AaronCrawfis** [comment]
I must be missing it on the page. Do you have a screenshot/direct link?

**Comment by mukundansundar** [comment]
So this is only for CLI since the docs are generated via the Cobra package which the Dapr CLI uses. 
Also in the PR, it generates markdown docs, one such example is https://github.com/dapr/cli/pull/446/files#diff-056ef09541e5428e72875507a8a3540a.

**Comment by AaronCrawfis** [comment]
Ahh gothca. Very cool! What do you think the process would be to get the generated docs into the website?

Should we go cobra build to docs repo PR to hugo build to website?

**Comment by hhunter-ms** [comment]
since code PR was closed, will close this docs issue. feel free to resurface as a new docs issue if necessary.
