### ISSUE TITLE
Documentation Relevancy 

### ISSUE THREAD

**Issue by amreshkris** [dapr/docs#765]
## Ask your question here
May I know the reason why have we called out _'Secrets'_ under _'Contents'_ of DAPR in this page - https://github.com/dapr/docs/tree/master/concepts . While I understand _Managing Secrets_ is definitely one of the Building Blocks provided by Dapr , it doesn't mean to be a part of DAPR system by itself  As I also see there is no active reference in the document ( may be for the same reason). Please correct me if my understanding is wrong.

**Comment by AaronCrawfis** [comment]
New link: https://v1-rc2.docs.dapr.io/concepts/overview/

As you mentioned above secrets is a [building block](https://v1-rc2.docs.dapr.io/developing-applications/building-blocks/secrets/) of Dapr, where you can [get secrets](https://v1-rc2.docs.dapr.io/reference/api/secrets_api/) from a secret store. 

I believe the new docs have addressed your issue of lack of links and unclear docs. Please reopen if you feel like we haven't addressed your issue.
