### ISSUE TITLE
Document pubsub event appcallback response behavior

### ISSUE THREAD

**Issue by youngbupark** [dapr/docs#772]
pubsub api doc doesn't describe the behavior of application callback response.

https://github.com/dapr/docs/blob/master/reference/api/pubsub_api.md#required-application-user-code-routes

Add dapr behavior based on the application response code.

https://github.com/dapr/dapr/blob/ce89980eda9cc86efbc11a745e2959b1925236ca/pkg/runtime/runtime.go#L1079

**Comment by youngbupark** [comment]
@artursouza did we document pubsub event appcallback behavior ?

**Comment by artursouza** [comment]
No, we haven't. Working on it today.
