### ISSUE TITLE
Add Opa Middleware Docs

### ISSUE THREAD

**Issue by RichiCoder1** [dapr/docs#786]
## Describe the proposal
Add basic document and examples for the new Open Policy Agent Middleware: https://github.com/dapr/dapr/issues/1617

**Comment by msfussell** [comment]
@RichiCoder1 Will you be able to get to these docs? We like to ensure that docs are there to support the code in the release. Thanks

**Comment by RichiCoder1** [comment]
@msfussell My pr https://github.com/dapr/docs/pull/787/files should have all the basics. Might expand on it, but not sure what else I should add that wouldn't be redundant.
