### ISSUE TITLE
Update Redis State Store with Failover

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#791]
Update the How-To for Redis to include the failover YAML specs.

**Comment by tcnghia** [comment]
https://github.com/dapr/docs/pull/792 is merged. @youngbupark @mukundansundar should this issue be closed?

**Comment by yaron2** [comment]
> #792 is merged. @youngbupark @mukundansundar should this issue be closed?

This can be closed.

**Comment by tcnghia** [comment]
Thanks @yaron2
