### ISSUE TITLE
Need to update the conceptual docs for pub/sub for declarative subscribe 

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#795]
https://github.com/dapr/docs/pull/784/files needs to also have the conceptual docs update https://github.com/dapr/docs/tree/master/concepts/publish-subscribe-messaging for this feature

**Comment by msfussell** [comment]
This feature is not in the docs and therefore unknown.

**Comment by yaron2** [comment]
> This feature is not in the docs and therefore unknown.

Not correct, it's listed here: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#declarative-subscriptions
