### ISSUE TITLE
When using multiple replicas to subscribe a message, multiple duplicate messages are received.

### ISSUE THREAD

**Issue by AI-Marvel** [dapr/docs#805]
My Dapr CLI/Runtime is 0.8.0 in kubernetes.

When I used emqx as the mqtt broker to subscribe and publish messages, the following problems occurred:

I use the dapr mqtt component to subscribe and publish messages. I set the number of replicas of the receiver to 3. When the sender sends one message, only one copy should receive one message, but the reality is that all three copies have received the message. They received 4, 2, 2 identical messages respectively.

When I try to set the QOS of the mqtt component to 0, it will return to normal. The number of messages received by the three replicas is 0, 1, 0, but when the QOS is 1 or 2, they are all 4, 2, 2.

Due to the needs of the project, QOS can only be set to 2. I hope to know the reason and modification method of this problem in dapr. 

Thanks！

**Comment by yaron2** [comment]
Hi, this was fixed and will come out in 0.11 release.

**Comment by yaron2** [comment]
@AI-Marvel, I'm closing this for now. If you're still encountering this after upgrading to 0.11, please re-open.

**Comment by AI-Marvel** [comment]
In the new version 0.11.2, I found that it is normal only when sending multiple copies for the first time. If the pod is deleted and restarted, the above problems will occur, unless the name of deployment in YAML file is changed.

In addition, when sending messages with multiple copies, the receiver often receives more messages than its own copies. For example:

Pod A has three copies, and each copy sends a piece of data to pod B, but actually B receives more than ten or more pieces of data.

**Comment by madhavan-j** [comment]
I'm also facing the same issue. There are more messages received by the consumers when using MQTT with activemq. I see MQTT is the only supported protocol for connecting to activemq.
