### ISSUE TITLE
Update vscode-debugging-daprd

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/docs#806]
## Expected Behavior
https://github.com/dapr/docs/tree/master/howto/vscode-debugging-daprd should be up to date with the current CLI behavior.

It also mentions that the `components yaml files` are created, but that's not the case anymore.
The default ones are used of dapr is executed without any components argument.

## Actual Behavior

The doc is not setting `components-path` for daprd which is not the behavior you want.
It should also mention how to change it if non-default components should be used.

The other question is, if it is still recommended to use daprd directly or just use dapr without app launch command.

**Comment by AaronCrawfis** [comment]
New link: https://v1-rc2.docs.dapr.io/developing-applications/ides/vscode/#troubleshooting

**Comment by willtsai** [comment]
@RicardoNiepel @AaronCrawfis @jasonviviano - I think this is now addressed in this parameters table description, which indicates that `components-path` for daprd can be optionally set as well as describes the behavior if not set. **Does this resolve this issue?**
https://docs.dapr.io/developing-applications/ides/vscode/vscode-how-to-debug-multiple-dapr-apps/#daprd-parameter-table
