### ISSUE TITLE
Document the Metadata API

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#825]
Dapr has a `v1.0/metadata` API that returns, among other things, a list of activated actors.

This API endpoint is currently undocumented.

**Comment by msfussell** [comment]
These docs should also include a "HowTo use the metadata endpoint API". Provide some examples in the API reference and also consider having a separate HowTo topic that shows a scenario with a code example.

**Comment by juazasan** [comment]
@yaron2 I have just submitted a PR to try to get this close. Btw, wondering whether we need to update the dapr cli as well as it uses the metadata endpoint. Please let me know.
