### ISSUE TITLE
Oauth2 middleware: add forceHTTPS key definition

### ISSUE THREAD

**Issue by TenSt** [dapr/docs#836]
Update documentation to cover PR for issue dapr/components-contrib#486.
As I understand the change is very small - need to add new key to the definition of the Authorization Code Grant component with comments of how/why to use it in the https://github.com/dapr/docs/tree/master/howto/authorization-with-oauth file.

Please let me know if there are any other locations that this change needs to be highlighted.

**Comment by msfussell** [comment]
@TenSt Can you create documentation to cover this issue? Thanks

**Comment by TenSt** [comment]
@msfussell Will do over the weekend. Sorry, I got pinned down with work and it slipped from my plate.

**Comment by msfussell** [comment]
Resolved. Closed
