### ISSUE TITLE
Update the mTLS configuration doc to describe how to run Sentry control plan service locally

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#851]
This doc https://github.com/dapr/docs/blob/3ac61f2933edf858dc97219dfb7b82d619fd9831/howto/configure-mtls/README.md#self-hosted need updates to describe how to start the Sentry service locally so that developers can test the allowlist feature.

The https://github.com/dapr/docs/tree/master/howto/allowlists-serviceinvocation doc needs to be updated at the start of the doc to point to the above doc . In other words we need to make it clear that allowlists depends upon the Sentry service to work correctly.

**Comment by AaronCrawfis** [comment]
Related to #857

**Comment by yaron2** [comment]
Closed with #996
