### ISSUE TITLE
Make it clear in the docs that all Dapr services Placements and Sentry service do not need Docker to run locally

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#857]
Currently there is CLI slim mode for Dapr that describes how Dapr runtime can be deployed and run without a Docker dependency here https://github.com/dapr/cli/blob/master/README.md#slim-init with a sample here https://github.com/dapr/samples/tree/master/hello-dapr-slim

It should also be made clear that the Placement and Sentry services can be run locally as executable by downloading them from https://github.com/dapr/dapr/releases and simply starting them. No Docker dependency required. Docker is a convenient packaging deployment for the dev environment and not a hard dependency.

**Comment by samcov** [comment]
I ran the placement service with no luck. Port 8080 on windows is used by the system with a very low PID, which can't be stopped.

I tried to see if I could change this port for the Healthz server, but it appears to be no way that I can see.

PS C:\Users\samco\Desktop\Quickies\Dapr\dotnet-sdk-master\samples> ./placement.exe
time="2020-10-11T02:57:10.371892-07:00" level=info msg="starting Dapr Placement Service -- version 0.11.2 -- commit c704551" instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
time="2020-10-11T02:57:10.3728919-07:00" level=info msg="log level set to: info" instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
time="2020-10-11T02:57:10.3728919-07:00" level=info msg="metrics server started on :9090/" instance=DESKTOP-R7P681D scope=dapr.metrics type=log ver=0.11.2
time="2020-10-11T02:57:10.3728919-07:00" level=info msg="placement Service started on port 50005" instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
time="2020-10-11T02:57:10.3738933-07:00" level=info msg="Healthz server is listening on :8080" instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
time="2020-10-11T02:57:10.374892-07:00" level=error msg=**"Healthz server error: listen tcp :8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions." instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2**
time="2020-10-11T02:57:10.374892-07:00" level=fatal msg="failed to start healthz server: listen tcp :8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions." instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2

PS C:\Users\samco\Desktop\Quickies\Dapr\dotnet-sdk-master\samples> **./placement.exe -help**
Usage of C:\Users\samco\Desktop\Quickies\Dapr\dotnet-sdk-master\samples\placement.exe:
  -certchain string
        Path to the credentials directory holding the cert chain (default "/var/run/dapr/credentials")
  -enable-metrics
        Enable prometheus metric (default true)
  -log-as-json
        print log as JSON (default false)
  -log-level string
        Options are debug, info, warning, error, or fatal (default "info")
  -metrics-port string
        The port for the metrics server (default "9090")
  -port string
         (default "50005")
  -tls-enabled
        Should TLS be enabled for the placement gRPC server
P

**Comment by yaron2** [comment]
> I ran the placement service with no luck. Port 8080 on windows is used by the system with a very low PID, which can't be stopped.
> 
> I tried to see if I could change this port for the Healthz server, but it appears to be no way that I can see.
> 
> PS C:\Users\samco\Desktop\Quickies\Dapr\dotnet-sdk-master\samples> ./placement.exe
> time="2020-10-11T02:57:10.371892-07:00" level=info msg="starting Dapr Placement Service -- version 0.11.2 -- commit c704551" instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
> time="2020-10-11T02:57:10.3728919-07:00" level=info msg="log level set to: info" instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
> time="2020-10-11T02:57:10.3728919-07:00" level=info msg="metrics server started on :9090/" instance=DESKTOP-R7P681D scope=dapr.metrics type=log ver=0.11.2
> time="2020-10-11T02:57:10.3728919-07:00" level=info msg="placement Service started on port 50005" instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
> time="2020-10-11T02:57:10.3738933-07:00" level=info msg="Healthz server is listening on :8080" instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
> time="2020-10-11T02:57:10.374892-07:00" level=error msg=**"Healthz server error: listen tcp :8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions." instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2**
> time="2020-10-11T02:57:10.374892-07:00" level=fatal msg="failed to start healthz server: listen tcp :8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions." instance=DESKTOP-R7P681D scope=dapr.placement type=log ver=0.11.2
> 
> PS C:\Users\samco\Desktop\Quickies\Dapr\dotnet-sdk-master\samples> **./placement.exe -help**
> Usage of C:\Users\samco\Desktop\Quickies\Dapr\dotnet-sdk-master\samples\placement.exe:
> -certchain string
> Path to the credentials directory holding the cert chain (default "/var/run/dapr/credentials")
> -enable-metrics
> Enable prometheus metric (default true)
> -log-as-json
> print log as JSON (default false)
> -log-level string
> Options are debug, info, warning, error, or fatal (default "info")
> -metrics-port string
> The port for the metrics server (default "9090")
> -port string
> (default "50005")
> -tls-enabled
> Should TLS be enabled for the placement gRPC server
> P

Thanks a bunch for trying this out.

Just to be clear, the healthz server is not required when running Dapr in self-hosted, and is also part of the reason why we do not exit the process. So the placement service is running normally in this case.

Nevertheless, the healthz port needs to be configurable and I've opened an issue [here](https://github.com/dapr/dapr/issues/2242) to track this.

**Comment by samcov** [comment]
Thanks.

**Comment by samcov** [comment]
BTW, the service does exit on this error.

**Comment by yaron2** [comment]
> BTW, the service does exit on this error.

Right, didn't notice the `log.Fatal` there. We'll change this for the upcoming release.

**Comment by samcov** [comment]
Love your responsiveness, looking forward to the next release, but I can still play with Dapr using Docker.

**Comment by hhunter-ms** [comment]
resolved in the docs
