### ISSUE TITLE
Create performance section for docs

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#863]
A performance section detailing the performance characteristics of the Dapr sidecar and Control Plane for a given versioned release will help users assess resources when doing capacity planning and make decisions about whether or the performance numbers are in-line with their SLAs.

Our community call [here](https://www.youtube.com/watch?v=4kV3SHs1j2k) covered numbers, test setup, test parameters etc.
This needs to be translated into a doc similar to [this one](https://istio.io/latest/docs/ops/deployment/performance-and-scalability/) by Istio.

**Comment by MotaOcimar** [comment]
For those looking for how to reproduce the tests: https://github.com/dapr/dapr/tree/master/tests
