### ISSUE TITLE
Establish a deprecation/support versions policy

### ISSUE THREAD

**Issue by tcnghia** [dapr/docs#864]
## Describe the proposal

It would be great for both users and Dapr developers to know about Dapr deprecation policy: 
* Users can plan the upgrade timeline of their production environments.
* Dapr developers are clear about how long they need to keep old code around. This policy also influences how to design new features.

Beside Dapr component versions, we may need to include the supported K8s versions as well. For SDKs, we may also need to include versions of the corresponding language/ecosystems.

**Comment by tcnghia** [comment]
@msfussell I believe you already have this in mind, so I'm assigning to you

**Comment by AaronCrawfis** [comment]
Similar to #939

**Comment by yaron2** [comment]
Closed with #1225
