### ISSUE TITLE
[Proposal] Move dapr Wiki content to docs

### ISSUE THREAD

**Issue by orizohar** [dapr/docs#869]
To include the wiki content (FAQ, roadmap etc) content currently in the [wiki](https://github.com/dapr/dapr/wiki/) in the upcoming docs website (as well as remove redundancy of FAQ articles), need to remove it and integrate with docs structure.

**Comment by AaronCrawfis** [comment]
- Home can go
- Roadmap seems obsolete, but #726 covers needing one so should eventually create a page
- Iteration Plans is out of date and just links, can go
- Release Process might need to be backed up? It seems out of date.
- FAQ is a dup of the docs one it appears.
- Feedback & Help is duplicate of docs. Can go
- The rest are just links

**Comment by AaronCrawfis** [comment]
Overall I think we just need to assess Release Process. @yaron2 is this up to date and worth keeping?
