### ISSUE TITLE
Where should getting-started/readme.md link to 'dapr cli' point for installation? 

### ISSUE THREAD

**Issue by stephenrwalli** [dapr/docs#89]
It presently points to https://github.com/dapr/cli/releases. 
This means a new user needs to choose a release without context. 

Pointing to https://github.com/dapr/cli gives them useful info (but the same general releases link). Is there a way to force a general 'stable' releases link equivalent where the downloads actually exist (i.e. https://github.com/dapr/cli/releases/tag/v0.3.0-alpha.1)?

**Comment by youngbupark** [comment]
@stephenrwalli now, we have one line install script for each OSes. So user would not think about which version is stable one. - https://github.com/dapr/cli/tree/master/install

**Comment by msfussell** [comment]
PLease reopen if you think this is still an issue
