### ISSUE TITLE
Docs disappear when resizing brower windows

### ISSUE THREAD

**Issue by tcnghia** [dapr/docs#891]
## Expected Behavior

When resizing windows, doc texts get squeezed but still visible.

## Actual Behavior

Text disappears when the browser window approaches 8-inch width. 

## Steps to Reproduce the Problem

* Opening docs.dapr.io in Microsoft Edge browser
* Gradually reduce window width.

![ezgif-1-95852688d830](https://user-images.githubusercontent.com/138266/98044697-21158080-1ddc-11eb-8569-740b023faea8.gif)

## Release Note

RELEASE NOTE:

**Comment by tcnghia** [comment]
cc @AaronCrawfis @orizohar

**Comment by AaronCrawfis** [comment]
CSS issue is causing bootstrap columns to not resize properly. Content (middle column) is getting pushed below left column. Will look at when I get back from vacation on the 12th.

**Comment by tcnghia** [comment]
Fixed by https://github.com/dapr/docs/pull/980
