### ISSUE TITLE
Possible missing word in docs?

### ISSUE THREAD

**Issue by issacg** [dapr/docs#904]
At the top of https://github.com/dapr/docs/edit/website/daprdocs/content/en/concepts/building-blocks-concept.md is a sentence which seems to be missing a word (marked by XXX):

A building block is XXX as an HTTP or gRPC API that can be called from your code and uses one or more Dapr components.

As I'm a bit too new to dapr (<1 hr ) I don't want to suggest what the best word is with a PR  :)

**Comment by yaron2** [comment]
The word `as` in that sentence is redundant. Would be more than happy for you to fix this with a PR!

**Comment by issacg** [comment]
Yaron!!! It's been a while - I'd say we should catch up, but we seem to no longer be in the same country, let alone company.

PR forthcoming.

**Comment by yaron2** [comment]
> Yaron!!! It's been a while - we should catch up, although we seem to no longer be in the same country, let alone company.
> 
> PR forthcoming.

Feel free to reach out whenever at yaronsc@microsoft.com :)
