### ISSUE TITLE
Update the getting started guide for v1.0-rc1

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#914]
The getting started guide need to be updated to
1) Ensure that local and K8s install experiences are separate.
2) The reader is directed to the quickstarts
3) The install script will install v1.0.0-rc.2 CLI as a choice.

**Comment by AaronCrawfis** [comment]
RC1 website has been setup and configured with versioning

**Comment by AaronCrawfis** [comment]
Rest of work (link to quickstarts, separate installation guides) can be done tomorrow first thing
