### ISSUE TITLE
Missing explanation what is Highly Available mode on Kubernetes

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/docs#931]
Right now the only refernce to HA mode is https://docs.dapr.io/getting-started/install-dapr-kubernetes/#install-in-highly-available-mode

There should be a dedicated page to describe the feature, how it works, and how to enable it on difference platforms.

**Comment by AaronCrawfis** [comment]
@yaron2 @msfussell is HA mode just for Kubernetes?

**Comment by msfussell** [comment]
Yes, HA mode is only for K8s.

**Comment by AaronCrawfis** [comment]
@msfussell 

> This command creates three replicas of each control plane pod for an HA deployment (with the exception of the Placement pod) in the dapr-system namespace.

Is there anything else that HA mode does that should be documented?

And what is our recommendation? Should all production deployments have HA mode enabled? What's a scenario where you don't want it enabled?

And more for my benefit, why isn't HA mode always enabled on Kubernetes? What's the tradeoff that's being made?
