### ISSUE TITLE
Document components maturity status

### ISSUE THREAD

**Issue by yaron2** [dapr/docs#935]
Components can have the following maturity statuses:

* `alpha`
* `beta`
* `stable`

This issue is to update each component with its maturity level, and provide a high-level explanation about what the different statuses mean.

**Comment by mukundansundar** [comment]
One of the steps is API conformance tests: https://github.com/dapr/components-contrib/issues/405#issuecomment-672173468

Additional steps should be documented.

**Comment by mukundansundar** [comment]
closed by #1203
