### ISSUE TITLE
The new "How-To: Install Dapr CLI" doc's powershell script errors and stops executing 

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#936]
## Expected Behavior

I expect the power shell scripts in these documents to work.

## Actual Behavior

I was NOT running powershell as admin since the doc said nothing about that.  I executed the below script copy/pasted from the document and got the following error:

PS C:\> powershell -Command "$script=iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1; $block=[ScriptBlock]::Create($script); invoke-command -ScriptBlock $block -ArgumentList 1.0.0-rc.2"
powershell : At line:1 char:106
At line:1 char:1
+ powershell -Command "$script=iwr -useb https://raw.githubusercontent. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (At line:1 char:106:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
+ ... /dapr/cli/master/install/install.ps1; =[ScriptBlock]::Create(); invok ...
+                                                                  ~
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression
 
PS  I ran the script in the pre 11/17/20 version of this document and it worked fine.  Here it is:
powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"

## Steps to Reproduce the Problem

Follow the instructions in the How-To document without being logged in as admin.

## Release Note

RELEASE NOTE:

**Comment by AaronCrawfis** [comment]
Thanks for the feedback! As a workaround please run in Command Prompt and we'll update our docs/command to work as expected.
