### ISSUE TITLE
Use a standardized noun for "compoment implementation"

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#953]
**What content needs to be created or modified?**
I noticed when working on https://github.com/dapr/docs/pull/934 that we're missing a common word for the various "component implementations", such as all the different state store implementation. This leads to some discrepancies in the documentation: In the list of supported pub/sub implementation the expression "Supported pub/sub components" is used, and under "List of all the supported external bindings that can interface with Dapr" - this is unfortunate because a "binding" is something very specific in dapr, and using the word like this leads to confusion. However, in the state store list, one has simply used the plural: "different state stores".

This may seem like pedantics, but I think having a common vocabulary is super-important, as it makes it way easier to both write and read documentation, and can help in troubleshooting as well.

**Describe the solution you'd like**
- Decide on what to call component implementations, such as the redis pubsub. I would consider "driver", "implementation", "component implementation" or something along those lines good candidates
- Make sure we don't use dapr-overloaded terms such as "binding(s)" anywhere we shouldn't in the documentation
- consider adding a "vocabulary" section under "reference" with the most important terms and what they mean in the context of dapr

**Where should the new material be placed?**

**Additional context**

**Comment by msfussell** [comment]
Addressing this issue, like this
1) Decide on what to call component implementations, such as the redis pubsub. I would consider "driver", "implementation", "component implementation" or something along those lines good candidates
@trondhindenes Not sure what this means. Can you provide more examples/details?

2) Make sure we don't use dapr-overloaded terms such as "binding(s)" anywhere we shouldn't in the documentation
I suggest changing the title of the support component topics to be like this.

https://v1-rc3.docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/
"The supported pub/sub brokers that interface with Dapr"

https://v1-rc3.docs.dapr.io/operations/components/setup-state-store/supported-state-stores/
"The supported state stores that interface with Dapr"
And remove this sentence "The following stores are supported, at various levels, by the Dapr state management building block"

https://v1-rc3.docs.dapr.io/operations/components/setup-secret-store/supported-secret-stores/
"The supported secret stores that interface with Dapr"

https://v1-rc3.docs.dapr.io/operations/components/setup-bindings/supported-bindings/
"The supported external systems that interface with Dapr as input/output bindings" 
And remove this sentence "Every binding has its own unique set of properties. Click the name link to see the component YAML for each binding."

3) Consider adding a "vocabulary" section under "reference" with the most important terms and what they mean in the context of dapr
 -- For vocabulary section - This issue need to be addressed https://github.com/dapr/docs/issues/25
