### ISSUE TITLE
Add info on querying Redis for pub/sub topics (for debug)

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#955]
**What content needs to be created or modified?**
There needs to be an example of the redis commands required to display the contents of a given topic.  This is quite useful for learning and debugging.

**Describe the solution you'd like**
There is a state related document on how to query saved state in redis, for both normal state and actor state.  This is as https://docs.dapr.io/developing-applications/building-blocks/state-management/query-state-store/query-redis-store/.

However it says nothing about querying the contents of a topic.  I would like to see all of the "How to query redis and maybe do other things as well to redis" development aids being in one document, and then have storage, actors, and pub/sub specific articles reference this single article.

**Where should the new material be placed?**
See above.

**Additional context**
None.

**Comment by georgestevens99** [comment]
I just looked in the Redis documentation under [PubSub](https://redis.io/topics/pubsub) and, to my surprise, found no commands that display the message data in a topic.  Perhaps I did not look far enough.  But my request may be impossible,

**Comment by georgestevens99** [comment]
OK, got it thanks to a discord conversation.  

Dapr pubsubs uses redis streams.  Here is how to see the contents of a topic named TestTopic that is displayed in the redis-cli by the command keys *
xread count 100 streams TestTopic 0
I tested it and it works.

From Aii3n's answer in discord of: exec into the container, redis-cli -> keys '*' -> xread count 100 streams TOPIC 0

**Comment by msfussell** [comment]
@hhunter-ms - We should pull this into the docs. In many ways this is another example of this PR done into the QS https://github.com/dapr/quickstarts/pull/784. I suggest that we compare the two and decide which is best or just close this issue.
