### ISSUE TITLE
The Dapr System service dashboard do not have docs describing how to read the information.

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#959]
The docs do not describe what the Dapr system service dashboards are useful for either here 
https://docs.dapr.io/operations/monitoring/grafana/ or here https://github.com/dapr/dapr/tree/master/grafana.

The operations sections instead should have a topics called "Configuring Dapr system service dashboards" and "How To: Use the Dapr system service dashboards" to explain what is useful on them.

These dashboards 
![image](https://user-images.githubusercontent.com/11199644/100577443-20fe8880-3295-11eb-8b26-6b53370c8fcd.png)

Also we should be clear listing all the dashboards for Dapr, given that there is also an application dashboard that is installed via the CLI.

**Comment by youngbupark** [comment]
Dashboard panel has its self-description note when a user hovers `i` icon. Therefore I am not sure we need to document it separately. We can move [this metrics list doc](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md) to docs repo.

![image](https://user-images.githubusercontent.com/11863108/100650571-fba36600-32f8-11eb-9f35-5e2f26ed3d9d.png)

Here is my suggestion:
1. Move [this metrics list doc](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md) from dapr/dapr to dapr/docs
2. Describe how to see the description note on grafana dashboard.

@msfussell Any thoughts?
