### ISSUE TITLE
There's no complete list of supported redis pubsub parameters

### ISSUE THREAD

**Issue by trondhindenes** [dapr/docs#962]
**What content needs to be created or modified?**
I was a little surprised to see that not all supported attributes in the redis pubsub driver (or what do we call it? #953  ) are actually documented. It seems to me that we should strive to have all supported parameters clearly defined in each component implementation. Examples are awesome, but they often leave the user uncertain about whether or not a certain parameter is required or optional, in addition to what it means.

I would also argue that explaining each attribute inline in a code example (example: https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-azure-eventhubs/ ) is better than nothing, but it would be way better to have a simple table instead. For comparison, here's a good example of a well-structured documentation: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_storageaccount_module.html#ansible-collections-azure-azcollection-azure-rm-storageaccount-module - while not the most beatiful styling, it's very clear how to use the various options.

I know we touched on this a while back ( #584 ) but I still feel like the current docs aren't up to par.

Specifically, I wanted to look into using KEDA autoscaler with redis pubsub today. KEDA requires a consumer group, and I actually had to dig into the dapr-components-contrib codebase to learn that `consumerID` is a supported parameter.

**Describe the solution you'd like**
We just need to standardize (and improve) the documentation so that users can understand the configuration options for every implementation/driver (again, we need a word for this - #953).

**Where should the new material be placed?**

**Additional context**

**Comment by AaronCrawfis** [comment]
We should follow the format here: https://v1-rc2.docs.dapr.io/operations/components/component-schema/ 

From #1018

**Comment by trondhindenes** [comment]
I believe #1088 fixes this issue

**Comment by msfussell** [comment]
Closing this issue as this specific issue addressed and all the components are now being updated (or have been updated) to have tables for the metadata as per your suggestions.
