### ISSUE TITLE
The pub/sub overview needs to describe how subscription and topic information is set

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#987]
Subscription and topics are set automatically on the pub/sub component however it does not say this explicitly in the docs here
https://v1-rc1.docs.dapr.io/operations/components/setup-pubsub/setup-pubsub-overview/

And if you do want to set topics your own topics it would be good to describe how this can be done on a component. 
For example on Service Bus component this can be set and it would be good to show how to use this setting with your own topics
name: disableEntityManagement
    value: <REPLACE-WITH-DISABLE-ENTITY-MANAGEMENT> # Optional. Default: false. When set to true, topics and subscriptions do not get created automatically.

RELEASE NOTE: **UPDATE** overview description for pub/sub topics and subscriptions

**Comment by yaron2** [comment]
Closed with #1201
